-- ============================================
-- Achou Trocador — Passo 5: 100 locais pesquisados em Buenos Aires
-- Entram como "não verificados" (verified = false) e sem nenhuma
-- confirmação ainda (dad_allowed/is_paid/still_open ficam null,
-- last_confirmed_at fica null) -- é a comunidade que vai confirmar.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda);
-- a localização exata do trocador em si também precisa ser
-- confirmada por quem for lá.
-- Rode isso no SQL Editor do MESMO projeto Supabase, DEPOIS do Passo 4.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('bsas-001', 'Galerías Pacífico', -34.5983, -58.375, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-002', 'Patio Bullrich', -34.5847, -58.3934, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-003', 'Paseo Alcorta', -34.5758, -58.4188, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-004', 'Distrito Arcos', -34.5735, -58.4297, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-005', 'DOT Baires Shopping', -34.5507, -58.4869, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-006', 'Devoto Shopping', -34.5985, -58.5133, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-007', 'Caballito Shopping', -34.6183, -58.439, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-008', 'Plaza Liniers Shopping', -34.6392, -58.5225, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-009', 'Buenos Aires Design', -34.586, -58.394, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-010', 'Solar de la Abadía', -34.561, -58.456, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-011', 'Spinetto Shopping', -34.6316, -58.4693, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-012', 'Village Recoleta', -34.5895, -58.3922, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-013', 'Alto Avellaneda', -34.6612, -58.3651, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-014', 'Unicenter', -34.5083, -58.5341, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-015', 'Village Caballito', -34.618, -58.4385, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-016', 'Jumbo Palermo', -34.5764, -58.4213, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-017', 'Carrefour Hipermercado Palermo', -34.5786, -58.4406, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-018', 'Coto Hipermercado Abasto', -34.6032, -58.4103, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-019', 'Disco Av. Cabildo', -34.5615, -58.4571, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-020', 'Vea Hipermercado Almagro', -34.6082, -58.4183, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-021', 'Carrefour Market Belgrano', -34.5661, -58.4562, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-022', 'Coto Caballito', -34.6165, -58.436, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-023', 'Jumbo Almagro', -34.6003, -58.4197, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-024', 'Día Supermercado Boedo', -34.6265, -58.4171, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-025', 'La Anónima Puerto Madero', -34.6118, -58.3634, 'familia', 'Hipermercado grande — por la ley de cambiadores debería tener uno. Todavía sin confirmar.', false),
  ('bsas-026', 'Parque Tres de Febrero (Bosques de Palermo)', -34.5697, -58.4157, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-027', 'Jardín Japonés', -34.5763, -58.4144, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-028', 'Jardín Botánico Carlos Thays', -34.5799, -58.4187, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-029', 'Ecoparque Buenos Aires', -34.5776, -58.4147, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-030', 'Plaza San Martín', -34.5949, -58.3746, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-031', 'Plaza de Mayo', -34.6083, -58.3712, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-032', 'Plaza Francia', -34.585, -58.3936, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-033', 'Parque Lezama', -34.6285, -58.3699, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-034', 'Parque Centenario', -34.606, -58.4357, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-035', 'Parque Rivadavia', -34.6178, -58.4363, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-036', 'Parque Chacabuco', -34.6367, -58.4374, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-037', 'Parque Avellaneda', -34.6461, -58.4707, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-038', 'Parque Saavedra', -34.554, -58.4884, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-039', 'Parque Sarmiento', -34.5813, -58.5023, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-040', 'Parque Patricios', -34.6363, -58.4034, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-041', 'Reserva Ecológica Costanera Sur', -34.6076, -58.3538, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-042', 'Parque Micaela Bastidas', -34.6183, -58.3627, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-043', 'Plaza Vicente López', -34.5876, -58.3927, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-044', 'Plaza del Congreso', -34.6095, -58.3922, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-045', 'Parque Los Andes', -34.59, -58.4525, 'familia', 'Espacio público — puede haber baño público cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-046', 'MALBA', -34.5773, -58.4028, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-047', 'Museo Nacional de Bellas Artes', -34.5837, -58.3934, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-048', 'Museo de Arte Moderno (MAMBA)', -34.618, -58.3714, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-049', 'Centro Cultural Kirchner', -34.6018, -58.3701, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-050', 'Centro Cultural Recoleta', -34.5878, -58.3927, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-051', 'Museo del Bicentenario', -34.6082, -58.3697, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-052', 'Museo Argentino de Ciencias Naturales', -34.6089, -58.4374, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-053', 'Planetario Galileo Galilei', -34.5721, -58.4133, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-054', 'Museo Larreta', -34.5622, -58.4562, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-055', 'Museo Sívori', -34.5729, -58.4171, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-056', 'Usina del Arte', -34.6335, -58.3616, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-057', 'El Ateneo Grand Splendid', -34.5959, -58.3935, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-058', 'Museo Etnográfico', -34.6112, -58.3735, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-059', 'La Rural (Predio Ferial)', -34.5765, -58.4106, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-060', 'Museo del Holocausto', -34.6033, -58.3925, 'familia', 'Museo / centro cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-061', 'Museo de los Niños Abasto', -34.6036, -58.4106, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-062', 'Tierra Santa', -34.5588, -58.4229, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-063', 'Parque de la Costa (Tigre)', -34.427, -58.5786, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-064', 'Acuario Buenos Aires', -34.5623, -58.4212, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-065', 'Puerto Madero (Puente de la Mujer)', -34.6083, -58.3631, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-066', 'Feria de Mataderos', -34.6598, -58.5031, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-067', 'Tecnópolis', -34.5423, -58.5027, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-068', 'Parque Norte', -34.5443, -58.4489, 'familia', 'Atracción pensada para chicos — alta probabilidad de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-069', 'Estación Retiro', -34.592, -58.3745, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-070', 'Estación Once', -34.6088, -58.4058, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-071', 'Estación Constitución', -34.6265, -58.3808, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-072', 'Estación Federico Lacroze', -34.5847, -58.4548, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-073', 'Aeroparque Jorge Newbery', -34.5592, -58.4156, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-074', 'Aeropuerto Internacional Ezeiza', -34.8222, -58.5358, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-075', 'Terminal de Ómnibus de Retiro', -34.5915, -58.3736, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-076', 'Estación Diagonal Norte (Subte)', -34.6034, -58.3813, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-077', 'Estación Carlos Pellegrini (Subte)', -34.6035, -58.3815, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-078', 'Estación 9 de Julio (Subte)', -34.6045, -58.382, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-079', 'Estación Facultad de Medicina (Subte)', -34.5993, -58.3966, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-080', 'Estación Palermo (Subte)', -34.588, -58.43, 'familia', 'Estación / terminal grande — los baños públicos más nuevos suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-081', 'Hospital Garrahan', -34.628, -58.3937, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-082', 'Hospital Italiano', -34.606, -58.421, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-083', 'Hospital Alemán', -34.592, -58.402, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-084', 'Hospital de Clínicas José de San Martín', -34.5997, -58.397, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-085', 'Hospital Fernández', -34.5814, -58.4131, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-086', 'Hospital Argerich', -34.6262, -58.3625, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-087', 'Hospital Durand', -34.6098, -58.438, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-088', 'Hospital Pirovano', -34.5636, -58.4741, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-089', 'Hospital Rivadavia', -34.586, -58.4021, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-090', 'Sanatorio Otamendi', -34.594, -58.396, 'familia', 'Hospital — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-091', 'Estadio Luna Park', -34.6019, -58.3691, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-092', 'Teatro Colón', -34.601, -58.3831, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-093', 'Biblioteca Nacional Mariano Moreno', -34.5847, -58.4001, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-094', 'Congreso de la Nación (área visitantes)', -34.6097, -58.3925, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-095', 'Museo del Cabildo', -34.6083, -58.3701, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-096', 'Cinemark Palermo', -34.5854, -58.413, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-097', 'Coto Hipermercado Palermo', -34.5825, -58.4295, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-098', 'Hospital Naval Pedro Mallo', -34.6068, -58.433, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-099', 'Parque de la Memoria', -34.5453, -58.4451, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-100', 'Catedral Metropolitana', -34.6084, -58.3731, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false)
on conflict (id) do nothing;
