-- ============================================
-- Achou Trocador — 100 locais pesquisados em Florianópolis
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- é a comunidade (seus colegas de Floripa) que
-- vai confirmar tipo de banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('floripa-001', 'Beiramar Shopping', -27.5945, -48.5615, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-002', 'Floripa Shopping', -27.535, -48.488, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-003', 'Iguatemi Florianópolis', -27.5945, -48.509, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-004', 'Jurerê Open Shopping', -27.436, -48.493, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-005', 'Shopping Nações', -27.429, -48.456, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-006', 'Mac Shopping', -27.589, -48.568, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-007', 'Shopping Itaguaçu', -27.591, -48.566, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-008', 'Continente Shopping', -27.596, -48.562, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-009', 'Villa Romana Shopping', -27.594, -48.5085, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-010', 'Shopping Total Ilha', -27.586, -48.522, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('floripa-011', 'Angeloni Beira-Mar', -27.586, -48.554, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-012', 'Angeloni Kobrasol', -27.596, -48.61, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-013', 'Big Bompreço Trindade', -27.592, -48.523, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-014', 'Giassi Estreito', -27.594, -48.565, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-015', 'Giassi Kobrasol', -27.5975, -48.608, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-016', 'Angeloni Itaguaçu', -27.585, -48.566, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-017', 'Comper Trindade', -27.59, -48.521, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-018', 'Angeloni Canasvieiras', -27.43, -48.457, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-019', 'Giassi Ingleses', -27.433, -48.398, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-020', 'Angeloni Campeche', -27.672, -48.487, 'familia', 'Supermercado grande — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('floripa-021', 'Parque de Coqueiros', -27.598, -48.57, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-022', 'Parque da Luz', -27.6, -48.549, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-023', 'Parque Ecológico do Córrego Grande', -27.587, -48.504, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-024', 'Parque Estadual do Rio Vermelho', -27.505, -48.413, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-025', 'Praça XV de Novembro', -27.5965, -48.548, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-026', 'Praça do Carianos', -27.668, -48.554, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-027', 'Largo da Alfândega', -27.597, -48.549, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-028', 'Parque Municipal da Lagoa do Peri', -27.715, -48.515, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-029', 'Praça Getúlio Vargas (Estreito)', -27.594, -48.566, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-030', 'Parque das Nações (Canasvieiras)', -27.43, -48.455, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-031', 'Praça da Bandeira (Trindade)', -27.591, -48.522, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-032', 'Parque Linear do Itacorubi', -27.582, -48.503, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-033', 'Praça da Lagoa da Conceição', -27.605, -48.455, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-034', 'Parque da Figueira', -27.596, -48.547, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-035', 'Praça Santa Terezinha (Ingleses)', -27.433, -48.398, 'familia', 'Espaço público — pode ter banheiro público perto da entrada principal. Ainda sem confirmação.', false),
  ('floripa-036', 'Praia Mole', -27.628, -48.452, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-037', 'Praia da Joaquina', -27.63, -48.448, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-038', 'Praia dos Ingleses', -27.433, -48.396, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-039', 'Praia de Canasvieiras', -27.429, -48.456, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-040', 'Praia de Jurerê Internacional', -27.436, -48.493, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-041', 'Praia do Campeche', -27.672, -48.487, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-042', 'Praia da Barra da Lagoa', -27.575, -48.429, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-043', 'Praia de Ponta das Canas', -27.409, -48.439, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-044', 'Praia do Santinho', -27.438, -48.383, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-045', 'Praia da Daniela', -27.455, -48.53, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-046', 'Praia do Forte (Jurerê)', -27.42, -48.498, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-047', 'Praia da Armação', -27.737, -48.503, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-048', 'Praia do Pântano do Sul', -27.783, -48.509, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-049', 'Praia da Solidão', -27.755, -48.508, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-050', 'Praia do Matadeiro', -27.748, -48.506, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('floripa-051', 'Museu Histórico de Santa Catarina', -27.596, -48.548, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-052', 'Museu de Arte de Santa Catarina (MASC)', -27.5955, -48.5485, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-053', 'Catedral Metropolitana de Florianópolis', -27.5965, -48.548, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-054', 'Mercado Público de Florianópolis', -27.5965, -48.547, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-055', 'Fortaleza de Santa Cruz de Anhatomirim', -27.433, -48.562, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-056', 'Fortaleza de São José da Ponta Grossa', -27.418, -48.505, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-057', 'Teatro Álvaro de Carvalho (TAC)', -27.5975, -48.548, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-058', 'Centro Integrado de Cultura (CIC)', -27.583, -48.506, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-059', 'Museu da Escola Catarinense', -27.596, -48.547, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-060', 'Casa da Alfândega (Centro Cultural)', -27.5968, -48.5488, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('floripa-061', 'Aeroporto Internacional Hercílio Luz', -27.67, -48.547, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-062', 'Terminal Rodoviário Rita Maria', -27.601, -48.554, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-063', 'Terminal de Integração Sudoeste (TICOR)', -27.628, -48.47, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-064', 'Terminal de Integração do Centro (TICEN)', -27.599, -48.551, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-065', 'Terminal de Integração da Trindade (TITRI)', -27.588, -48.523, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-066', 'Terminal de Integração da Lagoa (TILAG)', -27.606, -48.465, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-067', 'Terminal de Integração Norte da Ilha (TINOI)', -27.43, -48.452, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-068', 'Terminal de Integração dos Ingleses (TIING)', -27.433, -48.397, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-069', 'Ponte Hercílio Luz', -27.594, -48.557, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-070', 'Ponte Colombo Salles', -27.592, -48.558, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-071', 'Terminal Marítimo (travessia para ilhas)', -27.5975, -48.549, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-072', 'Estação Rodoviária de São José', -27.596, -48.628, 'familia', 'Terminal/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('floripa-073', 'Hospital Universitário (HU/UFSC)', -27.599, -48.517, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-074', 'Hospital Governador Celso Ramos', -27.59, -48.548, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-075', 'Hospital Infantil Joana de Gusmão', -27.592, -48.535, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-076', 'Hospital Regional Homero de Miranda Gomes', -27.6, -48.625, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-077', 'Hospital Baía Sul Medical Center', -27.594, -48.561, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-078', 'Hospital Florianópolis (Unimed)', -27.583, -48.508, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-079', 'Multi Hospital Florianópolis', -27.665, -48.548, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-080', 'Hospital SOS Cárdio', -27.592, -48.567, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-081', 'Maternidade Carmela Dutra', -27.591, -48.549, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-082', 'Instituto de Cardiologia de Santa Catarina', -27.61, -48.63, 'familia', 'Hospital — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('floripa-083', 'UFSC — Campus Trindade (Reitoria)', -27.601, -48.519, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-084', 'UDESC — Centro', -27.594, -48.545, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-085', 'Assembleia Legislativa de SC', -27.598, -48.549, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-086', 'Prefeitura Municipal de Florianópolis', -27.597, -48.548, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-087', 'Biblioteca Pública de Santa Catarina', -27.596, -48.547, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-088', 'Estádio Orlando Scarpelli (Avaí)', -27.587, -48.517, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-089', 'Ginásio da Ressacada (Figueirense)', -27.63, -48.525, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-090', 'Centrosul — Centro de Convenções', -27.59, -48.556, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-091', 'Marina Pública (Beira-Mar)', -27.588, -48.557, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-092', 'Colégio de Aplicação UFSC', -27.6, -48.518, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('floripa-093', 'Museu Ao Ar Livre Ratones (Forte Santana)', -27.592, -48.561, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-094', 'Piscinão do Rio Tavares', -27.635, -48.472, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-095', 'Parque Aquático Cascaville', -27.465, -48.575, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-096', 'Ilha do Campeche (ponto de partida dos barcos)', -27.69, -48.475, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-097', 'Dunas da Joaquina', -27.628, -48.455, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-098', 'Costão do Santinho Resort (acesso público à praia)', -27.439, -48.385, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-099', 'Parque de Diversões Beira-Mar Norte', -27.587, -48.556, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('floripa-100', 'Complexo Cultural Fortaleza da Barra (Barra da Lagoa)', -27.573, -48.43, 'familia', 'Atração voltada pra família — boa chance de ter trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
