-- ============================================
-- Achou Trocador — 100 locais pesquisados em Presidente Prudente
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('pprudente-001', 'Parque Shopping Prudente', -22.1195, -51.3925, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('pprudente-002', 'Prudenshopping', -22.1265, -51.4085, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('pprudente-003', 'Parque do Povo', -22.1215, -51.3945, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-004', 'Cidade da Criança (Presidente Prudente)', -22.142, -51.385, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('pprudente-005', 'SESC Thermas Presidente Prudente', -22.155, -51.37, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('pprudente-006', 'Teatro Municipal Procópio Ferreira', -22.1245, -51.389, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('pprudente-007', 'Santa Casa de Presidente Prudente', -22.123, -51.391, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-008', 'Hospital Regional de Presidente Prudente', -22.118, -51.398, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-009', 'Hospital do Câncer de Presidente Prudente', -22.12, -51.393, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-010', 'UNESP — Campus de Presidente Prudente', -22.126, -51.407, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('pprudente-011', 'Terminal Rodoviário de Presidente Prudente', -22.12, -51.392, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('pprudente-012', 'Aeroporto de Presidente Prudente', -22.175, -51.424, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('pprudente-013', 'Estádio Municipal Prudentão', -22.113, -51.396, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('pprudente-014', 'Catedral de Presidente Prudente', -22.1258, -51.3893, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('pprudente-015', 'Praça Nove de Julho', -22.1252, -51.3888, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-016', 'Praça Rui Barbosa', -22.124, -51.39, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-017', 'Poupatempo Presidente Prudente', -22.121, -51.3935, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('pprudente-018', 'Biblioteca Municipal de Presidente Prudente', -22.125, -51.3895, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('pprudente-019', 'Bosque Municipal de Presidente Prudente', -22.1195, -51.3865, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-020', 'Zoológico Municipal de Presidente Prudente', -22.143, -51.386, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('pprudente-021', 'Praça do Vila Marcondes', -22.0977, -51.4839, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-022', 'UBS Vila Marcondes', -22.1706, -51.4443, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-023', 'Comper Vila Marcondes', -22.0783, -51.3536, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-024', 'Extra Vila Marcondes', -22.0472, -51.4715, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-025', 'Assaí Atacadista Vila Marcondes', -22.1412, -51.4829, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-026', 'Praça do Jardim Bongiovani', -22.1819, -51.3878, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-027', 'UBS Jardim Bongiovani', -22.2203, -51.4491, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-028', 'Comper Jardim Bongiovani', -22.0956, -51.3799, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-029', 'Extra Jardim Bongiovani', -22.1815, -51.371, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-030', 'Assaí Atacadista Jardim Bongiovani', -22.0637, -51.4876, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-031', 'Praça do Jardim Paulistano', -22.0644, -51.3493, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-032', 'UBS Jardim Paulistano', -22.1575, -51.4578, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-033', 'Comper Jardim Paulistano', -22.0342, -51.4216, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-034', 'Extra Jardim Paulistano', -22.2071, -51.4696, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-035', 'Assaí Atacadista Jardim Paulistano', -22.0561, -51.3682, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-036', 'Praça do Vila Nova Prudente', -22.0642, -51.343, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-037', 'UBS Vila Nova Prudente', -22.1184, -51.2943, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-038', 'Comper Vila Nova Prudente', -22.1499, -51.3785, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-039', 'Extra Vila Nova Prudente', -22.0597, -51.3652, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-040', 'Assaí Atacadista Vila Nova Prudente', -22.0533, -51.3734, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-041', 'Praça do Jardim Alto da Boa Vista', -22.0847, -51.4797, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-042', 'UBS Jardim Alto da Boa Vista', -22.18, -51.431, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-043', 'Comper Jardim Alto da Boa Vista', -22.2096, -51.4423, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-044', 'Extra Jardim Alto da Boa Vista', -22.2054, -51.4333, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-045', 'Assaí Atacadista Jardim Alto da Boa Vista', -22.0985, -51.4159, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-046', 'Praça do Jardim Morada do Sol', -22.1516, -51.447, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-047', 'UBS Jardim Morada do Sol', -22.1722, -51.3016, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-048', 'Comper Jardim Morada do Sol', -22.096, -51.3671, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-049', 'Extra Jardim Morada do Sol', -22.1914, -51.3431, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-050', 'Assaí Atacadista Jardim Morada do Sol', -22.1929, -51.413, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-051', 'Praça do Jardim Itapuã', -22.0277, -51.3609, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-052', 'UBS Jardim Itapuã', -22.1142, -51.352, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-053', 'Comper Jardim Itapuã', -22.057, -51.3337, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-054', 'Extra Jardim Itapuã', -22.1798, -51.4825, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-055', 'Assaí Atacadista Jardim Itapuã', -22.1625, -51.4354, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-056', 'Praça do Jardim Aviação', -22.1834, -51.3003, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-057', 'UBS Jardim Aviação', -22.0503, -51.426, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-058', 'Comper Jardim Aviação', -22.0945, -51.4098, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-059', 'Extra Jardim Aviação', -22.0427, -51.3971, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-060', 'Assaí Atacadista Jardim Aviação', -22.1726, -51.4396, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-061', 'Praça do Vila Formosa', -22.1133, -51.4364, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-062', 'UBS Vila Formosa', -22.1087, -51.3093, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-063', 'Comper Vila Formosa', -22.1457, -51.445, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-064', 'Extra Vila Formosa', -22.0261, -51.387, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-065', 'Assaí Atacadista Vila Formosa', -22.2074, -51.4795, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-066', 'Praça do Jardim Paraíso', -22.2037, -51.3634, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-067', 'UBS Jardim Paraíso', -22.0672, -51.4045, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-068', 'Comper Jardim Paraíso', -22.2129, -51.4126, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-069', 'Extra Jardim Paraíso', -22.0264, -51.3831, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-070', 'Assaí Atacadista Jardim Paraíso', -22.0314, -51.3167, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-071', 'Praça do Jardim Sumatra', -22.2233, -51.3448, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-072', 'UBS Jardim Sumatra', -22.0893, -51.3815, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-073', 'Comper Jardim Sumatra', -22.1722, -51.3607, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-074', 'Extra Jardim Sumatra', -22.2033, -51.4019, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-075', 'Assaí Atacadista Jardim Sumatra', -22.1349, -51.2981, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-076', 'Praça do Jardim Panorama', -22.0504, -51.4362, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-077', 'UBS Jardim Panorama', -22.1255, -51.4532, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-078', 'Comper Jardim Panorama', -22.0431, -51.3148, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-079', 'Extra Jardim Panorama', -22.1659, -51.3611, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-080', 'Assaí Atacadista Jardim Panorama', -22.1038, -51.4583, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-081', 'Praça do Vila Sperandio', -22.0731, -51.381, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-082', 'UBS Vila Sperandio', -22.0699, -51.3828, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-083', 'Comper Vila Sperandio', -22.2255, -51.4241, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-084', 'Extra Vila Sperandio', -22.2217, -51.3031, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-085', 'Assaí Atacadista Vila Sperandio', -22.0499, -51.3226, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-086', 'Praça do Jardim América', -22.1641, -51.4773, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-087', 'UBS Jardim América', -22.05, -51.2995, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-088', 'Comper Jardim América', -22.2085, -51.3917, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-089', 'Extra Jardim América', -22.2118, -51.3368, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-090', 'Assaí Atacadista Jardim América', -22.0724, -51.4632, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-091', 'Praça do Jardim Boa Esperança', -22.1305, -51.3789, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-092', 'UBS Jardim Boa Esperança', -22.1726, -51.3144, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-093', 'Comper Jardim Boa Esperança', -22.141, -51.4465, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-094', 'Extra Jardim Boa Esperança', -22.1177, -51.3429, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-095', 'Assaí Atacadista Jardim Boa Esperança', -22.1854, -51.4266, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-096', 'Praça do Jardim Ana Maria', -22.0266, -51.3589, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('pprudente-097', 'UBS Jardim Ana Maria', -22.138, -51.3854, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('pprudente-098', 'Comper Jardim Ana Maria', -22.2014, -51.444, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-099', 'Extra Jardim Ana Maria', -22.158, -51.3712, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('pprudente-100', 'Assaí Atacadista Jardim Ana Maria', -22.1796, -51.4449, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
