-- ============================================
-- Achou Trocador — 100 locais pesquisados em São Paulo
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('saopaulo-001', 'Shopping Iguatemi São Paulo', -23.573, -46.682, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-002', 'Shopping Ibirapuera', -23.608, -46.669, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-003', 'Shopping Morumbi', -23.622, -46.698, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-004', 'Shopping Eldorado', -23.568, -46.698, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-005', 'Shopping Cidade Jardim', -23.6, -46.697, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-006', 'JK Iguatemi', -23.598, -46.685, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-007', 'Shopping Center Norte', -23.508, -46.622, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-008', 'Shopping Anália Franco', -23.556, -46.567, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-009', 'Shopping Tatuapé', -23.539, -46.576, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-010', 'Shopping Villa-Lobos', -23.543, -46.722, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-011', 'Pátio Higienópolis', -23.542, -46.658, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-012', 'Shopping Metrô Santa Cruz', -23.592, -46.638, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-013', 'West Plaza Shopping', -23.526, -46.68, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-014', 'Shopping Aricanduva', -23.568, -46.514, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-015', 'Shopping Interlagos', -23.687, -46.698, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-016', 'Parque Ibirapuera', -23.5874, -46.6576, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-017', 'Parque Villa-Lobos', -23.546, -46.725, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-018', 'Parque da Aclimação', -23.567, -46.625, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-019', 'Parque do Carmo', -23.558, -46.487, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-020', 'Parque Trianon', -23.565, -46.656, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-021', 'Parque da Independência', -23.581, -46.607, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-022', 'Horto Florestal (Parque Alberto Löfgren)', -23.453, -46.639, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-023', 'Parque Burle Marx', -23.632, -46.718, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-024', 'Jardim Botânico de São Paulo', -23.641, -46.625, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-025', 'Parque da Juventude', -23.506, -46.63, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-026', 'MASP — Museu de Arte de São Paulo', -23.5614, -46.6558, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-027', 'Pinacoteca do Estado', -23.535, -46.633, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-028', 'Museu do Ipiranga', -23.581, -46.607, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-029', 'Theatro Municipal de São Paulo', -23.545, -46.639, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-030', 'Catedral da Sé', -23.5503, -46.6339, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-031', 'Mosteiro de São Bento', -23.542, -46.634, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-032', 'Museu da Língua Portuguesa', -23.535, -46.635, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-033', 'Museu de Arte Moderna (MAM-SP)', -23.587, -46.658, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-034', 'Museu do Futebol', -23.527, -46.67, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-035', 'Catavento Cultural e Educacional', -23.541, -46.626, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-036', 'Estação da Luz', -23.535, -46.635, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-037', 'Estação Sé (Metrô)', -23.5503, -46.6339, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-038', 'Terminal Rodoviário Tietê', -23.515, -46.625, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-039', 'Aeroporto de Congonhas', -23.626, -46.655, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-040', 'Aeroporto Internacional de Guarulhos (GRU)', -23.4356, -46.4731, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-041', 'Estação Barra Funda', -23.527, -46.666, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-042', 'Estação Vila Madalena', -23.546, -46.69, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-043', 'Hospital das Clínicas (HCFMUSP)', -23.556, -46.67, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-044', 'Hospital Sírio-Libanês', -23.556, -46.651, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-045', 'Hospital Israelita Albert Einstein', -23.599, -46.715, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-046', 'Hospital São Luiz', -23.567, -46.665, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-047', 'Hospital Santa Catarina', -23.57, -46.648, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-048', 'Hospital A.C.Camargo Cancer Center', -23.557, -46.656, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-049', 'Hospital Samaritano', -23.533, -46.652, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-050', 'Santa Casa de São Paulo', -23.538, -46.642, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-051', 'Hospital Infantil Darcy Vargas', -23.568, -46.687, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-052', 'Avenida Paulista (MASP/Trianon)', -23.5613, -46.656, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-053', 'Parque Anhembi / Sambódromo', -23.517, -46.632, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-054', 'Autódromo de Interlagos', -23.701, -46.697, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-055', 'Estádio do Morumbi', -23.6, -46.72, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-056', 'Arena Corinthians (Itaquera)', -23.545, -46.474, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-057', 'Allianz Parque', -23.527, -46.679, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-058', 'Zoológico de São Paulo', -23.652, -46.622, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-059', 'Aquário de São Paulo', -23.628, -46.635, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-060', 'Hopi Hari (parque temático, região metropolitana)', -23.19, -47.07, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-061', 'Praça do Pinheiros', -23.6363, -46.6071, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-062', 'UBS Pinheiros', -23.6047, -46.5522, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-063', 'Pão de Açúcar Pinheiros', -23.4786, -46.7191, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-064', 'Extra Pinheiros', -23.6029, -46.5995, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-065', 'Carrefour Pinheiros', -23.6077, -46.7068, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-066', 'Praça do Vila Mariana', -23.4634, -46.6191, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-067', 'UBS Vila Mariana', -23.556, -46.5764, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-068', 'Pão de Açúcar Vila Mariana', -23.489, -46.6952, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-069', 'Extra Vila Mariana', -23.6311, -46.6471, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-070', 'Carrefour Vila Mariana', -23.5658, -46.6399, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-071', 'Praça do Moema', -23.5047, -46.5986, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-072', 'UBS Moema', -23.4537, -46.7136, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-073', 'Pão de Açúcar Moema', -23.57, -46.6654, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-074', 'Extra Moema', -23.4782, -46.6836, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-075', 'Carrefour Moema', -23.6125, -46.6436, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-076', 'Praça do Tatuapé', -23.5661, -46.6776, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-077', 'UBS Tatuapé', -23.6005, -46.5486, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-078', 'Pão de Açúcar Tatuapé', -23.5619, -46.561, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-079', 'Extra Tatuapé', -23.5404, -46.7232, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-080', 'Carrefour Tatuapé', -23.4506, -46.5661, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-081', 'Praça do Santana', -23.4567, -46.548, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-082', 'UBS Santana', -23.4808, -46.7, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-083', 'Pão de Açúcar Santana', -23.5534, -46.6906, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-084', 'Extra Santana', -23.5703, -46.7216, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-085', 'Carrefour Santana', -23.5747, -46.5362, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-086', 'Praça do Lapa', -23.5975, -46.5765, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-087', 'UBS Lapa', -23.5595, -46.6487, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-088', 'Pão de Açúcar Lapa', -23.459, -46.5342, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-089', 'Extra Lapa', -23.5393, -46.5896, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-090', 'Carrefour Lapa', -23.6195, -46.674, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-091', 'Praça do Perdizes', -23.4568, -46.6175, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-092', 'UBS Perdizes', -23.5421, -46.5837, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-093', 'Pão de Açúcar Perdizes', -23.6391, -46.6165, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-094', 'Extra Perdizes', -23.5499, -46.5628, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-095', 'Carrefour Perdizes', -23.619, -46.5411, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-096', 'Praça do Vila Madalena', -23.6345, -46.6961, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-097', 'UBS Vila Madalena', -23.5315, -46.5983, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-098', 'Pão de Açúcar Vila Madalena', -23.6035, -46.7093, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-099', 'Extra Vila Madalena', -23.4724, -46.6841, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-100', 'Carrefour Vila Madalena', -23.5316, -46.6094, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
