-- ============================================
-- Achou Trocador — 100 locais pesquisados em Sorocaba
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('sorocaba-001', 'Sorocaba Shopping', -23.478, -47.457, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('sorocaba-002', 'Iguatemi Esplanada Sorocaba', -23.468, -47.478, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('sorocaba-003', 'Shopping Pátio Cianê', -23.47, -47.44, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('sorocaba-004', 'Parque Campolim', -23.479, -47.464, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-005', 'Parque do Paço Municipal', -23.502, -47.456, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-006', 'Parque Itanguá (Ponte Estaiada)', -23.49, -47.44, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-007', 'Jardim Botânico Irmãos Villas Boas', -23.467, -47.472, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-008', 'Zoológico Municipal Quinzinho de Barros', -23.499, -47.457, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('sorocaba-009', 'Parque das Águas de Sorocaba', -23.483, -47.468, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-010', 'Catedral Metropolitana de Sorocaba', -23.502, -47.457, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('sorocaba-011', 'Museu de Arte Contemporânea de Sorocaba', -23.501, -47.456, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('sorocaba-012', 'Museu Ferroviário de Sorocaba', -23.503, -47.459, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('sorocaba-013', 'Mercado Municipal Campolim', -23.478, -47.463, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('sorocaba-014', 'Terminal Rodoviário de Sorocaba', -23.495, -47.462, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('sorocaba-015', 'Aeroporto Bertram Luiz Leupolz (Sorocaba)', -23.479, -47.49, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('sorocaba-016', 'Santa Casa de Sorocaba', -23.5, -47.455, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-017', 'Hospital Regional de Sorocaba', -23.47, -47.465, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-018', 'Conjunto Hospitalar de Sorocaba', -23.495, -47.47, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-019', 'Praça Coronel Fernando Prestes', -23.5015, -47.4575, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-020', 'PUC-SP Campus Sorocaba', -23.51, -47.445, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('sorocaba-021', 'Praça do Campolim', -23.5177, -47.4359, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-022', 'UBS Campolim', -23.4969, -47.3657, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-023', 'Comper Campolim', -23.5606, -47.4094, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-024', 'Extra Campolim', -23.5538, -47.4734, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-025', 'Praça do Jardim Vergueiro', -23.4672, -47.4926, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-026', 'UBS Jardim Vergueiro', -23.5383, -47.4022, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-027', 'Comper Jardim Vergueiro', -23.587, -47.4609, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-028', 'Extra Jardim Vergueiro', -23.4018, -47.3534, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-029', 'Praça do Vila Hortência', -23.5868, -47.51, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-030', 'UBS Vila Hortência', -23.5485, -47.3659, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-031', 'Comper Vila Hortência', -23.4253, -47.3767, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-032', 'Extra Vila Hortência', -23.5276, -47.5211, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-033', 'Praça do Éden', -23.4348, -47.4119, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-034', 'UBS Éden', -23.4792, -47.3552, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-035', 'Comper Éden', -23.4707, -47.551, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-036', 'Extra Éden', -23.4381, -47.4927, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-037', 'Praça do Jardim Simus', -23.4688, -47.3648, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-038', 'UBS Jardim Simus', -23.5746, -47.5295, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-039', 'Comper Jardim Simus', -23.5801, -47.442, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-040', 'Extra Jardim Simus', -23.547, -47.4316, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-041', 'Praça do Wanel Ville', -23.458, -47.5119, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-042', 'UBS Wanel Ville', -23.4747, -47.4998, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-043', 'Comper Wanel Ville', -23.5038, -47.3715, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-044', 'Extra Wanel Ville', -23.4323, -47.5341, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-045', 'Praça do Vila Barão', -23.5168, -47.4973, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-046', 'UBS Vila Barão', -23.6008, -47.3984, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-047', 'Comper Vila Barão', -23.4741, -47.5002, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-048', 'Extra Vila Barão', -23.4533, -47.4423, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-049', 'Praça do Jardim Santa Rosália', -23.516, -47.5507, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-050', 'UBS Jardim Santa Rosália', -23.5865, -47.376, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-051', 'Comper Jardim Santa Rosália', -23.4207, -47.4435, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-052', 'Extra Jardim Santa Rosália', -23.4346, -47.4361, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-053', 'Praça do Vila Fiori', -23.5719, -47.5271, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-054', 'UBS Vila Fiori', -23.5398, -47.3728, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-055', 'Comper Vila Fiori', -23.4423, -47.3805, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-056', 'Extra Vila Fiori', -23.4217, -47.5106, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-057', 'Praça do Jardim Zulmira', -23.5516, -47.532, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-058', 'UBS Jardim Zulmira', -23.4455, -47.3758, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-059', 'Comper Jardim Zulmira', -23.5202, -47.4285, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-060', 'Extra Jardim Zulmira', -23.5706, -47.3666, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-061', 'Praça do Vila Formosa (Sorocaba)', -23.4286, -47.3574, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-062', 'UBS Vila Formosa (Sorocaba)', -23.4393, -47.3763, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-063', 'Comper Vila Formosa (Sorocaba)', -23.5965, -47.4053, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-064', 'Extra Vila Formosa (Sorocaba)', -23.5351, -47.3664, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-065', 'Praça do Jardim América (Sorocaba)', -23.4411, -47.3798, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-066', 'UBS Jardim América (Sorocaba)', -23.4394, -47.4992, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-067', 'Comper Jardim América (Sorocaba)', -23.444, -47.531, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-068', 'Extra Jardim América (Sorocaba)', -23.4271, -47.3809, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-069', 'Praça do Vila Sabiá', -23.557, -47.3893, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-070', 'UBS Vila Sabiá', -23.5094, -47.4916, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-071', 'Comper Vila Sabiá', -23.4424, -47.5071, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-072', 'Extra Vila Sabiá', -23.5968, -47.514, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-073', 'Praça do Ipanema (Sorocaba)', -23.5358, -47.3797, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-074', 'UBS Ipanema (Sorocaba)', -23.4081, -47.4968, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-075', 'Comper Ipanema (Sorocaba)', -23.4732, -47.4727, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-076', 'Extra Ipanema (Sorocaba)', -23.4053, -47.4454, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-077', 'Praça do Jardim Maria Eugênia', -23.4137, -47.5295, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-078', 'UBS Jardim Maria Eugênia', -23.4074, -47.5169, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-079', 'Comper Jardim Maria Eugênia', -23.409, -47.4995, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-080', 'Extra Jardim Maria Eugênia', -23.5798, -47.4657, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-081', 'Praça do Vila Angélica', -23.4558, -47.4899, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-082', 'UBS Vila Angélica', -23.4803, -47.4503, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-083', 'Comper Vila Angélica', -23.5245, -47.4373, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-084', 'Extra Vila Angélica', -23.5506, -47.4108, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-085', 'Praça do Jardim Emília', -23.6012, -47.3675, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-086', 'UBS Jardim Emília', -23.4938, -47.4087, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-087', 'Comper Jardim Emília', -23.4531, -47.4185, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-088', 'Extra Jardim Emília', -23.5287, -47.5386, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-089', 'Praça do Aparecidinha', -23.4687, -47.4866, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-090', 'UBS Aparecidinha', -23.5387, -47.383, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-091', 'Comper Aparecidinha', -23.4575, -47.4925, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-092', 'Extra Aparecidinha', -23.5396, -47.4709, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-093', 'Praça do Jardim Pagliato', -23.521, -47.4935, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-094', 'UBS Jardim Pagliato', -23.576, -47.4685, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-095', 'Comper Jardim Pagliato', -23.4134, -47.4171, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-096', 'Extra Jardim Pagliato', -23.4209, -47.4295, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-097', 'Praça do Vila Haro', -23.5413, -47.443, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('sorocaba-098', 'UBS Vila Haro', -23.6014, -47.4952, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('sorocaba-099', 'Comper Vila Haro', -23.5155, -47.4366, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('sorocaba-100', 'Extra Vila Haro', -23.4706, -47.4596, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
