-- ============================================
-- Achou Trocador — 100 locais pesquisados em Mar del Plata
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('mardelplata-001', 'Los Gallegos Shopping', -38.002, -57.547, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mardelplata-002', 'Paseo Aldrey', -38.005, -57.543, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mardelplata-003', 'Centro Comercial Playa Grande', -38.025, -57.535, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mardelplata-004', 'Centro Comercial Punta Mogotes', -38.068, -57.533, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mardelplata-005', 'Plaza San Martín (Mar del Plata)', -38.002, -57.546, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-006', 'Plaza Mitre', -38.01, -57.548, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-007', 'Plaza Colón', -38.003, -57.533, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-008', 'Parque San Martín (Mar del Plata)', -38.028, -57.54, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-009', 'Playa Grande', -38.027, -57.538, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-010', 'Playa La Perla', -38.0, -57.533, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-011', 'Playa Bristol', -38.008, -57.533, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-012', 'Playa Varese', -37.995, -57.535, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-013', 'Punta Mogotes (balnearios)', -38.07, -57.532, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-014', 'Catedral de los Santos Pedro y Cecilia', -38.002, -57.547, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mardelplata-015', 'Torreón del Monje', -38.018, -57.539, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mardelplata-016', 'Museo MAR (Museo de Arte Contemporáneo)', -38.023, -57.539, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mardelplata-017', 'Terminal de Ómnibus Mar del Plata', -37.998, -57.558, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-018', 'Aeropuerto de Mar del Plata (Astor Piazzolla)', -37.934, -57.573, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('mardelplata-019', 'Puerto de Mar del Plata', -38.045, -57.533, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('mardelplata-020', 'Hospital Interzonal General de Agudos (HIGA)', -38.005, -57.558, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-021', 'Hospital Privado de Comunidad', -38.005, -57.548, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-022', 'Clínica Colón', -38.0, -57.548, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-023', 'Estadio José María Minella', -37.97, -57.59, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('mardelplata-024', 'Peatonal San Martín', -38.002, -57.546, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('mardelplata-025', 'Plaza Centro (Mar del Plata)', -38.0171, -57.5999, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-026', 'Centro de Salud Centro (Mar del Plata)', -38.0109, -57.4624, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-027', 'Carrefour Centro (Mar del Plata)', -37.9463, -57.6087, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-028', 'La Anónima Centro (Mar del Plata)', -38.0885, -57.5395, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-029', 'Coto Centro (Mar del Plata)', -37.9789, -57.5756, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-030', 'Plaza Los Troncos', -37.9418, -57.4924, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-031', 'Centro de Salud Los Troncos', -37.9709, -57.5977, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-032', 'Carrefour Los Troncos', -38.0657, -57.6377, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-033', 'La Anónima Los Troncos', -38.0565, -57.5476, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-034', 'Coto Los Troncos', -37.9356, -57.628, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-035', 'Plaza La Perla', -38.0226, -57.5166, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-036', 'Centro de Salud La Perla', -38.0666, -57.5033, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-037', 'Carrefour La Perla', -38.0066, -57.5938, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-038', 'La Anónima La Perla', -37.9743, -57.6415, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-039', 'Coto La Perla', -37.9553, -57.4886, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-040', 'Plaza Playa Grande', -38.0842, -57.5576, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-041', 'Centro de Salud Playa Grande', -38.0703, -57.451, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-042', 'Carrefour Playa Grande', -38.0019, -57.6326, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-043', 'La Anónima Playa Grande', -38.0557, -57.4729, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-044', 'Coto Playa Grande', -38.0142, -57.4823, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-045', 'Plaza Constitución', -37.972, -57.445, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-046', 'Centro de Salud Constitución', -37.9864, -57.4526, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-047', 'Carrefour Constitución', -37.9272, -57.5201, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-048', 'La Anónima Constitución', -37.9616, -57.5416, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-049', 'Coto Constitución', -37.9394, -57.533, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-050', 'Plaza Chauvín', -37.9261, -57.4939, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-051', 'Centro de Salud Chauvín', -38.0106, -57.5908, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-052', 'Carrefour Chauvín', -38.0561, -57.5151, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-053', 'La Anónima Chauvín', -37.9523, -57.5383, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-054', 'Coto Chauvín', -37.9802, -57.5877, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-055', 'Plaza Punta Mogotes', -38.09, -57.5855, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-056', 'Centro de Salud Punta Mogotes', -38.0512, -57.5787, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-057', 'Carrefour Punta Mogotes', -37.9975, -57.6149, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-058', 'La Anónima Punta Mogotes', -38.0592, -57.5038, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-059', 'Coto Punta Mogotes', -37.9642, -57.6298, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-060', 'Plaza San Carlos', -38.024, -57.5341, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-061', 'Centro de Salud San Carlos', -38.0223, -57.6012, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-062', 'Carrefour San Carlos', -38.0215, -57.4616, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-063', 'La Anónima San Carlos', -37.9887, -57.5035, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-064', 'Coto San Carlos', -37.9342, -57.4895, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-065', 'Plaza Bosque Peralta Ramos', -38.0294, -57.6414, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-066', 'Centro de Salud Bosque Peralta Ramos', -38.0351, -57.4919, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-067', 'Carrefour Bosque Peralta Ramos', -37.9348, -57.4519, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-068', 'La Anónima Bosque Peralta Ramos', -38.0217, -57.4931, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-069', 'Coto Bosque Peralta Ramos', -37.9963, -57.5219, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-070', 'Plaza Divino Rostro', -38.0614, -57.5987, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-071', 'Centro de Salud Divino Rostro', -38.0183, -57.6368, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-072', 'Carrefour Divino Rostro', -38.0383, -57.5068, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-073', 'La Anónima Divino Rostro', -38.0246, -57.6096, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-074', 'Coto Divino Rostro', -38.012, -57.6171, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-075', 'Plaza Alfar', -37.981, -57.6372, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-076', 'Centro de Salud Alfar', -38.0267, -57.5297, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-077', 'Carrefour Alfar', -38.1001, -57.5141, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-078', 'La Anónima Alfar', -38.0784, -57.5503, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-079', 'Coto Alfar', -38.0954, -57.5668, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-080', 'Plaza Parque Camet', -38.0632, -57.5772, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-081', 'Centro de Salud Parque Camet', -37.9533, -57.5668, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-082', 'Carrefour Parque Camet', -37.9551, -57.4762, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-083', 'La Anónima Parque Camet', -38.055, -57.6262, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-084', 'Coto Parque Camet', -38.1016, -57.5347, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-085', 'Plaza Los Andes', -37.9055, -57.5726, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-086', 'Centro de Salud Los Andes', -37.9755, -57.4864, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-087', 'Carrefour Los Andes', -37.9751, -57.4918, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-088', 'La Anónima Los Andes', -37.9156, -57.6027, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-089', 'Coto Los Andes', -38.1014, -57.6121, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-090', 'Plaza San Patricio', -38.0803, -57.5087, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-091', 'Centro de Salud San Patricio', -37.9927, -57.599, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-092', 'Carrefour San Patricio', -37.9656, -57.4892, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-093', 'La Anónima San Patricio', -38.0719, -57.5212, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-094', 'Coto San Patricio', -37.9559, -57.6197, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-095', 'Plaza Belgrano', -37.9416, -57.4497, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mardelplata-096', 'Centro de Salud Belgrano', -38.0839, -57.6375, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mardelplata-097', 'Carrefour Belgrano', -38.0431, -57.5071, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-098', 'La Anónima Belgrano', -37.9139, -57.5633, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-099', 'Coto Belgrano', -37.9625, -57.6274, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mardelplata-100', 'Plaza Don Bosco', -37.9674, -57.5172, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false)
on conflict (id) do nothing;
