-- ============================================
-- Achou Trocador — 100 locais pesquisados em Mendoza
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('mendoza-001', 'Mendoza Plaza Shopping', -32.928, -68.828, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mendoza-002', 'Palmares Open Mall', -32.955, -68.86, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mendoza-003', 'Paseo Alameda', -32.89, -68.845, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('mendoza-004', 'Parque General San Martín', -32.895, -68.87, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-005', 'Plaza Independencia', -32.89, -68.845, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-006', 'Plaza España', -32.893, -68.846, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-007', 'Plaza Italia (Mendoza)', -32.887, -68.838, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-008', 'Plaza Chile', -32.887, -68.851, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-009', 'Plaza San Martín (Mendoza)', -32.894, -68.842, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-010', 'Cerro de la Gloria', -32.903, -68.88, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-011', 'Terminal de Ómnibus de Mendoza', -32.892, -68.838, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('mendoza-012', 'Aeropuerto Internacional de Mendoza (El Plumerillo)', -32.832, -68.793, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('mendoza-013', 'Hospital Central de Mendoza', -32.888, -68.84, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-014', 'Hospital Universitario (Mendoza)', -32.883, -68.844, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-015', 'Hospital Notti (Pediátrico)', -32.902, -68.856, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-016', 'Museo Fundacional', -32.89, -68.839, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mendoza-017', 'Área Fundacional de Mendoza', -32.8895, -68.8395, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mendoza-018', 'Teatro Independencia', -32.8895, -68.8455, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('mendoza-019', 'Mercado Central de Mendoza', -32.889, -68.835, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('mendoza-020', 'Estadio Malvinas Argentinas', -32.925, -68.859, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('mendoza-021', 'Plaza Ciudad (Mendoza)', -32.9691, -68.7913, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-022', 'Centro de Salud Ciudad (Mendoza)', -32.8194, -68.8257, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-023', 'Carrefour Ciudad (Mendoza)', -32.9653, -68.749, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-024', 'Vea Ciudad (Mendoza)', -32.833, -68.8764, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-025', 'Jumbo Ciudad (Mendoza)', -32.9038, -68.8717, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-026', 'Plaza Godoy Cruz', -32.8883, -68.8776, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-027', 'Centro de Salud Godoy Cruz', -32.8196, -68.7813, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-028', 'Carrefour Godoy Cruz', -32.9684, -68.7536, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-029', 'Vea Godoy Cruz', -32.8624, -68.7801, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-030', 'Jumbo Godoy Cruz', -32.848, -68.8587, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-031', 'Plaza Guaymallén', -32.8427, -68.7527, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-032', 'Centro de Salud Guaymallén', -32.9355, -68.7842, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-033', 'Carrefour Guaymallén', -32.8819, -68.8491, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-034', 'Vea Guaymallén', -32.9024, -68.7996, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-035', 'Jumbo Guaymallén', -32.9358, -68.7755, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-036', 'Plaza Las Heras', -32.8234, -68.9285, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-037', 'Centro de Salud Las Heras', -32.8132, -68.897, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-038', 'Carrefour Las Heras', -32.8966, -68.8237, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-039', 'Vea Las Heras', -32.9137, -68.9401, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-040', 'Jumbo Las Heras', -32.8193, -68.9094, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-041', 'Plaza Maipú', -32.9471, -68.7862, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-042', 'Centro de Salud Maipú', -32.9214, -68.7697, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-043', 'Carrefour Maipú', -32.8493, -68.8905, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-044', 'Vea Maipú', -32.9875, -68.7562, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-045', 'Jumbo Maipú', -32.9724, -68.8018, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-046', 'Plaza Luján de Cuyo', -32.8918, -68.7942, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-047', 'Centro de Salud Luján de Cuyo', -32.8514, -68.8166, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-048', 'Carrefour Luján de Cuyo', -32.8913, -68.7872, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-049', 'Vea Luján de Cuyo', -32.9709, -68.9015, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-050', 'Jumbo Luján de Cuyo', -32.8511, -68.8846, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-051', 'Plaza Chacras de Coria', -32.8732, -68.8511, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-052', 'Centro de Salud Chacras de Coria', -32.8833, -68.8607, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-053', 'Carrefour Chacras de Coria', -32.8403, -68.8796, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-054', 'Vea Chacras de Coria', -32.8489, -68.8916, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-055', 'Jumbo Chacras de Coria', -32.9392, -68.9217, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-056', 'Plaza Dorrego', -32.951, -68.9219, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-057', 'Centro de Salud Dorrego', -32.8823, -68.7934, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-058', 'Carrefour Dorrego', -32.9525, -68.9025, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-059', 'Vea Dorrego', -32.8927, -68.8009, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-060', 'Jumbo Dorrego', -32.7942, -68.8409, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-061', 'Plaza San José (Guaymallén)', -32.9329, -68.9257, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-062', 'Centro de Salud San José (Guaymallén)', -32.9507, -68.9003, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-063', 'Carrefour San José (Guaymallén)', -32.9536, -68.943, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-064', 'Vea San José (Guaymallén)', -32.8827, -68.8909, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-065', 'Jumbo San José (Guaymallén)', -32.7946, -68.8351, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-066', 'Plaza Bermejo', -32.85, -68.9205, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-067', 'Centro de Salud Bermejo', -32.8158, -68.8476, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-068', 'Carrefour Bermejo', -32.815, -68.831, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-069', 'Vea Bermejo', -32.8956, -68.8577, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-070', 'Jumbo Bermejo', -32.9526, -68.9355, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-071', 'Plaza Villa Nueva', -32.8013, -68.8503, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-072', 'Centro de Salud Villa Nueva', -32.8251, -68.8657, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-073', 'Carrefour Villa Nueva', -32.9747, -68.8199, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-074', 'Vea Villa Nueva', -32.9788, -68.916, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-075', 'Jumbo Villa Nueva', -32.8769, -68.885, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-076', 'Plaza Rodeo de la Cruz', -32.7907, -68.9221, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-077', 'Centro de Salud Rodeo de la Cruz', -32.8366, -68.8245, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-078', 'Carrefour Rodeo de la Cruz', -32.8314, -68.9007, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-079', 'Vea Rodeo de la Cruz', -32.885, -68.8557, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-080', 'Jumbo Rodeo de la Cruz', -32.901, -68.7738, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-081', 'Plaza Coquimbito', -32.7915, -68.8847, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-082', 'Centro de Salud Coquimbito', -32.8653, -68.8239, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-083', 'Carrefour Coquimbito', -32.8415, -68.7563, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-084', 'Vea Coquimbito', -32.9479, -68.9036, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-085', 'Jumbo Coquimbito', -32.8574, -68.9144, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-086', 'Plaza Fray Luis Beltrán', -32.9547, -68.9308, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-087', 'Centro de Salud Fray Luis Beltrán', -32.989, -68.8557, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-088', 'Carrefour Fray Luis Beltrán', -32.8707, -68.8875, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-089', 'Vea Fray Luis Beltrán', -32.9432, -68.8044, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-090', 'Jumbo Fray Luis Beltrán', -32.8489, -68.855, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-091', 'Plaza Vistalba', -32.852, -68.761, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-092', 'Centro de Salud Vistalba', -32.8319, -68.8208, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-093', 'Carrefour Vistalba', -32.8573, -68.7591, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-094', 'Vea Vistalba', -32.9045, -68.8369, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-095', 'Jumbo Vistalba', -32.86, -68.7641, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-096', 'Plaza Perdriel', -32.8242, -68.9315, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('mendoza-097', 'Centro de Salud Perdriel', -32.9563, -68.8843, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('mendoza-098', 'Carrefour Perdriel', -32.8397, -68.832, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-099', 'Vea Perdriel', -32.9318, -68.9209, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('mendoza-100', 'Jumbo Perdriel', -32.8518, -68.8059, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
