-- ============================================
-- Achou Trocador — 100 locais pesquisados em Córdoba
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('cordoba-001', 'Nuevocentro Shopping', -31.431, -64.199, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('cordoba-002', 'Patio Olmos Shopping', -31.416, -64.183, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('cordoba-003', 'Córdoba Shopping Villa Cabrera', -31.383, -64.227, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('cordoba-004', 'Dinosaurio Mall', -31.398, -64.234, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('cordoba-005', 'Parque Sarmiento', -31.427, -64.184, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-006', 'Plaza San Martín (Córdoba)', -31.42, -64.188, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-007', 'Plaza España (Córdoba)', -31.413, -64.192, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-008', 'Parque Las Heras', -31.435, -64.175, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-009', 'Parque de la Biodiversidad', -31.385, -64.245, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-010', 'Paseo Sobremonte', -31.413, -64.178, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-011', 'Catedral de Córdoba', -31.419, -64.1875, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('cordoba-012', 'Manzana Jesuítica (Museo)', -31.42, -64.187, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('cordoba-013', 'Museo Superior de Bellas Artes Evita', -31.423, -64.177, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('cordoba-014', 'Mercado Norte', -31.416, -64.185, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('cordoba-015', 'Mercado Sur', -31.423, -64.188, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('cordoba-016', 'Terminal de Ómnibus de Córdoba', -31.418, -64.18, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('cordoba-017', 'Aeropuerto Internacional de Córdoba (Ingeniero Taravella)', -31.3236, -64.2081, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('cordoba-018', 'Hospital Nacional de Clínicas (Córdoba)', -31.418, -64.197, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-019', 'Hospital Pediátrico del Niño Jesús', -31.398, -64.201, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-020', 'Hospital Privado Universitario de Córdoba', -31.405, -64.197, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-021', 'Estadio Mario Alberto Kempes', -31.335, -64.226, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('cordoba-022', 'Plaza Nueva Córdoba', -31.3316, -64.1887, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-023', 'Centro de Salud Nueva Córdoba', -31.4213, -64.2727, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-024', 'Carrefour Nueva Córdoba', -31.5121, -64.2024, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-025', 'Disco Nueva Córdoba', -31.4556, -64.2387, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-026', 'Libertad Nueva Córdoba', -31.5018, -64.0964, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-027', 'Plaza Alberdi', -31.3529, -64.1738, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-028', 'Centro de Salud Alberdi', -31.3299, -64.0889, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-029', 'Carrefour Alberdi', -31.3856, -64.2349, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-030', 'Disco Alberdi', -31.5121, -64.1375, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-031', 'Libertad Alberdi', -31.426, -64.1585, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-032', 'Plaza Alta Córdoba', -31.3369, -64.2525, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-033', 'Centro de Salud Alta Córdoba', -31.403, -64.1618, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-034', 'Carrefour Alta Córdoba', -31.4218, -64.2706, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-035', 'Disco Alta Córdoba', -31.4505, -64.2221, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-036', 'Libertad Alta Córdoba', -31.3861, -64.1173, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-037', 'Plaza Cerro de las Rosas', -31.4541, -64.1501, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-038', 'Centro de Salud Cerro de las Rosas', -31.4625, -64.0998, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-039', 'Carrefour Cerro de las Rosas', -31.3574, -64.1788, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-040', 'Disco Cerro de las Rosas', -31.4291, -64.2259, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-041', 'Libertad Cerro de las Rosas', -31.4554, -64.0948, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-042', 'Plaza Güemes', -31.4393, -64.1859, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-043', 'Centro de Salud Güemes', -31.3225, -64.1573, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-044', 'Carrefour Güemes', -31.4116, -64.2062, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-045', 'Disco Güemes', -31.4826, -64.2164, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-046', 'Libertad Güemes', -31.3688, -64.1637, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-047', 'Plaza General Paz', -31.3681, -64.2481, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-048', 'Centro de Salud General Paz', -31.4103, -64.1033, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-049', 'Carrefour General Paz', -31.4325, -64.1491, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-050', 'Disco General Paz', -31.4958, -64.0942, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-051', 'Libertad General Paz', -31.3983, -64.2409, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-052', 'Plaza Villa Cabrera', -31.4884, -64.1786, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-053', 'Centro de Salud Villa Cabrera', -31.4096, -64.2702, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-054', 'Carrefour Villa Cabrera', -31.3216, -64.1062, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-055', 'Disco Villa Cabrera', -31.4278, -64.2653, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-056', 'Libertad Villa Cabrera', -31.3537, -64.1891, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-057', 'Plaza Providencia', -31.3768, -64.187, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-058', 'Centro de Salud Providencia', -31.4654, -64.1219, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-059', 'Carrefour Providencia', -31.3241, -64.2401, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-060', 'Disco Providencia', -31.4098, -64.2121, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-061', 'Libertad Providencia', -31.3357, -64.1872, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-062', 'Plaza Yofre Norte', -31.3442, -64.116, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-063', 'Centro de Salud Yofre Norte', -31.4649, -64.1308, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-064', 'Carrefour Yofre Norte', -31.4371, -64.102, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-065', 'Disco Yofre Norte', -31.4186, -64.1247, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-066', 'Libertad Yofre Norte', -31.4635, -64.2291, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-067', 'Plaza San Vicente', -31.4027, -64.089, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-068', 'Centro de Salud San Vicente', -31.4222, -64.2591, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-069', 'Carrefour San Vicente', -31.4124, -64.2198, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-070', 'Disco San Vicente', -31.4097, -64.1801, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-071', 'Libertad San Vicente', -31.429, -64.2244, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-072', 'Plaza Villa Belgrano', -31.4824, -64.1493, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-073', 'Centro de Salud Villa Belgrano', -31.4057, -64.2421, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-074', 'Carrefour Villa Belgrano', -31.365, -64.2801, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-075', 'Disco Villa Belgrano', -31.3712, -64.1478, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-076', 'Libertad Villa Belgrano', -31.3578, -64.2116, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-077', 'Plaza Argüello', -31.3874, -64.1247, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-078', 'Centro de Salud Argüello', -31.3239, -64.1897, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-079', 'Carrefour Argüello', -31.5127, -64.1883, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-080', 'Disco Argüello', -31.4021, -64.1149, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-081', 'Libertad Argüello', -31.3453, -64.2007, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-082', 'Plaza Jardín', -31.4149, -64.1974, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-083', 'Centro de Salud Jardín', -31.3756, -64.2068, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-084', 'Carrefour Jardín', -31.3891, -64.2579, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-085', 'Disco Jardín', -31.4262, -64.095, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-086', 'Libertad Jardín', -31.4524, -64.1503, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-087', 'Plaza Poeta Lugones', -31.3901, -64.1184, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-088', 'Centro de Salud Poeta Lugones', -31.3496, -64.1169, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-089', 'Carrefour Poeta Lugones', -31.4441, -64.2255, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-090', 'Disco Poeta Lugones', -31.3764, -64.1369, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-091', 'Libertad Poeta Lugones', -31.3456, -64.2816, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-092', 'Plaza Ciudad Universitaria', -31.5064, -64.1626, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-093', 'Centro de Salud Ciudad Universitaria', -31.3359, -64.0893, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-094', 'Carrefour Ciudad Universitaria', -31.3707, -64.202, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-095', 'Disco Ciudad Universitaria', -31.5004, -64.1621, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-096', 'Libertad Ciudad Universitaria', -31.3456, -64.2001, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-097', 'Plaza Rogelio Martínez', -31.3813, -64.1081, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('cordoba-098', 'Centro de Salud Rogelio Martínez', -31.5109, -64.1296, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('cordoba-099', 'Carrefour Rogelio Martínez', -31.4614, -64.2138, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('cordoba-100', 'Disco Rogelio Martínez', -31.491, -64.1826, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
