-- ============================================
-- Achou Trocador — 100 locais pesquisados em Rosario
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('rosario-001', 'Alto Rosario Shopping', -32.943, -60.658, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('rosario-002', 'Portal Rosario Shopping', -32.97, -60.635, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('rosario-003', 'Shopping del Siglo', -32.944, -60.639, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('rosario-004', 'Village Rosario', -32.925, -60.665, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('rosario-005', 'Parque Urquiza', -32.933, -60.628, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-006', 'Parque de la Independencia', -32.954, -60.665, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-007', 'Parque España (Rosario)', -32.945, -60.632, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-008', 'Plaza 25 de Mayo', -32.947, -60.639, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-009', 'Plaza San Martín (Rosario)', -32.944, -60.636, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-010', 'Plaza Pringles', -32.949, -60.642, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-011', 'Monumento a la Bandera', -32.942, -60.631, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('rosario-012', 'Museo MACRO', -32.937, -60.628, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('rosario-013', 'Centro Cultural Bernardino Rivadavia', -32.944, -60.64, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('rosario-014', 'Museo de los Niños (Alto Rosario)', -32.943, -60.658, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('rosario-015', 'Terminal de Ómnibus Mariano Moreno', -32.949, -60.628, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('rosario-016', 'Aeropuerto Internacional Rosario (Islas Malvinas)', -32.9036, -60.785, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('rosario-017', 'Hospital Provincial del Centenario', -32.933, -60.665, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-018', 'Hospital de Niños Víctor J. Vilela', -32.946, -60.654, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-019', 'Hospital Italiano de Rosario', -32.927, -60.657, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-020', 'Estadio Gigante de Arroyito', -32.927, -60.628, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('rosario-021', 'Plaza Centro (Rosario)', -32.931, -60.592, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-022', 'Centro de Salud Centro (Rosario)', -33.0102, -60.7347, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-023', 'Carrefour Centro (Rosario)', -32.87, -60.6266, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-024', 'Coto Centro (Rosario)', -32.996, -60.5679, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-025', 'La Reina Centro (Rosario)', -33.0156, -60.6583, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-026', 'Plaza Pichincha', -32.9934, -60.6994, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-027', 'Centro de Salud Pichincha', -33.0423, -60.5896, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-028', 'Carrefour Pichincha', -32.864, -60.615, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-029', 'Coto Pichincha', -33.0126, -60.6622, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-030', 'La Reina Pichincha', -32.9751, -60.633, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-031', 'Plaza Fisherton', -32.9164, -60.6656, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-032', 'Centro de Salud Fisherton', -32.9942, -60.5814, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-033', 'Carrefour Fisherton', -33.0044, -60.6736, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-034', 'Coto Fisherton', -32.9476, -60.7031, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-035', 'La Reina Fisherton', -32.9298, -60.6355, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-036', 'Plaza Alberdi', -32.8457, -60.6915, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-037', 'Centro de Salud Alberdi', -32.8486, -60.6189, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-038', 'Carrefour Alberdi', -32.9893, -60.6373, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-039', 'Coto Alberdi', -32.907, -60.6016, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-040', 'La Reina Alberdi', -33.0344, -60.6292, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-041', 'Plaza Refinería', -32.9449, -60.5697, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-042', 'Centro de Salud Refinería', -32.987, -60.5907, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-043', 'Carrefour Refinería', -32.9228, -60.68, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-044', 'Coto Refinería', -32.9169, -60.6263, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-045', 'La Reina Refinería', -32.9086, -60.6063, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-046', 'Plaza Echesortu', -32.9124, -60.5828, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-047', 'Centro de Salud Echesortu', -32.9186, -60.5698, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-048', 'Carrefour Echesortu', -32.9149, -60.6887, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-049', 'Coto Echesortu', -32.956, -60.6346, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-050', 'La Reina Echesortu', -32.8977, -60.7325, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-051', 'Plaza Parque Field', -32.9852, -60.601, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-052', 'Centro de Salud Parque Field', -33.0091, -60.7241, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-053', 'Carrefour Parque Field', -32.9363, -60.5562, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-054', 'Coto Parque Field', -32.938, -60.5678, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-055', 'La Reina Parque Field', -32.8781, -60.6991, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-056', 'Plaza Martin', -32.8793, -60.6541, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-057', 'Centro de Salud Martin', -32.8829, -60.6012, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-058', 'Carrefour Martin', -32.9765, -60.7275, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-059', 'Coto Martin', -32.8516, -60.7223, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-060', 'La Reina Martin', -32.8509, -60.5785, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-061', 'Plaza Tablada', -32.8994, -60.5545, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-062', 'Centro de Salud Tablada', -32.8507, -60.5896, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-063', 'Carrefour Tablada', -32.971, -60.5924, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-064', 'Coto Tablada', -33.0414, -60.6432, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-065', 'La Reina Tablada', -32.9532, -60.6159, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-066', 'Plaza Empalme Graneros', -32.9097, -60.6336, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-067', 'Centro de Salud Empalme Graneros', -32.8797, -60.5624, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-068', 'Carrefour Empalme Graneros', -33.0225, -60.7037, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-069', 'Coto Empalme Graneros', -33.0392, -60.5737, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-070', 'La Reina Empalme Graneros', -32.9319, -60.5674, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-071', 'Plaza Ludueña', -32.9999, -60.7379, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-072', 'Centro de Salud Ludueña', -32.8794, -60.5686, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-073', 'Carrefour Ludueña', -32.9838, -60.6688, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-074', 'Coto Ludueña', -33.0162, -60.5612, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-075', 'La Reina Ludueña', -32.9833, -60.652, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-076', 'Plaza Villa Manuelita', -33.0248, -60.573, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-077', 'Centro de Salud Villa Manuelita', -33.0171, -60.6598, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-078', 'Carrefour Villa Manuelita', -32.9101, -60.6019, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-079', 'Coto Villa Manuelita', -32.855, -60.6667, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-080', 'La Reina Villa Manuelita', -32.8957, -60.7196, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-081', 'Plaza Saladillo', -32.9612, -60.7307, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-082', 'Centro de Salud Saladillo', -32.9463, -60.6689, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-083', 'Carrefour Saladillo', -32.8539, -60.744, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-084', 'Coto Saladillo', -32.9701, -60.6618, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-085', 'La Reina Saladillo', -32.8541, -60.5794, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-086', 'Plaza Antártida Argentina', -33.0243, -60.6134, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-087', 'Centro de Salud Antártida Argentina', -32.9353, -60.5549, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-088', 'Carrefour Antártida Argentina', -32.9725, -60.6709, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-089', 'Coto Antártida Argentina', -33.0062, -60.7261, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-090', 'La Reina Antártida Argentina', -32.8746, -60.6596, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-091', 'Plaza Rucci', -32.9116, -60.6222, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-092', 'Centro de Salud Rucci', -32.9248, -60.7462, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-093', 'Carrefour Rucci', -32.8868, -60.7018, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-094', 'Coto Rucci', -33.019, -60.6376, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-095', 'La Reina Rucci', -33.0305, -60.5975, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-096', 'Plaza Belgrano (Rosario)', -33.0028, -60.7073, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('rosario-097', 'Centro de Salud Belgrano (Rosario)', -32.8703, -60.6848, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('rosario-098', 'Carrefour Belgrano (Rosario)', -33.0147, -60.5704, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-099', 'Coto Belgrano (Rosario)', -33.0436, -60.5788, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('rosario-100', 'La Reina Belgrano (Rosario)', -33.0153, -60.7245, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
