-- ============================================
-- Achou Trocador — 100 locais pesquisados em Porto Alegre
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('portoalegre-001', 'BarraShoppingSul', -30.115, -51.235, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-002', 'Shopping Iguatemi Porto Alegre', -30.101, -51.197, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-003', 'Praia de Belas Shopping', -30.047, -51.228, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-004', 'Bourbon Country Shopping', -30.023, -51.213, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-005', 'Bourbon Shopping Ipiranga', -30.073, -51.207, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-006', 'Shopping Total Porto Alegre', -30.063, -51.172, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('portoalegre-007', 'Parque Moinhos de Vento (Parcão)', -30.025, -51.202, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-008', 'Parque Germânia', -30.033, -51.187, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-009', 'Parque Marinha do Brasil', -30.05, -51.233, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-010', 'Parque Farroupilha (Redenção)', -30.035, -51.216, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-011', 'Usina do Gasômetro', -30.033, -51.24, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('portoalegre-012', 'Mercado Público de Porto Alegre', -30.029, -51.228, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('portoalegre-013', 'Catedral Metropolitana de Porto Alegre', -30.033, -51.23, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('portoalegre-014', 'Museu de Arte do Rio Grande do Sul (MARGS)', -30.029, -51.229, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('portoalegre-015', 'Estádio Beira-Rio', -30.066, -51.235, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('portoalegre-016', 'Estádio Arena do Grêmio', -29.999, -51.235, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('portoalegre-017', 'Terminal Rodoviário de Porto Alegre', -30.03, -51.22, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('portoalegre-018', 'Aeroporto Internacional Salgado Filho', -29.993, -51.171, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('portoalegre-019', 'Hospital Moinhos de Vento', -30.025, -51.205, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-020', 'Hospital de Clínicas de Porto Alegre', -30.04, -51.21, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-021', 'Hospital Cristo Redentor', -29.995, -51.185, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-022', 'Hospital Nossa Senhora da Conceição', -29.992, -51.19, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-023', 'Hospital São Lucas (PUCRS)', -30.055, -51.174, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-024', 'Praça do Moinhos de Vento', -30.0845, -51.2828, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-025', 'UBS Moinhos de Vento', -30.0024, -51.3125, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-026', 'Zaffari Moinhos de Vento', -30.1316, -51.1597, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-027', 'Carrefour Moinhos de Vento', -30.087, -51.2529, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-028', 'Nacional Moinhos de Vento', -30.0998, -51.3072, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-029', 'Praça do Bela Vista', -29.9863, -51.2125, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-030', 'UBS Bela Vista', -29.9855, -51.2225, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-031', 'Zaffari Bela Vista', -29.979, -51.2151, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-032', 'Carrefour Bela Vista', -30.1128, -51.2169, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-033', 'Nacional Bela Vista', -29.9455, -51.309, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-034', 'Praça do Petrópolis', -29.978, -51.1443, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-035', 'UBS Petrópolis', -30.0303, -51.2261, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-036', 'Zaffari Petrópolis', -29.9418, -51.3055, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-037', 'Carrefour Petrópolis', -30.0388, -51.2374, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-038', 'Nacional Petrópolis', -29.9974, -51.2196, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-039', 'Praça do Menino Deus', -29.9527, -51.303, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-040', 'UBS Menino Deus', -30.1184, -51.196, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-041', 'Zaffari Menino Deus', -30.1215, -51.2627, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-042', 'Carrefour Menino Deus', -30.008, -51.208, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-043', 'Nacional Menino Deus', -30.0696, -51.1188, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-044', 'Praça do Cidade Baixa', -30.0285, -51.227, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-045', 'UBS Cidade Baixa', -30.0135, -51.2979, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-046', 'Zaffari Cidade Baixa', -29.9942, -51.1471, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-047', 'Carrefour Cidade Baixa', -30.0044, -51.1639, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-048', 'Nacional Cidade Baixa', -29.9904, -51.2747, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-049', 'Praça do Bom Fim', -30.0443, -51.272, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-050', 'UBS Bom Fim', -30.0668, -51.227, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-051', 'Zaffari Bom Fim', -30.0514, -51.2987, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-052', 'Carrefour Bom Fim', -30.0492, -51.1847, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-053', 'Nacional Bom Fim', -30.0597, -51.2872, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-054', 'Praça do Rio Branco', -29.95, -51.3043, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-055', 'UBS Rio Branco', -29.9682, -51.2991, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-056', 'Zaffari Rio Branco', -30.1153, -51.1699, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-057', 'Carrefour Rio Branco', -29.9722, -51.2064, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-058', 'Nacional Rio Branco', -30.0173, -51.2054, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-059', 'Praça do Auxiliadora', -30.0687, -51.2933, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-060', 'UBS Auxiliadora', -30.0639, -51.1846, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-061', 'Zaffari Auxiliadora', -29.9845, -51.1441, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-062', 'Carrefour Auxiliadora', -29.9904, -51.124, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-063', 'Nacional Auxiliadora', -30.0145, -51.2474, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-064', 'Praça do Higienópolis', -30.019, -51.2752, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-065', 'UBS Higienópolis', -30.0033, -51.2729, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-066', 'Zaffari Higienópolis', -30.113, -51.1486, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-067', 'Carrefour Higienópolis', -30.0611, -51.1652, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-068', 'Nacional Higienópolis', -30.0198, -51.1563, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-069', 'Praça do Santana', -29.9656, -51.1228, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-070', 'UBS Santana', -29.9709, -51.195, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-071', 'Zaffari Santana', -30.0061, -51.3124, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-072', 'Carrefour Santana', -29.9488, -51.1518, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-073', 'Nacional Santana', -30.0811, -51.2816, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-074', 'Praça do Farroupilha', -29.9941, -51.2559, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-075', 'UBS Farroupilha', -30.0666, -51.3165, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-076', 'Zaffari Farroupilha', -29.9606, -51.2044, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-077', 'Carrefour Farroupilha', -30.0544, -51.2893, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-078', 'Nacional Farroupilha', -30.008, -51.3116, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-079', 'Praça do Praia de Belas', -29.9854, -51.2747, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-080', 'UBS Praia de Belas', -30.0506, -51.2495, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-081', 'Zaffari Praia de Belas', -30.0606, -51.1734, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-082', 'Carrefour Praia de Belas', -29.9792, -51.2042, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-083', 'Nacional Praia de Belas', -30.1176, -51.3072, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-084', 'Praça do Cristal', -30.1031, -51.1941, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-085', 'UBS Cristal', -29.9998, -51.2633, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-086', 'Zaffari Cristal', -30.0022, -51.2206, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-087', 'Carrefour Cristal', -30.0462, -51.2631, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-088', 'Nacional Cristal', -29.9836, -51.2949, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-089', 'Praça do Tristeza', -30.0486, -51.2611, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-090', 'UBS Tristeza', -29.9989, -51.2204, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-091', 'Zaffari Tristeza', -30.0012, -51.3086, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-092', 'Carrefour Tristeza', -30.0555, -51.1978, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-093', 'Nacional Tristeza', -30.1331, -51.2574, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-094', 'Praça do Ipanema (Porto Alegre)', -30.0924, -51.2903, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-095', 'UBS Ipanema (Porto Alegre)', -30.0835, -51.2521, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('portoalegre-096', 'Zaffari Ipanema (Porto Alegre)', -30.1331, -51.1683, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-097', 'Carrefour Ipanema (Porto Alegre)', -30.0995, -51.2417, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-098', 'Nacional Ipanema (Porto Alegre)', -29.9939, -51.2176, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('portoalegre-099', 'Praça do Vila Assunção', -29.9679, -51.1565, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('portoalegre-100', 'UBS Vila Assunção', -30.1202, -51.1453, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
