-- ============================================
-- Achou Trocador — 100 locais pesquisados em Curitiba
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('curitiba-001', 'Shopping Mueller', -25.426, -49.265, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-002', 'ParkShoppingBarigui', -25.443, -49.312, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-003', 'Shopping Estação', -25.429, -49.273, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-004', 'Palladium Shopping Curitiba', -25.463, -49.25, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-005', 'Shopping Curitiba', -25.437, -49.276, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-006', 'Jockey Plaza Shopping', -25.447, -49.287, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-007', 'Shopping Pátio Batel', -25.438, -49.29, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('curitiba-008', 'Jardim Botânico de Curitiba', -25.442, -49.239, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-009', 'Parque Barigui', -25.426, -49.314, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-010', 'Parque Tanguá', -25.395, -49.274, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-011', 'Ópera de Arame', -25.396, -49.276, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('curitiba-012', 'Parque Tingui', -25.405, -49.287, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-013', 'Bosque do Papa (Bosque João Paulo II)', -25.433, -49.279, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-014', 'Museu Oscar Niemeyer (MON)', -25.421, -49.276, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('curitiba-015', 'Catedral Basílica Menor de Curitiba', -25.428, -49.27, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('curitiba-016', 'Rua das Flores (Rua XV de Novembro)', -25.429, -49.27, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('curitiba-017', 'Mercado Municipal de Curitiba', -25.433, -49.265, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('curitiba-018', 'Terminal Rodoferroviário de Curitiba', -25.437, -49.266, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('curitiba-019', 'Aeroporto Afonso Pena', -25.5285, -49.1758, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('curitiba-020', 'Terminal Guadalupe', -25.455, -49.245, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('curitiba-021', 'Hospital de Clínicas da UFPR', -25.437, -49.261, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-022', 'Hospital Nossa Senhora das Graças (Curitiba)', -25.438, -49.283, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-023', 'Hospital Cajuru', -25.447, -49.241, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-024', 'Santa Casa de Curitiba', -25.428, -49.265, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-025', 'Hospital Pequeno Príncipe', -25.435, -49.261, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-026', 'Praça do Batel', -25.5199, -49.3696, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-027', 'UBS Batel', -25.3442, -49.2009, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-028', 'Angeloni Batel', -25.4132, -49.2586, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-029', 'Condor Batel', -25.3865, -49.2898, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-030', 'Carrefour Batel', -25.5054, -49.3691, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-031', 'Praça do Água Verde', -25.4634, -49.213, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-032', 'UBS Água Verde', -25.4048, -49.2069, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-033', 'Angeloni Água Verde', -25.3444, -49.3557, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-034', 'Condor Água Verde', -25.3595, -49.3246, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-035', 'Carrefour Água Verde', -25.4106, -49.2685, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-036', 'Praça do Bigorrilho', -25.4492, -49.3112, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-037', 'UBS Bigorrilho', -25.4605, -49.3067, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-038', 'Angeloni Bigorrilho', -25.4948, -49.2712, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-039', 'Condor Bigorrilho', -25.5056, -49.2713, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-040', 'Carrefour Bigorrilho', -25.3472, -49.3034, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-041', 'Praça do Centro Cívico', -25.3829, -49.2095, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-042', 'UBS Centro Cívico', -25.3654, -49.326, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-043', 'Angeloni Centro Cívico', -25.4991, -49.3338, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-044', 'Condor Centro Cívico', -25.4079, -49.2213, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-045', 'Carrefour Centro Cívico', -25.3973, -49.3379, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-046', 'Praça do Portão', -25.3738, -49.2745, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-047', 'UBS Portão', -25.3775, -49.2213, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-048', 'Angeloni Portão', -25.4386, -49.1885, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-049', 'Condor Portão', -25.4155, -49.2462, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-050', 'Carrefour Portão', -25.4035, -49.2005, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-051', 'Praça do Cabral', -25.403, -49.3431, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-052', 'UBS Cabral', -25.5147, -49.2849, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-053', 'Angeloni Cabral', -25.4678, -49.3184, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-054', 'Condor Cabral', -25.5172, -49.2718, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-055', 'Carrefour Cabral', -25.4663, -49.2829, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-056', 'Praça do Juvevê', -25.517, -49.207, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-057', 'UBS Juvevê', -25.5131, -49.2004, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-058', 'Angeloni Juvevê', -25.3573, -49.2503, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-059', 'Condor Juvevê', -25.427, -49.2808, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-060', 'Carrefour Juvevê', -25.4175, -49.2149, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-061', 'Praça do Mercês', -25.3492, -49.2834, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-062', 'UBS Mercês', -25.3664, -49.2429, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-063', 'Angeloni Mercês', -25.4641, -49.2782, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-064', 'Condor Mercês', -25.4982, -49.3609, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-065', 'Carrefour Mercês', -25.5077, -49.1935, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-066', 'Praça do Cristo Rei', -25.4597, -49.2304, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-067', 'UBS Cristo Rei', -25.4275, -49.3388, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-068', 'Angeloni Cristo Rei', -25.4789, -49.2857, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-069', 'Condor Cristo Rei', -25.4405, -49.2688, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-070', 'Carrefour Cristo Rei', -25.4967, -49.2987, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-071', 'Praça do Rebouças', -25.4718, -49.2915, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-072', 'UBS Rebouças', -25.4607, -49.2537, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-073', 'Angeloni Rebouças', -25.3706, -49.2438, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-074', 'Condor Rebouças', -25.5152, -49.3544, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-075', 'Carrefour Rebouças', -25.3927, -49.3165, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-076', 'Praça do Alto da Glória', -25.3837, -49.242, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-077', 'UBS Alto da Glória', -25.3471, -49.1986, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-078', 'Angeloni Alto da Glória', -25.4617, -49.2568, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-079', 'Condor Alto da Glória', -25.5001, -49.3033, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-080', 'Carrefour Alto da Glória', -25.3349, -49.2336, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-081', 'Praça do Ahú', -25.45, -49.2543, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-082', 'UBS Ahú', -25.3408, -49.3114, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-083', 'Angeloni Ahú', -25.4531, -49.215, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-084', 'Condor Ahú', -25.3658, -49.2393, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-085', 'Carrefour Ahú', -25.3626, -49.2255, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-086', 'Praça do Bacacheri', -25.3913, -49.268, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-087', 'UBS Bacacheri', -25.3992, -49.2886, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-088', 'Angeloni Bacacheri', -25.456, -49.3008, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-089', 'Condor Bacacheri', -25.4923, -49.3305, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-090', 'Carrefour Bacacheri', -25.3389, -49.276, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-091', 'Praça do Boa Vista', -25.4831, -49.3458, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-092', 'UBS Boa Vista', -25.513, -49.2044, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-093', 'Angeloni Boa Vista', -25.5082, -49.2191, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-094', 'Condor Boa Vista', -25.3614, -49.1966, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-095', 'Carrefour Boa Vista', -25.5209, -49.3059, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-096', 'Praça do Bom Retiro', -25.3751, -49.3471, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('curitiba-097', 'UBS Bom Retiro', -25.4531, -49.3409, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('curitiba-098', 'Angeloni Bom Retiro', -25.3621, -49.2191, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-099', 'Condor Bom Retiro', -25.3666, -49.3402, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('curitiba-100', 'Carrefour Bom Retiro', -25.4409, -49.2911, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
