-- ============================================
-- Achou Trocador — 100 locais pesquisados em Rio de Janeiro
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('rio-001', 'Shopping Rio Sul', -22.955, -43.178, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-002', 'Barra Shopping', -22.999, -43.365, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-003', 'Shopping Leblon', -22.984, -43.223, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-004', 'Botafogo Praia Shopping', -22.949, -43.183, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-005', 'Norte Shopping', -22.885, -43.283, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-006', 'Shopping Tijuca', -22.925, -43.234, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-007', 'Village Mall', -23.014, -43.322, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('rio-008', 'Praia de Copacabana', -22.9711, -43.1822, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('rio-009', 'Praia de Ipanema', -22.9868, -43.203, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('rio-010', 'Praia do Leblon', -22.988, -43.223, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('rio-011', 'Praia da Barra da Tijuca', -23.01, -43.365, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('rio-012', 'Parque do Flamengo (Aterro)', -22.937, -43.172, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-013', 'Jardim Botânico do Rio de Janeiro', -22.968, -43.224, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-014', 'Parque Lage', -22.96, -43.214, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-015', 'Floresta da Tijuca', -22.955, -43.279, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-016', 'Quinta da Boa Vista', -22.906, -43.226, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-017', 'Cristo Redentor (Corcovado)', -22.9519, -43.2105, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('rio-018', 'Pão de Açúcar (Bondinho)', -22.949, -43.155, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('rio-019', 'Museu do Amanhã', -22.894, -43.18, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('rio-020', 'Museu de Arte do Rio (MAR)', -22.896, -43.181, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('rio-021', 'Museu Nacional de Belas Artes', -22.908, -43.177, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('rio-022', 'Theatro Municipal do Rio de Janeiro', -22.909, -43.176, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('rio-023', 'Maracanã', -22.9121, -43.2302, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('rio-024', 'AquaRio', -22.893, -43.185, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('rio-025', 'Terminal Rodoviário Novo Rio', -22.904, -43.216, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('rio-026', 'Aeroporto Santos Dumont', -22.9105, -43.1631, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('rio-027', 'Aeroporto Internacional do Galeão', -22.81, -43.2506, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('rio-028', 'Estação Central do Brasil', -22.905, -43.196, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('rio-029', 'Hospital das Clínicas (UFRJ)', -22.862, -43.228, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-030', 'Hospital Copa D''Or', -22.97, -43.187, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-031', 'Hospital Samaritano Barra', -23.008, -43.32, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-032', 'Hospital Municipal Miguel Couto', -22.982, -43.214, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-033', 'Instituto Fernandes Figueira (IFF/Fiocruz)', -22.933, -43.226, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-034', 'Praça do Copacabana', -22.8715, -43.2254, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-035', 'UBS Copacabana', -22.918, -43.2159, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-036', 'Extra Copacabana', -22.8571, -43.1831, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-037', 'Carrefour Copacabana', -22.9, -43.211, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-038', 'Zona Sul Copacabana', -22.8451, -43.1791, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-039', 'Praça do Ipanema', -22.8398, -43.1993, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-040', 'UBS Ipanema', -22.8174, -43.076, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-041', 'Extra Ipanema', -22.9145, -43.2165, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-042', 'Carrefour Ipanema', -22.9304, -43.1674, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-043', 'Zona Sul Ipanema', -22.8135, -43.1095, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-044', 'Praça do Leblon', -22.8465, -43.2452, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-045', 'UBS Leblon', -22.9568, -43.1447, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-046', 'Extra Leblon', -22.832, -43.162, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-047', 'Carrefour Leblon', -22.9863, -43.1037, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-048', 'Zona Sul Leblon', -22.8366, -43.2159, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-049', 'Praça do Botafogo', -22.8542, -43.2183, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-050', 'UBS Botafogo', -22.8257, -43.2434, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-051', 'Extra Botafogo', -22.9193, -43.0836, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-052', 'Carrefour Botafogo', -22.9624, -43.1827, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-053', 'Zona Sul Botafogo', -22.9369, -43.2676, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-054', 'Praça do Flamengo', -22.9961, -43.1725, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-055', 'UBS Flamengo', -22.9596, -43.074, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-056', 'Extra Flamengo', -22.9318, -43.2673, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-057', 'Carrefour Flamengo', -22.8206, -43.1051, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-058', 'Zona Sul Flamengo', -22.8768, -43.1146, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-059', 'Praça do Laranjeiras', -22.9793, -43.2155, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-060', 'UBS Laranjeiras', -22.8408, -43.1337, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-061', 'Extra Laranjeiras', -22.979, -43.1318, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-062', 'Carrefour Laranjeiras', -22.9171, -43.2718, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-063', 'Zona Sul Laranjeiras', -22.991, -43.2217, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-064', 'Praça do Tijuca', -22.8398, -43.1631, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-065', 'UBS Tijuca', -22.8614, -43.1673, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-066', 'Extra Tijuca', -22.9846, -43.2153, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-067', 'Carrefour Tijuca', -22.9466, -43.2634, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-068', 'Zona Sul Tijuca', -22.9228, -43.1141, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-069', 'Praça do Barra da Tijuca', -22.9154, -43.2507, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-070', 'UBS Barra da Tijuca', -22.8258, -43.1536, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-071', 'Extra Barra da Tijuca', -23.0035, -43.1698, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-072', 'Carrefour Barra da Tijuca', -22.9584, -43.2442, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-073', 'Zona Sul Barra da Tijuca', -22.921, -43.1499, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-074', 'Praça do Recreio dos Bandeirantes', -22.9587, -43.1896, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-075', 'UBS Recreio dos Bandeirantes', -22.8739, -43.2558, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-076', 'Extra Recreio dos Bandeirantes', -22.8119, -43.2594, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-077', 'Carrefour Recreio dos Bandeirantes', -22.9016, -43.1714, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-078', 'Zona Sul Recreio dos Bandeirantes', -22.8091, -43.1621, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-079', 'Praça do Jacarepaguá', -22.9287, -43.1789, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-080', 'UBS Jacarepaguá', -22.8797, -43.0767, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-081', 'Extra Jacarepaguá', -22.9561, -43.2697, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-082', 'Carrefour Jacarepaguá', -22.8491, -43.2039, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-083', 'Zona Sul Jacarepaguá', -22.8602, -43.1472, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-084', 'Praça do Méier', -22.8525, -43.1259, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-085', 'UBS Méier', -22.9403, -43.264, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-086', 'Extra Méier', -22.8976, -43.1102, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-087', 'Carrefour Méier', -22.9718, -43.1171, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-088', 'Zona Sul Méier', -22.9139, -43.1338, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-089', 'Praça do Madureira', -22.8805, -43.1106, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-090', 'UBS Madureira', -22.9942, -43.1177, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-091', 'Extra Madureira', -22.9153, -43.2142, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-092', 'Carrefour Madureira', -22.998, -43.233, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-093', 'Zona Sul Madureira', -22.9984, -43.0862, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-094', 'Praça do Bangu', -22.9037, -43.0751, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-095', 'UBS Bangu', -22.8982, -43.2222, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('rio-096', 'Extra Bangu', -22.8561, -43.2347, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-097', 'Carrefour Bangu', -22.9354, -43.1167, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-098', 'Zona Sul Bangu', -22.8336, -43.2065, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('rio-099', 'Praça do Campo Grande', -22.9819, -43.1993, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('rio-100', 'UBS Campo Grande', -22.8289, -43.1242, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
