-- ============================================
-- Achou Trocador — 100 locais pesquisados em Salvador
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda -- a comunidade local vai confirmar tipo de
-- banheiro, se tem trocador de verdade, etc.
-- Coordenadas são aproximadas (pesquisa, ninguém visitou ainda).
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('salvador-001', 'Salvador Shopping', -12.977, -38.453, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('salvador-002', 'Shopping Barra', -13.008, -38.53, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('salvador-003', 'Parque Shopping Bahia', -12.933, -38.453, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('salvador-004', 'Shopping Paralela', -12.949, -38.44, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('salvador-005', 'Shopping da Bahia', -12.975, -38.463, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('salvador-006', 'Farol da Barra', -13.01, -38.532, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('salvador-007', 'Praça Municipal (Palácio Rio Branco)', -12.973, -38.51, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-008', 'Elevador Lacerda', -12.974, -38.511, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-009', 'Mercado Modelo', -12.972, -38.514, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('salvador-010', 'Pelourinho', -12.9714, -38.5088, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-011', 'Basílica Nossa Senhora da Conceição da Praia', -12.975, -38.515, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-012', 'Dique do Tororó', -12.967, -38.493, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-013', 'Parque de Pituaçu', -12.976, -38.427, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-014', 'Praia do Porto da Barra', -13.009, -38.533, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('salvador-015', 'Praia de Ondina', -13.0, -38.51, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('salvador-016', 'Praia de Piatã', -12.97, -38.42, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('salvador-017', 'Praia de Itapuã (Salvador)', -12.945, -38.36, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('salvador-018', 'Cidade da Música da Bahia', -12.975, -38.455, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-019', 'Casa do Carnaval da Bahia', -12.972, -38.512, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('salvador-020', 'Terminal Rodoviário de Salvador', -12.954, -38.453, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('salvador-021', 'Aeroporto Internacional de Salvador', -12.9086, -38.3225, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('salvador-022', 'Estação da Lapa (Terminal)', -12.98, -38.506, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('salvador-023', 'Hospital Geral Roberto Santos', -12.966, -38.463, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-024', 'Hospital Português da Bahia', -13.0, -38.501, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-025', 'Hospital São Rafael', -12.943, -38.447, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-026', 'Hospital Aliança', -13.0, -38.472, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-027', 'Maternidade Climério de Oliveira', -12.993, -38.502, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-028', 'Praça do Barra', -12.8925, -38.5241, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-029', 'UBS Barra', -12.8767, -38.5022, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-030', 'Extra Barra', -12.9719, -38.4165, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-031', 'Bompreço Barra', -12.9675, -38.4412, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-032', 'Atacadão Barra', -12.926, -38.5856, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-033', 'Praça do Ondina', -12.9509, -38.4369, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-034', 'UBS Ondina', -12.9623, -38.5372, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-035', 'Extra Ondina', -13.0554, -38.4692, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-036', 'Bompreço Ondina', -13.0101, -38.4809, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-037', 'Atacadão Ondina', -12.9862, -38.4634, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-038', 'Praça do Rio Vermelho', -13.0011, -38.5929, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-039', 'UBS Rio Vermelho', -12.8974, -38.5309, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-040', 'Extra Rio Vermelho', -12.8718, -38.5465, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-041', 'Bompreço Rio Vermelho', -12.8754, -38.4118, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-042', 'Atacadão Rio Vermelho', -13.0564, -38.4739, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-043', 'Praça do Pituba', -12.9987, -38.4412, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-044', 'UBS Pituba', -12.9355, -38.4108, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-045', 'Extra Pituba', -13.0428, -38.4799, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-046', 'Bompreço Pituba', -12.9151, -38.5944, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-047', 'Atacadão Pituba', -13.058, -38.4457, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-048', 'Praça do Itaigara', -12.9981, -38.5248, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-049', 'UBS Itaigara', -12.958, -38.4804, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-050', 'Extra Itaigara', -12.9356, -38.4116, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-051', 'Bompreço Itaigara', -12.997, -38.4488, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-052', 'Atacadão Itaigara', -12.9566, -38.4955, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-053', 'Praça do Caminho das Árvores', -12.9918, -38.4715, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-054', 'UBS Caminho das Árvores', -13.0215, -38.5787, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-055', 'Extra Caminho das Árvores', -12.9243, -38.5016, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-056', 'Bompreço Caminho das Árvores', -12.994, -38.4891, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-057', 'Atacadão Caminho das Árvores', -13.019, -38.5493, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-058', 'Praça do Stella Maris', -12.9821, -38.4021, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-059', 'UBS Stella Maris', -13.0143, -38.4181, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-060', 'Extra Stella Maris', -12.9732, -38.5769, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-061', 'Bompreço Stella Maris', -12.9008, -38.511, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-062', 'Atacadão Stella Maris', -12.8917, -38.5124, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-063', 'Praça do Piatã', -13.0538, -38.465, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-064', 'UBS Piatã', -12.9023, -38.5375, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-065', 'Extra Piatã', -13.0019, -38.5884, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-066', 'Bompreço Piatã', -12.963, -38.4231, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-067', 'Atacadão Piatã', -12.9011, -38.459, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-068', 'Praça do Itapuã', -12.8859, -38.4739, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-069', 'UBS Itapuã', -12.9127, -38.4996, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-070', 'Extra Itapuã', -13.0471, -38.5612, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-071', 'Bompreço Itapuã', -13.0436, -38.4433, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-072', 'Atacadão Itapuã', -13.0661, -38.4906, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-073', 'Praça do Boca do Rio', -12.9976, -38.4407, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-074', 'UBS Boca do Rio', -12.9611, -38.479, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-075', 'Extra Boca do Rio', -13.0542, -38.5395, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-076', 'Bompreço Boca do Rio', -12.8715, -38.4576, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-077', 'Atacadão Boca do Rio', -12.9663, -38.4476, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-078', 'Praça do Amaralina', -12.9067, -38.5866, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-079', 'UBS Amaralina', -12.8769, -38.4729, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-080', 'Extra Amaralina', -12.9814, -38.4654, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-081', 'Bompreço Amaralina', -13.0025, -38.4258, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-082', 'Atacadão Amaralina', -12.9153, -38.4734, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-083', 'Praça do Graça', -13.035, -38.4081, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-084', 'UBS Graça', -12.9849, -38.4193, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-085', 'Extra Graça', -13.0603, -38.5766, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-086', 'Bompreço Graça', -13.0408, -38.5685, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-087', 'Atacadão Graça', -13.0069, -38.4595, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-088', 'Praça do Vitória', -13.0022, -38.4132, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-089', 'UBS Vitória', -12.8924, -38.4322, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-090', 'Extra Vitória', -13.0213, -38.4744, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-091', 'Bompreço Vitória', -12.9612, -38.5764, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-092', 'Atacadão Vitória', -13.0108, -38.4947, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-093', 'Praça do Canela', -12.9709, -38.5677, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-094', 'UBS Canela', -12.8831, -38.5706, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-095', 'Extra Canela', -12.9397, -38.4573, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-096', 'Bompreço Canela', -12.9504, -38.4329, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-097', 'Atacadão Canela', -12.9587, -38.4364, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('salvador-098', 'Praça do Brotas', -13.0657, -38.5923, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('salvador-099', 'UBS Brotas', -12.9431, -38.486, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('salvador-100', 'Extra Brotas', -12.9412, -38.448, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
