-- ============================================
-- Achou Trocador — Buenos Aires (200 a mais)
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('bsas-101', 'Estación Perú (Subte)', -34.609, -58.373, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-102', 'Estación Piedras (Subte)', -34.611, -58.376, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-103', 'Estación Lima (Subte)', -34.61, -58.386, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-104', 'Estación Sáenz Peña (Subte)', -34.608, -58.383, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-105', 'Estación Congreso (Subte)', -34.6095, -58.3925, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-106', 'Estación Pasco (Subte)', -34.611, -58.397, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-107', 'Estación Alberti (Subte)', -34.6115, -58.401, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-108', 'Estación Plaza Miserere / Once (Subte)', -34.6088, -58.4058, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-109', 'Estación Loria (Subte)', -34.6115, -58.409, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-110', 'Estación Castro Barros (Subte)', -34.614, -58.415, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-111', 'Estación Río de Janeiro (Subte)', -34.617, -58.421, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-112', 'Estación Acoyte (Subte)', -34.619, -58.428, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-113', 'Estación Primera Junta (Subte)', -34.6205, -58.4335, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-114', 'Estación Puan (Subte)', -34.623, -58.44, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-115', 'Estación Carabobo (Subte)', -34.626, -58.447, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-116', 'Estación San Pedrito (Subte)', -34.628, -58.453, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-117', 'Estación San José de Flores (Subte)', -34.63, -58.46, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-118', 'Estación Boedo (Subte)', -34.628, -58.418, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-119', 'Estación Av. San Juan (Subte)', -34.621, -58.398, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-120', 'Estación Independencia (Subte)', -34.618, -58.389, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-121', 'Estación Humberto 1° (Subte)', -34.62, -58.38, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-122', 'Estación Callao (Subte)', -34.599, -58.393, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-123', 'Estación Uruguay (Subte)', -34.601, -58.392, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-124', 'Estación Tribunales (Subte)', -34.6015, -58.385, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-125', 'Estación Pueyrredón (Subte)', -34.592, -58.409, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-126', 'Estación Ángel Gallardo (Subte)', -34.603, -58.437, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-127', 'Estación Malabia (Subte)', -34.592, -58.439, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-128', 'Estación Dorrego (Subte)', -34.587, -58.446, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-129', 'Estación Constitución (Subte)', -34.6265, -58.3808, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-130', 'Estación Retiro (Subte)', -34.592, -58.3745, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bsas-131', 'La Bombonera (Estadio Boca Juniors)', -34.6356, -58.3648, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-132', 'Estadio Monumental (River Plate)', -34.5453, -58.4497, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-133', 'Hospital Italiano de Buenos Aires', -34.599, -58.429, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-134', 'Hospital Alemán (Buenos Aires)', -34.592, -58.402, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-135', 'Hospital de Clínicas José de San Martín', -34.5997, -58.397, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-136', 'Hospital Británico de Buenos Aires', -34.633, -58.383, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-137', 'Sanatorio Güemes', -34.599, -58.429, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-138', 'Sanatorio Mater Dei', -34.582, -58.403, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-139', 'Clínica y Maternidad Suizo Argentina', -34.598, -58.413, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-140', 'Hospital de Niños Ricardo Gutiérrez', -34.6, -58.415, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-141', 'Hospital Pirovano', -34.5636, -58.4741, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-142', 'Paseo Alcorta', -34.5758, -58.4188, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-143', 'Abasto de Buenos Aires (dentro do shopping)', -34.6036, -58.4106, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-144', 'Alto Avellaneda', -34.6612, -58.3651, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-145', 'Distrito Arcos', -34.5735, -58.4297, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-146', 'Soleil Premium Outlet (San Isidro)', -34.47, -58.53, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bsas-147', 'Plaza Serrano (Palermo Soho)', -34.588, -58.431, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-148', 'Plaza Armenia', -34.587, -58.433, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-149', 'Plaza Cortázar', -34.588, -58.4315, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-150', 'Plaza Güemes (Palermo)', -34.583, -58.429, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-151', 'Plaza Boedo', -34.629, -58.419, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-152', 'Plaza Flores', -34.63, -58.461, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-153', 'Plaza Once (Miserere)', -34.609, -58.4055, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-154', 'Plaza Constitución', -34.627, -58.381, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-155', 'Plaza Lavalle', -34.601, -58.385, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-156', 'Plaza Roberto Arlt', -34.608, -58.38, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-157', 'Parque Chacabuco', -34.6367, -58.4374, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-158', 'Parque Avellaneda', -34.6461, -58.4707, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-159', 'Parque Saavedra', -34.554, -58.4884, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-160', 'Parque Sarmiento (Buenos Aires)', -34.5813, -58.5023, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-161', 'Parque Centenario', -34.606, -58.4357, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-162', 'Jardín Zoológico de Buenos Aires (Ecoparque)', -34.5776, -58.4147, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('bsas-163', 'Museo del Traje', -34.59, -58.423, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-164', 'Museo Xul Solar', -34.594, -58.395, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-165', 'Museo Evita', -34.585, -58.427, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-166', 'Museo de Arte Popular José Hernández', -34.576, -58.411, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-167', 'Centro Cultural San Martín', -34.603, -58.38, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-168', 'Centro Cultural Konex', -34.61, -58.411, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-169', 'Teatro Colón', -34.601, -58.3831, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bsas-170', 'Basílica de San José de Flores', -34.63, -58.462, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-171', 'Basílica de Nuestra Señora del Pilar', -34.5875, -58.393, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-172', 'Plaza Palermo', -34.6435, -58.4801, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-173', 'Centro de Salud Palermo', -34.5846, -58.4943, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-174', 'Carrefour Palermo', -34.6053, -58.4415, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-175', 'Coto Palermo', -34.6914, -58.416, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-176', 'Jumbo Palermo', -34.6951, -58.4292, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-177', 'Día Palermo', -34.6892, -58.491, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-178', 'Estación de Servicio YPF Palermo', -34.6254, -58.3585, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-179', 'Estación de Servicio Shell Palermo', -34.6795, -58.4671, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-180', 'Estación de Servicio Axion Palermo', -34.5889, -58.3367, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-181', 'Farmacia Farmacity Palermo', -34.5979, -58.4359, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-182', 'Plaza Recoleta', -34.5261, -58.4989, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-183', 'Centro de Salud Recoleta', -34.5473, -58.4552, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-184', 'Carrefour Recoleta', -34.6758, -58.4861, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-185', 'Coto Recoleta', -34.6463, -58.3604, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-186', 'Jumbo Recoleta', -34.6693, -58.4026, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-187', 'Día Recoleta', -34.5868, -58.4403, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-188', 'Estación de Servicio YPF Recoleta', -34.6032, -58.496, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-189', 'Estación de Servicio Shell Recoleta', -34.6911, -58.4702, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-190', 'Estación de Servicio Axion Recoleta', -34.5793, -58.4303, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-191', 'Farmacia Farmacity Recoleta', -34.6453, -58.4019, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-192', 'Plaza Belgrano', -34.6202, -58.4533, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-193', 'Centro de Salud Belgrano', -34.5588, -58.3815, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-194', 'Carrefour Belgrano', -34.6579, -58.4039, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-195', 'Coto Belgrano', -34.6073, -58.3498, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-196', 'Jumbo Belgrano', -34.5705, -58.4555, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-197', 'Día Belgrano', -34.5254, -58.486, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-198', 'Estación de Servicio YPF Belgrano', -34.6265, -58.371, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-199', 'Estación de Servicio Shell Belgrano', -34.6744, -58.4193, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-200', 'Estación de Servicio Axion Belgrano', -34.6947, -58.387, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-201', 'Farmacia Farmacity Belgrano', -34.5642, -58.4042, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-202', 'Plaza Caballito', -34.5442, -58.4508, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-203', 'Centro de Salud Caballito', -34.5766, -58.4003, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-204', 'Carrefour Caballito', -34.5974, -58.4252, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-205', 'Coto Caballito', -34.5506, -58.3373, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-206', 'Jumbo Caballito', -34.6165, -58.3878, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-207', 'Día Caballito', -34.6909, -58.381, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-208', 'Estación de Servicio YPF Caballito', -34.5853, -58.3285, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-209', 'Estación de Servicio Shell Caballito', -34.5539, -58.4561, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-210', 'Estación de Servicio Axion Caballito', -34.6324, -58.3869, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-211', 'Farmacia Farmacity Caballito', -34.6977, -58.4242, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-212', 'Centro de Salud Flores', -34.6716, -58.4862, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-213', 'Carrefour Flores', -34.6912, -58.369, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-214', 'Coto Flores', -34.6785, -58.4627, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-215', 'Jumbo Flores', -34.6314, -58.3504, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-216', 'Día Flores', -34.6873, -58.4264, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-217', 'Estación de Servicio YPF Flores', -34.6029, -58.3483, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-218', 'Estación de Servicio Shell Flores', -34.5543, -58.3518, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-219', 'Estación de Servicio Axion Flores', -34.6517, -58.4325, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-220', 'Farmacia Farmacity Flores', -34.6372, -58.3481, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-221', 'Plaza Almagro', -34.5294, -58.4801, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-222', 'Centro de Salud Almagro', -34.6701, -58.4655, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-223', 'Carrefour Almagro', -34.6598, -58.42, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-224', 'Coto Almagro', -34.5958, -58.46, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-225', 'Jumbo Almagro', -34.7011, -58.4319, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-226', 'Día Almagro', -34.6353, -58.4054, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-227', 'Estación de Servicio YPF Almagro', -34.5302, -58.383, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-228', 'Estación de Servicio Shell Almagro', -34.609, -58.3961, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-229', 'Estación de Servicio Axion Almagro', -34.5801, -58.4976, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-230', 'Farmacia Farmacity Almagro', -34.5399, -58.3669, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-231', 'Centro de Salud Boedo', -34.5444, -58.3637, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-232', 'Carrefour Boedo', -34.6312, -58.4355, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-233', 'Coto Boedo', -34.6832, -58.3931, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-234', 'Jumbo Boedo', -34.6906, -58.4952, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-235', 'Día Boedo', -34.6642, -58.4781, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-236', 'Estación de Servicio YPF Boedo', -34.6406, -58.4978, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-237', 'Estación de Servicio Shell Boedo', -34.7018, -58.4801, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-238', 'Estación de Servicio Axion Boedo', -34.6835, -58.4419, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-239', 'Farmacia Farmacity Boedo', -34.6972, -58.3499, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-240', 'Plaza Villa Crespo', -34.5913, -58.4806, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-241', 'Centro de Salud Villa Crespo', -34.6564, -58.4448, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-242', 'Carrefour Villa Crespo', -34.6363, -58.4852, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-243', 'Coto Villa Crespo', -34.549, -58.3285, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-244', 'Jumbo Villa Crespo', -34.6179, -58.4202, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-245', 'Día Villa Crespo', -34.6863, -58.4889, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-246', 'Estación de Servicio YPF Villa Crespo', -34.6401, -58.4596, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-247', 'Estación de Servicio Shell Villa Crespo', -34.5526, -58.4782, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-248', 'Estación de Servicio Axion Villa Crespo', -34.6976, -58.3361, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-249', 'Farmacia Farmacity Villa Crespo', -34.6067, -58.4809, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-250', 'Plaza Chacarita', -34.604, -58.5024, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-251', 'Centro de Salud Chacarita', -34.6067, -58.3312, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-252', 'Carrefour Chacarita', -34.5464, -58.382, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-253', 'Coto Chacarita', -34.6548, -58.4413, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-254', 'Jumbo Chacarita', -34.6717, -58.3684, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-255', 'Día Chacarita', -34.6059, -58.3671, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-256', 'Estación de Servicio YPF Chacarita', -34.6425, -58.4672, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-257', 'Estación de Servicio Shell Chacarita', -34.5557, -58.33, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-258', 'Estación de Servicio Axion Chacarita', -34.5483, -58.3622, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-259', 'Farmacia Farmacity Chacarita', -34.5545, -58.3741, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-260', 'Plaza Colegiales', -34.661, -58.4141, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-261', 'Centro de Salud Colegiales', -34.6378, -58.5021, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-262', 'Carrefour Colegiales', -34.6968, -58.457, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-263', 'Coto Colegiales', -34.6551, -58.3826, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-264', 'Jumbo Colegiales', -34.5296, -58.4268, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-265', 'Día Colegiales', -34.5331, -58.3295, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-266', 'Estación de Servicio YPF Colegiales', -34.5299, -58.4417, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-267', 'Estación de Servicio Shell Colegiales', -34.6621, -58.4665, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-268', 'Estación de Servicio Axion Colegiales', -34.6664, -58.4705, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-269', 'Farmacia Farmacity Colegiales', -34.5895, -58.3452, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-270', 'Plaza Núñez', -34.5505, -58.421, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-271', 'Centro de Salud Núñez', -34.5843, -58.3634, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-272', 'Carrefour Núñez', -34.6865, -58.3884, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-273', 'Coto Núñez', -34.538, -58.3665, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-274', 'Jumbo Núñez', -34.5668, -58.4213, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-275', 'Día Núñez', -34.6697, -58.3653, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-276', 'Estación de Servicio YPF Núñez', -34.6419, -58.3632, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-277', 'Estación de Servicio Shell Núñez', -34.5269, -58.436, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-278', 'Estación de Servicio Axion Núñez', -34.6296, -58.3369, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-279', 'Farmacia Farmacity Núñez', -34.5713, -58.4767, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-280', 'Plaza Saavedra', -34.6789, -58.4801, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-281', 'Centro de Salud Saavedra', -34.5389, -58.3621, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-282', 'Carrefour Saavedra', -34.6755, -58.3585, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-283', 'Coto Saavedra', -34.5253, -58.389, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-284', 'Jumbo Saavedra', -34.6387, -58.4085, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-285', 'Día Saavedra', -34.6782, -58.5047, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-286', 'Estación de Servicio YPF Saavedra', -34.527, -58.3904, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-287', 'Estación de Servicio Shell Saavedra', -34.607, -58.3392, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-288', 'Estación de Servicio Axion Saavedra', -34.6237, -58.3504, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-289', 'Farmacia Farmacity Saavedra', -34.5531, -58.4693, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-290', 'Plaza Villa Urquiza', -34.6565, -58.4546, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bsas-291', 'Centro de Salud Villa Urquiza', -34.6585, -58.4017, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bsas-292', 'Carrefour Villa Urquiza', -34.6551, -58.4319, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-293', 'Coto Villa Urquiza', -34.6782, -58.3435, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-294', 'Jumbo Villa Urquiza', -34.6381, -58.4248, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-295', 'Día Villa Urquiza', -34.5968, -58.3445, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bsas-296', 'Estación de Servicio YPF Villa Urquiza', -34.6261, -58.3421, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-297', 'Estación de Servicio Shell Villa Urquiza', -34.6115, -58.4116, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-298', 'Estación de Servicio Axion Villa Urquiza', -34.6076, -58.5039, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-299', 'Farmacia Farmacity Villa Urquiza', -34.6226, -58.4743, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bsas-300', 'Plaza Villa Devoto', -34.7011, -58.3634, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false)
on conflict (id) do nothing;
