-- ============================================
-- Achou Trocador — São Paulo (200 a mais)
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('saopaulo-101', 'Estação Sé (Metrô SP)', -23.5503, -46.6339, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-102', 'Estação República (Metrô)', -23.543, -46.642, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-103', 'Estação Ana Rosa (Metrô)', -23.582, -46.639, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-104', 'Estação Paraíso (Metrô)', -23.574, -46.642, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-105', 'Estação Vergueiro (Metrô)', -23.576, -46.636, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-106', 'Estação Santa Cecília (Metrô)', -23.535, -46.657, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-107', 'Estação Clínicas (Metrô)', -23.556, -46.67, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-108', 'Estação Faria Lima (Metrô)', -23.568, -46.687, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-109', 'Estação Pinheiros (Metrô)', -23.567, -46.702, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-110', 'Estação Butantã (Metrô)', -23.571, -46.71, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-111', 'Estação Vila Madalena (Metrô)', -23.546, -46.69, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-112', 'Estação Santana (Metrô)', -23.502, -46.625, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-113', 'Estação Tucuruvi (Metrô)', -23.479, -46.603, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-114', 'Estação Tatuapé (Metrô)', -23.539, -46.576, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-115', 'Estação Carrão (Metrô)', -23.549, -46.562, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-116', 'Estação Itaquera (Metrô)', -23.539, -46.472, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-117', 'Estação Jabaquara (Metrô)', -23.647, -46.642, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-118', 'Estação Santo Amaro (Metrô)', -23.654, -46.71, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-119', 'Estação Morumbi (Metrô)', -23.618, -46.698, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-120', 'Estação Vila Prudente (Metrô)', -23.585, -46.582, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-121', 'Terminal Rodoviário Barra Funda', -23.527, -46.666, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-122', 'Terminal Rodoviário Jabaquara', -23.647, -46.642, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-123', 'Hospital Beneficência Portuguesa', -23.557, -46.642, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-124', 'Hospital Alemão Oswaldo Cruz', -23.568, -46.648, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-125', 'Hospital Nove de Julho', -23.582, -46.665, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-126', 'Hospital do Coração (HCor)', -23.592, -46.662, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-127', 'Hospital Santa Marcelina', -23.533, -46.482, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-128', 'Hospital Municipal do Campo Limpo', -23.648, -46.77, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-129', 'Hospital e Maternidade Pró Matre', -23.562, -46.658, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-130', 'Hospital Infantil Sabará', -23.567, -46.68, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-131', 'Shopping Higienópolis', -23.542, -46.658, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-132', 'Shopping SP Market', -23.622, -46.698, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-133', 'Shopping D&D', -23.576, -46.685, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-134', 'Shopping Bourbon Pompeia', -23.527, -46.679, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-135', 'Shopping Metrô Tatuapé', -23.539, -46.576, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-136', 'Shopping Light', -23.545, -46.636, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('saopaulo-137', 'Mercado Municipal de São Paulo (Mercadão)', -23.542, -46.628, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-138', 'Praça da Sé', -23.5503, -46.6339, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-139', 'Praça da República', -23.543, -46.642, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-140', 'Praça Roosevelt', -23.558, -46.648, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-141', 'Praça Benedito Calixto', -23.562, -46.689, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-142', 'Praça Pôr do Sol', -23.556, -46.696, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-143', 'Praça Vilaboim', -23.554, -46.665, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-144', 'Largo da Batata', -23.567, -46.696, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-145', 'Parque do Ibirapuera (Portão 10)', -23.592, -46.66, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-146', 'Parque Previdência', -23.628, -46.698, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-147', 'Parque Severo Gomes', -23.554, -46.705, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-148', 'Parque Raposo Tavares', -23.59, -46.748, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-149', 'Sesc Pompeia', -23.527, -46.68, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-150', 'Sesc Vila Mariana', -23.586, -46.635, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-151', 'Instituto Butantan', -23.571, -46.715, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-152', 'Planetário Ibirapuera', -23.588, -46.658, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('saopaulo-153', 'Museu do Café (São Paulo)', -23.54, -46.63, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-154', 'Casa das Rosas', -23.562, -46.656, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-155', 'Instituto Tomie Ohtake', -23.568, -46.689, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-156', 'Farol Santander', -23.548, -46.635, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('saopaulo-157', 'Praça do Pinheiros', -23.6095, -46.6381, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-158', 'UBS Pinheiros', -23.51, -46.6231, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-159', 'Pão de Açúcar Pinheiros', -23.5818, -46.63, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-160', 'Extra Pinheiros', -23.5405, -46.5821, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-161', 'Carrefour Pinheiros', -23.6214, -46.6224, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-162', 'Dia Pinheiros', -23.5958, -46.6735, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-163', 'Posto Ipiranga Pinheiros', -23.5015, -46.6319, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-164', 'Posto Shell Pinheiros', -23.5394, -46.5865, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-165', 'Posto Petrobras Pinheiros', -23.4763, -46.6435, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-166', 'Farmácia Droga Raia Pinheiros', -23.5302, -46.6323, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-167', 'Farmácia Drogasil Pinheiros', -23.5483, -46.5986, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-168', 'Praça do Vila Mariana', -23.5591, -46.6273, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-169', 'UBS Vila Mariana', -23.5545, -46.5538, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-170', 'Pão de Açúcar Vila Mariana', -23.5146, -46.5655, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-171', 'Extra Vila Mariana', -23.4709, -46.6766, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-172', 'Carrefour Vila Mariana', -23.5398, -46.5535, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-173', 'Dia Vila Mariana', -23.4893, -46.6986, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-174', 'Posto Ipiranga Vila Mariana', -23.6186, -46.6437, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-175', 'Posto Shell Vila Mariana', -23.6274, -46.68, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-176', 'Posto Petrobras Vila Mariana', -23.6273, -46.6028, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-177', 'Farmácia Droga Raia Vila Mariana', -23.4994, -46.5618, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-178', 'Farmácia Drogasil Vila Mariana', -23.6127, -46.5944, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-179', 'Praça do Moema', -23.5217, -46.6976, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-180', 'UBS Moema', -23.4816, -46.5491, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-181', 'Pão de Açúcar Moema', -23.601, -46.5518, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-182', 'Extra Moema', -23.5688, -46.6356, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-183', 'Carrefour Moema', -23.4623, -46.5735, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-184', 'Dia Moema', -23.6114, -46.6456, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-185', 'Posto Ipiranga Moema', -23.5477, -46.6623, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-186', 'Posto Shell Moema', -23.6053, -46.666, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-187', 'Posto Petrobras Moema', -23.5105, -46.7198, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-188', 'Farmácia Droga Raia Moema', -23.5408, -46.644, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-189', 'Farmácia Drogasil Moema', -23.6372, -46.6636, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-190', 'Praça do Tatuapé', -23.5282, -46.6311, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-191', 'UBS Tatuapé', -23.6289, -46.546, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-192', 'Pão de Açúcar Tatuapé', -23.4986, -46.5484, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-193', 'Extra Tatuapé', -23.6216, -46.6755, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-194', 'Carrefour Tatuapé', -23.6334, -46.5831, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-195', 'Dia Tatuapé', -23.5918, -46.7, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-196', 'Posto Ipiranga Tatuapé', -23.5645, -46.5592, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-197', 'Posto Shell Tatuapé', -23.4931, -46.6768, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-198', 'Posto Petrobras Tatuapé', -23.6136, -46.5578, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-199', 'Farmácia Droga Raia Tatuapé', -23.5378, -46.5972, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-200', 'Farmácia Drogasil Tatuapé', -23.6244, -46.7129, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-201', 'Praça do Santana', -23.5166, -46.6467, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-202', 'UBS Santana', -23.6275, -46.5544, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-203', 'Pão de Açúcar Santana', -23.5263, -46.579, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-204', 'Extra Santana', -23.6254, -46.5692, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-205', 'Carrefour Santana', -23.6285, -46.568, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-206', 'Dia Santana', -23.5588, -46.6623, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-207', 'Posto Ipiranga Santana', -23.5409, -46.5565, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-208', 'Posto Shell Santana', -23.5923, -46.7, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-209', 'Posto Petrobras Santana', -23.5457, -46.6804, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-210', 'Farmácia Droga Raia Santana', -23.6208, -46.6942, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-211', 'Farmácia Drogasil Santana', -23.6314, -46.687, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-212', 'Praça do Lapa', -23.5843, -46.6684, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-213', 'UBS Lapa', -23.5038, -46.6711, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-214', 'Pão de Açúcar Lapa', -23.5505, -46.6913, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-215', 'Extra Lapa', -23.578, -46.72, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-216', 'Carrefour Lapa', -23.5954, -46.7205, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-217', 'Dia Lapa', -23.5085, -46.6241, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-218', 'Posto Ipiranga Lapa', -23.6064, -46.6378, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-219', 'Posto Shell Lapa', -23.4723, -46.7042, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-220', 'Posto Petrobras Lapa', -23.4931, -46.6455, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-221', 'Farmácia Droga Raia Lapa', -23.5514, -46.5731, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-222', 'Farmácia Drogasil Lapa', -23.5697, -46.6321, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-223', 'Praça do Perdizes', -23.5167, -46.5465, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-224', 'UBS Perdizes', -23.5788, -46.5735, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-225', 'Pão de Açúcar Perdizes', -23.5133, -46.6088, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-226', 'Extra Perdizes', -23.5677, -46.6607, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-227', 'Carrefour Perdizes', -23.6307, -46.6999, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-228', 'Dia Perdizes', -23.6278, -46.5899, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-229', 'Posto Ipiranga Perdizes', -23.5945, -46.6939, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-230', 'Posto Shell Perdizes', -23.6253, -46.5719, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-231', 'Posto Petrobras Perdizes', -23.4838, -46.6026, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-232', 'Farmácia Droga Raia Perdizes', -23.5898, -46.6797, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-233', 'Farmácia Drogasil Perdizes', -23.5877, -46.6406, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-234', 'Praça do Vila Madalena', -23.6121, -46.6431, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-235', 'UBS Vila Madalena', -23.5931, -46.5502, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-236', 'Pão de Açúcar Vila Madalena', -23.4654, -46.6248, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-237', 'Extra Vila Madalena', -23.5965, -46.5495, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-238', 'Carrefour Vila Madalena', -23.5848, -46.6591, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-239', 'Dia Vila Madalena', -23.6403, -46.6546, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-240', 'Posto Ipiranga Vila Madalena', -23.5551, -46.6328, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-241', 'Posto Shell Vila Madalena', -23.6043, -46.6324, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-242', 'Posto Petrobras Vila Madalena', -23.6396, -46.6757, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-243', 'Farmácia Droga Raia Vila Madalena', -23.6243, -46.6514, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-244', 'Farmácia Drogasil Vila Madalena', -23.633, -46.7193, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-245', 'Praça do Itaim Bibi', -23.5857, -46.6814, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-246', 'UBS Itaim Bibi', -23.5351, -46.628, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-247', 'Pão de Açúcar Itaim Bibi', -23.5054, -46.6049, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-248', 'Extra Itaim Bibi', -23.5116, -46.5651, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-249', 'Carrefour Itaim Bibi', -23.5704, -46.6646, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-250', 'Dia Itaim Bibi', -23.4632, -46.6964, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-251', 'Posto Ipiranga Itaim Bibi', -23.5102, -46.6075, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-252', 'Posto Shell Itaim Bibi', -23.6326, -46.5729, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-253', 'Posto Petrobras Itaim Bibi', -23.48, -46.6104, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-254', 'Farmácia Droga Raia Itaim Bibi', -23.5084, -46.5771, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-255', 'Farmácia Drogasil Itaim Bibi', -23.6154, -46.629, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-256', 'Praça do Brooklin', -23.5497, -46.573, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-257', 'UBS Brooklin', -23.4957, -46.5745, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-258', 'Pão de Açúcar Brooklin', -23.5354, -46.5626, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-259', 'Extra Brooklin', -23.5176, -46.5985, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-260', 'Carrefour Brooklin', -23.5991, -46.7177, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-261', 'Dia Brooklin', -23.6165, -46.6584, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-262', 'Posto Ipiranga Brooklin', -23.6216, -46.5729, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-263', 'Posto Shell Brooklin', -23.54, -46.6103, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-264', 'Posto Petrobras Brooklin', -23.5278, -46.6008, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-265', 'Farmácia Droga Raia Brooklin', -23.5524, -46.7227, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-266', 'Farmácia Drogasil Brooklin', -23.4969, -46.5886, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-267', 'Praça do Saúde', -23.55, -46.627, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-268', 'UBS Saúde', -23.5218, -46.7114, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-269', 'Pão de Açúcar Saúde', -23.5079, -46.6779, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-270', 'Extra Saúde', -23.6271, -46.6755, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-271', 'Carrefour Saúde', -23.5092, -46.6864, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-272', 'Dia Saúde', -23.5073, -46.5477, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-273', 'Posto Ipiranga Saúde', -23.5516, -46.6544, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-274', 'Posto Shell Saúde', -23.5543, -46.6002, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-275', 'Posto Petrobras Saúde', -23.5024, -46.6122, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-276', 'Farmácia Droga Raia Saúde', -23.5248, -46.7094, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-277', 'Farmácia Drogasil Saúde', -23.614, -46.6776, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-278', 'Praça do Ipiranga', -23.5067, -46.6685, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-279', 'UBS Ipiranga', -23.5383, -46.7211, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-280', 'Pão de Açúcar Ipiranga', -23.6296, -46.6749, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-281', 'Extra Ipiranga', -23.5195, -46.5987, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-282', 'Carrefour Ipiranga', -23.5189, -46.6709, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-283', 'Dia Ipiranga', -23.5475, -46.6397, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-284', 'Posto Ipiranga Ipiranga', -23.5566, -46.702, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-285', 'Posto Shell Ipiranga', -23.4796, -46.6874, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-286', 'Posto Petrobras Ipiranga', -23.4644, -46.5548, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-287', 'Farmácia Droga Raia Ipiranga', -23.6373, -46.6407, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-288', 'Farmácia Drogasil Ipiranga', -23.4929, -46.549, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-289', 'Praça do Mooca', -23.5596, -46.6749, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('saopaulo-290', 'UBS Mooca', -23.6027, -46.5531, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('saopaulo-291', 'Pão de Açúcar Mooca', -23.6026, -46.6186, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-292', 'Extra Mooca', -23.615, -46.629, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-293', 'Carrefour Mooca', -23.469, -46.6994, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-294', 'Dia Mooca', -23.4929, -46.6317, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('saopaulo-295', 'Posto Ipiranga Mooca', -23.4809, -46.5967, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-296', 'Posto Shell Mooca', -23.5989, -46.5617, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-297', 'Posto Petrobras Mooca', -23.553, -46.7188, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-298', 'Farmácia Droga Raia Mooca', -23.6399, -46.6348, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-299', 'Farmácia Drogasil Mooca', -23.5594, -46.6689, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('saopaulo-300', 'Praça do Santo Amaro', -23.6152, -46.6614, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false)
on conflict (id) do nothing;
