-- ============================================
-- Achou Trocador — Salta
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('salta-001', 'Plaza 9 de Julio (Salta)', -24.7859, -65.4117, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-002', 'Catedral Basílica de Salta', -24.7862, -65.4108, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('salta-003', 'Cabildo de Salta (Museo Histórico del Norte)', -24.7865, -65.411, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('salta-004', 'Teleférico Cerro San Bernardo', -24.783, -65.402, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('salta-005', 'MAAM — Museo de Arqueología de Alta Montaña', -24.787, -65.412, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('salta-006', 'Paseo Güemes', -24.79, -65.41, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-007', 'Mercado Municipal San Miguel de Salta', -24.79, -65.413, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-008', 'Terminal de Ómnibus de Salta', -24.777, -65.398, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('salta-009', 'Aeropuerto Internacional de Salta (Martín Miguel de Güemes)', -24.8425, -65.4863, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('salta-010', 'Hospital San Bernardo (Salta)', -24.78, -65.416, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-011', 'Hospital del Milagro (Salta)', -24.787, -65.402, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-012', 'Hospital Materno Infantil de Salta', -24.777, -65.409, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-013', 'Alto Noa Shopping', -24.766, -65.413, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('salta-014', 'Portal Salta Shopping', -24.755, -65.426, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('salta-015', 'Plaza Güemes (Salta)', -24.783, -65.413, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-016', 'Parque San Martín (Salta)', -24.781, -65.42, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-017', 'Plaza Centro (Salta)', -24.8227, -65.3437, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-018', 'Centro de Salud Centro (Salta)', -24.8856, -65.3616, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-019', 'Carrefour Centro (Salta)', -24.7181, -65.4877, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-020', 'Libertad Centro (Salta)', -24.7006, -65.3691, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-021', 'Estación de Servicio YPF Centro (Salta)', -24.7056, -65.4537, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-022', 'Estación de Servicio Shell Centro (Salta)', -24.8115, -65.4331, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-023', 'Estación de Servicio Axion Centro (Salta)', -24.6861, -65.3939, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-024', 'Farmacia Farmacity Centro (Salta)', -24.8138, -65.4261, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-025', 'Plaza Tres Cerritos', -24.8309, -65.502, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-026', 'Centro de Salud Tres Cerritos', -24.8656, -65.3448, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-027', 'Carrefour Tres Cerritos', -24.8288, -65.3246, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-028', 'Libertad Tres Cerritos', -24.836, -65.4586, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-029', 'Estación de Servicio YPF Tres Cerritos', -24.7837, -65.4737, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-030', 'Estación de Servicio Shell Tres Cerritos', -24.8112, -65.3205, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-031', 'Estación de Servicio Axion Tres Cerritos', -24.709, -65.3493, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-032', 'Farmacia Farmacity Tres Cerritos', -24.7597, -65.329, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-033', 'Plaza Grand Bourg', -24.6978, -65.4019, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-034', 'Centro de Salud Grand Bourg', -24.742, -65.5018, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-035', 'Carrefour Grand Bourg', -24.7394, -65.4215, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-036', 'Libertad Grand Bourg', -24.7354, -65.3828, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-037', 'Estación de Servicio YPF Grand Bourg', -24.8287, -65.5019, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-038', 'Estación de Servicio Shell Grand Bourg', -24.7005, -65.4862, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-039', 'Estación de Servicio Axion Grand Bourg', -24.7915, -65.443, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-040', 'Farmacia Farmacity Grand Bourg', -24.8263, -65.3639, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-041', 'Plaza Limache', -24.6906, -65.4597, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-042', 'Centro de Salud Limache', -24.7547, -65.4515, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-043', 'Carrefour Limache', -24.7744, -65.4328, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-044', 'Libertad Limache', -24.8524, -65.4794, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-045', 'Estación de Servicio YPF Limache', -24.8443, -65.3305, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-046', 'Estación de Servicio Shell Limache', -24.7865, -65.4677, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-047', 'Estación de Servicio Axion Limache', -24.7046, -65.3124, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-048', 'Farmacia Farmacity Limache', -24.7959, -65.4838, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-049', 'Plaza San Lorenzo (Salta)', -24.8474, -65.4936, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-050', 'Centro de Salud San Lorenzo (Salta)', -24.8175, -65.4935, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-051', 'Carrefour San Lorenzo (Salta)', -24.8381, -65.46, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-052', 'Libertad San Lorenzo (Salta)', -24.772, -65.3342, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-053', 'Estación de Servicio YPF San Lorenzo (Salta)', -24.736, -65.4291, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-054', 'Estación de Servicio Shell San Lorenzo (Salta)', -24.8031, -65.4069, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-055', 'Estación de Servicio Axion San Lorenzo (Salta)', -24.8105, -65.4441, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-056', 'Farmacia Farmacity San Lorenzo (Salta)', -24.8735, -65.4562, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-057', 'Plaza Villa Soledad', -24.6924, -65.4865, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-058', 'Centro de Salud Villa Soledad', -24.7852, -65.3858, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-059', 'Carrefour Villa Soledad', -24.7133, -65.4685, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-060', 'Libertad Villa Soledad', -24.8317, -65.462, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-061', 'Estación de Servicio YPF Villa Soledad', -24.8059, -65.4225, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-062', 'Estación de Servicio Shell Villa Soledad', -24.6951, -65.342, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-063', 'Estación de Servicio Axion Villa Soledad', -24.7113, -65.5073, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-064', 'Farmacia Farmacity Villa Soledad', -24.8795, -65.3698, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-065', 'Plaza Ciudad del Milagro', -24.7068, -65.417, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-066', 'Centro de Salud Ciudad del Milagro', -24.7685, -65.5117, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-067', 'Carrefour Ciudad del Milagro', -24.8076, -65.3263, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-068', 'Libertad Ciudad del Milagro', -24.7208, -65.3406, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-069', 'Estación de Servicio YPF Ciudad del Milagro', -24.6915, -65.462, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-070', 'Estación de Servicio Shell Ciudad del Milagro', -24.8641, -65.4808, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-071', 'Estación de Servicio Axion Ciudad del Milagro', -24.7814, -65.3753, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-072', 'Farmacia Farmacity Ciudad del Milagro', -24.6976, -65.3674, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-073', 'Plaza Castañares', -24.7564, -65.3587, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-074', 'Centro de Salud Castañares', -24.7944, -65.4014, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-075', 'Carrefour Castañares', -24.878, -65.3552, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-076', 'Libertad Castañares', -24.8394, -65.3277, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-077', 'Estación de Servicio YPF Castañares', -24.7568, -65.4509, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-078', 'Estación de Servicio Shell Castañares', -24.8603, -65.4613, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-079', 'Estación de Servicio Axion Castañares', -24.7586, -65.372, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-080', 'Farmacia Farmacity Castañares', -24.8635, -65.4976, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-081', 'Plaza Vasco Ansaldo', -24.781, -65.3951, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-082', 'Centro de Salud Vasco Ansaldo', -24.8083, -65.467, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-083', 'Carrefour Vasco Ansaldo', -24.7657, -65.5096, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-084', 'Libertad Vasco Ansaldo', -24.8256, -65.4196, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-085', 'Estación de Servicio YPF Vasco Ansaldo', -24.6941, -65.3828, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-086', 'Estación de Servicio Shell Vasco Ansaldo', -24.7091, -65.4166, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-087', 'Estación de Servicio Axion Vasco Ansaldo', -24.8389, -65.4623, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-088', 'Farmacia Farmacity Vasco Ansaldo', -24.6938, -65.3708, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-089', 'Plaza Solidaridad', -24.8244, -65.5073, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-090', 'Centro de Salud Solidaridad', -24.7862, -65.3768, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-091', 'Carrefour Solidaridad', -24.8019, -65.4602, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-092', 'Libertad Solidaridad', -24.7524, -65.3267, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-093', 'Estación de Servicio YPF Solidaridad', -24.8405, -65.5049, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-094', 'Estación de Servicio Shell Solidaridad', -24.8183, -65.4276, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-095', 'Estación de Servicio Axion Solidaridad', -24.7494, -65.4721, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-096', 'Farmacia Farmacity Solidaridad', -24.7265, -65.3639, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('salta-097', 'Plaza Autódromo', -24.7849, -65.4707, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('salta-098', 'Centro de Salud Autódromo', -24.6919, -65.4494, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('salta-099', 'Carrefour Autódromo', -24.7219, -65.4655, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('salta-100', 'Libertad Autódromo', -24.8416, -65.3596, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
