-- ============================================
-- Achou Trocador — Bariloche
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('bariloche-001', 'Centro Cívico de Bariloche', -41.1335, -71.3103, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bariloche-002', 'Catedral Nuestra Señora del Nahuel Huapi', -41.135, -71.309, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('bariloche-003', 'Cerro Catedral (base)', -41.166, -71.449, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-004', 'Cerro Otto', -41.159, -71.345, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-005', 'Playa Bonita (Bariloche)', -41.115, -71.36, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-006', 'Playa Serena', -41.135, -71.38, 'familia', 'Playa con estructura (paradores/baños) — depende del punto exacto tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-007', 'Costanera de Bariloche', -41.133, -71.313, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-008', 'Parque Municipal Llao Llao', -41.057, -71.533, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-009', 'Terminal de Ómnibus de Bariloche', -41.149, -71.296, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-010', 'Aeropuerto Internacional de Bariloche (Teniente Candelaria)', -41.1512, -71.1575, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-011', 'Hospital Zonal Ramón Carrillo (Bariloche)', -41.13, -71.295, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-012', 'Alto Bariloche Shopping', -41.136, -71.311, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('bariloche-013', 'Plaza San Martín (Bariloche)', -41.133, -71.3095, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-014', 'Estación de Trenes La Trochita (Bariloche)', -41.145, -71.305, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('bariloche-015', 'Plaza Centro (Bariloche)', -41.1745, -71.2199, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-016', 'Centro de Salud Centro (Bariloche)', -41.1343, -71.3728, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-017', 'Carrefour Centro (Bariloche)', -41.1888, -71.3269, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-018', 'La Anónima Centro (Bariloche)', -41.1004, -71.2205, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-019', 'Estación de Servicio YPF Centro (Bariloche)', -41.2042, -71.3316, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-020', 'Estación de Servicio Shell Centro (Bariloche)', -41.1909, -71.2155, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-021', 'Estación de Servicio Axion Centro (Bariloche)', -41.2051, -71.3999, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-022', 'Farmacia Farmacity Centro (Bariloche)', -41.2215, -71.3316, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-023', 'Plaza Belgrano', -41.0539, -71.2336, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-024', 'Centro de Salud Belgrano', -41.087, -71.2108, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-025', 'Carrefour Belgrano', -41.0472, -71.3445, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-026', 'La Anónima Belgrano', -41.1964, -71.2231, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-027', 'Estación de Servicio YPF Belgrano', -41.0842, -71.4039, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-028', 'Estación de Servicio Shell Belgrano', -41.1006, -71.3346, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-029', 'Estación de Servicio Axion Belgrano', -41.1587, -71.344, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-030', 'Farmacia Farmacity Belgrano', -41.1996, -71.4097, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-031', 'Plaza Melipal', -41.1775, -71.34, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-032', 'Centro de Salud Melipal', -41.0424, -71.3856, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-033', 'Carrefour Melipal', -41.0406, -71.3688, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-034', 'La Anónima Melipal', -41.1622, -71.246, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-035', 'Estación de Servicio YPF Melipal', -41.0691, -71.3238, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-036', 'Estación de Servicio Shell Melipal', -41.2236, -71.3156, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-037', 'Estación de Servicio Axion Melipal', -41.159, -71.2264, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-038', 'Farmacia Farmacity Melipal', -41.1949, -71.3375, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-039', 'Plaza Las Victorias', -41.0541, -71.4042, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-040', 'Centro de Salud Las Victorias', -41.1513, -71.2479, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-041', 'Carrefour Las Victorias', -41.0802, -71.4022, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-042', 'La Anónima Las Victorias', -41.2265, -71.3978, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-043', 'Estación de Servicio YPF Las Victorias', -41.0495, -71.3589, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-044', 'Estación de Servicio Shell Las Victorias', -41.084, -71.2306, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-045', 'Estación de Servicio Axion Las Victorias', -41.1657, -71.3558, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-046', 'Farmacia Farmacity Las Victorias', -41.042, -71.2869, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-047', 'Plaza Nahuel Hue', -41.1811, -71.267, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-048', 'Centro de Salud Nahuel Hue', -41.1702, -71.3552, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-049', 'Carrefour Nahuel Hue', -41.2327, -71.2592, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-050', 'La Anónima Nahuel Hue', -41.0502, -71.2835, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-051', 'Estación de Servicio YPF Nahuel Hue', -41.0448, -71.4054, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-052', 'Estación de Servicio Shell Nahuel Hue', -41.1867, -71.3153, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-053', 'Estación de Servicio Axion Nahuel Hue', -41.0421, -71.2195, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-054', 'Farmacia Farmacity Nahuel Hue', -41.1562, -71.3601, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-055', 'Plaza Los Coihues', -41.1475, -71.3116, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-056', 'Centro de Salud Los Coihues', -41.0479, -71.3737, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-057', 'Carrefour Los Coihues', -41.073, -71.2626, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-058', 'La Anónima Los Coihues', -41.0689, -71.2557, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-059', 'Estación de Servicio YPF Los Coihues', -41.112, -71.3447, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-060', 'Estación de Servicio Shell Los Coihues', -41.1696, -71.3379, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-061', 'Estación de Servicio Axion Los Coihues', -41.0771, -71.3945, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-062', 'Farmacia Farmacity Los Coihues', -41.194, -71.2597, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-063', 'Plaza Pinar Este', -41.184, -71.3974, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-064', 'Centro de Salud Pinar Este', -41.2267, -71.2998, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-065', 'Carrefour Pinar Este', -41.1683, -71.2142, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-066', 'La Anónima Pinar Este', -41.0568, -71.2127, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-067', 'Estación de Servicio YPF Pinar Este', -41.1805, -71.3935, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-068', 'Estación de Servicio Shell Pinar Este', -41.2142, -71.3106, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-069', 'Estación de Servicio Axion Pinar Este', -41.0915, -71.3209, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-070', 'Farmacia Farmacity Pinar Este', -41.1867, -71.3269, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-071', 'Plaza Pinar Sur', -41.1094, -71.2755, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-072', 'Centro de Salud Pinar Sur', -41.0839, -71.2409, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-073', 'Carrefour Pinar Sur', -41.1006, -71.3861, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-074', 'La Anónima Pinar Sur', -41.0653, -71.3515, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-075', 'Estación de Servicio YPF Pinar Sur', -41.1201, -71.3357, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-076', 'Estación de Servicio Shell Pinar Sur', -41.0859, -71.3705, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-077', 'Estación de Servicio Axion Pinar Sur', -41.184, -71.3612, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-078', 'Farmacia Farmacity Pinar Sur', -41.2028, -71.2335, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-079', 'Plaza El Cóndor', -41.1178, -71.345, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-080', 'Centro de Salud El Cóndor', -41.1543, -71.2118, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-081', 'Carrefour El Cóndor', -41.132, -71.364, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-082', 'La Anónima El Cóndor', -41.0718, -71.2796, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-083', 'Estación de Servicio YPF El Cóndor', -41.0353, -71.3898, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-084', 'Estación de Servicio Shell El Cóndor', -41.1385, -71.2465, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-085', 'Estación de Servicio Axion El Cóndor', -41.0654, -71.2274, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-086', 'Farmacia Farmacity El Cóndor', -41.2254, -71.3516, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-087', 'Plaza Villa Los Coihues', -41.2097, -71.3724, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-088', 'Centro de Salud Villa Los Coihues', -41.0389, -71.2937, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-089', 'Carrefour Villa Los Coihues', -41.0475, -71.3359, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-090', 'La Anónima Villa Los Coihues', -41.0603, -71.3205, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-091', 'Estación de Servicio YPF Villa Los Coihues', -41.1815, -71.2547, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-092', 'Estación de Servicio Shell Villa Los Coihues', -41.0444, -71.3891, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-093', 'Estación de Servicio Axion Villa Los Coihues', -41.1143, -71.2863, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-094', 'Farmacia Farmacity Villa Los Coihues', -41.19, -71.3366, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-095', 'Plaza Playa Bonita', -41.2052, -71.3695, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('bariloche-096', 'Centro de Salud Playa Bonita', -41.1825, -71.2904, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('bariloche-097', 'Carrefour Playa Bonita', -41.1032, -71.3696, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-098', 'La Anónima Playa Bonita', -41.2312, -71.3449, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('bariloche-099', 'Estación de Servicio YPF Playa Bonita', -41.0978, -71.3733, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('bariloche-100', 'Estación de Servicio Shell Playa Bonita', -41.1711, -71.3696, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false)
on conflict (id) do nothing;
