-- ============================================
-- Achou Trocador — Puerto Iguazú
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('iguazuar-001', 'Hito Tres Fronteras', -25.6003, -54.5917, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-002', 'Parque Nacional Iguazú (Portal de Acceso)', -25.672, -54.44, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-003', 'Plaza San Martín (Puerto Iguazú)', -25.599, -54.573, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-004', 'Paseo Pachamama', -25.596, -54.572, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-005', 'Terminal de Ómnibus de Puerto Iguazú', -25.598, -54.576, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-006', 'Aeropuerto Internacional de Iguazú (Cataratas del Iguazú)', -25.7373, -54.4734, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-007', 'Hospital SAMIC Puerto Iguazú', -25.594, -54.569, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-008', 'Casino Iguazú', -25.596, -54.585, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-009', 'Güirá Oga (Refugio de vida silvestre)', -25.66, -54.49, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-010', 'La Aripuca', -25.635, -54.523, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('iguazuar-011', 'Plaza Centro (Puerto Iguazú)', -25.5399, -54.5634, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-012', 'Centro de Salud Centro (Puerto Iguazú)', -25.6863, -54.6527, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-013', 'La Anónima Centro (Puerto Iguazú)', -25.6199, -54.563, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-014', 'Vea Centro (Puerto Iguazú)', -25.5712, -54.6548, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-015', 'Estación de Servicio YPF Centro (Puerto Iguazú)', -25.6663, -54.5339, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-016', 'Estación de Servicio Shell Centro (Puerto Iguazú)', -25.617, -54.6163, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-017', 'Estación de Servicio Axion Centro (Puerto Iguazú)', -25.6375, -54.4824, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-018', 'Farmacia Farmacity Centro (Puerto Iguazú)', -25.6365, -54.5597, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-019', 'Plaza Villa Nueva', -25.6276, -54.5897, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-020', 'Centro de Salud Villa Nueva', -25.5262, -54.4737, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-021', 'La Anónima Villa Nueva', -25.6262, -54.6336, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-022', 'Vea Villa Nueva', -25.5534, -54.6323, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-023', 'Estación de Servicio YPF Villa Nueva', -25.6978, -54.4927, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-024', 'Estación de Servicio Shell Villa Nueva', -25.6142, -54.5089, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-025', 'Estación de Servicio Axion Villa Nueva', -25.6178, -54.4964, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-026', 'Farmacia Farmacity Villa Nueva', -25.6068, -54.6405, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-027', 'Plaza San Jorge', -25.696, -54.5627, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-028', 'Centro de Salud San Jorge', -25.5709, -54.491, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-029', 'La Anónima San Jorge', -25.6812, -54.5486, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-030', 'Vea San Jorge', -25.6248, -54.5721, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-031', 'Estación de Servicio YPF San Jorge', -25.6698, -54.6163, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-032', 'Estación de Servicio Shell San Jorge', -25.5948, -54.4879, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-033', 'Estación de Servicio Axion San Jorge', -25.6772, -54.5749, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-034', 'Farmacia Farmacity San Jorge', -25.538, -54.4796, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-035', 'Plaza Puerto Iguazú Norte', -25.6595, -54.6477, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-036', 'Centro de Salud Puerto Iguazú Norte', -25.5104, -54.4779, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-037', 'La Anónima Puerto Iguazú Norte', -25.6025, -54.6623, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-038', 'Vea Puerto Iguazú Norte', -25.5138, -54.5954, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-039', 'Estación de Servicio YPF Puerto Iguazú Norte', -25.5182, -54.5489, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-040', 'Estación de Servicio Shell Puerto Iguazú Norte', -25.5341, -54.6409, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-041', 'Estación de Servicio Axion Puerto Iguazú Norte', -25.5418, -54.6286, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-042', 'Farmacia Farmacity Puerto Iguazú Norte', -25.6181, -54.5037, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-043', 'Plaza Puerto Iguazú Sur', -25.5332, -54.6364, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-044', 'Centro de Salud Puerto Iguazú Sur', -25.6554, -54.5931, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-045', 'La Anónima Puerto Iguazú Sur', -25.5954, -54.5963, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-046', 'Vea Puerto Iguazú Sur', -25.6744, -54.6236, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-047', 'Estación de Servicio YPF Puerto Iguazú Sur', -25.554, -54.4935, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-048', 'Estación de Servicio Shell Puerto Iguazú Sur', -25.6908, -54.5605, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-049', 'Estación de Servicio Axion Puerto Iguazú Sur', -25.5475, -54.6654, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-050', 'Farmacia Farmacity Puerto Iguazú Sur', -25.5314, -54.6495, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-051', 'Plaza Km 5', -25.5791, -54.563, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-052', 'Centro de Salud Km 5', -25.5736, -54.6118, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-053', 'La Anónima Km 5', -25.615, -54.5565, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-054', 'Vea Km 5', -25.6139, -54.5412, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-055', 'Estación de Servicio YPF Km 5', -25.6096, -54.5853, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-056', 'Estación de Servicio Shell Km 5', -25.6943, -54.5492, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-057', 'Estación de Servicio Axion Km 5', -25.6011, -54.6259, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-058', 'Farmacia Farmacity Km 5', -25.5463, -54.517, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-059', 'Plaza Km 8', -25.6073, -54.6371, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-060', 'Centro de Salud Km 8', -25.6044, -54.6516, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-061', 'La Anónima Km 8', -25.6733, -54.5869, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-062', 'Vea Km 8', -25.6807, -54.5846, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-063', 'Estación de Servicio YPF Km 8', -25.597, -54.6648, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-064', 'Estación de Servicio Shell Km 8', -25.5717, -54.6566, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-065', 'Estación de Servicio Axion Km 8', -25.5523, -54.5175, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-066', 'Farmacia Farmacity Km 8', -25.5967, -54.6621, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-067', 'Plaza Km 12', -25.5982, -54.5974, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-068', 'Centro de Salud Km 12', -25.5088, -54.6458, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-069', 'La Anónima Km 12', -25.5276, -54.4738, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-070', 'Vea Km 12', -25.5526, -54.51, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-071', 'Estación de Servicio YPF Km 12', -25.6603, -54.4767, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-072', 'Estación de Servicio Shell Km 12', -25.6006, -54.4817, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-073', 'Estación de Servicio Axion Km 12', -25.5158, -54.64, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-074', 'Farmacia Farmacity Km 12', -25.5413, -54.4869, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-075', 'Plaza Km 16', -25.6859, -54.6028, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-076', 'Centro de Salud Km 16', -25.5478, -54.6412, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-077', 'La Anónima Km 16', -25.5197, -54.618, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-078', 'Vea Km 16', -25.5359, -54.6443, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-079', 'Estación de Servicio YPF Km 16', -25.5986, -54.489, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-080', 'Estación de Servicio Shell Km 16', -25.6573, -54.6204, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-081', 'Estación de Servicio Axion Km 16', -25.5978, -54.6092, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-082', 'Farmacia Farmacity Km 16', -25.6916, -54.6366, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-083', 'Plaza Barrio Uocra', -25.6668, -54.4857, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-084', 'Centro de Salud Barrio Uocra', -25.5631, -54.4939, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-085', 'La Anónima Barrio Uocra', -25.6653, -54.516, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-086', 'Vea Barrio Uocra', -25.676, -54.5669, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-087', 'Estación de Servicio YPF Barrio Uocra', -25.5717, -54.601, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-088', 'Estación de Servicio Shell Barrio Uocra', -25.5244, -54.562, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-089', 'Estación de Servicio Axion Barrio Uocra', -25.583, -54.4965, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-090', 'Farmacia Farmacity Barrio Uocra', -25.6781, -54.4744, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-091', 'Plaza Barrio 2 de Abril', -25.573, -54.5941, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-092', 'Centro de Salud Barrio 2 de Abril', -25.5395, -54.62, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('iguazuar-093', 'La Anónima Barrio 2 de Abril', -25.5009, -54.5575, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-094', 'Vea Barrio 2 de Abril', -25.6269, -54.5201, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('iguazuar-095', 'Estación de Servicio YPF Barrio 2 de Abril', -25.6105, -54.6376, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-096', 'Estación de Servicio Shell Barrio 2 de Abril', -25.5503, -54.6633, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-097', 'Estación de Servicio Axion Barrio 2 de Abril', -25.535, -54.6223, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-098', 'Farmacia Farmacity Barrio 2 de Abril', -25.5712, -54.4762, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('iguazuar-099', 'Plaza Barrio Aeropuerto', -25.5818, -54.5403, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('iguazuar-100', 'Centro de Salud Barrio Aeropuerto', -25.6365, -54.6726, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false)
on conflict (id) do nothing;
