-- ============================================
-- Achou Trocador — Foz do Iguaçu
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('foz-001', 'Parque Nacional do Iguaçu (Cataratas)', -25.6953, -54.4367, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('foz-002', 'Marco das Três Fronteiras', -25.5947, -54.5983, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('foz-003', 'Usina Hidrelétrica de Itaipu', -25.4084, -54.5886, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('foz-004', 'Parque das Aves', -25.639, -54.446, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('foz-005', 'Templo Budista de Foz do Iguaçu', -25.498, -54.573, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('foz-006', 'Mesquita Omar Ibn Al-Khattab', -25.525, -54.585, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('foz-007', 'Catedral Nossa Senhora Aparecida (Foz)', -25.53, -54.586, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('foz-008', 'Shopping Cataratas JL', -25.525, -54.57, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('foz-009', 'Avenida Shopping Foz', -25.53, -54.576, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('foz-010', 'Terminal de Transporte Urbano de Foz do Iguaçu (TTU)', -25.545, -54.577, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('foz-011', 'Aeroporto Internacional de Foz do Iguaçu', -25.6003, -54.489, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('foz-012', 'Ponte da Amizade (Brasil-Paraguai)', -25.51, -54.607, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('foz-013', 'Hospital Municipal Padre Germano Lauck', -25.535, -54.59, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-014', 'Hospital Ministro Costa Cavalcanti', -25.53, -54.575, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-015', 'Marco das Três Fronteiras — mirante brasileiro', -25.5947, -54.598, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-016', 'Praça do Centro (Foz do Iguaçu)', -25.641, -54.6583, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-017', 'UBS Centro (Foz do Iguaçu)', -25.5246, -54.6018, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-018', 'Muffato Centro (Foz do Iguaçu)', -25.5453, -54.5091, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-019', 'Big Centro (Foz do Iguaçu)', -25.6214, -54.6427, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-020', 'Posto Ipiranga Centro (Foz do Iguaçu)', -25.5172, -54.6837, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-021', 'Posto Shell Centro (Foz do Iguaçu)', -25.6473, -54.6172, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-022', 'Posto Petrobras Centro (Foz do Iguaçu)', -25.6265, -54.6168, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-023', 'Farmácia Droga Raia Centro (Foz do Iguaçu)', -25.6029, -54.5715, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-024', 'Farmácia Drogasil Centro (Foz do Iguaçu)', -25.53, -54.6474, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-025', 'Praça do Vila Yolanda', -25.523, -54.5932, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-026', 'UBS Vila Yolanda', -25.6209, -54.5009, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-027', 'Muffato Vila Yolanda', -25.5991, -54.6583, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-028', 'Big Vila Yolanda', -25.6286, -54.5606, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-029', 'Posto Ipiranga Vila Yolanda', -25.4735, -54.5318, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-030', 'Posto Shell Vila Yolanda', -25.5674, -54.6354, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-031', 'Posto Petrobras Vila Yolanda', -25.6455, -54.5592, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-032', 'Farmácia Droga Raia Vila Yolanda', -25.5353, -54.6181, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-033', 'Farmácia Drogasil Vila Yolanda', -25.5187, -54.5994, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-034', 'Praça do Jardim das Nações', -25.4604, -54.5415, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-035', 'UBS Jardim das Nações', -25.5981, -54.5075, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-036', 'Muffato Jardim das Nações', -25.639, -54.5819, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-037', 'Big Jardim das Nações', -25.5666, -54.6407, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-038', 'Posto Ipiranga Jardim das Nações', -25.6361, -54.5324, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-039', 'Posto Shell Jardim das Nações', -25.6453, -54.578, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-040', 'Posto Petrobras Jardim das Nações', -25.4596, -54.6597, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-041', 'Farmácia Droga Raia Jardim das Nações', -25.6079, -54.5666, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-042', 'Farmácia Drogasil Jardim das Nações', -25.5464, -54.5599, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-043', 'Praça do Vila A', -25.4851, -54.6533, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-044', 'UBS Vila A', -25.5859, -54.6281, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-045', 'Muffato Vila A', -25.6381, -54.5103, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-046', 'Big Vila A', -25.4912, -54.5451, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-047', 'Posto Ipiranga Vila A', -25.6465, -54.5193, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-048', 'Posto Shell Vila A', -25.4988, -54.5951, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-049', 'Posto Petrobras Vila A', -25.4994, -54.5977, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-050', 'Farmácia Droga Raia Vila A', -25.6026, -54.6671, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-051', 'Farmácia Drogasil Vila A', -25.6013, -54.6804, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-052', 'Praça do Vila C', -25.5807, -54.5383, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-053', 'UBS Vila C', -25.5088, -54.5191, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-054', 'Muffato Vila C', -25.5055, -54.635, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-055', 'Big Vila C', -25.537, -54.601, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-056', 'Posto Ipiranga Vila C', -25.4901, -54.5836, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-057', 'Posto Shell Vila C', -25.5947, -54.5598, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-058', 'Posto Petrobras Vila C', -25.4548, -54.6448, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-059', 'Farmácia Droga Raia Vila C', -25.4718, -54.6852, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-060', 'Farmácia Drogasil Vila C', -25.5957, -54.641, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-061', 'Praça do Porto Meira', -25.499, -54.4993, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-062', 'UBS Porto Meira', -25.4986, -54.6228, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-063', 'Muffato Porto Meira', -25.4718, -54.6225, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-064', 'Big Porto Meira', -25.6, -54.5067, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-065', 'Posto Ipiranga Porto Meira', -25.5217, -54.5496, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-066', 'Posto Shell Porto Meira', -25.5148, -54.4924, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-067', 'Posto Petrobras Porto Meira', -25.5539, -54.5203, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-068', 'Farmácia Droga Raia Porto Meira', -25.5083, -54.5167, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-069', 'Farmácia Drogasil Porto Meira', -25.5604, -54.5433, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-070', 'Praça do Três Lagoas', -25.5337, -54.6266, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-071', 'UBS Três Lagoas', -25.6054, -54.5637, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-072', 'Muffato Três Lagoas', -25.6322, -54.506, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-073', 'Big Três Lagoas', -25.6189, -54.6828, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-074', 'Posto Ipiranga Três Lagoas', -25.6265, -54.5024, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-075', 'Posto Shell Três Lagoas', -25.5788, -54.6598, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-076', 'Posto Petrobras Três Lagoas', -25.6421, -54.6799, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-077', 'Farmácia Droga Raia Três Lagoas', -25.5093, -54.5614, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-078', 'Farmácia Drogasil Três Lagoas', -25.5084, -54.5408, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-079', 'Praça do Cataratas', -25.6346, -54.5701, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-080', 'UBS Cataratas', -25.5751, -54.5247, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-081', 'Muffato Cataratas', -25.4839, -54.5099, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-082', 'Big Cataratas', -25.6346, -54.5146, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-083', 'Posto Ipiranga Cataratas', -25.4649, -54.4993, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-084', 'Posto Shell Cataratas', -25.6264, -54.6471, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-085', 'Posto Petrobras Cataratas', -25.6254, -54.6813, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-086', 'Farmácia Droga Raia Cataratas', -25.4783, -54.5258, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-087', 'Farmácia Drogasil Cataratas', -25.521, -54.5232, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-088', 'Praça do Jupira', -25.5215, -54.6307, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-089', 'UBS Jupira', -25.6278, -54.6686, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-090', 'Muffato Jupira', -25.4963, -54.6472, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-091', 'Big Jupira', -25.584, -54.6034, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-092', 'Posto Ipiranga Jupira', -25.6436, -54.6369, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-093', 'Posto Shell Jupira', -25.5913, -54.545, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-094', 'Posto Petrobras Jupira', -25.5742, -54.624, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-095', 'Farmácia Droga Raia Jupira', -25.455, -54.5875, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-096', 'Farmácia Drogasil Jupira', -25.4775, -54.5645, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('foz-097', 'Praça do Campos do Iguaçu', -25.6416, -54.6056, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('foz-098', 'UBS Campos do Iguaçu', -25.5605, -54.5336, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('foz-099', 'Muffato Campos do Iguaçu', -25.5784, -54.5473, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('foz-100', 'Big Campos do Iguaçu', -25.5402, -54.6449, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false)
on conflict (id) do nothing;
