-- ============================================
-- Achou Trocador — Río Gallegos
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('riogallegos-001', 'Plaza San Martín (Río Gallegos)', -51.623, -69.218, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-002', 'Catedral Nuestra Señora de Luján (Río Gallegos)', -51.6225, -69.2185, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('riogallegos-003', 'Museo de los Pioneros', -51.618, -69.223, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('riogallegos-004', 'Costanera de Río Gallegos', -51.628, -69.215, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-005', 'Terminal de Ómnibus de Río Gallegos', -51.61, -69.227, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('riogallegos-006', 'Aeropuerto Internacional de Río Gallegos (Piloto Civil Norberto Fernández)', -51.6089, -69.3128, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('riogallegos-007', 'Hospital Regional Río Gallegos', -51.62, -69.22, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-008', 'Laguna Azul (Río Gallegos)', -51.75, -69.1, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-009', 'Plaza Centro (Río Gallegos)', -51.5506, -69.2998, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-010', 'Centro de Salud Centro (Río Gallegos)', -51.559, -69.2839, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-011', 'La Anónima Centro (Río Gallegos)', -51.7227, -69.2776, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-012', 'Carrefour Centro (Río Gallegos)', -51.5706, -69.1224, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-013', 'Estación de Servicio YPF Centro (Río Gallegos)', -51.7221, -69.2198, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-014', 'Estación de Servicio Shell Centro (Río Gallegos)', -51.6247, -69.1586, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-015', 'Estación de Servicio Axion Centro (Río Gallegos)', -51.6861, -69.2191, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-016', 'Farmacia Farmacity Centro (Río Gallegos)', -51.6536, -69.1516, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-017', 'Plaza Jardín Norte', -51.6709, -69.1292, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-018', 'Centro de Salud Jardín Norte', -51.6663, -69.2751, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-019', 'La Anónima Jardín Norte', -51.5831, -69.2183, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-020', 'Carrefour Jardín Norte', -51.701, -69.1907, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-021', 'Estación de Servicio YPF Jardín Norte', -51.7068, -69.1604, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-022', 'Estación de Servicio Shell Jardín Norte', -51.5836, -69.1606, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-023', 'Estación de Servicio Axion Jardín Norte', -51.5974, -69.2469, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-024', 'Farmacia Farmacity Jardín Norte', -51.6427, -69.2391, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-025', 'Plaza Jorge Newbery', -51.5449, -69.3008, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-026', 'Centro de Salud Jorge Newbery', -51.5453, -69.313, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-027', 'La Anónima Jorge Newbery', -51.6818, -69.2654, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-028', 'Carrefour Jorge Newbery', -51.5428, -69.2178, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-029', 'Estación de Servicio YPF Jorge Newbery', -51.6471, -69.1412, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-030', 'Estación de Servicio Shell Jorge Newbery', -51.6763, -69.2258, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-031', 'Estación de Servicio Axion Jorge Newbery', -51.6167, -69.1671, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-032', 'Farmacia Farmacity Jorge Newbery', -51.5724, -69.1887, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-033', 'Plaza Provincias Argentinas', -51.6533, -69.2527, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-034', 'Centro de Salud Provincias Argentinas', -51.6919, -69.1494, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-035', 'La Anónima Provincias Argentinas', -51.5906, -69.1696, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-036', 'Carrefour Provincias Argentinas', -51.6891, -69.2302, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-037', 'Estación de Servicio YPF Provincias Argentinas', -51.5683, -69.2022, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-038', 'Estación de Servicio Shell Provincias Argentinas', -51.6978, -69.2256, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-039', 'Estación de Servicio Axion Provincias Argentinas', -51.546, -69.2704, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-040', 'Farmacia Farmacity Provincias Argentinas', -51.6847, -69.2577, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-041', 'Plaza Roca', -51.5824, -69.1493, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-042', 'Centro de Salud Roca', -51.6921, -69.2868, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-043', 'La Anónima Roca', -51.6735, -69.2527, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-044', 'Carrefour Roca', -51.6186, -69.2858, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-045', 'Estación de Servicio YPF Roca', -51.6574, -69.2801, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-046', 'Estación de Servicio Shell Roca', -51.528, -69.1723, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-047', 'Estación de Servicio Axion Roca', -51.7026, -69.1255, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-048', 'Farmacia Farmacity Roca', -51.7027, -69.2412, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-049', 'Plaza Belgrano (Río Gallegos)', -51.5262, -69.159, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-050', 'Centro de Salud Belgrano (Río Gallegos)', -51.5763, -69.231, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-051', 'La Anónima Belgrano (Río Gallegos)', -51.6838, -69.1904, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-052', 'Carrefour Belgrano (Río Gallegos)', -51.7016, -69.2767, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-053', 'Estación de Servicio YPF Belgrano (Río Gallegos)', -51.6453, -69.3112, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-054', 'Estación de Servicio Shell Belgrano (Río Gallegos)', -51.6432, -69.1598, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-055', 'Estación de Servicio Axion Belgrano (Río Gallegos)', -51.5843, -69.2179, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-056', 'Farmacia Farmacity Belgrano (Río Gallegos)', -51.5965, -69.2253, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-057', 'Plaza Malvinas Argentinas', -51.6946, -69.1973, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-058', 'Centro de Salud Malvinas Argentinas', -51.6421, -69.1698, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-059', 'La Anónima Malvinas Argentinas', -51.5414, -69.232, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-060', 'Carrefour Malvinas Argentinas', -51.6082, -69.1682, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-061', 'Estación de Servicio YPF Malvinas Argentinas', -51.6388, -69.2723, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-062', 'Estación de Servicio Shell Malvinas Argentinas', -51.5786, -69.142, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-063', 'Estación de Servicio Axion Malvinas Argentinas', -51.5682, -69.178, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-064', 'Farmacia Farmacity Malvinas Argentinas', -51.5525, -69.1821, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-065', 'Plaza San Benito', -51.5947, -69.2272, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-066', 'Centro de Salud San Benito', -51.6604, -69.1923, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-067', 'La Anónima San Benito', -51.7034, -69.2341, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-068', 'Carrefour San Benito', -51.5665, -69.1754, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-069', 'Estación de Servicio YPF San Benito', -51.5971, -69.268, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-070', 'Estación de Servicio Shell San Benito', -51.6383, -69.227, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-071', 'Estación de Servicio Axion San Benito', -51.5987, -69.2361, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-072', 'Farmacia Farmacity San Benito', -51.588, -69.132, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-073', 'Plaza Constitución (Río Gallegos)', -51.6864, -69.1871, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-074', 'Centro de Salud Constitución (Río Gallegos)', -51.5674, -69.2403, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-075', 'La Anónima Constitución (Río Gallegos)', -51.625, -69.1231, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-076', 'Carrefour Constitución (Río Gallegos)', -51.7154, -69.2093, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-077', 'Estación de Servicio YPF Constitución (Río Gallegos)', -51.6908, -69.1616, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-078', 'Estación de Servicio Shell Constitución (Río Gallegos)', -51.5349, -69.2142, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-079', 'Estación de Servicio Axion Constitución (Río Gallegos)', -51.7028, -69.2031, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-080', 'Farmacia Farmacity Constitución (Río Gallegos)', -51.6148, -69.1745, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-081', 'Plaza Kirchner', -51.6206, -69.1901, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-082', 'Centro de Salud Kirchner', -51.5572, -69.2137, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-083', 'La Anónima Kirchner', -51.6409, -69.1284, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-084', 'Carrefour Kirchner', -51.681, -69.1811, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-085', 'Estación de Servicio YPF Kirchner', -51.6445, -69.1655, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-086', 'Estación de Servicio Shell Kirchner', -51.6985, -69.1211, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-087', 'Estación de Servicio Axion Kirchner', -51.6519, -69.3067, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-088', 'Farmacia Farmacity Kirchner', -51.6681, -69.2381, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-089', 'Plaza 26 de Enero', -51.7203, -69.2343, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-090', 'Centro de Salud 26 de Enero', -51.6389, -69.1783, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-091', 'La Anónima 26 de Enero', -51.6526, -69.265, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-092', 'Carrefour 26 de Enero', -51.6781, -69.1697, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-093', 'Estación de Servicio YPF 26 de Enero', -51.535, -69.2126, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-094', 'Estación de Servicio Shell 26 de Enero', -51.6792, -69.1577, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-095', 'Estación de Servicio Axion 26 de Enero', -51.6446, -69.2756, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-096', 'Farmacia Farmacity 26 de Enero', -51.6971, -69.1627, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('riogallegos-097', 'Plaza Roca II', -51.5611, -69.1911, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('riogallegos-098', 'Centro de Salud Roca II', -51.6292, -69.2056, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('riogallegos-099', 'La Anónima Roca II', -51.6778, -69.1252, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('riogallegos-100', 'Carrefour Roca II', -51.6524, -69.1902, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
