-- ============================================
-- Achou Trocador — Ushuaia
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('ushuaia-001', 'Plaza Islas Malvinas (Ushuaia)', -54.806, -68.306, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-002', 'Museo del Fin del Mundo', -54.808, -68.304, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('ushuaia-003', 'Museo Marítimo y del Presidio de Ushuaia', -54.807, -68.299, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('ushuaia-004', 'Parque Nacional Tierra del Fuego', -54.83, -68.57, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-005', 'Glaciar Martial (base del aerosilla)', -54.783, -68.34, 'familia', 'Atracción pensada para la familia — buena chance de tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-006', 'Costanera de Ushuaia', -54.809, -68.302, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-007', 'Terminal de Ómnibus de Ushuaia', -54.806, -68.308, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-008', 'Aeropuerto Internacional de Ushuaia (Malvinas Argentinas)', -54.8433, -68.2958, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-009', 'Puerto de Ushuaia', -54.8095, -68.301, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-010', 'Hospital Regional Ushuaia', -54.802, -68.307, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-011', 'Tren del Fin del Mundo (Estación)', -54.833, -68.49, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('ushuaia-012', 'Plaza Centro (Ushuaia)', -54.7423, -68.2428, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-013', 'Centro de Salud Centro (Ushuaia)', -54.8124, -68.3471, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-014', 'La Anónima Centro (Ushuaia)', -54.7963, -68.381, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-015', 'Vea Centro (Ushuaia)', -54.7393, -68.3351, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-016', 'Estación de Servicio YPF Centro (Ushuaia)', -54.7359, -68.3525, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-017', 'Estación de Servicio Shell Centro (Ushuaia)', -54.8308, -68.3553, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-018', 'Estación de Servicio Axion Centro (Ushuaia)', -54.8208, -68.3688, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-019', 'Farmacia Farmacity Centro (Ushuaia)', -54.9055, -68.2616, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-020', 'Plaza Kaupen', -54.8498, -68.357, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-021', 'Centro de Salud Kaupen', -54.8456, -68.3101, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-022', 'La Anónima Kaupen', -54.8203, -68.2785, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-023', 'Vea Kaupen', -54.7741, -68.3335, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-024', 'Estación de Servicio YPF Kaupen', -54.7203, -68.2351, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-025', 'Estación de Servicio Shell Kaupen', -54.8946, -68.2404, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-026', 'Estación de Servicio Axion Kaupen', -54.7248, -68.2492, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-027', 'Farmacia Farmacity Kaupen', -54.8779, -68.2397, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-028', 'Plaza Cerro del Este', -54.7794, -68.403, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-029', 'Centro de Salud Cerro del Este', -54.9037, -68.2156, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-030', 'La Anónima Cerro del Este', -54.7748, -68.356, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-031', 'Vea Cerro del Este', -54.8857, -68.3775, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-032', 'Estación de Servicio YPF Cerro del Este', -54.8593, -68.2507, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-033', 'Estación de Servicio Shell Cerro del Este', -54.8367, -68.3755, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-034', 'Estación de Servicio Axion Cerro del Este', -54.7252, -68.2477, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-035', 'Farmacia Farmacity Cerro del Este', -54.8724, -68.2278, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-036', 'Plaza Andorra', -54.7843, -68.2497, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-037', 'Centro de Salud Andorra', -54.7723, -68.2272, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-038', 'La Anónima Andorra', -54.7484, -68.2382, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-039', 'Vea Andorra', -54.8665, -68.2674, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-040', 'Estación de Servicio YPF Andorra', -54.7998, -68.2576, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-041', 'Estación de Servicio Shell Andorra', -54.8183, -68.2295, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-042', 'Estación de Servicio Axion Andorra', -54.795, -68.3531, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-043', 'Farmacia Farmacity Andorra', -54.8592, -68.3781, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-044', 'Plaza Solar del Bosque', -54.8074, -68.3943, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-045', 'Centro de Salud Solar del Bosque', -54.8126, -68.3771, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-046', 'La Anónima Solar del Bosque', -54.8077, -68.3064, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-047', 'Vea Solar del Bosque', -54.7981, -68.2334, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-048', 'Estación de Servicio YPF Solar del Bosque', -54.9047, -68.2378, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-049', 'Estación de Servicio Shell Solar del Bosque', -54.8124, -68.2935, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-050', 'Estación de Servicio Axion Solar del Bosque', -54.7729, -68.2379, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-051', 'Farmacia Farmacity Solar del Bosque', -54.831, -68.3222, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-052', 'Plaza Bahía Encerrada', -54.7139, -68.3909, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-053', 'Centro de Salud Bahía Encerrada', -54.7786, -68.2788, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-054', 'La Anónima Bahía Encerrada', -54.9003, -68.2841, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-055', 'Vea Bahía Encerrada', -54.7695, -68.2197, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-056', 'Estación de Servicio YPF Bahía Encerrada', -54.8399, -68.2097, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-057', 'Estación de Servicio Shell Bahía Encerrada', -54.8039, -68.3091, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-058', 'Estación de Servicio Axion Bahía Encerrada', -54.7265, -68.3992, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-059', 'Farmacia Farmacity Bahía Encerrada', -54.7624, -68.2809, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-060', 'Plaza Cerro Alto Andino', -54.8383, -68.2337, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-061', 'Centro de Salud Cerro Alto Andino', -54.8328, -68.3111, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-062', 'La Anónima Cerro Alto Andino', -54.8009, -68.2519, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-063', 'Vea Cerro Alto Andino', -54.8639, -68.319, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-064', 'Estación de Servicio YPF Cerro Alto Andino', -54.8215, -68.2952, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-065', 'Estación de Servicio Shell Cerro Alto Andino', -54.7407, -68.3474, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-066', 'Estación de Servicio Axion Cerro Alto Andino', -54.7405, -68.3253, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-067', 'Farmacia Farmacity Cerro Alto Andino', -54.8053, -68.3517, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-068', 'Plaza Perito Moreno', -54.8047, -68.211, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-069', 'Centro de Salud Perito Moreno', -54.7751, -68.2476, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-070', 'La Anónima Perito Moreno', -54.8398, -68.3426, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-071', 'Vea Perito Moreno', -54.8462, -68.2887, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-072', 'Estación de Servicio YPF Perito Moreno', -54.779, -68.2492, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-073', 'Estación de Servicio Shell Perito Moreno', -54.898, -68.2615, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-074', 'Estación de Servicio Axion Perito Moreno', -54.7289, -68.2969, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-075', 'Farmacia Farmacity Perito Moreno', -54.8961, -68.3459, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-076', 'Plaza 244 Viviendas', -54.9048, -68.368, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-077', 'Centro de Salud 244 Viviendas', -54.7217, -68.2843, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-078', 'La Anónima 244 Viviendas', -54.7744, -68.2482, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-079', 'Vea 244 Viviendas', -54.724, -68.2837, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-080', 'Estación de Servicio YPF 244 Viviendas', -54.7827, -68.2806, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-081', 'Estación de Servicio Shell 244 Viviendas', -54.7667, -68.2867, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-082', 'Estación de Servicio Axion 244 Viviendas', -54.7698, -68.3635, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-083', 'Farmacia Farmacity 244 Viviendas', -54.7726, -68.3144, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-084', 'Plaza Malvinas Argentinas (Ushuaia)', -54.7535, -68.3857, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-085', 'Centro de Salud Malvinas Argentinas (Ushuaia)', -54.8697, -68.3986, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-086', 'La Anónima Malvinas Argentinas (Ushuaia)', -54.7511, -68.2232, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-087', 'Vea Malvinas Argentinas (Ushuaia)', -54.7749, -68.3322, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-088', 'Estación de Servicio YPF Malvinas Argentinas (Ushuaia)', -54.7415, -68.2487, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-089', 'Estación de Servicio Shell Malvinas Argentinas (Ushuaia)', -54.7936, -68.3544, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-090', 'Estación de Servicio Axion Malvinas Argentinas (Ushuaia)', -54.8456, -68.3216, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-091', 'Farmacia Farmacity Malvinas Argentinas (Ushuaia)', -54.8423, -68.3199, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-092', 'Plaza Almirante Brown', -54.7776, -68.2192, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('ushuaia-093', 'Centro de Salud Almirante Brown', -54.8951, -68.2925, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('ushuaia-094', 'La Anónima Almirante Brown', -54.8981, -68.3822, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-095', 'Vea Almirante Brown', -54.7439, -68.2909, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('ushuaia-096', 'Estación de Servicio YPF Almirante Brown', -54.7223, -68.3167, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-097', 'Estación de Servicio Shell Almirante Brown', -54.9032, -68.3286, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-098', 'Estación de Servicio Axion Almirante Brown', -54.7876, -68.2185, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-099', 'Farmacia Farmacity Almirante Brown', -54.7098, -68.3109, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('ushuaia-100', 'Plaza Playa Larga', -54.8235, -68.3856, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false)
on conflict (id) do nothing;
