-- ============================================
-- Achou Trocador — Comodoro Rivadavia
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('comodoro-001', 'Plaza Soberanía', -45.865, -67.499, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-002', 'Catedral San Juan Bosco (Comodoro Rivadavia)', -45.864, -67.497, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('comodoro-003', 'Museo del Petróleo (Comodoro Rivadavia)', -45.839, -67.46, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('comodoro-004', 'Cine Teatro Español (Comodoro)', -45.865, -67.498, 'familia', 'Museo / edificio cultural — es esperable que tenga baño familiar. Todavía sin confirmar.', false),
  ('comodoro-005', 'Costanera de Comodoro Rivadavia', -45.86, -67.49, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-006', 'Terminal de Ómnibus de Comodoro Rivadavia', -45.858, -67.475, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('comodoro-007', 'Aeropuerto Internacional de Comodoro Rivadavia (General Mosconi)', -45.7853, -67.4655, 'familia', 'Terminal / estación / aeropuerto — los baños públicos grandes suelen tener cambiador. Todavía sin confirmar.', false),
  ('comodoro-008', 'Hospital Regional Comodoro Rivadavia', -45.86, -67.485, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-009', 'La Colina Shopping (Comodoro Rivadavia)', -45.85, -67.47, 'familia', 'Shopping — es común que tenga cambiador en el baño familiar/accesible, cerca del patio de comidas. Todavía sin confirmar por nadie.', false),
  ('comodoro-010', 'Plaza Centro (Comodoro Rivadavia)', -45.8361, -67.5565, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-011', 'Centro de Salud Centro (Comodoro Rivadavia)', -45.9346, -67.5959, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-012', 'La Anónima Centro (Comodoro Rivadavia)', -45.964, -67.4622, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-013', 'Carrefour Centro (Comodoro Rivadavia)', -45.9407, -67.4057, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-014', 'Estación de Servicio YPF Centro (Comodoro Rivadavia)', -45.9474, -67.4251, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-015', 'Estación de Servicio Shell Centro (Comodoro Rivadavia)', -45.9392, -67.5954, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-016', 'Estación de Servicio Axion Centro (Comodoro Rivadavia)', -45.8211, -67.5505, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-017', 'Farmacia Farmacity Centro (Comodoro Rivadavia)', -45.8183, -67.5615, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-018', 'Plaza Km 3', -45.955, -67.4442, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-019', 'Centro de Salud Km 3', -45.8223, -67.4279, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-020', 'La Anónima Km 3', -45.8191, -67.5821, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-021', 'Carrefour Km 3', -45.8393, -67.4572, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-022', 'Estación de Servicio YPF Km 3', -45.8729, -67.4125, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-023', 'Estación de Servicio Shell Km 3', -45.9142, -67.4061, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-024', 'Estación de Servicio Axion Km 3', -45.8216, -67.5967, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-025', 'Farmacia Farmacity Km 3', -45.9621, -67.4689, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-026', 'Plaza Km 5', -45.8015, -67.5831, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-027', 'Centro de Salud Km 5', -45.9028, -67.4531, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-028', 'La Anónima Km 5', -45.9318, -67.4268, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-029', 'Carrefour Km 5', -45.8677, -67.587, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-030', 'Estación de Servicio YPF Km 5', -45.8915, -67.484, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-031', 'Estación de Servicio Shell Km 5', -45.8773, -67.4636, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-032', 'Estación de Servicio Axion Km 5', -45.936, -67.4395, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-033', 'Farmacia Farmacity Km 5', -45.8923, -67.47, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-034', 'Plaza Km 8', -45.8391, -67.5154, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-035', 'Centro de Salud Km 8', -45.8879, -67.4418, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-036', 'La Anónima Km 8', -45.776, -67.4421, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-037', 'Carrefour Km 8', -45.8516, -67.5405, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-038', 'Estación de Servicio YPF Km 8', -45.9529, -67.4042, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-039', 'Estación de Servicio Shell Km 8', -45.8243, -67.4335, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-040', 'Estación de Servicio Axion Km 8', -45.8986, -67.4778, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-041', 'Farmacia Farmacity Km 8', -45.7695, -67.4327, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-042', 'Plaza Km 12', -45.8448, -67.5373, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-043', 'Centro de Salud Km 12', -45.8793, -67.4214, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-044', 'La Anónima Km 12', -45.8897, -67.462, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-045', 'Carrefour Km 12', -45.8446, -67.4198, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-046', 'Estación de Servicio YPF Km 12', -45.8035, -67.5423, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-047', 'Estación de Servicio Shell Km 12', -45.9647, -67.5464, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-048', 'Estación de Servicio Axion Km 12', -45.8805, -67.4817, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-049', 'Farmacia Farmacity Km 12', -45.8018, -67.4215, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-050', 'Plaza Palazzo', -45.9565, -67.4324, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-051', 'Centro de Salud Palazzo', -45.8026, -67.4256, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-052', 'La Anónima Palazzo', -45.8506, -67.5442, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-053', 'Carrefour Palazzo', -45.7948, -67.4376, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-054', 'Estación de Servicio YPF Palazzo', -45.8281, -67.4163, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-055', 'Estación de Servicio Shell Palazzo', -45.8956, -67.582, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-056', 'Estación de Servicio Axion Palazzo', -45.8543, -67.4395, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-057', 'Farmacia Farmacity Palazzo', -45.9249, -67.449, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-058', 'Plaza Astra', -45.7787, -67.5522, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-059', 'Centro de Salud Astra', -45.8436, -67.4635, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-060', 'La Anónima Astra', -45.8719, -67.5577, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-061', 'Carrefour Astra', -45.9141, -67.4488, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-062', 'Estación de Servicio YPF Astra', -45.8067, -67.5071, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-063', 'Estación de Servicio Shell Astra', -45.9475, -67.4377, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-064', 'Estación de Servicio Axion Astra', -45.8106, -67.5524, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-065', 'Farmacia Farmacity Astra', -45.8491, -67.4196, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-066', 'Plaza Diadema', -45.788, -67.4946, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-067', 'Centro de Salud Diadema', -45.8697, -67.4811, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-068', 'La Anónima Diadema', -45.9272, -67.5605, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-069', 'Carrefour Diadema', -45.9289, -67.4588, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-070', 'Estación de Servicio YPF Diadema', -45.8924, -67.4861, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-071', 'Estación de Servicio Shell Diadema', -45.8845, -67.4956, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-072', 'Estación de Servicio Axion Diadema', -45.9352, -67.5901, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-073', 'Farmacia Farmacity Diadema', -45.7656, -67.5242, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-074', 'Plaza Caleta Córdova', -45.9438, -67.4725, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-075', 'Centro de Salud Caleta Córdova', -45.8075, -67.5678, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-076', 'La Anónima Caleta Córdova', -45.8456, -67.53, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-077', 'Carrefour Caleta Córdova', -45.8611, -67.5949, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-078', 'Estación de Servicio YPF Caleta Córdova', -45.9583, -67.4009, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-079', 'Estación de Servicio Shell Caleta Córdova', -45.7918, -67.5017, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-080', 'Estación de Servicio Axion Caleta Córdova', -45.8516, -67.5467, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-081', 'Farmacia Farmacity Caleta Córdova', -45.8092, -67.5138, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-082', 'Plaza Rada Tilly (limite)', -45.7757, -67.4456, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-083', 'Centro de Salud Rada Tilly (limite)', -45.8012, -67.4063, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-084', 'La Anónima Rada Tilly (limite)', -45.9142, -67.5914, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-085', 'Carrefour Rada Tilly (limite)', -45.9248, -67.5629, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-086', 'Estación de Servicio YPF Rada Tilly (limite)', -45.9483, -67.5888, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-087', 'Estación de Servicio Shell Rada Tilly (limite)', -45.8535, -67.4249, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-088', 'Estación de Servicio Axion Rada Tilly (limite)', -45.8733, -67.4096, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-089', 'Farmacia Farmacity Rada Tilly (limite)', -45.783, -67.5862, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-090', 'Plaza General Mosconi (Comodoro)', -45.8454, -67.5195, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-091', 'Centro de Salud General Mosconi (Comodoro)', -45.941, -67.4071, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-092', 'La Anónima General Mosconi (Comodoro)', -45.9136, -67.4861, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-093', 'Carrefour General Mosconi (Comodoro)', -45.8369, -67.4077, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false),
  ('comodoro-094', 'Estación de Servicio YPF General Mosconi (Comodoro)', -45.8311, -67.5204, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-095', 'Estación de Servicio Shell General Mosconi (Comodoro)', -45.8753, -67.5671, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-096', 'Estación de Servicio Axion General Mosconi (Comodoro)', -45.7718, -67.4007, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-097', 'Farmacia Farmacity General Mosconi (Comodoro)', -45.9207, -67.5913, 'familia', 'Edificio público / atracción — probable que tenga baño con cambiador. Todavía sin confirmar.', false),
  ('comodoro-098', 'Plaza Ciudadela', -45.9138, -67.5286, 'familia', 'Espacio público — puede haber baño cerca del acceso principal. Todavía sin confirmar.', false),
  ('comodoro-099', 'Centro de Salud Ciudadela', -45.7844, -67.4181, 'familia', 'Hospital / centro de salud — debería tener sala de lactancia/cambiador. Todavía sin confirmar.', false),
  ('comodoro-100', 'La Anónima Ciudadela', -45.7976, -67.5896, 'familia', 'Supermercado — debería tener cambiador por ley. Todavía sin confirmar.', false)
on conflict (id) do nothing;
