-- ============================================
-- Achou Trocador — Gramado
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('gramado-001', 'Lago Negro (Gramado)', -29.38, -50.872, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-002', 'Rua Coberta de Gramado', -29.378, -50.876, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-003', 'Mini Mundo', -29.37, -50.865, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('gramado-004', 'Snowland Gramado', -29.355, -50.83, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('gramado-005', 'Parque Knorrville', -29.365, -50.86, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('gramado-006', 'Igreja Matriz São Pedro (Gramado)', -29.379, -50.875, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('gramado-007', 'Mundo a Vapor', -29.369, -50.864, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('gramado-008', 'Vale dos Vinhedos (acesso Gramado)', -29.21, -51.53, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-009', 'Terminal Rodoviário de Gramado', -29.376, -50.879, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('gramado-010', 'Hospital de Caridade de Gramado', -29.38, -50.88, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-011', 'Palácio dos Festivais', -29.378, -50.874, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('gramado-012', 'Shopping Time Square Gramado', -29.372, -50.868, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('gramado-013', 'Praça do Centro (Gramado)', -29.3216, -50.8337, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-014', 'UBS Centro (Gramado)', -29.3496, -50.7785, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-015', 'Bistek Centro (Gramado)', -29.4677, -50.9466, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-016', 'Zaffari Centro (Gramado)', -29.3279, -50.7877, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-017', 'Posto Ipiranga Centro (Gramado)', -29.3435, -50.9158, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-018', 'Posto Shell Centro (Gramado)', -29.3606, -50.824, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-019', 'Posto Petrobras Centro (Gramado)', -29.4578, -50.9108, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-020', 'Farmácia Droga Raia Centro (Gramado)', -29.4275, -50.9508, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-021', 'Farmácia Drogasil Centro (Gramado)', -29.3826, -50.9419, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-022', 'Praça do Piratini', -29.4312, -50.947, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-023', 'UBS Piratini', -29.3434, -50.9731, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-024', 'Bistek Piratini', -29.3355, -50.9366, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-025', 'Zaffari Piratini', -29.4717, -50.7901, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-026', 'Posto Ipiranga Piratini', -29.4348, -50.7888, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-027', 'Posto Shell Piratini', -29.3055, -50.7979, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-028', 'Posto Petrobras Piratini', -29.4509, -50.8862, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-029', 'Farmácia Droga Raia Piratini', -29.4595, -50.7898, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-030', 'Farmácia Drogasil Piratini', -29.3105, -50.8499, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-031', 'Praça do Planalto', -29.3884, -50.9076, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-032', 'UBS Planalto', -29.3143, -50.8801, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-033', 'Bistek Planalto', -29.3533, -50.947, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-034', 'Zaffari Planalto', -29.4346, -50.9643, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-035', 'Posto Ipiranga Planalto', -29.3362, -50.8649, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-036', 'Posto Shell Planalto', -29.45, -50.8015, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-037', 'Posto Petrobras Planalto', -29.4256, -50.8932, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-038', 'Farmácia Droga Raia Planalto', -29.4478, -50.9214, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-039', 'Farmácia Drogasil Planalto', -29.311, -50.9087, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-040', 'Praça do Várzea Grande', -29.4453, -50.8774, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-041', 'UBS Várzea Grande', -29.4153, -50.795, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-042', 'Bistek Várzea Grande', -29.4561, -50.7799, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-043', 'Zaffari Várzea Grande', -29.4675, -50.7966, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-044', 'Posto Ipiranga Várzea Grande', -29.3452, -50.9334, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-045', 'Posto Shell Várzea Grande', -29.3834, -50.9184, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-046', 'Posto Petrobras Várzea Grande', -29.4273, -50.9353, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-047', 'Farmácia Droga Raia Várzea Grande', -29.406, -50.7774, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-048', 'Farmácia Drogasil Várzea Grande', -29.2793, -50.7906, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-049', 'Praça do Carniel', -29.4594, -50.9177, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-050', 'UBS Carniel', -29.2997, -50.9641, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-051', 'Bistek Carniel', -29.3336, -50.9169, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-052', 'Zaffari Carniel', -29.2832, -50.9724, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-053', 'Posto Ipiranga Carniel', -29.3175, -50.9074, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-054', 'Posto Shell Carniel', -29.4509, -50.9752, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-055', 'Posto Petrobras Carniel', -29.3125, -50.8703, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-056', 'Farmácia Droga Raia Carniel', -29.4417, -50.8886, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-057', 'Farmácia Drogasil Carniel', -29.2965, -50.9319, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-058', 'Praça do Bavária', -29.3646, -50.948, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-059', 'UBS Bavária', -29.4429, -50.8215, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-060', 'Bistek Bavária', -29.3366, -50.9363, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-061', 'Zaffari Bavária', -29.463, -50.9581, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-062', 'Posto Ipiranga Bavária', -29.3572, -50.8765, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-063', 'Posto Shell Bavária', -29.4241, -50.9344, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-064', 'Posto Petrobras Bavária', -29.3564, -50.834, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-065', 'Farmácia Droga Raia Bavária', -29.3166, -50.859, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-066', 'Farmácia Drogasil Bavária', -29.4384, -50.9625, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-067', 'Praça do Tirol', -29.3324, -50.894, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-068', 'UBS Tirol', -29.3346, -50.9645, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-069', 'Bistek Tirol', -29.3168, -50.9086, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-070', 'Zaffari Tirol', -29.3105, -50.8027, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-071', 'Posto Ipiranga Tirol', -29.3803, -50.9725, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-072', 'Posto Shell Tirol', -29.2969, -50.8803, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-073', 'Posto Petrobras Tirol', -29.3045, -50.9223, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-074', 'Farmácia Droga Raia Tirol', -29.4417, -50.8093, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-075', 'Farmácia Drogasil Tirol', -29.4055, -50.9429, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-076', 'Praça do Viação Férrea', -29.4047, -50.8566, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-077', 'UBS Viação Férrea', -29.478, -50.8716, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-078', 'Bistek Viação Férrea', -29.3897, -50.8725, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-079', 'Zaffari Viação Férrea', -29.4547, -50.8327, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-080', 'Posto Ipiranga Viação Férrea', -29.3156, -50.8025, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-081', 'Posto Shell Viação Férrea', -29.4147, -50.8334, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-082', 'Posto Petrobras Viação Férrea', -29.4026, -50.8253, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-083', 'Farmácia Droga Raia Viação Férrea', -29.4667, -50.801, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-084', 'Farmácia Drogasil Viação Férrea', -29.2881, -50.8766, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-085', 'Praça do Icaraí', -29.3762, -50.8695, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-086', 'UBS Icaraí', -29.3714, -50.9715, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-087', 'Bistek Icaraí', -29.2854, -50.9309, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-088', 'Zaffari Icaraí', -29.4424, -50.9551, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-089', 'Posto Ipiranga Icaraí', -29.4288, -50.8122, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-090', 'Posto Shell Icaraí', -29.4729, -50.9563, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-091', 'Posto Petrobras Icaraí', -29.3391, -50.9366, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-092', 'Farmácia Droga Raia Icaraí', -29.4754, -50.8557, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-093', 'Farmácia Drogasil Icaraí', -29.3636, -50.871, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-094', 'Praça do Poço Fundo', -29.3384, -50.955, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('gramado-095', 'UBS Poço Fundo', -29.305, -50.8322, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('gramado-096', 'Bistek Poço Fundo', -29.4699, -50.951, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-097', 'Zaffari Poço Fundo', -29.3802, -50.8754, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('gramado-098', 'Posto Ipiranga Poço Fundo', -29.423, -50.9512, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-099', 'Posto Shell Poço Fundo', -29.3978, -50.9482, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('gramado-100', 'Posto Petrobras Poço Fundo', -29.3605, -50.8034, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
