-- ============================================
-- Achou Trocador — Santa Maria (RS)
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('santamaria-001', 'Shopping Praça Nova Santa Maria', -29.69, -53.806, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('santamaria-002', 'Calçadão de Santa Maria', -29.685, -53.807, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-003', 'Praça Saldanha Marinho', -29.685, -53.8075, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-004', 'Museu Ferroviário de Santa Maria', -29.687, -53.802, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('santamaria-005', 'Parque Itaimbé', -29.695, -53.81, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-006', 'UFSM — Universidade Federal de Santa Maria', -29.716, -53.718, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-007', 'Catedral Diocesana de Santa Maria', -29.6845, -53.808, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('santamaria-008', 'Terminal Rodoviário de Santa Maria', -29.69, -53.798, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('santamaria-009', 'Aeroporto de Santa Maria', -29.7113, -53.6883, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('santamaria-010', 'Hospital Universitário de Santa Maria (HUSM)', -29.71, -53.725, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-011', 'Hospital de Caridade de Santa Maria', -29.687, -53.813, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-012', 'Parque Não Me Toque (Santa Maria)', -29.679, -53.825, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-013', 'Praça do Centro (Santa Maria)', -29.7548, -53.7923, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-014', 'UBS Centro (Santa Maria)', -29.6349, -53.874, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-015', 'Zaffari Centro (Santa Maria)', -29.619, -53.7194, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-016', 'Nacional Centro (Santa Maria)', -29.7065, -53.8228, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-017', 'Posto Ipiranga Centro (Santa Maria)', -29.6163, -53.8018, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-018', 'Posto Shell Centro (Santa Maria)', -29.7051, -53.7186, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-019', 'Posto Petrobras Centro (Santa Maria)', -29.6288, -53.8392, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-020', 'Farmácia Droga Raia Centro (Santa Maria)', -29.7361, -53.8399, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-021', 'Farmácia Drogasil Centro (Santa Maria)', -29.6971, -53.7107, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-022', 'Praça do Nossa Senhora de Lourdes', -29.6233, -53.7243, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-023', 'UBS Nossa Senhora de Lourdes', -29.6212, -53.7374, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-024', 'Zaffari Nossa Senhora de Lourdes', -29.7735, -53.8034, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-025', 'Nacional Nossa Senhora de Lourdes', -29.5926, -53.72, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-026', 'Posto Ipiranga Nossa Senhora de Lourdes', -29.7343, -53.8225, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-027', 'Posto Shell Nossa Senhora de Lourdes', -29.6577, -53.834, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-028', 'Posto Petrobras Nossa Senhora de Lourdes', -29.678, -53.893, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-029', 'Farmácia Droga Raia Nossa Senhora de Lourdes', -29.6976, -53.8059, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-030', 'Farmácia Drogasil Nossa Senhora de Lourdes', -29.78, -53.879, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-031', 'Praça do Camobi', -29.5903, -53.7516, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-032', 'UBS Camobi', -29.5968, -53.7803, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-033', 'Zaffari Camobi', -29.6223, -53.73, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-034', 'Nacional Camobi', -29.6073, -53.9, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-035', 'Posto Ipiranga Camobi', -29.6559, -53.8537, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-036', 'Posto Shell Camobi', -29.6485, -53.8522, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-037', 'Posto Petrobras Camobi', -29.6757, -53.722, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-038', 'Farmácia Droga Raia Camobi', -29.6599, -53.8568, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-039', 'Farmácia Drogasil Camobi', -29.6801, -53.8202, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-040', 'Praça do Nossa Senhora das Dores', -29.594, -53.8494, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-041', 'UBS Nossa Senhora das Dores', -29.7231, -53.7774, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-042', 'Zaffari Nossa Senhora das Dores', -29.7601, -53.788, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-043', 'Nacional Nossa Senhora das Dores', -29.593, -53.8041, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-044', 'Posto Ipiranga Nossa Senhora das Dores', -29.7305, -53.8136, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-045', 'Posto Shell Nossa Senhora das Dores', -29.6774, -53.8772, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-046', 'Posto Petrobras Nossa Senhora das Dores', -29.7594, -53.8806, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-047', 'Farmácia Droga Raia Nossa Senhora das Dores', -29.7255, -53.8256, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-048', 'Farmácia Drogasil Nossa Senhora das Dores', -29.7265, -53.8582, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-049', 'Praça do Nossa Senhora de Fátima', -29.7666, -53.7976, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-050', 'UBS Nossa Senhora de Fátima', -29.6163, -53.7849, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-051', 'Zaffari Nossa Senhora de Fátima', -29.6702, -53.7768, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-052', 'Nacional Nossa Senhora de Fátima', -29.744, -53.7648, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-053', 'Posto Ipiranga Nossa Senhora de Fátima', -29.692, -53.7973, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-054', 'Posto Shell Nossa Senhora de Fátima', -29.6616, -53.8131, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-055', 'Posto Petrobras Nossa Senhora de Fátima', -29.7221, -53.8584, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-056', 'Farmácia Droga Raia Nossa Senhora de Fátima', -29.7399, -53.8044, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-057', 'Farmácia Drogasil Nossa Senhora de Fátima', -29.7076, -53.7898, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-058', 'Praça do Patronato', -29.7818, -53.8364, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-059', 'UBS Patronato', -29.6118, -53.8592, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-060', 'Zaffari Patronato', -29.6729, -53.8086, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-061', 'Nacional Patronato', -29.7272, -53.7094, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-062', 'Posto Ipiranga Patronato', -29.7251, -53.7525, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-063', 'Posto Shell Patronato', -29.7525, -53.8935, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-064', 'Posto Petrobras Patronato', -29.6099, -53.8189, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-065', 'Farmácia Droga Raia Patronato', -29.7718, -53.8293, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-066', 'Farmácia Drogasil Patronato', -29.6962, -53.7598, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-067', 'Praça do Tancredo Neves', -29.7624, -53.8619, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-068', 'UBS Tancredo Neves', -29.5923, -53.7592, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-069', 'Zaffari Tancredo Neves', -29.7533, -53.8395, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-070', 'Nacional Tancredo Neves', -29.7137, -53.7718, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-071', 'Posto Ipiranga Tancredo Neves', -29.6609, -53.7369, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-072', 'Posto Shell Tancredo Neves', -29.62, -53.8033, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-073', 'Posto Petrobras Tancredo Neves', -29.6364, -53.7582, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-074', 'Farmácia Droga Raia Tancredo Neves', -29.6323, -53.8119, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-075', 'Farmácia Drogasil Tancredo Neves', -29.6272, -53.7652, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-076', 'Praça do Boi Morto', -29.6013, -53.8814, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-077', 'UBS Boi Morto', -29.61, -53.906, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-078', 'Zaffari Boi Morto', -29.6311, -53.7897, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-079', 'Nacional Boi Morto', -29.6846, -53.7144, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-080', 'Posto Ipiranga Boi Morto', -29.6698, -53.8233, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-081', 'Posto Shell Boi Morto', -29.6275, -53.7323, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-082', 'Posto Petrobras Boi Morto', -29.6627, -53.831, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-083', 'Farmácia Droga Raia Boi Morto', -29.6937, -53.8153, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-084', 'Farmácia Drogasil Boi Morto', -29.6396, -53.8483, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-085', 'Praça do Km 3', -29.7061, -53.7958, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-086', 'UBS Km 3', -29.7073, -53.8425, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-087', 'Zaffari Km 3', -29.6268, -53.737, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-088', 'Nacional Km 3', -29.6843, -53.8181, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-089', 'Posto Ipiranga Km 3', -29.7474, -53.8461, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-090', 'Posto Shell Km 3', -29.7552, -53.7918, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-091', 'Posto Petrobras Km 3', -29.6679, -53.8893, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-092', 'Farmácia Droga Raia Km 3', -29.6002, -53.8421, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-093', 'Farmácia Drogasil Km 3', -29.6155, -53.7393, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-094', 'Praça do Itararé', -29.5924, -53.866, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('santamaria-095', 'UBS Itararé', -29.6989, -53.7248, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('santamaria-096', 'Zaffari Itararé', -29.7821, -53.8974, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-097', 'Nacional Itararé', -29.6712, -53.8074, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('santamaria-098', 'Posto Ipiranga Itararé', -29.6001, -53.7522, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-099', 'Posto Shell Itararé', -29.6765, -53.7072, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('santamaria-100', 'Posto Petrobras Itararé', -29.6807, -53.8034, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
