-- ============================================
-- Achou Trocador — Balneário Camboriú
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('bcamboriu-001', 'Praia Central de Balneário Camboriú', -26.9906, -48.635, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-002', 'Praia dos Estados', -27.01, -48.61, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-003', 'Praia de Laranjeiras', -27.03, -48.59, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-004', 'Parque Unipraias (base)', -26.999, -48.621, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-005', 'Cristo Luz', -26.994, -48.618, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-006', 'Avenida Atlântica (Balneário Camboriú)', -26.9906, -48.632, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-007', 'Balneário Shopping', -26.995, -48.633, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('bcamboriu-008', 'Neumarkt Shopping', -26.98, -48.64, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('bcamboriu-009', 'Marina Balneário Camboriú', -26.986, -48.622, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-010', 'Igreja Matriz São João Batista (Balneário Camboriú)', -26.992, -48.637, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('bcamboriu-011', 'Terminal Rodoviário de Balneário Camboriú', -26.995, -48.642, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-012', 'Hospital Municipal Balneário Camboriú', -27.002, -48.628, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-013', 'Parque Cyro Gevaerd (Zoológico)', -27.008, -48.625, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('bcamboriu-014', 'Praça do Centro (Balneário Camboriú)', -26.9536, -48.6571, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-015', 'UBS Centro (Balneário Camboriú)', -27.0191, -48.6161, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-016', 'Angeloni Centro (Balneário Camboriú)', -27.0204, -48.5454, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-017', 'Giassi Centro (Balneário Camboriú)', -26.9553, -48.63, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-018', 'Posto Ipiranga Centro (Balneário Camboriú)', -27.0708, -48.6601, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-019', 'Posto Shell Centro (Balneário Camboriú)', -27.0104, -48.6227, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-020', 'Posto Petrobras Centro (Balneário Camboriú)', -26.9758, -48.559, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-021', 'Farmácia Droga Raia Centro (Balneário Camboriú)', -26.8977, -48.6377, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-022', 'Farmácia Drogasil Centro (Balneário Camboriú)', -27.0026, -48.6101, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-023', 'Praça do Barra Sul', -26.8914, -48.6663, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-024', 'UBS Barra Sul', -26.9846, -48.5718, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-025', 'Angeloni Barra Sul', -27.0565, -48.6714, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-026', 'Giassi Barra Sul', -26.8949, -48.5698, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-027', 'Posto Ipiranga Barra Sul', -26.9881, -48.7129, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-028', 'Posto Shell Barra Sul', -26.9117, -48.597, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-029', 'Posto Petrobras Barra Sul', -26.9265, -48.537, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-030', 'Farmácia Droga Raia Barra Sul', -26.913, -48.6508, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-031', 'Farmácia Drogasil Barra Sul', -27.0593, -48.677, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-032', 'Praça do Barra Norte', -26.9883, -48.634, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-033', 'UBS Barra Norte', -27.053, -48.6985, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-034', 'Angeloni Barra Norte', -26.9646, -48.6144, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-035', 'Giassi Barra Norte', -27.02, -48.5363, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-036', 'Posto Ipiranga Barra Norte', -26.9633, -48.7265, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-037', 'Posto Shell Barra Norte', -27.0083, -48.5775, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-038', 'Posto Petrobras Barra Norte', -27.0293, -48.5969, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-039', 'Farmácia Droga Raia Barra Norte', -27.0898, -48.6741, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-040', 'Farmácia Drogasil Barra Norte', -26.9222, -48.6178, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-041', 'Praça do Pioneiros', -26.957, -48.6957, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-042', 'UBS Pioneiros', -26.991, -48.6244, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-043', 'Angeloni Pioneiros', -27.0374, -48.6056, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-044', 'Giassi Pioneiros', -26.9843, -48.5356, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-045', 'Posto Ipiranga Pioneiros', -26.9757, -48.6528, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-046', 'Posto Shell Pioneiros', -27.0663, -48.7036, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-047', 'Posto Petrobras Pioneiros', -26.9387, -48.7137, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-048', 'Farmácia Droga Raia Pioneiros', -27.0706, -48.7009, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-049', 'Farmácia Drogasil Pioneiros', -26.9861, -48.5704, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-050', 'Praça do Nações', -26.968, -48.5737, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-051', 'UBS Nações', -27.0782, -48.7325, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-052', 'Angeloni Nações', -26.9365, -48.6704, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-053', 'Giassi Nações', -26.9475, -48.6642, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-054', 'Posto Ipiranga Nações', -27.0567, -48.6817, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-055', 'Posto Shell Nações', -27.0707, -48.5542, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-056', 'Posto Petrobras Nações', -26.9741, -48.6652, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-057', 'Farmácia Droga Raia Nações', -27.0006, -48.6579, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-058', 'Farmácia Drogasil Nações', -27.0797, -48.5569, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-059', 'Praça do Municípios', -26.9741, -48.5431, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-060', 'UBS Municípios', -27.0027, -48.611, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-061', 'Angeloni Municípios', -27.0407, -48.7262, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-062', 'Giassi Municípios', -26.9044, -48.5641, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-063', 'Posto Ipiranga Municípios', -27.0276, -48.5552, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-064', 'Posto Shell Municípios', -26.9274, -48.6743, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-065', 'Posto Petrobras Municípios', -26.9701, -48.543, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-066', 'Farmácia Droga Raia Municípios', -26.9915, -48.5451, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-067', 'Farmácia Drogasil Municípios', -27.042, -48.657, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-068', 'Praça do Ariribá', -26.9469, -48.6907, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-069', 'UBS Ariribá', -27.0288, -48.5599, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-070', 'Angeloni Ariribá', -26.9937, -48.5764, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-071', 'Giassi Ariribá', -27.0419, -48.7003, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-072', 'Posto Ipiranga Ariribá', -27.0189, -48.6977, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-073', 'Posto Shell Ariribá', -26.8963, -48.6769, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-074', 'Posto Petrobras Ariribá', -26.9783, -48.712, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-075', 'Farmácia Droga Raia Ariribá', -26.9838, -48.6579, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-076', 'Farmácia Drogasil Ariribá', -27.01, -48.7219, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-077', 'Praça do Estados', -27.0659, -48.5698, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-078', 'UBS Estados', -27.0204, -48.686, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-079', 'Angeloni Estados', -27.0524, -48.6783, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-080', 'Giassi Estados', -27.0432, -48.728, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-081', 'Posto Ipiranga Estados', -26.9577, -48.6667, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-082', 'Posto Shell Estados', -27.0594, -48.5938, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-083', 'Posto Petrobras Estados', -27.0721, -48.6811, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-084', 'Farmácia Droga Raia Estados', -26.9236, -48.7094, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-085', 'Farmácia Drogasil Estados', -27.0019, -48.5677, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-086', 'Praça do São Judas Tadeu', -26.9296, -48.7032, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-087', 'UBS São Judas Tadeu', -27.02, -48.5905, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-088', 'Angeloni São Judas Tadeu', -27.0152, -48.5433, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-089', 'Giassi São Judas Tadeu', -27.049, -48.5448, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-090', 'Posto Ipiranga São Judas Tadeu', -26.9896, -48.6895, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-091', 'Posto Shell São Judas Tadeu', -27.0001, -48.7088, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-092', 'Posto Petrobras São Judas Tadeu', -26.9493, -48.6828, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-093', 'Farmácia Droga Raia São Judas Tadeu', -26.9107, -48.6175, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-094', 'Farmácia Drogasil São Judas Tadeu', -27.017, -48.6857, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-095', 'Praça do Praia dos Amores', -26.969, -48.6925, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('bcamboriu-096', 'UBS Praia dos Amores', -26.9161, -48.7104, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('bcamboriu-097', 'Angeloni Praia dos Amores', -26.988, -48.6265, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-098', 'Giassi Praia dos Amores', -27.0365, -48.5807, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('bcamboriu-099', 'Posto Ipiranga Praia dos Amores', -27.0136, -48.6035, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('bcamboriu-100', 'Posto Shell Praia dos Amores', -26.9771, -48.6728, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
