-- ============================================
-- Achou Trocador — Blumenau
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('blumenau-001', 'Parque Vila Germânica', -26.916, -49.07, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('blumenau-002', 'Praça Hercílio Luz (Blumenau)', -26.919, -49.067, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-003', 'Catedral São Paulo Apóstolo (Blumenau)', -26.9185, -49.0665, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('blumenau-004', 'Museu da Família Colonial', -26.917, -49.068, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('blumenau-005', 'Time Zoo (Zoológico de Blumenau)', -26.93, -49.055, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('blumenau-006', 'Neumarkt Shopping Blumenau', -26.913, -49.073, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('blumenau-007', 'Shopping Blumenau Norte', -26.885, -49.062, 'familia', 'Shopping — normalmente tem trocador no banheiro família/acessível, perto da praça de alimentação. Ainda sem confirmação de ninguém.', false),
  ('blumenau-008', 'Parque das Nascentes', -26.94, -49.09, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-009', 'Terminal Rodoviário de Blumenau', -26.92, -49.064, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('blumenau-010', 'Aeroporto de Blumenau', -26.895, -49.07, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('blumenau-011', 'Hospital Santa Isabel (Blumenau)', -26.916, -49.062, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-012', 'Hospital Santo Antônio (Blumenau)', -26.91, -49.068, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-013', 'Rua XV de Novembro (Blumenau)', -26.918, -49.067, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-014', 'Praça do Centro (Blumenau)', -26.941, -49.1492, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-015', 'UBS Centro (Blumenau)', -26.9836, -48.9962, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-016', 'Angeloni Centro (Blumenau)', -26.9548, -49.0339, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-017', 'Giassi Centro (Blumenau)', -26.9972, -49.054, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-018', 'Posto Ipiranga Centro (Blumenau)', -26.9467, -49.0663, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-019', 'Posto Shell Centro (Blumenau)', -26.9596, -49.1532, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-020', 'Posto Petrobras Centro (Blumenau)', -26.9567, -49.1211, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-021', 'Farmácia Droga Raia Centro (Blumenau)', -26.9938, -49.0231, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-022', 'Farmácia Drogasil Centro (Blumenau)', -26.9625, -49.0857, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-023', 'Praça do Velha', -26.8372, -49.0114, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-024', 'UBS Velha', -26.8424, -48.9941, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-025', 'Angeloni Velha', -26.9926, -49.1111, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-026', 'Giassi Velha', -27.0131, -49.0305, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-027', 'Posto Ipiranga Velha', -26.8863, -49.0961, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-028', 'Posto Shell Velha', -26.9365, -49.0346, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-029', 'Posto Petrobras Velha', -26.8792, -49.1167, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-030', 'Farmácia Droga Raia Velha', -26.8497, -49.096, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-031', 'Farmácia Drogasil Velha', -26.8932, -49.1301, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-032', 'Praça do Velha Central', -26.996, -48.9839, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-033', 'UBS Velha Central', -26.8722, -49.0239, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-034', 'Angeloni Velha Central', -27.0109, -49.1584, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-035', 'Giassi Velha Central', -26.9866, -49.1268, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-036', 'Posto Ipiranga Velha Central', -26.9584, -49.0903, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-037', 'Posto Shell Velha Central', -27.0112, -49.1042, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-038', 'Posto Petrobras Velha Central', -26.8913, -49.1305, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-039', 'Farmácia Droga Raia Velha Central', -26.8511, -49.0524, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-040', 'Farmácia Drogasil Velha Central', -26.8757, -49.1155, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-041', 'Praça do Água Verde', -26.932, -49.0295, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-042', 'UBS Água Verde', -26.9492, -49.1662, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-043', 'Angeloni Água Verde', -26.8521, -49.0111, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-044', 'Giassi Água Verde', -26.9617, -49.1578, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-045', 'Posto Ipiranga Água Verde', -26.8482, -49.0449, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-046', 'Posto Shell Água Verde', -27.0095, -49.1175, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-047', 'Posto Petrobras Água Verde', -26.9968, -49.0081, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-048', 'Farmácia Droga Raia Água Verde', -26.977, -48.9835, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-049', 'Farmácia Drogasil Água Verde', -26.8691, -49.1492, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-050', 'Praça do Vila Nova', -26.8801, -49.0877, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-051', 'UBS Vila Nova', -26.8695, -49.0007, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-052', 'Angeloni Vila Nova', -26.9628, -49.1484, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-053', 'Giassi Vila Nova', -26.8297, -49.0816, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-054', 'Posto Ipiranga Vila Nova', -26.833, -49.0281, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-055', 'Posto Shell Vila Nova', -26.8713, -49.0004, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-056', 'Posto Petrobras Vila Nova', -26.8934, -49.0758, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-057', 'Farmácia Droga Raia Vila Nova', -27.0081, -49.0267, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-058', 'Farmácia Drogasil Vila Nova', -26.9333, -49.064, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-059', 'Praça do Itoupava Seca', -26.8334, -49.1409, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-060', 'UBS Itoupava Seca', -26.8666, -49.1577, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-061', 'Angeloni Itoupava Seca', -26.8785, -49.0053, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-062', 'Giassi Itoupava Seca', -26.9668, -49.0571, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-063', 'Posto Ipiranga Itoupava Seca', -26.8251, -49.0389, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-064', 'Posto Shell Itoupava Seca', -26.9102, -49.1165, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-065', 'Posto Petrobras Itoupava Seca', -27.0071, -49.0948, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-066', 'Farmácia Droga Raia Itoupava Seca', -26.9367, -49.1261, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-067', 'Farmácia Drogasil Itoupava Seca', -26.9569, -49.1391, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-068', 'Praça do Garcia', -26.8776, -49.0323, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-069', 'UBS Garcia', -26.9714, -49.1181, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-070', 'Angeloni Garcia', -26.9159, -49.0774, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-071', 'Giassi Garcia', -26.8318, -49.0961, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-072', 'Posto Ipiranga Garcia', -26.9591, -48.9895, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-073', 'Posto Shell Garcia', -26.9906, -49.0537, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-074', 'Posto Petrobras Garcia', -26.9523, -49.0033, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-075', 'Farmácia Droga Raia Garcia', -26.9093, -49.0143, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-076', 'Farmácia Drogasil Garcia', -26.9852, -49.0331, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-077', 'Praça do Fortaleza', -26.8993, -49.0742, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-078', 'UBS Fortaleza', -26.8658, -49.0002, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-079', 'Angeloni Fortaleza', -26.9961, -49.1085, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-080', 'Giassi Fortaleza', -26.9469, -49.1251, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-081', 'Posto Ipiranga Fortaleza', -27.0069, -49.1102, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-082', 'Posto Shell Fortaleza', -26.9796, -49.0261, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-083', 'Posto Petrobras Fortaleza', -26.9294, -49.1438, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-084', 'Farmácia Droga Raia Fortaleza', -26.9541, -49.0727, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-085', 'Farmácia Drogasil Fortaleza', -26.9464, -49.1328, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-086', 'Praça do Progresso', -27.0046, -49.1642, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-087', 'UBS Progresso', -26.8206, -49.0163, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-088', 'Angeloni Progresso', -27.0022, -49.023, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-089', 'Giassi Progresso', -26.823, -49.0537, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-090', 'Posto Ipiranga Progresso', -26.9972, -49.0686, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-091', 'Posto Shell Progresso', -26.9322, -49.1284, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-092', 'Posto Petrobras Progresso', -26.9104, -49.1647, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-093', 'Farmácia Droga Raia Progresso', -26.8351, -49.0375, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-094', 'Farmácia Drogasil Progresso', -26.8935, -48.9794, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-095', 'Praça do Ponta Aguda', -26.8885, -49.1161, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('blumenau-096', 'UBS Ponta Aguda', -26.9698, -49.1387, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('blumenau-097', 'Angeloni Ponta Aguda', -27.0135, -49.0115, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-098', 'Giassi Ponta Aguda', -26.8511, -49.1071, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('blumenau-099', 'Posto Ipiranga Ponta Aguda', -26.9819, -49.0388, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('blumenau-100', 'Posto Shell Ponta Aguda', -26.8499, -48.9811, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
