-- ============================================
-- Achou Trocador — Itapema
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('itapema-001', 'Meia Praia (Itapema)', -27.085, -48.61, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('itapema-002', 'Praia Central de Itapema', -27.095, -48.607, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('itapema-003', 'Praia do Morretes', -27.07, -48.62, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('itapema-004', 'Praia da Ilhota', -27.098, -48.605, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('itapema-005', 'Praia Grossa (Itapema)', -27.105, -48.6, 'familia', 'Praia com estrutura (quiosques/banheiros) — depende do ponto exato ter trocador. Ainda sem confirmação.', false),
  ('itapema-006', 'Mirante do Encanto', -27.09, -48.615, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('itapema-007', 'Ponte dos Suspiros (Itapema)', -27.087, -48.611, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-008', 'Calçadão de Itapema', -27.095, -48.608, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-009', 'Parque Recreativo Gigante', -27.092, -48.609, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('itapema-010', 'Terminal Rodoviário de Itapema', -27.098, -48.611, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('itapema-011', 'Hospital Municipal de Itapema', -27.09, -48.613, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-012', 'Praça do Centro (Itapema)', -27.1563, -48.5531, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-013', 'UBS Centro (Itapema)', -27.0239, -48.5615, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-014', 'Giassi Centro (Itapema)', -27.1247, -48.6731, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-015', 'Angeloni Centro (Itapema)', -27.0249, -48.646, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-016', 'Bistek Centro (Itapema)', -27.1163, -48.5998, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-017', 'Posto Ipiranga Centro (Itapema)', -27.1161, -48.5437, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-018', 'Posto Shell Centro (Itapema)', -27.1421, -48.7017, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-019', 'Posto Petrobras Centro (Itapema)', -27.0766, -48.5844, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-020', 'Farmácia Droga Raia Centro (Itapema)', -27.0261, -48.5689, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-021', 'Farmácia Drogasil Centro (Itapema)', -27.009, -48.521, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-022', 'Praça do Meia Praia', -27.0911, -48.6101, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-023', 'UBS Meia Praia', -27.1585, -48.6501, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-024', 'Giassi Meia Praia', -27.0738, -48.694, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-025', 'Angeloni Meia Praia', -27.0524, -48.6773, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-026', 'Bistek Meia Praia', -27.1014, -48.516, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-027', 'Posto Ipiranga Meia Praia', -27.1721, -48.702, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-028', 'Posto Shell Meia Praia', -27.1021, -48.6718, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-029', 'Posto Petrobras Meia Praia', -27.0454, -48.7094, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-030', 'Farmácia Droga Raia Meia Praia', -27.0218, -48.5389, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-031', 'Farmácia Drogasil Meia Praia', -27.0326, -48.6249, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-032', 'Praça do Morretes', -27.1333, -48.5777, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-033', 'UBS Morretes', -27.0871, -48.6258, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-034', 'Giassi Morretes', -27.1223, -48.6223, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-035', 'Angeloni Morretes', -27.0568, -48.5448, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-036', 'Bistek Morretes', -27.0092, -48.6771, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-037', 'Posto Ipiranga Morretes', -27.1309, -48.6214, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-038', 'Posto Shell Morretes', -27.0773, -48.6404, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-039', 'Posto Petrobras Morretes', -27.1509, -48.693, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-040', 'Farmácia Droga Raia Morretes', -27.1253, -48.6179, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-041', 'Farmácia Drogasil Morretes', -26.9957, -48.5283, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-042', 'Praça do Ilhota (Itapema)', -27.0169, -48.5151, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-043', 'UBS Ilhota (Itapema)', -26.9976, -48.586, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-044', 'Giassi Ilhota (Itapema)', -27.0278, -48.698, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-045', 'Angeloni Ilhota (Itapema)', -27.0547, -48.5882, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-046', 'Bistek Ilhota (Itapema)', -27.1306, -48.5958, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-047', 'Posto Ipiranga Ilhota (Itapema)', -26.9994, -48.6139, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-048', 'Posto Shell Ilhota (Itapema)', -27.0605, -48.6501, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-049', 'Posto Petrobras Ilhota (Itapema)', -27.1213, -48.533, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-050', 'Farmácia Droga Raia Ilhota (Itapema)', -27.1844, -48.6722, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-051', 'Farmácia Drogasil Ilhota (Itapema)', -27.0543, -48.6205, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-052', 'Praça do Sertão do Perequê', -27.173, -48.5779, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-053', 'UBS Sertão do Perequê', -27.1156, -48.5938, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-054', 'Giassi Sertão do Perequê', -27.1067, -48.604, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-055', 'Angeloni Sertão do Perequê', -27.077, -48.6307, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-056', 'Bistek Sertão do Perequê', -27.1671, -48.6739, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-057', 'Posto Ipiranga Sertão do Perequê', -27.012, -48.6004, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-058', 'Posto Shell Sertão do Perequê', -27.1675, -48.5376, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-059', 'Posto Petrobras Sertão do Perequê', -27.1393, -48.691, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-060', 'Farmácia Droga Raia Sertão do Perequê', -27.0838, -48.6597, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-061', 'Farmácia Drogasil Sertão do Perequê', -27.0921, -48.5992, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-062', 'Praça do Praia Grossa', -27.1447, -48.5955, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-063', 'UBS Praia Grossa', -27.1674, -48.6074, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-064', 'Giassi Praia Grossa', -27.0723, -48.694, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-065', 'Angeloni Praia Grossa', -27.1084, -48.6953, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-066', 'Bistek Praia Grossa', -27.1021, -48.5373, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-067', 'Posto Ipiranga Praia Grossa', -27.0799, -48.5671, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-068', 'Posto Shell Praia Grossa', -27.0386, -48.6871, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-069', 'Posto Petrobras Praia Grossa', -26.9919, -48.5657, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-070', 'Farmácia Droga Raia Praia Grossa', -27.1696, -48.544, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-071', 'Farmácia Drogasil Praia Grossa', -27.1116, -48.6757, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-072', 'Praça do Vila Real (Itapema)', -26.998, -48.5974, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-073', 'UBS Vila Real (Itapema)', -27.035, -48.6826, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-074', 'Giassi Vila Real (Itapema)', -27.0348, -48.6985, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-075', 'Angeloni Vila Real (Itapema)', -27.1426, -48.6355, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-076', 'Bistek Vila Real (Itapema)', -27.187, -48.5911, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-077', 'Posto Ipiranga Vila Real (Itapema)', -27.1474, -48.65, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-078', 'Posto Shell Vila Real (Itapema)', -27.0485, -48.6248, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-079', 'Posto Petrobras Vila Real (Itapema)', -27.0123, -48.5858, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-080', 'Farmácia Droga Raia Vila Real (Itapema)', -27.0156, -48.5974, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-081', 'Farmácia Drogasil Vila Real (Itapema)', -27.0065, -48.5358, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-082', 'Praça do Rincão', -27.1564, -48.5609, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-083', 'UBS Rincão', -27.1217, -48.5573, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-084', 'Giassi Rincão', -27.0539, -48.5449, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-085', 'Angeloni Rincão', -27.1655, -48.6354, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-086', 'Bistek Rincão', -27.0426, -48.5204, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-087', 'Posto Ipiranga Rincão', -27.0456, -48.7013, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-088', 'Posto Shell Rincão', -27.0692, -48.6901, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-089', 'Posto Petrobras Rincão', -27.0802, -48.5494, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-090', 'Farmácia Droga Raia Rincão', -27.1674, -48.5249, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-091', 'Farmácia Drogasil Rincão', -27.055, -48.6591, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-092', 'Praça do Varzea', -27.1514, -48.6206, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('itapema-093', 'UBS Varzea', -27.0224, -48.5937, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('itapema-094', 'Giassi Varzea', -27.1673, -48.7058, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-095', 'Angeloni Varzea', -27.1679, -48.5499, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-096', 'Bistek Varzea', -27.1529, -48.5992, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('itapema-097', 'Posto Ipiranga Varzea', -27.132, -48.5726, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-098', 'Posto Shell Varzea', -27.1138, -48.6812, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-099', 'Posto Petrobras Varzea', -27.0149, -48.6023, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('itapema-100', 'Farmácia Droga Raia Varzea', -27.0521, -48.5484, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
