-- ============================================
-- Achou Trocador — Campos do Jordão
-- Entram como "não verificados" (verified = false), sem nenhuma
-- confirmação ainda. Coordenadas são aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('camposjordao-001', 'Horto Florestal (Campos do Jordão)', -22.715, -45.475, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-002', 'Parque Capivari', -22.735, -45.59, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-003', 'Teleférico de Campos do Jordão', -22.718, -45.478, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('camposjordao-004', 'Palácio Boa Vista', -22.75, -45.595, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('camposjordao-005', 'Auditório Cláudio Santoro (Campos do Jordão)', -22.734, -45.591, 'familia', 'Museu/prédio cultural — é esperado ter banheiro família. Ainda sem confirmação.', false),
  ('camposjordao-006', 'Vila Capivari (Campos do Jordão)', -22.735, -45.59, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-007', 'Morro do Elefante', -22.73, -45.585, 'familia', 'Atração pensada pra família — boa chance de ter trocador. Ainda sem confirmação.', false),
  ('camposjordao-008', 'Terminal Rodoviário de Campos do Jordão', -22.74, -45.58, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('camposjordao-009', 'Aeroporto Estadual de Campos do Jordão', -22.695, -45.595, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('camposjordao-010', 'Santa Casa de Campos do Jordão', -22.74, -45.585, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-011', 'Estação Ferroviária Campos do Jordão', -22.738, -45.581, 'familia', 'Terminal/estação/aeroporto — banheiros públicos maiores costumam ter trocador. Ainda sem confirmação.', false),
  ('camposjordao-012', 'Praça do Capivari', -22.6494, -45.6883, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-013', 'UBS Capivari', -22.7707, -45.6609, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-014', 'Alta Montanha Capivari', -22.7388, -45.5165, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-015', 'Dia Capivari', -22.6791, -45.684, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-016', 'São Vicente Capivari', -22.8027, -45.5274, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-017', 'Posto Ipiranga Capivari', -22.7033, -45.6126, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-018', 'Posto Shell Capivari', -22.744, -45.6594, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-019', 'Posto Petrobras Capivari', -22.6702, -45.6124, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-020', 'Farmácia Droga Raia Capivari', -22.6646, -45.5689, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-021', 'Farmácia Drogasil Capivari', -22.824, -45.6252, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-022', 'Praça do Abernéssia', -22.7959, -45.5123, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-023', 'UBS Abernéssia', -22.7214, -45.6824, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-024', 'Alta Montanha Abernéssia', -22.8053, -45.6189, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-025', 'Dia Abernéssia', -22.7456, -45.5757, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-026', 'São Vicente Abernéssia', -22.7616, -45.6204, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-027', 'Posto Ipiranga Abernéssia', -22.838, -45.5753, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-028', 'Posto Shell Abernéssia', -22.7724, -45.687, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-029', 'Posto Petrobras Abernéssia', -22.7473, -45.4938, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-030', 'Farmácia Droga Raia Abernéssia', -22.8301, -45.6619, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-031', 'Farmácia Drogasil Abernéssia', -22.705, -45.6366, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-032', 'Praça do Jaguaribe', -22.7845, -45.5911, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-033', 'UBS Jaguaribe', -22.7868, -45.5773, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-034', 'Alta Montanha Jaguaribe', -22.7336, -45.4997, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-035', 'Dia Jaguaribe', -22.6408, -45.6843, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-036', 'São Vicente Jaguaribe', -22.7271, -45.5369, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-037', 'Posto Ipiranga Jaguaribe', -22.6647, -45.5362, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-038', 'Posto Shell Jaguaribe', -22.7126, -45.5642, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-039', 'Posto Petrobras Jaguaribe', -22.7666, -45.6348, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-040', 'Farmácia Droga Raia Jaguaribe', -22.6801, -45.5165, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-041', 'Farmácia Drogasil Jaguaribe', -22.6515, -45.5548, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-042', 'Praça do Vila Inglesa', -22.7784, -45.5384, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-043', 'UBS Vila Inglesa', -22.6913, -45.5893, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-044', 'Alta Montanha Vila Inglesa', -22.7122, -45.621, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-045', 'Dia Vila Inglesa', -22.7291, -45.6099, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-046', 'São Vicente Vila Inglesa', -22.8271, -45.6237, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-047', 'Posto Ipiranga Vila Inglesa', -22.7746, -45.4934, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-048', 'Posto Shell Vila Inglesa', -22.7429, -45.6176, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-049', 'Posto Petrobras Vila Inglesa', -22.7905, -45.6441, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-050', 'Farmácia Droga Raia Vila Inglesa', -22.7694, -45.664, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-051', 'Farmácia Drogasil Vila Inglesa', -22.8378, -45.5169, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-052', 'Praça do Alto da Boa Vista (Campos do Jordão)', -22.7486, -45.602, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-053', 'UBS Alto da Boa Vista (Campos do Jordão)', -22.7255, -45.6306, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-054', 'Alta Montanha Alto da Boa Vista (Campos do Jordão)', -22.8054, -45.6778, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-055', 'Dia Alto da Boa Vista (Campos do Jordão)', -22.7789, -45.6294, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-056', 'São Vicente Alto da Boa Vista (Campos do Jordão)', -22.6939, -45.5808, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-057', 'Posto Ipiranga Alto da Boa Vista (Campos do Jordão)', -22.6517, -45.623, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-058', 'Posto Shell Alto da Boa Vista (Campos do Jordão)', -22.655, -45.5744, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-059', 'Posto Petrobras Alto da Boa Vista (Campos do Jordão)', -22.8232, -45.6554, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-060', 'Farmácia Droga Raia Alto da Boa Vista (Campos do Jordão)', -22.7231, -45.4936, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-061', 'Farmácia Drogasil Alto da Boa Vista (Campos do Jordão)', -22.7678, -45.5362, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-062', 'Praça do Vila Albertina (Campos do Jordão)', -22.7535, -45.5174, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-063', 'UBS Vila Albertina (Campos do Jordão)', -22.8257, -45.5942, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-064', 'Alta Montanha Vila Albertina (Campos do Jordão)', -22.6594, -45.6359, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-065', 'Dia Vila Albertina (Campos do Jordão)', -22.7877, -45.6865, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-066', 'São Vicente Vila Albertina (Campos do Jordão)', -22.8063, -45.6375, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-067', 'Posto Ipiranga Vila Albertina (Campos do Jordão)', -22.6983, -45.6474, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-068', 'Posto Shell Vila Albertina (Campos do Jordão)', -22.7593, -45.651, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-069', 'Posto Petrobras Vila Albertina (Campos do Jordão)', -22.7186, -45.5183, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-070', 'Farmácia Droga Raia Vila Albertina (Campos do Jordão)', -22.7096, -45.6518, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-071', 'Farmácia Drogasil Vila Albertina (Campos do Jordão)', -22.6924, -45.4985, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-072', 'Praça do Emílio Ribas', -22.719, -45.6752, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-073', 'UBS Emílio Ribas', -22.6773, -45.516, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-074', 'Alta Montanha Emílio Ribas', -22.771, -45.6638, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-075', 'Dia Emílio Ribas', -22.8016, -45.5837, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-076', 'São Vicente Emílio Ribas', -22.6641, -45.5631, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-077', 'Posto Ipiranga Emílio Ribas', -22.6546, -45.6487, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-078', 'Posto Shell Emílio Ribas', -22.7738, -45.5412, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-079', 'Posto Petrobras Emílio Ribas', -22.7094, -45.61, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-080', 'Farmácia Droga Raia Emílio Ribas', -22.7034, -45.6235, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-081', 'Farmácia Drogasil Emílio Ribas', -22.8277, -45.6082, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-082', 'Praça do Socorro (Campos do Jordão)', -22.8301, -45.5658, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-083', 'UBS Socorro (Campos do Jordão)', -22.7723, -45.5922, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-084', 'Alta Montanha Socorro (Campos do Jordão)', -22.7196, -45.6397, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-085', 'Dia Socorro (Campos do Jordão)', -22.7465, -45.6884, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-086', 'São Vicente Socorro (Campos do Jordão)', -22.6541, -45.5783, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-087', 'Posto Ipiranga Socorro (Campos do Jordão)', -22.6417, -45.6799, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-088', 'Posto Shell Socorro (Campos do Jordão)', -22.7164, -45.5463, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-089', 'Posto Petrobras Socorro (Campos do Jordão)', -22.7734, -45.6724, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-090', 'Farmácia Droga Raia Socorro (Campos do Jordão)', -22.808, -45.6626, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-091', 'Farmácia Drogasil Socorro (Campos do Jordão)', -22.6858, -45.6731, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-092', 'Praça do Independência (Campos do Jordão)', -22.6764, -45.6065, 'familia', 'Espaço público — pode ter banheiro perto da entrada principal. Ainda sem confirmação.', false),
  ('camposjordao-093', 'UBS Independência (Campos do Jordão)', -22.7315, -45.5734, 'familia', 'Hospital/UBS — deveria ter sala de amamentação/trocador. Ainda sem confirmação.', false),
  ('camposjordao-094', 'Alta Montanha Independência (Campos do Jordão)', -22.7282, -45.5596, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-095', 'Dia Independência (Campos do Jordão)', -22.7189, -45.6249, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-096', 'São Vicente Independência (Campos do Jordão)', -22.691, -45.6395, 'familia', 'Supermercado — deveria ter trocador por lei. Ainda sem confirmação.', false),
  ('camposjordao-097', 'Posto Ipiranga Independência (Campos do Jordão)', -22.6969, -45.5384, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-098', 'Posto Shell Independência (Campos do Jordão)', -22.684, -45.6292, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-099', 'Posto Petrobras Independência (Campos do Jordão)', -22.6847, -45.4956, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false),
  ('camposjordao-100', 'Farmácia Droga Raia Independência (Campos do Jordão)', -22.7486, -45.6354, 'familia', 'Prédio público/atração — provável ter banheiro com trocador. Ainda sem confirmação.', false)
on conflict (id) do nothing;
