-- ============================================
-- Achou Trocador — 250 locais em cidades populosas da America Latina
-- Poucos pontos por cidade (nao 100 cada), espalhados por varias
-- cidades da America Latina. Nao verificados. Coordenadas aproximadas.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('poplat-001', 'Plaza Mayor de Lima', -12.0464, -77.0311, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-002', 'Larcomar (Miraflores)', -12.1319, -77.0304, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-003', 'Aeropuerto Internacional Jorge Chávez', -12.0219, -77.1143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-004', 'Parque Kennedy (Miraflores)', -12.1214, -77.0296, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-005', 'Real Plaza Salaverry (Lima)', -12.08, -77.049, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-006', 'Zócalo (Cidade do México)', 19.4326, -99.1332, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-007', 'Bosque de Chapultepec', 19.4204, -99.1817, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-008', 'Aeroporto Internacional Cidade do México (AICM)', 19.4363, -99.0721, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-009', 'Basílica de Guadalupe', 19.485, -99.1178, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-010', 'Centro Comercial Santa Fe (CDMX)', 19.3597, -99.2596, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-011', 'Estadio Azteca', 19.3029, -99.1505, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-012', 'Plaza de Bolívar (Bogotá)', 4.5981, -74.0761, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-013', 'Cerro de Monserrate', 4.6058, -74.0567, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-014', 'Aeropuerto Internacional El Dorado', 4.7016, -74.1469, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-015', 'Centro Comercial Andino (Bogotá)', 4.6668, -74.0533, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-016', 'Parque Simón Bolívar (Bogotá)', 4.6584, -74.093, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-017', 'Congresso Nacional (Brasília)', -15.7997, -47.8645, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-018', 'Aeroporto Internacional de Brasília', -15.8697, -47.9208, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-019', 'Shopping Conjunto Nacional (Brasília)', -15.7934, -47.8823, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-020', 'Torre de TV de Brasília', -15.7909, -47.8934, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-021', 'Malecón 2000 (Guayaquil)', -2.1962, -79.8862, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-022', 'Aeropuerto José Joaquín de Olmedo', -2.1575, -79.8836, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-023', 'Mall del Sol (Guayaquil)', -2.1543, -79.8988, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-024', 'Puente sobre el Lago de Maracaibo (acceso)', 10.6316, -71.6337, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-025', 'Basílica de Nuestra Señora de Chiquinquirá', 10.6438, -71.6125, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-026', 'Praia de Iracema (Fortaleza)', -3.7212, -38.5217, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-027', 'Aeroporto Pinto Martins (Fortaleza)', -3.7763, -38.5326, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-028', 'Shopping Iguatemi Fortaleza', -3.744, -38.498, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-029', 'Plaza Botero (Medellín)', 6.2519, -75.5687, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-030', 'Parque Arví / Metrocable (Medellín)', 6.285, -75.501, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-031', 'Aeropuerto José María Córdova (Medellín)', 6.1645, -75.4231, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-032', 'Centro Comercial Santafé (Medellín)', 6.21, -75.568, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-033', 'Praça da Liberdade (BH)', -19.932, -43.937, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-034', 'Mercado Central de Belo Horizonte', -19.92, -43.939, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-035', 'Aeroporto de Confins (BH)', -19.6336, -43.9686, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-036', 'Teatro Amazonas (Manaus)', -3.1301, -60.0233, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-037', 'Aeroporto Eduardo Gomes (Manaus)', -3.0386, -60.0497, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-038', 'Mercado Municipal de Manaus', -3.1385, -60.0244, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-039', 'Cristo Rey (Cali)', 3.4372, -76.5697, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-040', 'Aeropuerto Alfonso Bonilla Aragón (Cali)', 3.5433, -76.3816, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-041', 'Unicentro Cali', 3.3745, -76.535, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-042', 'Plaza Bolívar (Caracas)', 10.5061, -66.9146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-043', 'Aeropuerto Internacional Simón Bolívar (Maiquetía)', 10.6031, -66.9906, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-044', 'Centro Comercial Sambil Caracas', 10.4956, -66.8508, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-045', 'Avenida Revolución (Tijuana)', 32.5283, -117.0349, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-046', 'Aeropuerto Internacional de Tijuana', 32.5411, -116.97, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-047', 'Centro Histórico de Quito', -0.2201, -78.5123, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-048', 'TelefériQo (Quito)', -0.1889, -78.5289, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-049', 'Aeropuerto Mariscal Sucre (Quito)', -0.1292, -78.3575, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-050', 'Parque La Carolina (Quito)', -0.1807, -78.4863, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-051', 'Municipio de La Matanza', -34.7697, -58.6221, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-052', 'Plaza San Justo (La Matanza)', -34.7684, -58.6236, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-053', 'Centro Histórico de León (Guanajuato)', 21.1226, -101.6822, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-054', 'Plaza Mayor León', 21.118, -101.69, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-055', 'Plaza Bolívar de Valencia', 10.162, -68.0077, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-056', 'Sambil Valencia', 10.19, -68.0, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-057', 'Plaza 24 de Septiembre (Santa Cruz)', -17.7833, -63.1821, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-058', 'Aeropuerto Internacional Viru Viru', -17.6448, -63.1354, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-059', 'Ventura Mall (Santa Cruz)', -17.769, -63.178, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-060', 'Centro de Ecatepec', 19.6018, -99.0602, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-061', 'Puente Internacional Santa Fe (Cd. Juárez)', 31.735, -106.488, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-062', 'Aeropuerto de Ciudad Juárez', 31.6361, -106.4287, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-063', 'Zócalo de Puebla', 19.0433, -98.1982, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-064', 'Angelópolis (Puebla)', 19.0, -98.247, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-065', 'Aeropuerto Internacional de Puebla', 19.1581, -98.3717, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-066', 'Marco Zero (Recife)', -8.0631, -34.8711, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-067', 'Praia de Boa Viagem (Recife)', -8.12, -34.898, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-068', 'Aeroporto Guararapes (Recife)', -8.1264, -34.9236, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-069', 'RioMar Shopping (Recife)', -8.085, -34.883, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-070', 'Praça Cívica (Goiânia)', -16.6786, -49.2553, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-071', 'Flamboyant Shopping (Goiânia)', -16.713, -49.265, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-072', 'Ver-o-Peso (Belém)', -1.453, -48.503, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-073', 'Estação das Docas (Belém)', -1.452, -48.504, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-074', 'Aeroporto Internacional de Belém', -1.3792, -48.4761, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-075', 'Shopping Internacional de Guarulhos', -23.462, -46.533, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-076', 'Parque Estadual da Cantareira (acesso Guarulhos)', -23.42, -46.51, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-077', 'Basílica de Zapopan', 20.7206, -103.3897, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-078', 'Andares Shopping (Zapopan)', 20.715, -103.391, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-079', 'Catedral de Guadalajara', 20.6767, -103.3475, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-080', 'Aeropuerto Internacional de Guadalajara', 20.5218, -103.3111, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-081', 'Plaza del Sol (Guadalajara)', 20.658, -103.396, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-082', 'Rambla de Montevideo', -34.91, -56.16, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-083', 'Mercado del Puerto (Montevideo)', -34.907, -56.209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-084', 'Aeropuerto Internacional de Carrasco', -34.8384, -56.0308, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-085', 'Punta Carretas Shopping (Montevideo)', -34.921, -56.162, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-086', 'Malecón del Río (Barranquilla)', 10.9878, -74.7889, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-087', 'Aeropuerto Ernesto Cortissoz (Barranquilla)', 10.8896, -74.7808, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-088', 'Buenavista Mall (Barranquilla)', 11.01, -74.818, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-089', 'Catedral de Barquisimeto', 10.0678, -69.3467, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-090', 'Shopping Iguatemi Campinas', -22.863, -47.073, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-091', 'Aeroporto Internacional de Viracopos', -23.0074, -47.1345, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-092', 'UNICAMP (Campinas)', -22.8172, -47.0694, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-093', 'Plaza de Armas de Arequipa', -16.3989, -71.535, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-094', 'Monasterio de Santa Catalina (Arequipa)', -16.3958, -71.5369, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-095', 'Aeropuerto Rodríguez Ballón (Arequipa)', -16.3411, -71.5831, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-096', 'Plaza Morazán (Tegucigalpa)', 14.1004, -87.2065, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-097', 'Aeropuerto de Tegucigalpa', 14.0608, -87.2172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-098', 'Casco Viejo (Cidade do Panamá)', 8.9518, -79.5397, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-099', 'Esclusas de Miraflores (Canal do Panamá)', 8.9944, -79.5967, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-100', 'Aeroporto Internacional de Tocumen', 9.0714, -79.3835, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-101', 'Multiplaza Pacific (Panamá)', 8.977, -79.521, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-102', 'Macroplaza (Monterrey)', 25.669, -100.3097, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-103', 'Cerro de la Silla (Monterrey)', 25.628, -100.24, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-104', 'Aeropuerto Internacional de Monterrey', 25.7785, -100.1069, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-105', 'Paseo San Pedro (Monterrey)', 25.651, -100.403, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-106', 'Orinokia Mall (Ciudad Guayana)', 8.3533, -62.635, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-107', 'Plaza de Armas de Trujillo', -8.1116, -79.0288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-108', 'Complejo Arqueológico Chan Chan', -8.1105, -79.0742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-109', 'Centro Histórico de São Luís', -2.5297, -44.3028, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-110', 'Aeroporto de São Luís', -2.585, -44.234, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-111', 'Zona Hotelera de Cancún', 21.1319, -86.7456, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-112', 'Aeroporto Internacional de Cancún', 21.0365, -86.8771, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-113', 'La Isla Shopping Village (Cancún)', 21.118, -86.758, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-114', 'Malecón de Managua', 12.15, -86.29, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-115', 'Ciudad Jardín Bicentenario (Nezahualcóyotl)', 19.399, -99.014, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-116', 'Paseo de Montejo (Mérida)', 20.98, -89.62, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-117', 'Aeropuerto Internacional de Mérida', 20.937, -89.6577, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-118', 'Ciudad Amurallada (Cartagena)', 10.4236, -75.5518, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-119', 'Aeropuerto Rafael Núñez (Cartagena)', 10.4424, -75.513, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-120', 'Praia de Pajuçara (Maceió)', -9.666, -35.708, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-121', 'Aeroporto Zumbi dos Palmares (Maceió)', -9.5108, -35.7917, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-122', 'Catedral de Chihuahua', 28.6353, -106.0889, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-123', 'Feira Central de Campo Grande', -20.46, -54.62, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-124', 'Aeroporto de Campo Grande', -20.4687, -54.6725, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-125', 'Plaza de Armas de Saltillo', 25.4232, -101.0053, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-126', 'Shopping Total São Gonçalo', -22.827, -43.054, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-127', 'Plaza de la Patria (Aguascalientes)', 21.8818, -102.2916, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-128', 'Catedral de Hermosillo', 29.0729, -110.9559, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-129', 'Plaza de Armas de San Luis Potosí', 22.1565, -100.9855, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-130', 'Ponte Estaiada de Teresina', -5.0892, -42.8016, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-131', 'Plaza de la Constitución (Cidade da Guatemala)', 14.6415, -90.5133, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-132', 'Aeroporto La Aurora (Guatemala)', 14.5833, -90.5275, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-133', 'Praia de Tambaú (João Pessoa)', -7.105, -34.83, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-134', 'Catedral de Culiacán', 24.7999, -107.394, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-135', 'Centro Histórico de Querétaro', 20.5888, -100.3899, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-136', 'Aeropuerto Intercontinental de Querétaro', 20.6173, -100.1857, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-137', 'Parque Principal de Soacha', 4.5794, -74.2168, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-138', 'Aeropuerto Internacional El Alto (La Paz)', -16.5133, -68.1925, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-139', 'Shopping Grande Rio (Duque de Caxias)', -22.79, -43.32, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-140', 'Catedral de Mexicali', 32.6245, -115.4523, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-141', 'Paço Municipal de São Bernardo do Campo', -23.6939, -46.565, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-142', 'Catedral de Morelia', 19.706, -101.195, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-143', 'Shopping Nova Iguaçu', -22.759, -43.451, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-144', 'Praia de Ponta Negra (Natal)', -5.877, -35.167, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-145', 'Aeroporto de Natal (Governador Aluízio Alves)', -5.7681, -35.3764, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-146', 'Catedral de La Plata', -34.9214, -57.9544, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-147', 'Plaza Moreno (La Plata)', -34.921, -57.954, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-148', 'Parque Santander (Cúcuta)', 7.8939, -72.5078, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-149', 'Paço Municipal de Santo André', -23.654, -46.53, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-150', 'Praça Tubal Vilela (Uberlândia)', -18.9186, -48.2772, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-151', 'Aeroporto de Uberlândia', -18.8828, -48.2256, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-152', 'Centro Comercial Interlomas (Naucalpan)', 19.39, -99.27, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-153', 'Shopping União de Osasco', -23.532, -46.792, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-154', 'Parroquia de Chimalhuacán', 19.42, -98.95, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-155', 'Puente Internacional Reynosa-McAllen', 26.05, -98.29, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-156', 'Parque Central de San Pedro Sula', 15.5041, -88.025, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-157', 'Aeropuerto Ramón Villeda Morales', 15.4526, -87.9236, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-158', 'Plaza Murillo (La Paz)', -16.495, -68.1333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-159', 'Teleférico de La Paz', -16.5, -68.12, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-160', 'Plaza Mayor de Torreón', 25.5428, -103.4068, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-161', 'Shopping Iguatemi Ribeirão Preto', -21.16, -47.81, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-162', 'Aeroporto de Ribeirão Preto', -21.1367, -47.7742, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-163', 'Shopping Colinas (São José dos Campos)', -23.18, -45.89, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-164', 'Parque Principal de Soledad', 10.9186, -74.7658, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-165', 'Plaza Grigera (Lomas de Zamora)', -34.7605, -58.4008, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-166', 'Praça da República (Cuiabá)', -15.5989, -56.0949, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-167', 'Aeroporto Marechal Rondon (Cuiabá)', -15.6529, -56.1167, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-168', 'Centro Histórico de Tlaquepaque', 20.6403, -103.3128, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-169', 'Plaza de Armas de Chiclayo', -6.7714, -79.8409, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-170', 'Shopping Recife (Jaboatão)', -8.135, -34.92, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-171', 'Plaza de Armas de Durango', 24.0277, -104.6532, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-172', 'Cristo de la Concordia (Cochabamba)', -17.373, -66.137, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-173', 'Plaza 14 de Septiembre (Cochabamba)', -17.3935, -66.157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-174', 'Plaza de Armas de Puente Alto', -33.611, -70.576, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-175', 'Museu Nacional de Imigração e Colonização (Joinville)', -26.303, -48.846, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-176', 'Shopping Cidade das Flores (Joinville)', -26.29, -48.83, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-177', 'Centro de Convenções de Feira de Santana', -12.25, -38.97, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-178', 'Catedral de Tlalnepantla', 19.54, -99.195, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-179', 'Shopping Contagem', -19.932, -44.07, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-180', 'Hospital Nacional Dos de Mayo (Lima)', -12.057, -77.014, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-181', 'Museo Nacional de Historia (CDMX)', 19.4204, -99.1817, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-182', 'Museo Nacional (Bogotá)', 4.6136, -74.0705, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-183', 'Aeroporto Militar de Brasília', -15.86, -47.92, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-184', 'Parque Histórico de Guayaquil', -2.167, -79.89, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-185', 'Terminal de Maracaibo', 10.66, -71.63, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-186', 'Centro Dragão do Mar (Fortaleza)', -3.725, -38.527, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-187', 'Parque Explora (Medellín)', 6.271, -75.565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-188', 'Mercado Central de Belo Horizonte II', -19.919, -43.938, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-189', 'Ponta Negra (Manaus)', -3.07, -60.09, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-190', 'Terminal de Transporte de Cali', 3.446, -76.522, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-191', 'Universidad Central de Venezuela (Caracas)', 10.4917, -66.8917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-192', 'Plaza Río Tijuana II (CECUT)', 32.525, -117.023, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-193', 'Basílica de la Merced (Quito)', -0.221, -78.513, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-194', 'Terminal de Ómnibus de La Matanza', -34.775, -58.63, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-195', 'Hospital General de León (México)', 21.13, -101.67, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-196', 'Terminal de Valencia (Venezuela)', 10.17, -68.0, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-197', 'Terminal Bimodal de Santa Cruz', -17.79, -63.16, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-198', 'Palacio Municipal de Ecatepec', 19.605, -99.06, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-199', 'Puente Internacional Paso del Norte (Cd. Juárez)', 31.74, -106.48, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-200', 'Fuertes de Loreto y Guadalupe (Puebla)', 19.06, -98.19, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-201', 'Museu Cais do Sertão (Recife)', -8.064, -34.872, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-202', 'Praça Cívica de Goiânia II (Palácio)', -16.679, -49.255, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-203', 'Mangal das Garças (Belém)', -1.455, -48.498, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-204', 'Aeroporto de Guarulhos (Terminal 3)', -23.434, -46.482, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-205', 'Terminal de Ônibus de Zapopan', 20.72, -103.4, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-206', 'Templo Expiatorio (Guadalajara)', 20.674, -103.354, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-207', 'Terminal Tres Cruces (Montevideo)', -34.894, -56.159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-208', 'Terminal de Buquebus (Barranquilla)', 11.0, -74.81, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-209', 'Terminal de Barquisimeto', 10.06, -69.34, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-210', 'Parque Taquaral (Campinas)', -22.87, -47.065, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-211', 'Terminal Terrestre de Arequipa', -16.42, -71.51, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-212', 'Estadio Nacional de Tegucigalpa', 14.09, -87.21, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-213', 'Cinta Costera II (Panamá)', 8.97, -79.535, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-214', 'Parque Fundidora (Monterrey)', 25.678, -100.284, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-215', 'Terminal de Ciudad Guayana', 8.36, -62.64, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-216', 'Playa Huanchaco (Trujillo)', -8.08, -79.12, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-217', 'Terminal Rodoviário de São Luís', -2.54, -44.28, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-218', 'Playa Delfines (Cancún)', 21.07, -86.766, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-219', 'Terminal de Ómnibus de Managua', 12.14, -86.28, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-220', 'Terminal Nezahualcóyotl', 19.4, -99.02, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-221', 'Gran Museo del Mundo Maya (Mérida)', 21.04, -89.62, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-222', 'Museo del Oro Zenú (Cartagena)', 10.424, -75.548, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-223', 'Terminal Rodoviário de Maceió', -9.62, -35.73, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-224', 'Terminal de Chihuahua', 28.65, -106.08, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-225', 'Parque das Nações Indígenas (Campo Grande)', -20.475, -54.61, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-226', 'Terminal de Saltillo', 25.44, -100.98, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-227', 'Terminal Rodoviário de São Gonçalo', -22.825, -43.06, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-228', 'Termas de Aguascalientes', 21.88, -102.28, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-229', 'Terminal de Hermosillo', 29.08, -110.97, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-230', 'Terminal de San Luis Potosí', 22.15, -100.97, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-231', 'Parque da Cidade de Teresina', -5.07, -42.82, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-232', 'Mercado Central (Cidade da Guatemala)', 14.643, -90.517, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-233', 'Estação Cabo Branco (João Pessoa)', -7.145, -34.795, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-234', 'Terminal de Culiacán', 24.8, -107.38, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-235', 'Terminal de Querétaro', 20.6, -100.42, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-236', 'Terminal de Soacha', 4.58, -74.22, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-237', 'Terminal Terrestre de El Alto', -16.51, -68.18, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-238', 'Terminal Rodoviário de Duque de Caxias', -22.785, -43.31, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-239', 'Terminal de Mexicali', 32.63, -115.44, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-240', 'Paço Municipal de São Bernardo II', -23.695, -46.567, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-241', 'Bosque Cuauhtémoc (Morelia)', 19.7, -101.19, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-242', 'Terminal Rodoviário de Nova Iguaçu', -22.76, -43.45, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-243', 'Forte dos Reis Magos (Natal)', -5.763, -35.199, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-244', 'Terminal de Ómnibus de La Plata', -34.92, -57.95, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-245', 'Terminal de Cúcuta', 7.89, -72.5, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas — la comunidad local confirma los detalles.', false),
  ('poplat-246', 'Paço Municipal de Santo André II', -23.655, -46.531, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-247', 'Aeroclube de Uberlândia', -18.89, -48.24, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-248', 'Terminal de Naucalpan', 19.47, -99.24, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-249', 'Terminal de Osasco', -23.53, -46.79, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false),
  ('poplat-250', 'Terminal de Chimalhuacán', 19.41, -98.96, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas — comunidade local confirma os detalhes.', false)
on conflict (id) do nothing;
