-- ============================================
-- Achou Trocador — Argentina: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('ar150-001', 'Plaza Belgrano (Jujuy)', -24.1858, -65.2995, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-002', 'Parque San Martín (Jujuy)', -24.195, -65.29, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-003', 'Terminal de Ómnibus de Jujuy', -24.19, -65.295, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-004', 'McDonald''s — San Salvador de Jujuy', -24.2087, -65.2993, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-005', 'Burger King — San Salvador de Jujuy', -24.1851, -65.2779, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-006', 'KFC — San Salvador de Jujuy', -24.2096, -65.3161, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-007', 'Plaza Central — Centro (San Salvador de Jujuy)', -24.205, -65.2926, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-008', 'Centro de Salud — Centro (San Salvador de Jujuy)', -24.2107, -65.3046, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-009', 'Carrefour — Centro (San Salvador de Jujuy)', -24.1406, -65.275, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-010', 'Coto — Centro (San Salvador de Jujuy)', -24.1765, -65.3565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-011', 'Farmacia Farmacity — Centro (San Salvador de Jujuy)', -24.1605, -65.3159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-012', 'Estación YPF — Centro (San Salvador de Jujuy)', -24.1951, -65.3116, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-013', 'Estación Shell — Centro (San Salvador de Jujuy)', -24.1755, -65.2997, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-014', 'Hotel — Centro (San Salvador de Jujuy)', -24.2318, -65.2987, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-015', 'Restaurante — Centro (San Salvador de Jujuy)', -24.1558, -65.2875, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-016', 'Plaza Central — Zona Norte (San Salvador de Jujuy)', -24.1869, -65.2495, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-017', 'Centro de Salud — Zona Norte (San Salvador de Jujuy)', -24.2148, -65.3091, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-018', 'Carrefour — Zona Norte (San Salvador de Jujuy)', -24.1347, -65.302, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-019', 'Coto — Zona Norte (San Salvador de Jujuy)', -24.1836, -65.3565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-020', 'Farmacia Farmacity — Zona Norte (San Salvador de Jujuy)', -24.2189, -65.344, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-021', 'Estación YPF — Zona Norte (San Salvador de Jujuy)', -24.2399, -65.2749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-022', 'Estación Shell — Zona Norte (San Salvador de Jujuy)', -24.1394, -65.3472, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-023', 'Hotel — Zona Norte (San Salvador de Jujuy)', -24.1711, -65.3031, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-024', 'Restaurante — Zona Norte (San Salvador de Jujuy)', -24.1879, -65.332, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-025', 'Plaza Central — Zona Sur (San Salvador de Jujuy)', -24.1395, -65.2843, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-026', 'Centro de Salud — Zona Sur (San Salvador de Jujuy)', -24.191, -65.3032, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-027', 'Carrefour — Zona Sur (San Salvador de Jujuy)', -24.1343, -65.241, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-028', 'Coto — Zona Sur (San Salvador de Jujuy)', -24.1803, -65.2923, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-029', 'Farmacia Farmacity — Zona Sur (San Salvador de Jujuy)', -24.1654, -65.3226, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-030', 'Estación YPF — Zona Sur (San Salvador de Jujuy)', -24.1498, -65.2993, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-031', 'Catedral de La Plata', -34.9214, -57.9544, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-032', 'Plaza Moreno (La Plata)', -34.921, -57.954, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-033', 'Estadio Único de La Plata', -34.945, -57.97, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-034', 'Subway — La Plata', -34.9153, -57.951, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-035', 'Pizza Hut — La Plata', -34.9044, -57.9515, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-036', 'Starbucks — La Plata', -34.9076, -57.9383, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-037', 'Plaza Central — Centro (La Plata)', -34.9239, -57.9083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-038', 'Centro de Salud — Centro (La Plata)', -34.9294, -57.9791, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-039', 'Carrefour — Centro (La Plata)', -34.9491, -58.0104, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-040', 'Coto — Centro (La Plata)', -34.9027, -57.9427, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-041', 'Farmacia Farmacity — Centro (La Plata)', -34.9264, -57.9517, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-042', 'Estación YPF — Centro (La Plata)', -34.9227, -57.9038, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-043', 'Estación Shell — Centro (La Plata)', -34.9502, -57.9561, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-044', 'Hotel — Centro (La Plata)', -34.92, -57.9153, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-045', 'Restaurante — Centro (La Plata)', -34.8844, -57.9475, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-046', 'Plaza Central — Zona Norte (La Plata)', -34.8725, -57.9146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-047', 'Centro de Salud — Zona Norte (La Plata)', -34.9434, -57.9044, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-048', 'Carrefour — Zona Norte (La Plata)', -34.9696, -57.9317, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-049', 'Coto — Zona Norte (La Plata)', -34.8872, -57.9526, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-050', 'Farmacia Farmacity — Zona Norte (La Plata)', -34.927, -57.8986, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-051', 'Estación YPF — Zona Norte (La Plata)', -34.8653, -57.9133, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-052', 'Estación Shell — Zona Norte (La Plata)', -34.9239, -58.0067, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-053', 'Hotel — Zona Norte (La Plata)', -34.9494, -57.9546, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-054', 'Restaurante — Zona Norte (La Plata)', -34.9698, -57.9247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-055', 'Plaza Central — Zona Sur (La Plata)', -34.932, -57.9605, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-056', 'Centro de Salud — Zona Sur (La Plata)', -34.9797, -58.0144, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-057', 'Carrefour — Zona Sur (La Plata)', -34.9117, -57.9025, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-058', 'Coto — Zona Sur (La Plata)', -34.9714, -57.9191, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-059', 'Farmacia Farmacity — Zona Sur (La Plata)', -34.9517, -57.9399, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-060', 'Estación YPF — Zona Sur (La Plata)', -34.8912, -57.8996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-061', 'Casa Histórica de Tucumán', -26.828, -65.205, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-062', 'Plaza Independencia (Tucumán)', -26.829, -65.204, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-063', 'Aeropuerto de Tucumán', -26.8409, -65.1049, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-064', 'Domino''s Pizza — San Miguel de Tucumán', -26.809, -65.2174, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-065', 'Mostaza — San Miguel de Tucumán', -26.8397, -65.2157, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-066', 'Freddo — San Miguel de Tucumán', -26.8475, -65.2036, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-067', 'Plaza Central — Centro (San Miguel de Tucumán)', -26.8039, -65.2064, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-068', 'Centro de Salud — Centro (San Miguel de Tucumán)', -26.8655, -65.245, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-069', 'Carrefour — Centro (San Miguel de Tucumán)', -26.8141, -65.1903, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-070', 'Coto — Centro (San Miguel de Tucumán)', -26.7701, -65.2236, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-071', 'Farmacia Farmacity — Centro (San Miguel de Tucumán)', -26.7976, -65.2664, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-072', 'Estación YPF — Centro (San Miguel de Tucumán)', -26.8573, -65.212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-073', 'Estación Shell — Centro (San Miguel de Tucumán)', -26.7691, -65.1775, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-074', 'Hotel — Centro (San Miguel de Tucumán)', -26.8235, -65.2725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-075', 'Restaurante — Centro (San Miguel de Tucumán)', -26.8039, -65.1704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-076', 'Plaza Central — Zona Norte (San Miguel de Tucumán)', -26.7901, -65.1728, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-077', 'Centro de Salud — Zona Norte (San Miguel de Tucumán)', -26.8474, -65.2332, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-078', 'Carrefour — Zona Norte (San Miguel de Tucumán)', -26.7871, -65.2202, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-079', 'Coto — Zona Norte (San Miguel de Tucumán)', -26.8605, -65.2809, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-080', 'Farmacia Farmacity — Zona Norte (San Miguel de Tucumán)', -26.8714, -65.1761, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-081', 'Estación YPF — Zona Norte (San Miguel de Tucumán)', -26.8779, -65.241, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-082', 'Estación Shell — Zona Norte (San Miguel de Tucumán)', -26.8417, -65.1903, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-083', 'Hotel — Zona Norte (San Miguel de Tucumán)', -26.881, -65.2214, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-084', 'Restaurante — Zona Norte (San Miguel de Tucumán)', -26.8448, -65.2462, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-085', 'Plaza Central — Zona Sur (San Miguel de Tucumán)', -26.845, -65.268, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-086', 'Centro de Salud — Zona Sur (San Miguel de Tucumán)', -26.7702, -65.214, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-087', 'Carrefour — Zona Sur (San Miguel de Tucumán)', -26.7875, -65.2641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-088', 'Coto — Zona Sur (San Miguel de Tucumán)', -26.8217, -65.2306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-089', 'Farmacia Farmacity — Zona Sur (San Miguel de Tucumán)', -26.8437, -65.2108, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-090', 'Estación YPF — Zona Sur (San Miguel de Tucumán)', -26.8027, -65.2743, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-091', 'Plaza 25 de Mayo (Santa Fe)', -31.6333, -60.7, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-092', 'Puente Colgante de Santa Fe', -31.62, -60.69, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-093', 'Havanna — Santa Fe de la Vera Cruz', -31.6363, -60.6811, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-094', 'Grido — Santa Fe de la Vera Cruz', -31.6222, -60.6892, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-095', 'Kansas — Santa Fe de la Vera Cruz', -31.6507, -60.7149, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-096', 'Plaza Central — Centro (Santa Fe de la Vera Cruz)', -31.6454, -60.7365, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-097', 'Centro de Salud — Centro (Santa Fe de la Vera Cruz)', -31.5827, -60.7546, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-098', 'Carrefour — Centro (Santa Fe de la Vera Cruz)', -31.6279, -60.6593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-099', 'Coto — Centro (Santa Fe de la Vera Cruz)', -31.6391, -60.6694, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-100', 'Farmacia Farmacity — Centro (Santa Fe de la Vera Cruz)', -31.6707, -60.6747, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-101', 'Estación YPF — Centro (Santa Fe de la Vera Cruz)', -31.588, -60.7445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-102', 'Estación Shell — Centro (Santa Fe de la Vera Cruz)', -31.6297, -60.6658, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-103', 'Hotel — Centro (Santa Fe de la Vera Cruz)', -31.6313, -60.6452, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-104', 'Restaurante — Centro (Santa Fe de la Vera Cruz)', -31.6741, -60.6587, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-105', 'Plaza Central — Zona Norte (Santa Fe de la Vera Cruz)', -31.6465, -60.709, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-106', 'Centro de Salud — Zona Norte (Santa Fe de la Vera Cruz)', -31.6436, -60.7506, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-107', 'Carrefour — Zona Norte (Santa Fe de la Vera Cruz)', -31.6567, -60.7187, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-108', 'Coto — Zona Norte (Santa Fe de la Vera Cruz)', -31.6617, -60.7003, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-109', 'Farmacia Farmacity — Zona Norte (Santa Fe de la Vera Cruz)', -31.5997, -60.7101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-110', 'Estación YPF — Zona Norte (Santa Fe de la Vera Cruz)', -31.6372, -60.7209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-111', 'Estación Shell — Zona Norte (Santa Fe de la Vera Cruz)', -31.6355, -60.7456, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-112', 'Hotel — Zona Norte (Santa Fe de la Vera Cruz)', -31.5977, -60.6644, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-113', 'Restaurante — Zona Norte (Santa Fe de la Vera Cruz)', -31.5954, -60.6583, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-114', 'Plaza Central — Zona Sur (Santa Fe de la Vera Cruz)', -31.6655, -60.6456, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-115', 'Centro de Salud — Zona Sur (Santa Fe de la Vera Cruz)', -31.5879, -60.6825, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-116', 'Carrefour — Zona Sur (Santa Fe de la Vera Cruz)', -31.6443, -60.666, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-117', 'Coto — Zona Sur (Santa Fe de la Vera Cruz)', -31.5914, -60.6796, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-118', 'Farmacia Farmacity — Zona Sur (Santa Fe de la Vera Cruz)', -31.578, -60.7178, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-119', 'Estación YPF — Zona Sur (Santa Fe de la Vera Cruz)', -31.6745, -60.6926, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-120', 'Estación Shell — Zona Sur (Santa Fe de la Vera Cruz)', -31.6246, -60.6954, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-121', 'Costanera de Corrientes', -27.475, -58.83, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-122', 'Plaza 25 de Mayo (Corrientes)', -27.47, -58.835, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-123', 'El Noble Repulgue — Corrientes', -27.4518, -58.8083, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-124', 'La Parolaccia — Corrientes', -27.4623, -58.8041, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-125', 'Wendy''s — Corrientes', -27.4798, -58.8595, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ar150-126', 'Plaza Central — Centro (Corrientes)', -27.5274, -58.8082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-127', 'Centro de Salud — Centro (Corrientes)', -27.4739, -58.8259, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-128', 'Carrefour — Centro (Corrientes)', -27.5149, -58.8587, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-129', 'Coto — Centro (Corrientes)', -27.5084, -58.8274, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-130', 'Farmacia Farmacity — Centro (Corrientes)', -27.5284, -58.8625, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-131', 'Estación YPF — Centro (Corrientes)', -27.426, -58.8735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-132', 'Estación Shell — Centro (Corrientes)', -27.4585, -58.803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-133', 'Hotel — Centro (Corrientes)', -27.4539, -58.8718, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-134', 'Restaurante — Centro (Corrientes)', -27.465, -58.8333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-135', 'Plaza Central — Zona Norte (Corrientes)', -27.5074, -58.7936, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-136', 'Centro de Salud — Zona Norte (Corrientes)', -27.5057, -58.8563, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-137', 'Carrefour — Zona Norte (Corrientes)', -27.5093, -58.8866, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-138', 'Coto — Zona Norte (Corrientes)', -27.4912, -58.7863, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-139', 'Farmacia Farmacity — Zona Norte (Corrientes)', -27.4474, -58.8444, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-140', 'Estación YPF — Zona Norte (Corrientes)', -27.5387, -58.8825, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-141', 'Estación Shell — Zona Norte (Corrientes)', -27.5378, -58.8793, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-142', 'Hotel — Zona Norte (Corrientes)', -27.4583, -58.8249, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-143', 'Restaurante — Zona Norte (Corrientes)', -27.4283, -58.8521, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-144', 'Plaza Central — Zona Sur (Corrientes)', -27.447, -58.8212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-145', 'Centro de Salud — Zona Sur (Corrientes)', -27.462, -58.8203, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-146', 'Carrefour — Zona Sur (Corrientes)', -27.4296, -58.8562, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-147', 'Coto — Zona Sur (Corrientes)', -27.5147, -58.8386, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-148', 'Farmacia Farmacity — Zona Sur (Corrientes)', -27.4231, -58.7887, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-149', 'Estación YPF — Zona Sur (Corrientes)', -27.4582, -58.7907, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-150', 'Estación Shell — Zona Sur (Corrientes)', -27.4588, -58.7833, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-151', 'Glaciar Perito Moreno (acceso)', -50.4967, -73.0378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-152', 'Aeropuerto de El Calafate', -50.2803, -72.0531, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-153', 'Plaza Central — Centro (El Calafate)', -50.3512, -72.2112, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-154', 'Centro de Salud — Centro (El Calafate)', -50.3551, -72.2366, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-155', 'Carrefour — Centro (El Calafate)', -50.3455, -72.322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-156', 'Coto — Centro (El Calafate)', -50.3145, -72.2901, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-157', 'Farmacia Farmacity — Centro (El Calafate)', -50.2829, -72.2288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-158', 'Estación YPF — Centro (El Calafate)', -50.3832, -72.2327, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-159', 'Estación Shell — Centro (El Calafate)', -50.3596, -72.2164, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-160', 'Hotel — Centro (El Calafate)', -50.3328, -72.2837, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-161', 'Restaurante — Centro (El Calafate)', -50.3306, -72.2382, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-162', 'Plaza Central — Zona Norte (El Calafate)', -50.3844, -72.2505, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-163', 'Centro de Salud — Zona Norte (El Calafate)', -50.3837, -72.3097, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-164', 'Carrefour — Zona Norte (El Calafate)', -50.3554, -72.2471, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-165', 'Coto — Zona Norte (El Calafate)', -50.3192, -72.3213, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-166', 'Reloj Cucú (Villa Carlos Paz)', -31.4241, -64.4978, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-167', 'Lago San Roque (Villa Carlos Paz)', -31.41, -64.5, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-168', 'Plaza Central — Centro (Villa Carlos Paz)', -31.4147, -64.5151, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-169', 'Centro de Salud — Centro (Villa Carlos Paz)', -31.438, -64.5291, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-170', 'Carrefour — Centro (Villa Carlos Paz)', -31.4336, -64.5315, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-171', 'Coto — Centro (Villa Carlos Paz)', -31.4691, -64.4926, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-172', 'Farmacia Farmacity — Centro (Villa Carlos Paz)', -31.4047, -64.4456, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-173', 'Estación YPF — Centro (Villa Carlos Paz)', -31.402, -64.5102, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-174', 'Estación Shell — Centro (Villa Carlos Paz)', -31.4535, -64.5401, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-175', 'Hotel — Centro (Villa Carlos Paz)', -31.4813, -64.5246, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-176', 'Restaurante — Centro (Villa Carlos Paz)', -31.4266, -64.5261, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-177', 'Plaza Central — Zona Norte (Villa Carlos Paz)', -31.4463, -64.4445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-178', 'Centro de Salud — Zona Norte (Villa Carlos Paz)', -31.4129, -64.4571, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-179', 'Carrefour — Zona Norte (Villa Carlos Paz)', -31.4177, -64.4798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-180', 'Coto — Zona Norte (Villa Carlos Paz)', -31.3687, -64.4961, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-181', 'Cerro Fitz Roy (acceso El Chaltén)', -49.27, -73.05, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-182', 'Plaza Central — Centro (El Chaltén)', -49.3597, -72.8702, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-183', 'Centro de Salud — Centro (El Chaltén)', -49.301, -72.9081, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-184', 'Carrefour — Centro (El Chaltén)', -49.3126, -72.9448, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-185', 'Coto — Centro (El Chaltén)', -49.2741, -72.8897, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-186', 'Farmacia Farmacity — Centro (El Chaltén)', -49.2751, -72.8647, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-187', 'Estación YPF — Centro (El Chaltén)', -49.288, -72.8349, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-188', 'Estación Shell — Centro (El Chaltén)', -49.2828, -72.8983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-189', 'Hotel — Centro (El Chaltén)', -49.2744, -72.8321, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-190', 'Restaurante — Centro (El Chaltén)', -49.3636, -72.8467, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-191', 'Plaza Central — Zona Norte (El Chaltén)', -49.3503, -72.9221, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-192', 'Centro de Salud — Zona Norte (El Chaltén)', -49.3484, -72.8698, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-193', 'Carrefour — Zona Norte (El Chaltén)', -49.3256, -72.8893, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-194', 'Coto — Zona Norte (El Chaltén)', -49.2969, -72.8765, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-195', 'Farmacia Farmacity — Zona Norte (El Chaltén)', -49.369, -72.8708, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-196', 'Península Valdés (acceso)', -42.47, -63.97, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-197', 'Playa El Doradillo (Puerto Madryn)', -42.66, -64.92, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-198', 'Plaza Central — Centro (Puerto Madryn)', -42.8107, -64.9912, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-199', 'Centro de Salud — Centro (Puerto Madryn)', -42.7151, -65.0008, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-200', 'Carrefour — Centro (Puerto Madryn)', -42.729, -65.0142, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-201', 'Coto — Centro (Puerto Madryn)', -42.7338, -65.0218, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-202', 'Farmacia Farmacity — Centro (Puerto Madryn)', -42.8191, -65.0538, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-203', 'Estación YPF — Centro (Puerto Madryn)', -42.7415, -65.0819, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-204', 'Estación Shell — Centro (Puerto Madryn)', -42.7405, -64.9786, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-205', 'Hotel — Centro (Puerto Madryn)', -42.827, -65.0724, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-206', 'Restaurante — Centro (Puerto Madryn)', -42.7274, -65.0286, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-207', 'Plaza Central — Zona Norte (Puerto Madryn)', -42.7605, -64.9838, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-208', 'Centro de Salud — Zona Norte (Puerto Madryn)', -42.7835, -64.9829, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-209', 'Carrefour — Zona Norte (Puerto Madryn)', -42.7672, -65.0212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-210', 'Coto — Zona Norte (Puerto Madryn)', -42.8102, -65.0374, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-211', 'Bodegas de Cafayate (centro)', -26.073, -65.975, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-212', 'Plaza Central — Centro (Cafayate)', -26.1227, -65.9471, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-213', 'Centro de Salud — Centro (Cafayate)', -26.093, -66.0036, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-214', 'Carrefour — Centro (Cafayate)', -26.128, -65.9639, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-215', 'Coto — Centro (Cafayate)', -26.0385, -66.0155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-216', 'Farmacia Farmacity — Centro (Cafayate)', -26.0979, -65.9701, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-217', 'Estación YPF — Centro (Cafayate)', -26.0901, -65.9183, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-218', 'Estación Shell — Centro (Cafayate)', -26.1104, -65.9454, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-219', 'Hotel — Centro (Cafayate)', -26.1319, -65.9623, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-220', 'Restaurante — Centro (Cafayate)', -26.0754, -65.9843, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-221', 'Plaza Central — Zona Norte (Cafayate)', -26.0355, -65.9267, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-222', 'Centro de Salud — Zona Norte (Cafayate)', -26.0155, -65.9154, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-223', 'Carrefour — Zona Norte (Cafayate)', -26.1125, -65.9731, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-224', 'Coto — Zona Norte (Cafayate)', -26.1114, -65.9703, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ar150-225', 'Farmacia Farmacity — Zona Norte (Cafayate)', -26.1133, -65.9285, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
