-- ============================================
-- Achou Trocador — Chile: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('cl150-001', 'Plaza de Armas de Puente Alto', -33.611, -70.576, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-002', 'McDonald''s — Puente Alto', -33.6101, -70.5531, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-003', 'Burger King — Puente Alto', -33.6024, -70.6059, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-004', 'KFC — Puente Alto', -33.6185, -70.5839, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-005', 'Plaza Central — Centro (Puente Alto)', -33.5806, -70.6089, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-006', 'Centro de Salud — Centro (Puente Alto)', -33.632, -70.5752, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-007', 'Jumbo — Centro (Puente Alto)', -33.6312, -70.5271, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-008', 'Líder — Centro (Puente Alto)', -33.5841, -70.5331, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-009', 'Farmacia Cruz Verde — Centro (Puente Alto)', -33.6226, -70.6148, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-010', 'Farmacia Salcobrand — Centro (Puente Alto)', -33.5742, -70.6096, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-011', 'Estación Copec — Centro (Puente Alto)', -33.5883, -70.5942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-012', 'Estación Shell — Centro (Puente Alto)', -33.5765, -70.5868, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-013', 'Hotel — Centro (Puente Alto)', -33.5746, -70.5902, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-014', 'Restaurante — Centro (Puente Alto)', -33.6525, -70.5468, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-015', 'Plaza Central — Zona Norte (Puente Alto)', -33.5922, -70.6207, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-016', 'Centro de Salud — Zona Norte (Puente Alto)', -33.6389, -70.5357, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-017', 'Jumbo — Zona Norte (Puente Alto)', -33.6326, -70.5351, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-018', 'Líder — Zona Norte (Puente Alto)', -33.6177, -70.6186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-019', 'Farmacia Cruz Verde — Zona Norte (Puente Alto)', -33.5958, -70.6079, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-020', 'Farmacia Salcobrand — Zona Norte (Puente Alto)', -33.5543, -70.5686, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-021', 'Estación Copec — Zona Norte (Puente Alto)', -33.6562, -70.6008, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-022', 'Estación Shell — Zona Norte (Puente Alto)', -33.616, -70.5879, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-023', 'Hotel — Zona Norte (Puente Alto)', -33.6684, -70.55, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-024', 'Restaurante — Zona Norte (Puente Alto)', -33.5901, -70.5956, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-025', 'Plaza Central — Zona Sur (Puente Alto)', -33.5895, -70.5253, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-026', 'Centro de Salud — Zona Sur (Puente Alto)', -33.562, -70.5343, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-027', 'Jumbo — Zona Sur (Puente Alto)', -33.5567, -70.5559, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-028', 'Líder — Zona Sur (Puente Alto)', -33.6054, -70.6108, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-029', 'Farmacia Cruz Verde — Zona Sur (Puente Alto)', -33.6287, -70.5963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-030', 'Farmacia Salcobrand — Zona Sur (Puente Alto)', -33.5603, -70.5491, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-031', 'Templo Votivo de Maipú', -33.5, -70.76, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-032', 'Subway — Maipú', -33.527, -70.7787, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-033', 'Pizza Hut — Maipú', -33.5034, -70.7804, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-034', 'Starbucks — Maipú', -33.4809, -70.7589, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-035', 'Plaza Central — Centro (Maipú)', -33.5687, -70.7509, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-036', 'Centro de Salud — Centro (Maipú)', -33.5397, -70.7779, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-037', 'Jumbo — Centro (Maipú)', -33.4927, -70.7682, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-038', 'Líder — Centro (Maipú)', -33.4766, -70.7609, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-039', 'Farmacia Cruz Verde — Centro (Maipú)', -33.4633, -70.7774, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-040', 'Farmacia Salcobrand — Centro (Maipú)', -33.5655, -70.7916, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-041', 'Estación Copec — Centro (Maipú)', -33.5555, -70.7158, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-042', 'Estación Shell — Centro (Maipú)', -33.5378, -70.8159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-043', 'Hotel — Centro (Maipú)', -33.5449, -70.7631, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-044', 'Restaurante — Centro (Maipú)', -33.5368, -70.7424, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-045', 'Plaza Central — Zona Norte (Maipú)', -33.5605, -70.7349, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-046', 'Centro de Salud — Zona Norte (Maipú)', -33.5053, -70.8166, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-047', 'Jumbo — Zona Norte (Maipú)', -33.5585, -70.7784, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-048', 'Líder — Zona Norte (Maipú)', -33.5437, -70.7624, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-049', 'Farmacia Cruz Verde — Zona Norte (Maipú)', -33.4973, -70.7975, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-050', 'Farmacia Salcobrand — Zona Norte (Maipú)', -33.5329, -70.7499, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-051', 'Estación Copec — Zona Norte (Maipú)', -33.4846, -70.7363, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-052', 'Estación Shell — Zona Norte (Maipú)', -33.5029, -70.805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-053', 'Hotel — Zona Norte (Maipú)', -33.5375, -70.7677, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-054', 'Restaurante — Zona Norte (Maipú)', -33.5478, -70.7299, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-055', 'Plaza Central — Zona Sur (Maipú)', -33.4514, -70.6994, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-056', 'Centro de Salud — Zona Sur (Maipú)', -33.4607, -70.7391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-057', 'Jumbo — Zona Sur (Maipú)', -33.529, -70.7763, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-058', 'Líder — Zona Sur (Maipú)', -33.4972, -70.7874, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-059', 'Farmacia Cruz Verde — Zona Sur (Maipú)', -33.464, -70.7173, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-060', 'Farmacia Salcobrand — Zona Sur (Maipú)', -33.5656, -70.7592, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-061', 'Ruinas de Huanchaca (Antofagasta)', -23.63, -70.39, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-062', 'Aeropuerto de Antofagasta', -23.4445, -70.4451, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-063', 'Domino''s Pizza — Antofagasta', -23.6285, -70.3839, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-064', 'Doggis — Antofagasta', -23.658, -70.3905, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-065', 'Fritz — Antofagasta', -23.642, -70.4066, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-066', 'Plaza Central — Centro (Antofagasta)', -23.7083, -70.3604, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-067', 'Centro de Salud — Centro (Antofagasta)', -23.6804, -70.3669, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-068', 'Jumbo — Centro (Antofagasta)', -23.6871, -70.4247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-069', 'Líder — Centro (Antofagasta)', -23.6098, -70.4095, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-070', 'Farmacia Cruz Verde — Centro (Antofagasta)', -23.6847, -70.451, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-071', 'Farmacia Salcobrand — Centro (Antofagasta)', -23.6616, -70.4498, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-072', 'Estación Copec — Centro (Antofagasta)', -23.6243, -70.3782, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-073', 'Estación Shell — Centro (Antofagasta)', -23.6291, -70.3656, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-074', 'Hotel — Centro (Antofagasta)', -23.6751, -70.3996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-075', 'Restaurante — Centro (Antofagasta)', -23.7, -70.3963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-076', 'Plaza Central — Zona Norte (Antofagasta)', -23.6482, -70.4185, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-077', 'Centro de Salud — Zona Norte (Antofagasta)', -23.6727, -70.4167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-078', 'Jumbo — Zona Norte (Antofagasta)', -23.6892, -70.3388, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-079', 'Líder — Zona Norte (Antofagasta)', -23.6073, -70.4366, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-080', 'Farmacia Cruz Verde — Zona Norte (Antofagasta)', -23.68, -70.3438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-081', 'Farmacia Salcobrand — Zona Norte (Antofagasta)', -23.6063, -70.395, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-082', 'Estación Copec — Zona Norte (Antofagasta)', -23.665, -70.4447, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-083', 'Estación Shell — Zona Norte (Antofagasta)', -23.6378, -70.4317, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-084', 'Hotel — Zona Norte (Antofagasta)', -23.6552, -70.4323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-085', 'Restaurante — Zona Norte (Antofagasta)', -23.6499, -70.3943, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-086', 'Plaza Central — Zona Sur (Antofagasta)', -23.6493, -70.3625, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-087', 'Centro de Salud — Zona Sur (Antofagasta)', -23.6784, -70.3526, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-088', 'Jumbo — Zona Sur (Antofagasta)', -23.6523, -70.3904, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-089', 'Líder — Zona Sur (Antofagasta)', -23.61, -70.4184, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-090', 'Farmacia Cruz Verde — Zona Sur (Antofagasta)', -23.5912, -70.4105, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-091', 'Plaza de Armas de San Bernardo', -33.5928, -70.6997, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-092', 'Juan Maestro — San Bernardo', -33.5682, -70.7224, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-093', 'Lomiton — San Bernardo', -33.5917, -70.68, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-094', 'Bavaria — San Bernardo', -33.5818, -70.7023, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-095', 'Plaza Central — Centro (San Bernardo)', -33.579, -70.695, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-096', 'Centro de Salud — Centro (San Bernardo)', -33.6346, -70.6935, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-097', 'Jumbo — Centro (San Bernardo)', -33.5352, -70.6723, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-098', 'Líder — Centro (San Bernardo)', -33.637, -70.6618, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-099', 'Farmacia Cruz Verde — Centro (San Bernardo)', -33.574, -70.7524, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-100', 'Farmacia Salcobrand — Centro (San Bernardo)', -33.5728, -70.7556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-101', 'Estación Copec — Centro (San Bernardo)', -33.5581, -70.6468, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-102', 'Estación Shell — Centro (San Bernardo)', -33.6313, -70.7276, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-103', 'Hotel — Centro (San Bernardo)', -33.588, -70.7169, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-104', 'Restaurante — Centro (San Bernardo)', -33.5979, -70.7373, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-105', 'Plaza Central — Zona Norte (San Bernardo)', -33.6464, -70.7374, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-106', 'Centro de Salud — Zona Norte (San Bernardo)', -33.6343, -70.6828, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-107', 'Jumbo — Zona Norte (San Bernardo)', -33.594, -70.6942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-108', 'Líder — Zona Norte (San Bernardo)', -33.6493, -70.7332, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-109', 'Farmacia Cruz Verde — Zona Norte (San Bernardo)', -33.6091, -70.6946, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-110', 'Farmacia Salcobrand — Zona Norte (San Bernardo)', -33.5969, -70.67, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-111', 'Estación Copec — Zona Norte (San Bernardo)', -33.6342, -70.7208, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-112', 'Estación Shell — Zona Norte (San Bernardo)', -33.567, -70.7549, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-113', 'Hotel — Zona Norte (San Bernardo)', -33.6519, -70.7483, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-114', 'Restaurante — Zona Norte (San Bernardo)', -33.5825, -70.6751, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-115', 'Plaza Central — Zona Sur (San Bernardo)', -33.5552, -70.7288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-116', 'Centro de Salud — Zona Sur (San Bernardo)', -33.562, -70.74, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-117', 'Jumbo — Zona Sur (San Bernardo)', -33.6298, -70.6617, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-118', 'Líder — Zona Sur (San Bernardo)', -33.6021, -70.7077, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-119', 'Farmacia Cruz Verde — Zona Sur (San Bernardo)', -33.5528, -70.7392, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-120', 'Farmacia Salcobrand — Zona Sur (San Bernardo)', -33.6258, -70.6435, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-121', 'Parque Araucano (Las Condes)', -33.402, -70.573, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-122', 'Schop Dog — Las Condes', -33.4038, -70.5943, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-123', 'Telepizza — Las Condes', -33.3922, -70.594, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-124', 'Wendy''s — Las Condes', -33.4092, -70.5806, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cl150-125', 'Plaza Central — Centro (Las Condes)', -33.4434, -70.6103, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-126', 'Centro de Salud — Centro (Las Condes)', -33.3499, -70.5787, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-127', 'Jumbo — Centro (Las Condes)', -33.4181, -70.5266, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-128', 'Líder — Centro (Las Condes)', -33.3843, -70.5131, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-129', 'Farmacia Cruz Verde — Centro (Las Condes)', -33.3934, -70.5764, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-130', 'Farmacia Salcobrand — Centro (Las Condes)', -33.3551, -70.5565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-131', 'Estación Copec — Centro (Las Condes)', -33.4579, -70.5217, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-132', 'Estación Shell — Centro (Las Condes)', -33.3802, -70.6154, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-133', 'Hotel — Centro (Las Condes)', -33.4594, -70.5435, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-134', 'Restaurante — Centro (Las Condes)', -33.3942, -70.6103, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-135', 'Plaza Central — Zona Norte (Las Condes)', -33.4482, -70.5524, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-136', 'Centro de Salud — Zona Norte (Las Condes)', -33.4462, -70.5155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-137', 'Jumbo — Zona Norte (Las Condes)', -33.3509, -70.6256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-138', 'Líder — Zona Norte (Las Condes)', -33.3524, -70.5515, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-139', 'Farmacia Cruz Verde — Zona Norte (Las Condes)', -33.3593, -70.5346, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-140', 'Farmacia Salcobrand — Zona Norte (Las Condes)', -33.4344, -70.5855, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-141', 'Estación Copec — Zona Norte (Las Condes)', -33.4678, -70.5668, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-142', 'Estación Shell — Zona Norte (Las Condes)', -33.3625, -70.5284, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-143', 'Hotel — Zona Norte (Las Condes)', -33.4103, -70.6127, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-144', 'Restaurante — Zona Norte (Las Condes)', -33.3737, -70.5621, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-145', 'Plaza Central — Zona Sur (Las Condes)', -33.3525, -70.5746, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-146', 'Centro de Salud — Zona Sur (Las Condes)', -33.3959, -70.5581, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-147', 'Jumbo — Zona Sur (Las Condes)', -33.3572, -70.5489, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-148', 'Líder — Zona Sur (Las Condes)', -33.4297, -70.5987, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-149', 'Farmacia Cruz Verde — Zona Sur (Las Condes)', -33.3871, -70.574, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-150', 'Farmacia Salcobrand — Zona Sur (Las Condes)', -33.4274, -70.5302, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-151', 'Museo de Colchagua', -34.638, -71.367, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-152', 'Plaza Central — Centro (Valle de Colchagua (Santa Cruz))', -34.635, -71.3634, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-153', 'Centro de Salud — Centro (Valle de Colchagua (Santa Cruz))', -34.6862, -71.3939, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-154', 'Jumbo — Centro (Valle de Colchagua (Santa Cruz))', -34.6935, -71.3562, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-155', 'Líder — Centro (Valle de Colchagua (Santa Cruz))', -34.6896, -71.3163, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-156', 'Farmacia Cruz Verde — Centro (Valle de Colchagua (Santa Cruz))', -34.6303, -71.3807, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-157', 'Farmacia Salcobrand — Centro (Valle de Colchagua (Santa Cruz))', -34.6205, -71.358, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-158', 'Estación Copec — Centro (Valle de Colchagua (Santa Cruz))', -34.6432, -71.3696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-159', 'Estación Shell — Centro (Valle de Colchagua (Santa Cruz))', -34.6954, -71.3192, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-160', 'Hotel — Centro (Valle de Colchagua (Santa Cruz))', -34.6819, -71.4144, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-161', 'Restaurante — Centro (Valle de Colchagua (Santa Cruz))', -34.687, -71.3628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-162', 'Plaza Central — Zona Norte (Valle de Colchagua (Santa Cruz))', -34.6674, -71.3104, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-163', 'Centro de Salud — Zona Norte (Valle de Colchagua (Santa Cruz))', -34.6081, -71.4185, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-164', 'Jumbo — Zona Norte (Valle de Colchagua (Santa Cruz))', -34.6258, -71.4126, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-165', 'Líder — Zona Norte (Valle de Colchagua (Santa Cruz))', -34.5823, -71.3184, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-166', 'Faro Monumental de La Serena', -29.92, -71.26, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-167', 'Playa Coquimbo', -29.953, -71.339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-168', 'Plaza Central — Centro (La Serena e Coquimbo)', -29.8766, -71.2751, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-169', 'Centro de Salud — Centro (La Serena e Coquimbo)', -29.9062, -71.2732, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-170', 'Jumbo — Centro (La Serena e Coquimbo)', -29.8551, -71.229, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-171', 'Líder — Centro (La Serena e Coquimbo)', -29.9147, -71.2502, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-172', 'Farmacia Cruz Verde — Centro (La Serena e Coquimbo)', -29.8609, -71.2616, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-173', 'Farmacia Salcobrand — Centro (La Serena e Coquimbo)', -29.904, -71.2404, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-174', 'Estación Copec — Centro (La Serena e Coquimbo)', -29.9101, -71.2196, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-175', 'Estación Shell — Centro (La Serena e Coquimbo)', -29.8921, -71.241, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-176', 'Hotel — Centro (La Serena e Coquimbo)', -29.9048, -71.3099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-177', 'Restaurante — Centro (La Serena e Coquimbo)', -29.8492, -71.2657, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-178', 'Plaza Central — Zona Norte (La Serena e Coquimbo)', -29.9586, -71.256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-179', 'Centro de Salud — Zona Norte (La Serena e Coquimbo)', -29.9459, -71.283, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-180', 'Jumbo — Zona Norte (La Serena e Coquimbo)', -29.9001, -71.2798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-181', 'Centro de Ski Valle Nevado', -33.354, -70.25, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-182', 'Plaza Central — Centro (Valle Nevado e Farellones)', -33.3622, -70.2218, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-183', 'Centro de Salud — Centro (Valle Nevado e Farellones)', -33.4108, -70.2377, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-184', 'Jumbo — Centro (Valle Nevado e Farellones)', -33.3516, -70.1956, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-185', 'Líder — Centro (Valle Nevado e Farellones)', -33.3993, -70.2658, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-186', 'Farmacia Cruz Verde — Centro (Valle Nevado e Farellones)', -33.388, -70.3009, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-187', 'Farmacia Salcobrand — Centro (Valle Nevado e Farellones)', -33.3936, -70.2614, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-188', 'Estación Copec — Centro (Valle Nevado e Farellones)', -33.4007, -70.2973, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-189', 'Estación Shell — Centro (Valle Nevado e Farellones)', -33.2952, -70.2619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-190', 'Hotel — Centro (Valle Nevado e Farellones)', -33.4133, -70.2864, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-191', 'Restaurante — Centro (Valle Nevado e Farellones)', -33.3825, -70.214, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-192', 'Plaza Central — Zona Norte (Valle Nevado e Farellones)', -33.351, -70.2005, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-193', 'Centro de Salud — Zona Norte (Valle Nevado e Farellones)', -33.4039, -70.2899, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-194', 'Jumbo — Zona Norte (Valle Nevado e Farellones)', -33.3046, -70.2838, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-195', 'Líder — Zona Norte (Valle Nevado e Farellones)', -33.3129, -70.2136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-196', 'Plaza Muñoz Gamero (Punta Arenas)', -53.1638, -70.9171, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-197', 'Aeropuerto de Punta Arenas', -53.0026, -70.8546, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-198', 'Plaza Central — Centro (Punta Arenas)', -53.1563, -70.8692, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-199', 'Centro de Salud — Centro (Punta Arenas)', -53.1578, -70.9728, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-200', 'Jumbo — Centro (Punta Arenas)', -53.1086, -70.8596, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-201', 'Líder — Centro (Punta Arenas)', -53.1405, -70.8762, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-202', 'Farmacia Cruz Verde — Centro (Punta Arenas)', -53.1619, -70.865, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-203', 'Farmacia Salcobrand — Centro (Punta Arenas)', -53.109, -70.8688, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-204', 'Estación Copec — Centro (Punta Arenas)', -53.1077, -70.899, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-205', 'Estación Shell — Centro (Punta Arenas)', -53.1073, -70.9715, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-206', 'Hotel — Centro (Punta Arenas)', -53.2129, -70.8989, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-207', 'Restaurante — Centro (Punta Arenas)', -53.1903, -70.9762, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-208', 'Plaza Central — Zona Norte (Punta Arenas)', -53.1497, -70.9719, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-209', 'Centro de Salud — Zona Norte (Punta Arenas)', -53.1128, -70.9685, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-210', 'Jumbo — Zona Norte (Punta Arenas)', -53.1397, -70.9115, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-211', 'Costanera de Frutillar', -41.125, -73.07, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-212', 'Plaza Central — Centro (Frutillar)', -41.1193, -73.068, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-213', 'Centro de Salud — Centro (Frutillar)', -41.1202, -73.0706, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-214', 'Jumbo — Centro (Frutillar)', -41.1786, -73.0878, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-215', 'Líder — Centro (Frutillar)', -41.1206, -73.0743, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-216', 'Farmacia Cruz Verde — Centro (Frutillar)', -41.1559, -73.1282, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-217', 'Farmacia Salcobrand — Centro (Frutillar)', -41.1387, -73.1193, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-218', 'Estación Copec — Centro (Frutillar)', -41.104, -73.1086, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-219', 'Estación Shell — Centro (Frutillar)', -41.1566, -73.0629, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-220', 'Hotel — Centro (Frutillar)', -41.1244, -73.0895, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-221', 'Restaurante — Centro (Frutillar)', -41.1515, -73.0525, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-222', 'Plaza Central — Zona Norte (Frutillar)', -41.1647, -73.1189, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-223', 'Centro de Salud — Zona Norte (Frutillar)', -41.1437, -73.0403, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-224', 'Jumbo — Zona Norte (Frutillar)', -41.1694, -73.0172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cl150-225', 'Líder — Zona Norte (Frutillar)', -41.0815, -73.0365, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
