-- ============================================
-- Achou Trocador — Brasil: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('br150-001', 'Praça dos Três Poderes', -15.7998, -47.8644, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-002', 'Catedral de Brasília', -15.7986, -47.8756, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-003', 'McDonald''s — Brasília (populosas)', -15.8117, -47.853, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-004', 'Burger King — Brasília (populosas)', -15.7966, -47.8711, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-005', 'KFC — Brasília (populosas)', -15.8169, -47.8678, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-006', 'Praça Central — Centro (Brasília (populosas))', -15.7664, -47.8453, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-007', 'UBS — Centro (Brasília (populosas))', -15.7518, -47.9025, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-008', 'Extra — Centro (Brasília (populosas))', -15.8435, -47.9189, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-009', 'Carrefour — Centro (Brasília (populosas))', -15.822, -47.9327, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-010', 'Farmácia Droga Raia — Centro (Brasília (populosas))', -15.8331, -47.8556, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-011', 'Farmácia Drogasil — Centro (Brasília (populosas))', -15.8271, -47.9051, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-012', 'Posto Ipiranga — Centro (Brasília (populosas))', -15.8054, -47.8412, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-013', 'Posto Shell — Centro (Brasília (populosas))', -15.8491, -47.9093, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-014', 'Hotel — Centro (Brasília (populosas))', -15.7389, -47.8359, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-015', 'Restaurante — Centro (Brasília (populosas))', -15.8194, -47.9312, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-016', 'Praça Central — Zona Norte (Brasília (populosas))', -15.8486, -47.8422, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-017', 'UBS — Zona Norte (Brasília (populosas))', -15.7609, -47.9019, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-018', 'Extra — Zona Norte (Brasília (populosas))', -15.7571, -47.8509, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-019', 'Carrefour — Zona Norte (Brasília (populosas))', -15.7475, -47.8809, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-020', 'Farmácia Droga Raia — Zona Norte (Brasília (populosas))', -15.7648, -47.8919, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-021', 'Farmácia Drogasil — Zona Norte (Brasília (populosas))', -15.8398, -47.8599, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-022', 'Posto Ipiranga — Zona Norte (Brasília (populosas))', -15.8399, -47.9356, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-023', 'Posto Shell — Zona Norte (Brasília (populosas))', -15.7503, -47.9125, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-024', 'Hotel — Zona Norte (Brasília (populosas))', -15.8151, -47.8729, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-025', 'Restaurante — Zona Norte (Brasília (populosas))', -15.8161, -47.9151, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-026', 'Praça Central — Zona Sul (Brasília (populosas))', -15.7805, -47.9098, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-027', 'UBS — Zona Sul (Brasília (populosas))', -15.7727, -47.833, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-028', 'Extra — Zona Sul (Brasília (populosas))', -15.7863, -47.9093, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-029', 'Carrefour — Zona Sul (Brasília (populosas))', -15.7965, -47.887, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-030', 'Farmácia Droga Raia — Zona Sul (Brasília (populosas))', -15.7921, -47.856, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-031', 'Centro Dragão do Mar (Fortaleza)', -3.725, -38.527, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-032', 'Mercado Central de Fortaleza', -3.728, -38.527, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-033', 'Subway — Fortaleza (populosas)', -3.7302, -38.5356, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-034', 'Pizza Hut — Fortaleza (populosas)', -3.7383, -38.5085, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-035', 'Starbucks — Fortaleza (populosas)', -3.7233, -38.5078, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-036', 'Praça Central — Centro (Fortaleza (populosas))', -3.7029, -38.4947, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-037', 'UBS — Centro (Fortaleza (populosas))', -3.7764, -38.4902, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-038', 'Extra — Centro (Fortaleza (populosas))', -3.7442, -38.5652, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-039', 'Carrefour — Centro (Fortaleza (populosas))', -3.6763, -38.5125, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-040', 'Farmácia Droga Raia — Centro (Fortaleza (populosas))', -3.7434, -38.5197, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-041', 'Farmácia Drogasil — Centro (Fortaleza (populosas))', -3.791, -38.5196, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-042', 'Posto Ipiranga — Centro (Fortaleza (populosas))', -3.7836, -38.4806, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-043', 'Posto Shell — Centro (Fortaleza (populosas))', -3.6743, -38.5815, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-044', 'Hotel — Centro (Fortaleza (populosas))', -3.7543, -38.571, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-045', 'Restaurante — Centro (Fortaleza (populosas))', -3.7894, -38.5805, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-046', 'Praça Central — Zona Norte (Fortaleza (populosas))', -3.7898, -38.4734, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-047', 'UBS — Zona Norte (Fortaleza (populosas))', -3.7387, -38.5806, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-048', 'Extra — Zona Norte (Fortaleza (populosas))', -3.7016, -38.5154, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-049', 'Carrefour — Zona Norte (Fortaleza (populosas))', -3.7328, -38.4702, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-050', 'Farmácia Droga Raia — Zona Norte (Fortaleza (populosas))', -3.7872, -38.5323, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-051', 'Farmácia Drogasil — Zona Norte (Fortaleza (populosas))', -3.768, -38.5493, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-052', 'Posto Ipiranga — Zona Norte (Fortaleza (populosas))', -3.6737, -38.5294, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-053', 'Posto Shell — Zona Norte (Fortaleza (populosas))', -3.7086, -38.5034, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-054', 'Hotel — Zona Norte (Fortaleza (populosas))', -3.7803, -38.5362, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-055', 'Restaurante — Zona Norte (Fortaleza (populosas))', -3.7066, -38.4843, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-056', 'Praça Central — Zona Sul (Fortaleza (populosas))', -3.6841, -38.55, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-057', 'UBS — Zona Sul (Fortaleza (populosas))', -3.7633, -38.5767, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-058', 'Extra — Zona Sul (Fortaleza (populosas))', -3.7913, -38.5833, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-059', 'Carrefour — Zona Sul (Fortaleza (populosas))', -3.7305, -38.473, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-060', 'Farmácia Droga Raia — Zona Sul (Fortaleza (populosas))', -3.7859, -38.5501, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-061', 'Mercado Central de Belo Horizonte', -19.92, -43.939, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-062', 'Aeroporto de Confins', -19.6336, -43.9686, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-063', 'Domino''s Pizza — Belo Horizonte (populosas)', -19.9046, -43.9464, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-064', 'Habib''s — Belo Horizonte (populosas)', -19.9282, -43.9387, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-065', 'Giraffas — Belo Horizonte (populosas)', -19.9213, -43.9383, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-066', 'Praça Central — Centro (Belo Horizonte (populosas))', -19.9011, -43.9941, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-067', 'UBS — Centro (Belo Horizonte (populosas))', -19.9759, -43.9745, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-068', 'Extra — Centro (Belo Horizonte (populosas))', -19.9531, -43.9413, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-069', 'Carrefour — Centro (Belo Horizonte (populosas))', -19.9663, -43.9428, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-070', 'Farmácia Droga Raia — Centro (Belo Horizonte (populosas))', -19.9649, -43.8855, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-071', 'Farmácia Drogasil — Centro (Belo Horizonte (populosas))', -19.9553, -43.9235, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-072', 'Posto Ipiranga — Centro (Belo Horizonte (populosas))', -19.867, -43.9847, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-073', 'Posto Shell — Centro (Belo Horizonte (populosas))', -19.8569, -43.9443, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-074', 'Hotel — Centro (Belo Horizonte (populosas))', -19.9716, -43.91, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-075', 'Restaurante — Centro (Belo Horizonte (populosas))', -19.8828, -43.9014, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-076', 'Praça Central — Zona Norte (Belo Horizonte (populosas))', -19.8732, -43.9406, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-077', 'UBS — Zona Norte (Belo Horizonte (populosas))', -19.9743, -43.9538, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-078', 'Extra — Zona Norte (Belo Horizonte (populosas))', -19.9168, -43.9078, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-079', 'Carrefour — Zona Norte (Belo Horizonte (populosas))', -19.9066, -43.9202, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-080', 'Farmácia Droga Raia — Zona Norte (Belo Horizonte (populosas))', -19.9522, -43.8927, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-081', 'Farmácia Drogasil — Zona Norte (Belo Horizonte (populosas))', -19.9686, -43.8892, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-082', 'Posto Ipiranga — Zona Norte (Belo Horizonte (populosas))', -19.9539, -43.9355, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-083', 'Posto Shell — Zona Norte (Belo Horizonte (populosas))', -19.8759, -43.8757, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-084', 'Hotel — Zona Norte (Belo Horizonte (populosas))', -19.8946, -43.9824, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-085', 'Restaurante — Zona Norte (Belo Horizonte (populosas))', -19.9264, -43.9504, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-086', 'Praça Central — Zona Sul (Belo Horizonte (populosas))', -19.8718, -43.9783, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-087', 'UBS — Zona Sul (Belo Horizonte (populosas))', -19.9066, -43.8893, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-088', 'Extra — Zona Sul (Belo Horizonte (populosas))', -19.9048, -43.8847, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-089', 'Carrefour — Zona Sul (Belo Horizonte (populosas))', -19.8585, -43.8835, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-090', 'Farmácia Droga Raia — Zona Sul (Belo Horizonte (populosas))', -19.8969, -43.938, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-091', 'Marco Zero (Recife)', -8.0631, -34.8711, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-092', 'Instituto Ricardo Brennand (Recife)', -8.064, -34.95, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-093', 'Bob''s — Recife (populosas)', -8.0671, -34.8957, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-094', 'Spoleto — Recife (populosas)', -8.0705, -34.879, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-095', 'China in Box — Recife (populosas)', -8.0802, -34.8685, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-096', 'Praça Central — Centro (Recife (populosas))', -8.0822, -34.8999, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-097', 'UBS — Centro (Recife (populosas))', -8.0146, -34.9243, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-098', 'Extra — Centro (Recife (populosas))', -8.0757, -34.8151, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-099', 'Carrefour — Centro (Recife (populosas))', -8.0252, -34.9195, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-100', 'Farmácia Droga Raia — Centro (Recife (populosas))', -8.0633, -34.8367, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-101', 'Farmácia Drogasil — Centro (Recife (populosas))', -8.0609, -34.8126, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-102', 'Posto Ipiranga — Centro (Recife (populosas))', -8.0255, -34.8613, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-103', 'Posto Shell — Centro (Recife (populosas))', -8.0996, -34.8652, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-104', 'Hotel — Centro (Recife (populosas))', -8.1122, -34.8992, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-105', 'Restaurante — Centro (Recife (populosas))', -8.0685, -34.8129, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-106', 'Praça Central — Zona Norte (Recife (populosas))', -8.0411, -34.8493, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-107', 'UBS — Zona Norte (Recife (populosas))', -8.1038, -34.8992, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-108', 'Extra — Zona Norte (Recife (populosas))', -8.0254, -34.8412, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-109', 'Carrefour — Zona Norte (Recife (populosas))', -8.0743, -34.8342, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-110', 'Farmácia Droga Raia — Zona Norte (Recife (populosas))', -8.0611, -34.9107, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-111', 'Farmácia Drogasil — Zona Norte (Recife (populosas))', -8.1201, -34.852, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-112', 'Posto Ipiranga — Zona Norte (Recife (populosas))', -8.0497, -34.8134, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-113', 'Posto Shell — Zona Norte (Recife (populosas))', -8.1213, -34.8434, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-114', 'Hotel — Zona Norte (Recife (populosas))', -8.0373, -34.915, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-115', 'Restaurante — Zona Norte (Recife (populosas))', -8.0366, -34.9126, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-116', 'Praça Central — Zona Sul (Recife (populosas))', -8.1045, -34.8415, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-117', 'UBS — Zona Sul (Recife (populosas))', -8.1068, -34.9115, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-118', 'Extra — Zona Sul (Recife (populosas))', -8.0963, -34.8751, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-119', 'Carrefour — Zona Sul (Recife (populosas))', -8.0057, -34.837, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-120', 'Farmácia Droga Raia — Zona Sul (Recife (populosas))', -8.0412, -34.8598, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-121', 'Praça Cívica (Goiânia)', -16.6786, -49.2553, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-122', 'Flamboyant Shopping (Goiânia)', -16.713, -49.265, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-123', 'Outback Brasil — Goiânia', -16.6728, -49.2392, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-124', 'Madero — Goiânia', -16.6511, -49.2696, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-125', 'Cacau Show — Goiânia', -16.6896, -49.2424, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('br150-126', 'Praça Central — Centro (Goiânia)', -16.6547, -49.31, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-127', 'UBS — Centro (Goiânia)', -16.7314, -49.1954, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-128', 'Extra — Centro (Goiânia)', -16.7242, -49.197, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-129', 'Carrefour — Centro (Goiânia)', -16.668, -49.2487, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-130', 'Farmácia Droga Raia — Centro (Goiânia)', -16.7373, -49.3006, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-131', 'Farmácia Drogasil — Centro (Goiânia)', -16.7241, -49.2061, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-132', 'Posto Ipiranga — Centro (Goiânia)', -16.7321, -49.3027, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-133', 'Posto Shell — Centro (Goiânia)', -16.7109, -49.2403, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-134', 'Hotel — Centro (Goiânia)', -16.6974, -49.2939, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-135', 'Restaurante — Centro (Goiânia)', -16.6676, -49.2087, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-136', 'Praça Central — Zona Norte (Goiânia)', -16.6861, -49.2018, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-137', 'UBS — Zona Norte (Goiânia)', -16.6201, -49.2588, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-138', 'Extra — Zona Norte (Goiânia)', -16.6257, -49.2188, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-139', 'Carrefour — Zona Norte (Goiânia)', -16.6288, -49.2678, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-140', 'Farmácia Droga Raia — Zona Norte (Goiânia)', -16.7347, -49.2539, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-141', 'Farmácia Drogasil — Zona Norte (Goiânia)', -16.7271, -49.2126, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-142', 'Posto Ipiranga — Zona Norte (Goiânia)', -16.6903, -49.3022, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-143', 'Posto Shell — Zona Norte (Goiânia)', -16.7273, -49.2519, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-144', 'Hotel — Zona Norte (Goiânia)', -16.6971, -49.308, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-145', 'Restaurante — Zona Norte (Goiânia)', -16.7336, -49.2953, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-146', 'Praça Central — Zona Sul (Goiânia)', -16.713, -49.2667, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-147', 'UBS — Zona Sul (Goiânia)', -16.6472, -49.2457, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-148', 'Extra — Zona Sul (Goiânia)', -16.6664, -49.2752, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-149', 'Carrefour — Zona Sul (Goiânia)', -16.7074, -49.3001, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-150', 'Farmácia Droga Raia — Zona Sul (Goiânia)', -16.7031, -49.2678, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-151', 'Praia do Sancho (Fernando de Noronha)', -3.8536, -32.4297, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-152', 'Praça Central — Centro (Fernando de Noronha)', -3.8754, -32.4512, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-153', 'UBS — Centro (Fernando de Noronha)', -3.9057, -32.3854, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-154', 'Extra — Centro (Fernando de Noronha)', -3.8241, -32.4754, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-155', 'Carrefour — Centro (Fernando de Noronha)', -3.8259, -32.372, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-156', 'Farmácia Droga Raia — Centro (Fernando de Noronha)', -3.9073, -32.4665, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-157', 'Farmácia Drogasil — Centro (Fernando de Noronha)', -3.8078, -32.4316, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-158', 'Posto Ipiranga — Centro (Fernando de Noronha)', -3.9051, -32.4036, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-159', 'Posto Shell — Centro (Fernando de Noronha)', -3.8085, -32.4328, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-160', 'Hotel — Centro (Fernando de Noronha)', -3.7985, -32.4748, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-161', 'Restaurante — Centro (Fernando de Noronha)', -3.8221, -32.3866, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-162', 'Praça Central — Zona Norte (Fernando de Noronha)', -3.8864, -32.4141, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-163', 'UBS — Zona Norte (Fernando de Noronha)', -3.9049, -32.449, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-164', 'Extra — Zona Norte (Fernando de Noronha)', -3.8695, -32.4184, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-165', 'Carrefour — Zona Norte (Fernando de Noronha)', -3.8469, -32.4409, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-166', 'Torre de TV de Brasília', -15.7909, -47.8934, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-167', 'Praça Central — Centro (Brasília (turística))', -15.7888, -47.8495, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-168', 'UBS — Centro (Brasília (turística))', -15.8152, -47.9161, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-169', 'Extra — Centro (Brasília (turística))', -15.8078, -47.9372, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-170', 'Carrefour — Centro (Brasília (turística))', -15.744, -47.8302, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-171', 'Farmácia Droga Raia — Centro (Brasília (turística))', -15.8368, -47.9001, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-172', 'Farmácia Drogasil — Centro (Brasília (turística))', -15.8354, -47.8997, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-173', 'Posto Ipiranga — Centro (Brasília (turística))', -15.8352, -47.8981, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-174', 'Posto Shell — Centro (Brasília (turística))', -15.768, -47.9321, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-175', 'Hotel — Centro (Brasília (turística))', -15.7904, -47.9257, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-176', 'Restaurante — Centro (Brasília (turística))', -15.776, -47.8437, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-177', 'Praça Central — Zona Norte (Brasília (turística))', -15.7573, -47.8239, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-178', 'UBS — Zona Norte (Brasília (turística))', -15.8195, -47.8741, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-179', 'Extra — Zona Norte (Brasília (turística))', -15.7509, -47.9262, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-180', 'Carrefour — Zona Norte (Brasília (turística))', -15.8285, -47.8811, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-181', 'Cachoeira da Fumaça (Chapada Diamantina)', -12.56, -41.397, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-182', 'Praça Central — Centro (Chapada Diamantina (Lençóis))', -12.5315, -41.4491, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-183', 'UBS — Centro (Chapada Diamantina (Lençóis))', -12.5927, -41.361, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-184', 'Extra — Centro (Chapada Diamantina (Lençóis))', -12.5321, -41.3485, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-185', 'Carrefour — Centro (Chapada Diamantina (Lençóis))', -12.6043, -41.436, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-186', 'Farmácia Droga Raia — Centro (Chapada Diamantina (Lençóis))', -12.5941, -41.3598, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-187', 'Farmácia Drogasil — Centro (Chapada Diamantina (Lençóis))', -12.5573, -41.3772, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-188', 'Posto Ipiranga — Centro (Chapada Diamantina (Lençóis))', -12.5747, -41.3983, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-189', 'Posto Shell — Centro (Chapada Diamantina (Lençóis))', -12.5121, -41.3622, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-190', 'Hotel — Centro (Chapada Diamantina (Lençóis))', -12.5643, -41.4095, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-191', 'Restaurante — Centro (Chapada Diamantina (Lençóis))', -12.5853, -41.4556, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-192', 'Praça Central — Zona Norte (Chapada Diamantina (Lençóis))', -12.5834, -41.4364, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-193', 'UBS — Zona Norte (Chapada Diamantina (Lençóis))', -12.5188, -41.3946, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-194', 'Extra — Zona Norte (Chapada Diamantina (Lençóis))', -12.581, -41.3755, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-195', 'Carrefour — Zona Norte (Chapada Diamantina (Lençóis))', -12.5893, -41.3662, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-196', 'Dunas dos Lençóis Maranhenses', -2.75, -42.82, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-197', 'Praça Central — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7583, -42.7799, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-198', 'UBS — Centro (Lençóis Maranhenses (Barreirinhas))', -2.8015, -42.7954, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-199', 'Extra — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7363, -42.7722, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-200', 'Carrefour — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7346, -42.8212, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-201', 'Farmácia Droga Raia — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7794, -42.8041, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-202', 'Farmácia Drogasil — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7615, -42.8753, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-203', 'Posto Ipiranga — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7104, -42.7695, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-204', 'Posto Shell — Centro (Lençóis Maranhenses (Barreirinhas))', -2.754, -42.8531, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-205', 'Hotel — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7827, -42.7931, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-206', 'Restaurante — Centro (Lençóis Maranhenses (Barreirinhas))', -2.7306, -42.8391, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-207', 'Praça Central — Zona Norte (Lençóis Maranhenses (Barreirinhas))', -2.7758, -42.8327, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-208', 'UBS — Zona Norte (Lençóis Maranhenses (Barreirinhas))', -2.6962, -42.8787, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-209', 'Extra — Zona Norte (Lençóis Maranhenses (Barreirinhas))', -2.7604, -42.8395, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-210', 'Carrefour — Zona Norte (Lençóis Maranhenses (Barreirinhas))', -2.7782, -42.8536, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-211', 'Igreja São Francisco de Assis (Ouro Preto)', -20.385, -43.504, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-212', 'Praça Central — Centro (Ouro Preto e Tiradentes)', -20.4206, -43.5071, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-213', 'UBS — Centro (Ouro Preto e Tiradentes)', -20.3505, -43.4822, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-214', 'Extra — Centro (Ouro Preto e Tiradentes)', -20.425, -43.4977, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-215', 'Carrefour — Centro (Ouro Preto e Tiradentes)', -20.3869, -43.5499, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-216', 'Farmácia Droga Raia — Centro (Ouro Preto e Tiradentes)', -20.3701, -43.4524, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-217', 'Farmácia Drogasil — Centro (Ouro Preto e Tiradentes)', -20.3968, -43.5324, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-218', 'Posto Ipiranga — Centro (Ouro Preto e Tiradentes)', -20.3971, -43.4913, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-219', 'Posto Shell — Centro (Ouro Preto e Tiradentes)', -20.3482, -43.5576, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-220', 'Hotel — Centro (Ouro Preto e Tiradentes)', -20.4157, -43.5416, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-221', 'Restaurante — Centro (Ouro Preto e Tiradentes)', -20.4074, -43.4983, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-222', 'Praça Central — Zona Norte (Ouro Preto e Tiradentes)', -20.3467, -43.4528, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-223', 'UBS — Zona Norte (Ouro Preto e Tiradentes)', -20.3458, -43.5163, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-224', 'Extra — Zona Norte (Ouro Preto e Tiradentes)', -20.3636, -43.5625, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('br150-225', 'Carrefour — Zona Norte (Ouro Preto e Tiradentes)', -20.4043, -43.5025, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
