-- ============================================
-- Achou Trocador — Colômbia: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('co150-001', 'Parque Santander (Bucaramanga)', 7.1254, -73.1198, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-002', 'McDonald''s — Bucaramanga', 7.152, -73.1286, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-003', 'Burger King — Bucaramanga', 7.1199, -73.1317, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-004', 'KFC — Bucaramanga', 7.0989, -73.1161, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-005', 'Plaza Central — Centro (Bucaramanga)', 7.0669, -73.1206, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-006', 'Centro de Salud — Centro (Bucaramanga)', 7.1785, -73.1044, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-007', 'Éxito — Centro (Bucaramanga)', 7.1618, -73.0647, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-008', 'Carulla — Centro (Bucaramanga)', 7.0828, -73.1057, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-009', 'Farmacia La Rebaja — Centro (Bucaramanga)', 7.0967, -73.1574, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-010', 'Farmacia Cruz Verde — Centro (Bucaramanga)', 7.1252, -73.1626, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-011', 'Estación Terpel — Centro (Bucaramanga)', 7.1496, -73.0917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-012', 'Estación Primax — Centro (Bucaramanga)', 7.1627, -73.1466, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-013', 'Hotel — Centro (Bucaramanga)', 7.0974, -73.1723, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-014', 'Restaurante — Centro (Bucaramanga)', 7.1214, -73.1271, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-015', 'Plaza Central — Zona Norte (Bucaramanga)', 7.1164, -73.0834, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-016', 'Centro de Salud — Zona Norte (Bucaramanga)', 7.098, -73.1599, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-017', 'Éxito — Zona Norte (Bucaramanga)', 7.0903, -73.128, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-018', 'Carulla — Zona Norte (Bucaramanga)', 7.1223, -73.1271, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-019', 'Farmacia La Rebaja — Zona Norte (Bucaramanga)', 7.1369, -73.1696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-020', 'Farmacia Cruz Verde — Zona Norte (Bucaramanga)', 7.0764, -73.1351, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-021', 'Estación Terpel — Zona Norte (Bucaramanga)', 7.18, -73.0767, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-022', 'Estación Primax — Zona Norte (Bucaramanga)', 7.1566, -73.145, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-023', 'Hotel — Zona Norte (Bucaramanga)', 7.1184, -73.085, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-024', 'Restaurante — Zona Norte (Bucaramanga)', 7.1828, -73.1325, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-025', 'Plaza Central — Zona Sur (Bucaramanga)', 7.0814, -73.1377, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-026', 'Centro de Salud — Zona Sur (Bucaramanga)', 7.0861, -73.116, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-027', 'Éxito — Zona Sur (Bucaramanga)', 7.1364, -73.1756, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-028', 'Carulla — Zona Sur (Bucaramanga)', 7.0906, -73.1596, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-029', 'Farmacia La Rebaja — Zona Sur (Bucaramanga)', 7.0807, -73.1279, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-030', 'Farmacia Cruz Verde — Zona Sur (Bucaramanga)', 7.1129, -73.1298, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-031', 'Parque Los Fundadores (Villavicencio)', 4.142, -73.6266, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-032', 'Subway — Villavicencio', 4.1225, -73.6169, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-033', 'Pizza Hut — Villavicencio', 4.1654, -73.6222, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-034', 'Starbucks — Villavicencio', 4.1223, -73.6458, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-035', 'Plaza Central — Centro (Villavicencio)', 4.1528, -73.5693, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-036', 'Centro de Salud — Centro (Villavicencio)', 4.102, -73.5864, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-037', 'Éxito — Centro (Villavicencio)', 4.1084, -73.664, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-038', 'Carulla — Centro (Villavicencio)', 4.1744, -73.666, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-039', 'Farmacia La Rebaja — Centro (Villavicencio)', 4.1498, -73.5974, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-040', 'Farmacia Cruz Verde — Centro (Villavicencio)', 4.1407, -73.642, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-041', 'Estación Terpel — Centro (Villavicencio)', 4.0853, -73.5711, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-042', 'Estación Primax — Centro (Villavicencio)', 4.0972, -73.5967, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-043', 'Hotel — Centro (Villavicencio)', 4.1564, -73.6687, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-044', 'Restaurante — Centro (Villavicencio)', 4.1037, -73.6277, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-045', 'Plaza Central — Zona Norte (Villavicencio)', 4.1025, -73.6404, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-046', 'Centro de Salud — Zona Norte (Villavicencio)', 4.1205, -73.6183, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-047', 'Éxito — Zona Norte (Villavicencio)', 4.1047, -73.6749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-048', 'Carulla — Zona Norte (Villavicencio)', 4.1657, -73.6605, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-049', 'Farmacia La Rebaja — Zona Norte (Villavicencio)', 4.1212, -73.635, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-050', 'Farmacia Cruz Verde — Zona Norte (Villavicencio)', 4.1776, -73.6017, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-051', 'Estación Terpel — Zona Norte (Villavicencio)', 4.1893, -73.6556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-052', 'Estación Primax — Zona Norte (Villavicencio)', 4.0825, -73.5836, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-053', 'Hotel — Zona Norte (Villavicencio)', 4.0913, -73.6416, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-054', 'Restaurante — Zona Norte (Villavicencio)', 4.1961, -73.6522, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-055', 'Plaza Central — Zona Sur (Villavicencio)', 4.0859, -73.5781, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-056', 'Centro de Salud — Zona Sur (Villavicencio)', 4.1336, -73.6433, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-057', 'Éxito — Zona Sur (Villavicencio)', 4.1581, -73.6525, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-058', 'Carulla — Zona Sur (Villavicencio)', 4.1707, -73.5765, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-059', 'Farmacia La Rebaja — Zona Sur (Villavicencio)', 4.0854, -73.6108, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-060', 'Farmacia Cruz Verde — Zona Sur (Villavicencio)', 4.1675, -73.6478, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-061', 'Parque Principal de Bello', 6.3373, -75.5581, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-062', 'Domino''s Pizza — Bello', 6.3421, -75.5561, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-063', 'Frisby — Bello', 6.3338, -75.5537, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-064', 'El Corral — Bello', 6.3222, -75.5334, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-065', 'Plaza Central — Centro (Bello)', 6.3859, -75.5529, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-066', 'Centro de Salud — Centro (Bello)', 6.3939, -75.6047, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-067', 'Éxito — Centro (Bello)', 6.3736, -75.6104, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-068', 'Carulla — Centro (Bello)', 6.3711, -75.5667, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-069', 'Farmacia La Rebaja — Centro (Bello)', 6.3082, -75.5362, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-070', 'Farmacia Cruz Verde — Centro (Bello)', 6.3438, -75.5181, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-071', 'Estación Terpel — Centro (Bello)', 6.3848, -75.5567, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-072', 'Estación Primax — Centro (Bello)', 6.3857, -75.545, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-073', 'Hotel — Centro (Bello)', 6.3768, -75.5247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-074', 'Restaurante — Centro (Bello)', 6.3888, -75.5676, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-075', 'Plaza Central — Zona Norte (Bello)', 6.3876, -75.6163, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-076', 'Centro de Salud — Zona Norte (Bello)', 6.2848, -75.549, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-077', 'Éxito — Zona Norte (Bello)', 6.3924, -75.5183, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-078', 'Carulla — Zona Norte (Bello)', 6.3628, -75.5046, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-079', 'Farmacia La Rebaja — Zona Norte (Bello)', 6.39, -75.5811, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-080', 'Farmacia Cruz Verde — Zona Norte (Bello)', 6.2851, -75.6059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-081', 'Estación Terpel — Zona Norte (Bello)', 6.3199, -75.5595, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-082', 'Estación Primax — Zona Norte (Bello)', 6.3664, -75.5884, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-083', 'Hotel — Zona Norte (Bello)', 6.3532, -75.602, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-084', 'Restaurante — Zona Norte (Bello)', 6.2856, -75.5379, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-085', 'Plaza Central — Zona Sur (Bello)', 6.3194, -75.5495, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-086', 'Centro de Salud — Zona Sur (Bello)', 6.3668, -75.5157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-087', 'Éxito — Zona Sur (Bello)', 6.3505, -75.5177, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-088', 'Carulla — Zona Sur (Bello)', 6.391, -75.5171, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-089', 'Farmacia La Rebaja — Zona Sur (Bello)', 6.3433, -75.5576, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-090', 'Farmacia Cruz Verde — Zona Sur (Bello)', 6.3764, -75.5296, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-091', 'Plaza de Bolívar de Ibagué', 4.4389, -75.2322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-092', 'Crepes & Waffles — Ibagué', 4.452, -75.2323, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-093', 'Presto — Ibagué', 4.4156, -75.2606, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-094', 'Kokoriko — Ibagué', 4.443, -75.2263, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-095', 'Plaza Central — Centro (Ibagué)', 4.4129, -75.2197, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-096', 'Centro de Salud — Centro (Ibagué)', 4.4089, -75.2831, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-097', 'Éxito — Centro (Ibagué)', 4.4148, -75.2657, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-098', 'Carulla — Centro (Ibagué)', 4.454, -75.2663, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-099', 'Farmacia La Rebaja — Centro (Ibagué)', 4.4248, -75.2242, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-100', 'Farmacia Cruz Verde — Centro (Ibagué)', 4.4323, -75.2539, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-101', 'Estación Terpel — Centro (Ibagué)', 4.4982, -75.2421, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-102', 'Estación Primax — Centro (Ibagué)', 4.4181, -75.1787, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-103', 'Hotel — Centro (Ibagué)', 4.3958, -75.2368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-104', 'Restaurante — Centro (Ibagué)', 4.4108, -75.2059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-105', 'Plaza Central — Zona Norte (Ibagué)', 4.3803, -75.2223, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-106', 'Centro de Salud — Zona Norte (Ibagué)', 4.497, -75.232, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-107', 'Éxito — Zona Norte (Ibagué)', 4.4668, -75.2479, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-108', 'Carulla — Zona Norte (Ibagué)', 4.4415, -75.2497, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-109', 'Farmacia La Rebaja — Zona Norte (Ibagué)', 4.4314, -75.1953, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-110', 'Farmacia Cruz Verde — Zona Norte (Ibagué)', 4.3954, -75.2528, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-111', 'Estación Terpel — Zona Norte (Ibagué)', 4.4429, -75.2534, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-112', 'Estación Primax — Zona Norte (Ibagué)', 4.4716, -75.2831, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-113', 'Hotel — Zona Norte (Ibagué)', 4.4414, -75.1751, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-114', 'Restaurante — Zona Norte (Ibagué)', 4.4635, -75.2608, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-115', 'Plaza Central — Zona Sur (Ibagué)', 4.4563, -75.2443, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-116', 'Centro de Salud — Zona Sur (Ibagué)', 4.4049, -75.2328, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-117', 'Éxito — Zona Sur (Ibagué)', 4.4223, -75.243, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-118', 'Carulla — Zona Sur (Ibagué)', 4.463, -75.2733, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-119', 'Farmacia La Rebaja — Zona Sur (Ibagué)', 4.4567, -75.2148, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-120', 'Farmacia Cruz Verde — Zona Sur (Ibagué)', 4.4438, -75.2777, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-121', 'Plaza de Bolívar de Pereira', 4.8087, -75.6906, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-122', 'Juan Valdez Café — Pereira', 4.8087, -75.6805, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-123', 'Wok — Pereira', 4.7805, -75.6752, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-124', 'Andrés Carne de Res — Pereira', 4.8274, -75.7106, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('co150-125', 'Plaza Central — Centro (Pereira)', 4.7855, -75.7255, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-126', 'Centro de Salud — Centro (Pereira)', 4.7576, -75.6772, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-127', 'Éxito — Centro (Pereira)', 4.858, -75.6399, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-128', 'Carulla — Centro (Pereira)', 4.7753, -75.7472, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-129', 'Farmacia La Rebaja — Centro (Pereira)', 4.7816, -75.6965, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-130', 'Farmacia Cruz Verde — Centro (Pereira)', 4.795, -75.6698, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-131', 'Estación Terpel — Centro (Pereira)', 4.8426, -75.6883, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-132', 'Estación Primax — Centro (Pereira)', 4.7972, -75.6826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-133', 'Hotel — Centro (Pereira)', 4.8132, -75.7136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-134', 'Restaurante — Centro (Pereira)', 4.8442, -75.6671, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-135', 'Plaza Central — Zona Norte (Pereira)', 4.7577, -75.6989, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-136', 'Centro de Salud — Zona Norte (Pereira)', 4.7568, -75.6513, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-137', 'Éxito — Zona Norte (Pereira)', 4.8269, -75.6724, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-138', 'Carulla — Zona Norte (Pereira)', 4.7542, -75.6411, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-139', 'Farmacia La Rebaja — Zona Norte (Pereira)', 4.7998, -75.6744, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-140', 'Farmacia Cruz Verde — Zona Norte (Pereira)', 4.7995, -75.7233, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-141', 'Estación Terpel — Zona Norte (Pereira)', 4.8657, -75.728, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-142', 'Estación Primax — Zona Norte (Pereira)', 4.8187, -75.6479, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-143', 'Hotel — Zona Norte (Pereira)', 4.792, -75.7175, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-144', 'Restaurante — Zona Norte (Pereira)', 4.7971, -75.6594, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-145', 'Plaza Central — Zona Sur (Pereira)', 4.81, -75.6631, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-146', 'Centro de Salud — Zona Sur (Pereira)', 4.8597, -75.7086, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-147', 'Éxito — Zona Sur (Pereira)', 4.8013, -75.737, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-148', 'Carulla — Zona Sur (Pereira)', 4.8082, -75.6352, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-149', 'Farmacia La Rebaja — Zona Sur (Pereira)', 4.7822, -75.7041, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-150', 'Farmacia Cruz Verde — Zona Sur (Pereira)', 4.7842, -75.7301, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-151', 'Playa Spratt Bight (San Andrés)', 12.5847, -81.7006, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-152', 'Plaza Central — Centro (San Andrés (ilha))', 12.5423, -81.643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-153', 'Centro de Salud — Centro (San Andrés (ilha))', 12.637, -81.7383, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-154', 'Éxito — Centro (San Andrés (ilha))', 12.625, -81.6949, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-155', 'Carulla — Centro (San Andrés (ilha))', 12.5401, -81.6425, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-156', 'Farmacia La Rebaja — Centro (San Andrés (ilha))', 12.6233, -81.7579, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-157', 'Farmacia Cruz Verde — Centro (San Andrés (ilha))', 12.5436, -81.7165, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-158', 'Estación Terpel — Centro (San Andrés (ilha))', 12.5997, -81.669, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-159', 'Estación Primax — Centro (San Andrés (ilha))', 12.6212, -81.7073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-160', 'Hotel — Centro (San Andrés (ilha))', 12.5323, -81.7022, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-161', 'Restaurante — Centro (San Andrés (ilha))', 12.5867, -81.7014, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-162', 'Plaza Central — Zona Norte (San Andrés (ilha))', 12.5551, -81.6916, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-163', 'Centro de Salud — Zona Norte (San Andrés (ilha))', 12.6401, -81.6678, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-164', 'Éxito — Zona Norte (San Andrés (ilha))', 12.5391, -81.6893, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-165', 'Carulla — Zona Norte (San Andrés (ilha))', 12.5896, -81.6524, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-166', 'El Peñol (Guatapé)', 6.22, -75.17, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-167', 'Plaza Central — Centro (Guatapé)', 6.2136, -75.1612, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-168', 'Centro de Salud — Centro (Guatapé)', 6.2216, -75.2186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-169', 'Éxito — Centro (Guatapé)', 6.2169, -75.1042, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-170', 'Carulla — Centro (Guatapé)', 6.2072, -75.1565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-171', 'Farmacia La Rebaja — Centro (Guatapé)', 6.2816, -75.1328, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-172', 'Farmacia Cruz Verde — Centro (Guatapé)', 6.2519, -75.1386, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-173', 'Estación Terpel — Centro (Guatapé)', 6.2568, -75.136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-174', 'Estación Primax — Centro (Guatapé)', 6.2215, -75.2129, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-175', 'Hotel — Centro (Guatapé)', 6.2377, -75.1607, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-176', 'Restaurante — Centro (Guatapé)', 6.2129, -75.2116, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-177', 'Plaza Central — Zona Norte (Guatapé)', 6.2793, -75.1886, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-178', 'Centro de Salud — Zona Norte (Guatapé)', 6.2087, -75.1578, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-179', 'Éxito — Zona Norte (Guatapé)', 6.1803, -75.1657, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-180', 'Carulla — Zona Norte (Guatapé)', 6.2347, -75.1082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-181', 'Plaza Mayor de Villa de Leyva', 5.6333, -73.525, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-182', 'Plaza Central — Centro (Villa de Leyva)', 5.6222, -73.5516, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-183', 'Centro de Salud — Centro (Villa de Leyva)', 5.6718, -73.5683, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-184', 'Éxito — Centro (Villa de Leyva)', 5.5819, -73.5747, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-185', 'Carulla — Centro (Villa de Leyva)', 5.5938, -73.5685, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-186', 'Farmacia La Rebaja — Centro (Villa de Leyva)', 5.5799, -73.493, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-187', 'Farmacia Cruz Verde — Centro (Villa de Leyva)', 5.6281, -73.5812, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-188', 'Estación Terpel — Centro (Villa de Leyva)', 5.637, -73.528, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-189', 'Estación Primax — Centro (Villa de Leyva)', 5.6323, -73.5242, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-190', 'Hotel — Centro (Villa de Leyva)', 5.6929, -73.5445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-191', 'Restaurante — Centro (Villa de Leyva)', 5.6095, -73.528, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-192', 'Plaza Central — Zona Norte (Villa de Leyva)', 5.5838, -73.5717, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-193', 'Centro de Salud — Zona Norte (Villa de Leyva)', 5.6861, -73.5388, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-194', 'Éxito — Zona Norte (Villa de Leyva)', 5.6805, -73.5635, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-195', 'Carulla — Zona Norte (Villa de Leyva)', 5.6467, -73.4962, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-196', 'Parque El Gallineral (San Gil)', 6.554, -73.133, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-197', 'Plaza Central — Centro (San Gil e Barichara)', 6.6139, -73.1701, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-198', 'Centro de Salud — Centro (San Gil e Barichara)', 6.5475, -73.0785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-199', 'Éxito — Centro (San Gil e Barichara)', 6.5987, -73.1593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-200', 'Carulla — Centro (San Gil e Barichara)', 6.5861, -73.0748, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-201', 'Farmacia La Rebaja — Centro (San Gil e Barichara)', 6.527, -73.1547, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-202', 'Farmacia Cruz Verde — Centro (San Gil e Barichara)', 6.5083, -73.1541, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-203', 'Estación Terpel — Centro (San Gil e Barichara)', 6.519, -73.1168, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-204', 'Estación Primax — Centro (San Gil e Barichara)', 6.5484, -73.1445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-205', 'Hotel — Centro (San Gil e Barichara)', 6.5517, -73.0968, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-206', 'Restaurante — Centro (San Gil e Barichara)', 6.5776, -73.1563, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-207', 'Plaza Central — Zona Norte (San Gil e Barichara)', 6.5031, -73.0763, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-208', 'Centro de Salud — Zona Norte (San Gil e Barichara)', 6.5174, -73.1661, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-209', 'Éxito — Zona Norte (San Gil e Barichara)', 6.5138, -73.1023, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-210', 'Carulla — Zona Norte (San Gil e Barichara)', 6.5384, -73.0747, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-211', 'Malecón de Leticia (Amazonas)', -4.2153, -69.9406, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-212', 'Plaza Central — Centro (Leticia)', -4.1623, -69.893, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-213', 'Centro de Salud — Centro (Leticia)', -4.1685, -69.942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-214', 'Éxito — Centro (Leticia)', -4.2615, -69.9798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-215', 'Carulla — Centro (Leticia)', -4.2216, -69.9704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-216', 'Farmacia La Rebaja — Centro (Leticia)', -4.1716, -69.999, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-217', 'Farmacia Cruz Verde — Centro (Leticia)', -4.2486, -69.9959, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-218', 'Estación Terpel — Centro (Leticia)', -4.1818, -69.9671, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-219', 'Estación Primax — Centro (Leticia)', -4.2129, -69.9635, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-220', 'Hotel — Centro (Leticia)', -4.1636, -69.9013, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-221', 'Restaurante — Centro (Leticia)', -4.1757, -69.8858, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-222', 'Plaza Central — Zona Norte (Leticia)', -4.1757, -69.977, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-223', 'Centro de Salud — Zona Norte (Leticia)', -4.2061, -69.8949, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-224', 'Éxito — Zona Norte (Leticia)', -4.2139, -69.909, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('co150-225', 'Carulla — Zona Norte (Leticia)', -4.165, -69.9885, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
