-- ============================================
-- Achou Trocador — Equador: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('ec150-001', 'Parque Zaracay (Santo Domingo)', -0.253, -79.175, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-002', 'McDonald''s — Santo Domingo (Equador)', -0.2656, -79.168, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-003', 'Burger King — Santo Domingo (Equador)', -0.263, -79.1765, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-004', 'KFC — Santo Domingo (Equador)', -0.2307, -79.1505, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-005', 'Plaza Central — Centro (Santo Domingo (Equador))', -0.27, -79.1233, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-006', 'Centro de Salud — Centro (Santo Domingo (Equador))', -0.2395, -79.2279, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-007', 'Supermaxi — Centro (Santo Domingo (Equador))', -0.2563, -79.2261, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-008', 'Mi Comisariato — Centro (Santo Domingo (Equador))', -0.1935, -79.1917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-009', 'Farmacia Fybeca — Centro (Santo Domingo (Equador))', -0.2483, -79.142, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-010', 'Farmacia Sana Sana — Centro (Santo Domingo (Equador))', -0.2705, -79.1654, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-011', 'Estación Petroecuador — Centro (Santo Domingo (Equador))', -0.2615, -79.1962, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-012', 'Estación Primax — Centro (Santo Domingo (Equador))', -0.3018, -79.1368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-013', 'Hotel — Centro (Santo Domingo (Equador))', -0.2517, -79.2289, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-014', 'Restaurante — Centro (Santo Domingo (Equador))', -0.1956, -79.1597, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-015', 'Plaza Central — Zona Norte (Santo Domingo (Equador))', -0.2586, -79.1975, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-016', 'Centro de Salud — Zona Norte (Santo Domingo (Equador))', -0.2668, -79.1308, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-017', 'Supermaxi — Zona Norte (Santo Domingo (Equador))', -0.1974, -79.1811, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-018', 'Mi Comisariato — Zona Norte (Santo Domingo (Equador))', -0.2916, -79.2147, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-019', 'Farmacia Fybeca — Zona Norte (Santo Domingo (Equador))', -0.2113, -79.1724, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-020', 'Farmacia Sana Sana — Zona Norte (Santo Domingo (Equador))', -0.2503, -79.2073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-021', 'Estación Petroecuador — Zona Norte (Santo Domingo (Equador))', -0.2008, -79.2146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-022', 'Estación Primax — Zona Norte (Santo Domingo (Equador))', -0.265, -79.1938, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-023', 'Hotel — Zona Norte (Santo Domingo (Equador))', -0.2394, -79.231, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-024', 'Restaurante — Zona Norte (Santo Domingo (Equador))', -0.2424, -79.2145, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-025', 'Plaza Central — Zona Sur (Santo Domingo (Equador))', -0.2847, -79.1386, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-026', 'Centro de Salud — Zona Sur (Santo Domingo (Equador))', -0.2879, -79.1399, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-027', 'Supermaxi — Zona Sur (Santo Domingo (Equador))', -0.2721, -79.1378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-028', 'Mi Comisariato — Zona Sur (Santo Domingo (Equador))', -0.2269, -79.2346, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-029', 'Farmacia Fybeca — Zona Sur (Santo Domingo (Equador))', -0.262, -79.1258, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-030', 'Farmacia Sana Sana — Zona Sur (Santo Domingo (Equador))', -0.2977, -79.1378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-031', 'Parque Juan Montalvo (Machala)', -3.2581, -79.9553, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-032', 'Subway — Machala', -3.2837, -79.9384, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-033', 'Pizza Hut — Machala', -3.2315, -79.9624, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-034', 'Starbucks — Machala', -3.2779, -79.9463, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-035', 'Plaza Central — Centro (Machala)', -3.2737, -79.9873, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-036', 'Centro de Salud — Centro (Machala)', -3.2786, -79.9482, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-037', 'Supermaxi — Centro (Machala)', -3.2895, -79.9837, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-038', 'Mi Comisariato — Centro (Machala)', -3.2583, -79.9783, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-039', 'Farmacia Fybeca — Centro (Machala)', -3.2761, -79.9432, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-040', 'Farmacia Sana Sana — Centro (Machala)', -3.21, -79.977, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-041', 'Estación Petroecuador — Centro (Machala)', -3.2058, -79.9278, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-042', 'Estación Primax — Centro (Machala)', -3.2748, -79.9391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-043', 'Hotel — Centro (Machala)', -3.2298, -79.9128, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-044', 'Restaurante — Centro (Machala)', -3.2465, -79.9018, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-045', 'Plaza Central — Zona Norte (Machala)', -3.2533, -79.9596, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-046', 'Centro de Salud — Zona Norte (Machala)', -3.2271, -79.992, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-047', 'Supermaxi — Zona Norte (Machala)', -3.2693, -79.9394, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-048', 'Mi Comisariato — Zona Norte (Machala)', -3.2352, -79.9621, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-049', 'Farmacia Fybeca — Zona Norte (Machala)', -3.3168, -79.9857, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-050', 'Farmacia Sana Sana — Zona Norte (Machala)', -3.2744, -79.912, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-051', 'Estación Petroecuador — Zona Norte (Machala)', -3.2685, -80.0144, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-052', 'Estación Primax — Zona Norte (Machala)', -3.2588, -79.9239, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-053', 'Hotel — Zona Norte (Machala)', -3.3118, -79.9272, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-054', 'Restaurante — Zona Norte (Machala)', -3.3045, -79.9334, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-055', 'Plaza Central — Zona Sur (Machala)', -3.2406, -79.9892, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-056', 'Centro de Salud — Zona Sur (Machala)', -3.2282, -79.9359, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-057', 'Supermaxi — Zona Sur (Machala)', -3.2694, -79.9979, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-058', 'Mi Comisariato — Zona Sur (Machala)', -3.2895, -79.9185, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-059', 'Farmacia Fybeca — Zona Sur (Machala)', -3.221, -79.93, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-060', 'Farmacia Sana Sana — Zona Sur (Machala)', -3.2224, -79.9585, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-061', 'Malecón Escénico de Manta', -0.95, -80.7333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-062', 'Domino''s Pizza — Manta', -0.9755, -80.7551, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-063', 'Sweet & Coffee — Manta', -0.9384, -80.7543, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-064', 'Juan Valdez Café — Manta', -0.9316, -80.7207, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-065', 'Plaza Central — Centro (Manta)', -0.9271, -80.7388, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-066', 'Centro de Salud — Centro (Manta)', -0.9227, -80.7368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-067', 'Supermaxi — Centro (Manta)', -1.0068, -80.7923, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-068', 'Mi Comisariato — Centro (Manta)', -1.0042, -80.7472, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-069', 'Farmacia Fybeca — Centro (Manta)', -0.9912, -80.7372, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-070', 'Farmacia Sana Sana — Centro (Manta)', -0.9942, -80.7604, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-071', 'Estación Petroecuador — Centro (Manta)', -0.9767, -80.7742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-072', 'Estación Primax — Centro (Manta)', -0.9746, -80.7661, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-073', 'Hotel — Centro (Manta)', -0.9338, -80.7004, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-074', 'Restaurante — Centro (Manta)', -0.978, -80.779, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-075', 'Plaza Central — Zona Norte (Manta)', -0.9752, -80.7102, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-076', 'Centro de Salud — Zona Norte (Manta)', -0.9512, -80.7447, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-077', 'Supermaxi — Zona Norte (Manta)', -0.9769, -80.7117, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-078', 'Mi Comisariato — Zona Norte (Manta)', -0.9898, -80.6792, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-079', 'Farmacia Fybeca — Zona Norte (Manta)', -0.9977, -80.7547, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-080', 'Farmacia Sana Sana — Zona Norte (Manta)', -0.9026, -80.7458, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-081', 'Estación Petroecuador — Zona Norte (Manta)', -0.9325, -80.7352, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-082', 'Estación Primax — Zona Norte (Manta)', -0.9563, -80.6981, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-083', 'Hotel — Zona Norte (Manta)', -0.9307, -80.6967, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-084', 'Restaurante — Zona Norte (Manta)', -0.895, -80.7908, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-085', 'Plaza Central — Zona Sur (Manta)', -0.9425, -80.6834, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-086', 'Centro de Salud — Zona Sur (Manta)', -0.9995, -80.6811, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-087', 'Supermaxi — Zona Sur (Manta)', -0.9211, -80.7286, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-088', 'Mi Comisariato — Zona Sur (Manta)', -0.9409, -80.77, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-089', 'Farmacia Fybeca — Zona Sur (Manta)', -0.9837, -80.7744, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-090', 'Farmacia Sana Sana — Zona Sur (Manta)', -0.9385, -80.7898, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-091', 'Catedral de Portoviejo', -1.0546, -80.4525, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-092', 'El Español — Portoviejo', -1.0465, -80.4588, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-093', 'Noe Sushi Bar — Portoviejo', -1.0312, -80.4778, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-094', 'D''Rose — Portoviejo', -1.0439, -80.4352, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-095', 'Plaza Central — Centro (Portoviejo)', -1.0013, -80.4554, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-096', 'Centro de Salud — Centro (Portoviejo)', -1.0423, -80.4856, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-097', 'Supermaxi — Centro (Portoviejo)', -1.1043, -80.4714, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-098', 'Mi Comisariato — Centro (Portoviejo)', -1.1112, -80.3946, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-099', 'Farmacia Fybeca — Centro (Portoviejo)', -1.0679, -80.4982, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-100', 'Farmacia Sana Sana — Centro (Portoviejo)', -1.0431, -80.4068, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-101', 'Estación Petroecuador — Centro (Portoviejo)', -0.9981, -80.476, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-102', 'Estación Primax — Centro (Portoviejo)', -1.0824, -80.4586, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-103', 'Hotel — Centro (Portoviejo)', -1.0602, -80.4512, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-104', 'Restaurante — Centro (Portoviejo)', -1.0547, -80.452, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-105', 'Plaza Central — Zona Norte (Portoviejo)', -1.0347, -80.4017, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-106', 'Centro de Salud — Zona Norte (Portoviejo)', -1.0587, -80.458, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-107', 'Supermaxi — Zona Norte (Portoviejo)', -1.0628, -80.505, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-108', 'Mi Comisariato — Zona Norte (Portoviejo)', -1.0056, -80.4066, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-109', 'Farmacia Fybeca — Zona Norte (Portoviejo)', -1.0917, -80.4748, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-110', 'Farmacia Sana Sana — Zona Norte (Portoviejo)', -1.0299, -80.4623, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-111', 'Estación Petroecuador — Zona Norte (Portoviejo)', -1.0303, -80.5073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-112', 'Estación Primax — Zona Norte (Portoviejo)', -1.0623, -80.4467, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-113', 'Hotel — Zona Norte (Portoviejo)', -1.0021, -80.4724, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-114', 'Restaurante — Zona Norte (Portoviejo)', -1.0252, -80.4792, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-115', 'Plaza Central — Zona Sur (Portoviejo)', -1.0751, -80.4786, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-116', 'Centro de Salud — Zona Sur (Portoviejo)', -1.0575, -80.49, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-117', 'Supermaxi — Zona Sur (Portoviejo)', -1.0387, -80.4575, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-118', 'Mi Comisariato — Zona Sur (Portoviejo)', -1.023, -80.4216, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-119', 'Farmacia Fybeca — Zona Sur (Portoviejo)', -1.064, -80.4322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-120', 'Farmacia Sana Sana — Zona Sur (Portoviejo)', -1.0323, -80.4898, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-121', 'Parque Montalvo (Ambato)', -1.2417, -78.6197, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-122', 'Menestras del Negro — Ambato', -1.2289, -78.6389, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-123', 'La Choza — Ambato', -1.2174, -78.6123, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-124', 'Mall Food Court — Ambato', -1.2118, -78.6172, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ec150-125', 'Plaza Central — Centro (Ambato)', -1.1863, -78.5859, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-126', 'Centro de Salud — Centro (Ambato)', -1.2709, -78.6683, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-127', 'Supermaxi — Centro (Ambato)', -1.1903, -78.6652, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-128', 'Mi Comisariato — Centro (Ambato)', -1.241, -78.5805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-129', 'Farmacia Fybeca — Centro (Ambato)', -1.2764, -78.6225, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-130', 'Farmacia Sana Sana — Centro (Ambato)', -1.2796, -78.6734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-131', 'Estación Petroecuador — Centro (Ambato)', -1.2644, -78.5996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-132', 'Estación Primax — Centro (Ambato)', -1.1933, -78.6425, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-133', 'Hotel — Centro (Ambato)', -1.2883, -78.6537, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-134', 'Restaurante — Centro (Ambato)', -1.2893, -78.5996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-135', 'Plaza Central — Zona Norte (Ambato)', -1.2439, -78.6237, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-136', 'Centro de Salud — Zona Norte (Ambato)', -1.2168, -78.6452, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-137', 'Supermaxi — Zona Norte (Ambato)', -1.2184, -78.6002, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-138', 'Mi Comisariato — Zona Norte (Ambato)', -1.1834, -78.6022, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-139', 'Farmacia Fybeca — Zona Norte (Ambato)', -1.2916, -78.652, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-140', 'Farmacia Sana Sana — Zona Norte (Ambato)', -1.2109, -78.6376, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-141', 'Estación Petroecuador — Zona Norte (Ambato)', -1.2058, -78.5734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-142', 'Estación Primax — Zona Norte (Ambato)', -1.1878, -78.5975, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-143', 'Hotel — Zona Norte (Ambato)', -1.2568, -78.6042, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-144', 'Restaurante — Zona Norte (Ambato)', -1.2146, -78.5981, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-145', 'Plaza Central — Zona Sur (Ambato)', -1.2626, -78.6269, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-146', 'Centro de Salud — Zona Sur (Ambato)', -1.2114, -78.6643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-147', 'Supermaxi — Zona Sur (Ambato)', -1.2519, -78.6749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-148', 'Mi Comisariato — Zona Sur (Ambato)', -1.1883, -78.663, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-149', 'Farmacia Fybeca — Zona Sur (Ambato)', -1.2229, -78.6586, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-150', 'Farmacia Sana Sana — Zona Sur (Ambato)', -1.2549, -78.6574, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-151', 'Estação Charles Darwin (Galápagos)', -0.742, -90.303, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-152', 'Plaza Central — Centro (Galápagos (Puerto Ayora))', -0.7277, -90.3868, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-153', 'Centro de Salud — Centro (Galápagos (Puerto Ayora))', -0.7457, -90.3606, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-154', 'Supermaxi — Centro (Galápagos (Puerto Ayora))', -0.6912, -90.3385, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-155', 'Mi Comisariato — Centro (Galápagos (Puerto Ayora))', -0.7906, -90.3665, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-156', 'Farmacia Fybeca — Centro (Galápagos (Puerto Ayora))', -0.7205, -90.3202, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-157', 'Farmacia Sana Sana — Centro (Galápagos (Puerto Ayora))', -0.7909, -90.3791, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-158', 'Estación Petroecuador — Centro (Galápagos (Puerto Ayora))', -0.7312, -90.3999, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-159', 'Estación Primax — Centro (Galápagos (Puerto Ayora))', -0.7378, -90.3783, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-160', 'Hotel — Centro (Galápagos (Puerto Ayora))', -0.6879, -90.3376, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-161', 'Restaurante — Centro (Galápagos (Puerto Ayora))', -0.7276, -90.3146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-162', 'Plaza Central — Zona Norte (Galápagos (Puerto Ayora))', -0.6872, -90.3553, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-163', 'Centro de Salud — Zona Norte (Galápagos (Puerto Ayora))', -0.7164, -90.3018, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-164', 'Supermaxi — Zona Norte (Galápagos (Puerto Ayora))', -0.7431, -90.3385, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-165', 'Mi Comisariato — Zona Norte (Galápagos (Puerto Ayora))', -0.6934, -90.3955, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-166', 'Cascada Pailón del Diablo', -1.4967, -78.4283, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-167', 'Plaza Central — Centro (Baños de Agua Santa (turística))', -1.4098, -78.4073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-168', 'Centro de Salud — Centro (Baños de Agua Santa (turística))', -1.4515, -78.4539, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-169', 'Supermaxi — Centro (Baños de Agua Santa (turística))', -1.4391, -78.3906, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-170', 'Mi Comisariato — Centro (Baños de Agua Santa (turística))', -1.4155, -78.3826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-171', 'Farmacia Fybeca — Centro (Baños de Agua Santa (turística))', -1.341, -78.4807, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-172', 'Farmacia Sana Sana — Centro (Baños de Agua Santa (turística))', -1.3557, -78.465, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-173', 'Estación Petroecuador — Centro (Baños de Agua Santa (turística))', -1.3579, -78.4116, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-174', 'Estación Primax — Centro (Baños de Agua Santa (turística))', -1.3397, -78.3679, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-175', 'Hotel — Centro (Baños de Agua Santa (turística))', -1.4164, -78.4126, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-176', 'Restaurante — Centro (Baños de Agua Santa (turística))', -1.346, -78.3656, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-177', 'Plaza Central — Zona Norte (Baños de Agua Santa (turística))', -1.3489, -78.4486, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-178', 'Centro de Salud — Zona Norte (Baños de Agua Santa (turística))', -1.338, -78.4423, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-179', 'Supermaxi — Zona Norte (Baños de Agua Santa (turística))', -1.4408, -78.4335, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-180', 'Mi Comisariato — Zona Norte (Baños de Agua Santa (turística))', -1.3954, -78.3717, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-181', 'Mercado de Otavalo', 0.234, -78.261, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-182', 'Plaza Central — Centro (Otavalo (turística))', 0.2382, -78.2702, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-183', 'Centro de Salud — Centro (Otavalo (turística))', 0.1999, -78.3077, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-184', 'Supermaxi — Centro (Otavalo (turística))', 0.2453, -78.3154, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-185', 'Mi Comisariato — Centro (Otavalo (turística))', 0.2305, -78.2576, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-186', 'Farmacia Fybeca — Centro (Otavalo (turística))', 0.2811, -78.2041, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-187', 'Farmacia Sana Sana — Centro (Otavalo (turística))', 0.2726, -78.234, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-188', 'Estación Petroecuador — Centro (Otavalo (turística))', 0.2317, -78.3157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-189', 'Estación Primax — Centro (Otavalo (turística))', 0.289, -78.2493, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-190', 'Hotel — Centro (Otavalo (turística))', 0.243, -78.2378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-191', 'Restaurante — Centro (Otavalo (turística))', 0.2449, -78.2734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-192', 'Plaza Central — Zona Norte (Otavalo (turística))', 0.2886, -78.3049, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-193', 'Centro de Salud — Zona Norte (Otavalo (turística))', 0.2207, -78.2994, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-194', 'Supermaxi — Zona Norte (Otavalo (turística))', 0.242, -78.3072, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-195', 'Mi Comisariato — Zona Norte (Otavalo (turística))', 0.2276, -78.2436, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-196', 'Playa de Montañita', -1.833, -80.742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-197', 'Plaza Central — Centro (Montañita)', -1.8388, -80.6952, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-198', 'Centro de Salud — Centro (Montañita)', -1.8056, -80.7663, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-199', 'Supermaxi — Centro (Montañita)', -1.8041, -80.7332, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-200', 'Mi Comisariato — Centro (Montañita)', -1.7918, -80.7364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-201', 'Farmacia Fybeca — Centro (Montañita)', -1.8037, -80.7054, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-202', 'Farmacia Sana Sana — Centro (Montañita)', -1.7836, -80.7705, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-203', 'Estación Petroecuador — Centro (Montañita)', -1.8543, -80.786, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-204', 'Estación Primax — Centro (Montañita)', -1.7751, -80.7609, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-205', 'Hotel — Centro (Montañita)', -1.89, -80.7712, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-206', 'Restaurante — Centro (Montañita)', -1.8652, -80.7627, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-207', 'Plaza Central — Zona Norte (Montañita)', -1.7835, -80.7328, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-208', 'Centro de Salud — Zona Norte (Montañita)', -1.8423, -80.7968, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-209', 'Supermaxi — Zona Norte (Montañita)', -1.8694, -80.7771, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-210', 'Mi Comisariato — Zona Norte (Montañita)', -1.8823, -80.7488, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-211', 'Reserva de Mindo', 0.05, -78.767, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-212', 'Plaza Central — Centro (Mindo)', 0.0853, -78.7783, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-213', 'Centro de Salud — Centro (Mindo)', 0.0553, -78.7551, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-214', 'Supermaxi — Centro (Mindo)', 0.0843, -78.7808, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-215', 'Mi Comisariato — Centro (Mindo)', 0.1014, -78.8149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-216', 'Farmacia Fybeca — Centro (Mindo)', 0.0748, -78.7747, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-217', 'Farmacia Sana Sana — Centro (Mindo)', 0.0113, -78.7175, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-218', 'Estación Petroecuador — Centro (Mindo)', 0.0214, -78.8135, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-219', 'Estación Primax — Centro (Mindo)', 0.0183, -78.788, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-220', 'Hotel — Centro (Mindo)', 0.0123, -78.7696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-221', 'Restaurante — Centro (Mindo)', 0.044, -78.8027, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-222', 'Plaza Central — Zona Norte (Mindo)', -0.006, -78.8217, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-223', 'Centro de Salud — Zona Norte (Mindo)', 0.0941, -78.7537, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-224', 'Supermaxi — Zona Norte (Mindo)', 0.089, -78.7092, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ec150-225', 'Mi Comisariato — Zona Norte (Mindo)', 0.0777, -78.7164, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
