-- ============================================
-- Achou Trocador — Peru: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('pe150-001', 'Fortaleza del Real Felipe (Callao)', -12.064, -77.159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-002', 'Aeropuerto Jorge Chávez', -12.0219, -77.1143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-003', 'McDonald''s — Callao', -12.0643, -77.1297, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-004', 'Burger King — Callao', -12.0546, -77.1155, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-005', 'KFC — Callao', -12.0844, -77.1437, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-006', 'Plaza Central — Centro (Callao)', -12.0868, -77.0656, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-007', 'Centro de Salud — Centro (Callao)', -12.1085, -77.1643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-008', 'Plaza Vea — Centro (Callao)', -12.0502, -77.1466, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-009', 'Metro — Centro (Callao)', -12.025, -77.0735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-010', 'Farmacia Inkafarma — Centro (Callao)', -12.0939, -77.1303, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-011', 'Farmacia Mifarma — Centro (Callao)', -12.014, -77.1743, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-012', 'Estación Primax — Centro (Callao)', -12.1057, -77.1587, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-013', 'Estación Repsol — Centro (Callao)', -12.0946, -77.1029, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-014', 'Hotel — Centro (Callao)', -12.0332, -77.1321, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-015', 'Restaurante — Centro (Callao)', -12.0652, -77.1604, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-016', 'Plaza Central — Zona Norte (Callao)', -12.1154, -77.139, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-017', 'Centro de Salud — Zona Norte (Callao)', -12.0764, -77.1104, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-018', 'Plaza Vea — Zona Norte (Callao)', -12.0239, -77.15, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-019', 'Metro — Zona Norte (Callao)', -12.0984, -77.1623, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-020', 'Farmacia Inkafarma — Zona Norte (Callao)', -11.9984, -77.1756, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-021', 'Farmacia Mifarma — Zona Norte (Callao)', -12.0359, -77.0838, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-022', 'Estación Primax — Zona Norte (Callao)', -12.1059, -77.129, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-023', 'Estación Repsol — Zona Norte (Callao)', -12.0631, -77.1704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-024', 'Hotel — Zona Norte (Callao)', -12.0015, -77.127, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-025', 'Restaurante — Zona Norte (Callao)', -12.0327, -77.1481, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-026', 'Plaza Central — Zona Sur (Callao)', -12.1059, -77.0983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-027', 'Centro de Salud — Zona Sur (Callao)', -12.0503, -77.1635, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-028', 'Plaza Vea — Zona Sur (Callao)', -12.0304, -77.0936, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-029', 'Metro — Zona Sur (Callao)', -12.0375, -77.0762, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-030', 'Farmacia Inkafarma — Zona Sur (Callao)', -12.0958, -77.1532, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-031', 'Plaza de Armas de Chiclayo', -6.7714, -79.8409, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-032', 'Subway — Chiclayo (populosas)', -6.7711, -79.8682, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-033', 'Pizza Hut — Chiclayo (populosas)', -6.7429, -79.8629, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-034', 'Starbucks — Chiclayo (populosas)', -6.7647, -79.8275, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-035', 'Plaza Central — Centro (Chiclayo (populosas))', -6.7366, -79.8604, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-036', 'Centro de Salud — Centro (Chiclayo (populosas))', -6.7542, -79.8401, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-037', 'Plaza Vea — Centro (Chiclayo (populosas))', -6.7666, -79.8235, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-038', 'Metro — Centro (Chiclayo (populosas))', -6.7744, -79.8559, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-039', 'Farmacia Inkafarma — Centro (Chiclayo (populosas))', -6.7365, -79.8019, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-040', 'Farmacia Mifarma — Centro (Chiclayo (populosas))', -6.807, -79.8314, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-041', 'Estación Primax — Centro (Chiclayo (populosas))', -6.767, -79.8878, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-042', 'Estación Repsol — Centro (Chiclayo (populosas))', -6.7156, -79.8805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-043', 'Hotel — Centro (Chiclayo (populosas))', -6.7961, -79.8277, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-044', 'Restaurante — Centro (Chiclayo (populosas))', -6.7116, -79.8648, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-045', 'Plaza Central — Zona Norte (Chiclayo (populosas))', -6.7125, -79.7957, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-046', 'Centro de Salud — Zona Norte (Chiclayo (populosas))', -6.8018, -79.8059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-047', 'Plaza Vea — Zona Norte (Chiclayo (populosas))', -6.7933, -79.8442, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-048', 'Metro — Zona Norte (Chiclayo (populosas))', -6.7748, -79.8884, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-049', 'Farmacia Inkafarma — Zona Norte (Chiclayo (populosas))', -6.7182, -79.835, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-050', 'Farmacia Mifarma — Zona Norte (Chiclayo (populosas))', -6.7331, -79.7934, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-051', 'Estación Primax — Zona Norte (Chiclayo (populosas))', -6.737, -79.8468, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-052', 'Estación Repsol — Zona Norte (Chiclayo (populosas))', -6.7409, -79.8101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-053', 'Hotel — Zona Norte (Chiclayo (populosas))', -6.7604, -79.7974, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-054', 'Restaurante — Zona Norte (Chiclayo (populosas))', -6.8168, -79.8275, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-055', 'Plaza Central — Zona Sur (Chiclayo (populosas))', -6.7473, -79.8777, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-056', 'Centro de Salud — Zona Sur (Chiclayo (populosas))', -6.7596, -79.8601, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-057', 'Plaza Vea — Zona Sur (Chiclayo (populosas))', -6.8142, -79.8867, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-058', 'Metro — Zona Sur (Chiclayo (populosas))', -6.7529, -79.8084, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-059', 'Farmacia Inkafarma — Zona Sur (Chiclayo (populosas))', -6.7379, -79.8516, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-060', 'Farmacia Mifarma — Zona Sur (Chiclayo (populosas))', -6.773, -79.8841, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-061', 'Plaza de Armas de Piura', -5.1945, -80.6328, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-062', 'Domino''s Pizza — Piura', -5.2209, -80.6403, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-063', 'Bembos — Piura', -5.2084, -80.6071, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-064', 'China Wok — Piura', -5.172, -80.6328, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-065', 'Plaza Central — Centro (Piura)', -5.1784, -80.6612, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-066', 'Centro de Salud — Centro (Piura)', -5.2417, -80.6543, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-067', 'Plaza Vea — Centro (Piura)', -5.2054, -80.6708, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-068', 'Metro — Centro (Piura)', -5.1497, -80.5898, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-069', 'Farmacia Inkafarma — Centro (Piura)', -5.2412, -80.5906, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-070', 'Farmacia Mifarma — Centro (Piura)', -5.1731, -80.5781, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-071', 'Estación Primax — Centro (Piura)', -5.1674, -80.5859, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-072', 'Estación Repsol — Centro (Piura)', -5.1493, -80.6268, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-073', 'Hotel — Centro (Piura)', -5.2205, -80.651, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-074', 'Restaurante — Centro (Piura)', -5.1794, -80.6093, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-075', 'Plaza Central — Zona Norte (Piura)', -5.2239, -80.6846, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-076', 'Centro de Salud — Zona Norte (Piura)', -5.2149, -80.6863, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-077', 'Plaza Vea — Zona Norte (Piura)', -5.1613, -80.6599, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-078', 'Metro — Zona Norte (Piura)', -5.251, -80.6285, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-079', 'Farmacia Inkafarma — Zona Norte (Piura)', -5.1648, -80.6218, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-080', 'Farmacia Mifarma — Zona Norte (Piura)', -5.1388, -80.6566, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-081', 'Estación Primax — Zona Norte (Piura)', -5.178, -80.622, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-082', 'Estación Repsol — Zona Norte (Piura)', -5.1423, -80.6851, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-083', 'Hotel — Zona Norte (Piura)', -5.1786, -80.6805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-084', 'Restaurante — Zona Norte (Piura)', -5.2541, -80.6898, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-085', 'Plaza Central — Zona Sur (Piura)', -5.156, -80.6353, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-086', 'Centro de Salud — Zona Sur (Piura)', -5.2231, -80.5969, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-087', 'Plaza Vea — Zona Sur (Piura)', -5.1759, -80.6887, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-088', 'Metro — Zona Sur (Piura)', -5.1504, -80.591, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-089', 'Farmacia Inkafarma — Zona Sur (Piura)', -5.1625, -80.6587, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-090', 'Farmacia Mifarma — Zona Sur (Piura)', -5.1683, -80.6853, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-091', 'Parque de la Identidad Huanca', -12.07, -75.21, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-092', 'Rosatel — Huancayo', -12.0877, -75.2207, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-093', 'Norky''s — Huancayo', -12.0485, -75.2253, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-094', 'Pardos Chicken — Huancayo', -12.0452, -75.2029, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-095', 'Plaza Central — Centro (Huancayo)', -12.0625, -75.2236, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-096', 'Centro de Salud — Centro (Huancayo)', -12.0195, -75.2243, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-097', 'Plaza Vea — Centro (Huancayo)', -12.0356, -75.2571, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-098', 'Metro — Centro (Huancayo)', -12.1128, -75.1947, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-099', 'Farmacia Inkafarma — Centro (Huancayo)', -12.0786, -75.2477, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-100', 'Farmacia Mifarma — Centro (Huancayo)', -12.1203, -75.1878, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-101', 'Estación Primax — Centro (Huancayo)', -12.0773, -75.232, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-102', 'Estación Repsol — Centro (Huancayo)', -12.125, -75.2407, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-103', 'Hotel — Centro (Huancayo)', -12.1214, -75.2097, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-104', 'Restaurante — Centro (Huancayo)', -12.091, -75.2212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-105', 'Plaza Central — Zona Norte (Huancayo)', -12.0894, -75.208, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-106', 'Centro de Salud — Zona Norte (Huancayo)', -12.0708, -75.2247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-107', 'Plaza Vea — Zona Norte (Huancayo)', -12.0976, -75.2254, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-108', 'Metro — Zona Norte (Huancayo)', -12.1078, -75.1833, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-109', 'Farmacia Inkafarma — Zona Norte (Huancayo)', -12.0403, -75.2577, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-110', 'Farmacia Mifarma — Zona Norte (Huancayo)', -12.0059, -75.2625, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-111', 'Estación Primax — Zona Norte (Huancayo)', -12.0226, -75.2261, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-112', 'Estación Repsol — Zona Norte (Huancayo)', -12.0982, -75.2051, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-113', 'Hotel — Zona Norte (Huancayo)', -12.1239, -75.1821, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-114', 'Restaurante — Zona Norte (Huancayo)', -12.1238, -75.147, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-115', 'Plaza Central — Zona Sur (Huancayo)', -12.1117, -75.1822, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-116', 'Centro de Salud — Zona Sur (Huancayo)', -12.0656, -75.1611, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-117', 'Plaza Vea — Zona Sur (Huancayo)', -12.019, -75.2633, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-118', 'Metro — Zona Sur (Huancayo)', -12.071, -75.1571, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-119', 'Farmacia Inkafarma — Zona Sur (Huancayo)', -12.1104, -75.2087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-120', 'Farmacia Mifarma — Zona Sur (Huancayo)', -12.1095, -75.1767, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-121', 'Plaza de Armas de Chimbote', -9.0853, -78.5783, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-122', 'La Lucha Sanguchería — Chimbote', -9.086, -78.5695, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-123', 'Otto Grill — Chimbote', -9.0681, -78.6061, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-124', 'Roky''s — Chimbote', -9.0993, -78.5569, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pe150-125', 'Plaza Central — Centro (Chimbote)', -9.0458, -78.5411, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-126', 'Centro de Salud — Centro (Chimbote)', -9.1113, -78.5335, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-127', 'Plaza Vea — Centro (Chimbote)', -9.1386, -78.5934, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-128', 'Metro — Centro (Chimbote)', -9.0771, -78.6089, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-129', 'Farmacia Inkafarma — Centro (Chimbote)', -9.1347, -78.6157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-130', 'Farmacia Mifarma — Centro (Chimbote)', -9.1218, -78.522, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-131', 'Estación Primax — Centro (Chimbote)', -9.1447, -78.5609, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-132', 'Estación Repsol — Centro (Chimbote)', -9.1267, -78.6062, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-133', 'Hotel — Centro (Chimbote)', -9.1131, -78.5626, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-134', 'Restaurante — Centro (Chimbote)', -9.1314, -78.5875, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-135', 'Plaza Central — Zona Norte (Chimbote)', -9.1057, -78.6135, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-136', 'Centro de Salud — Zona Norte (Chimbote)', -9.1409, -78.5926, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-137', 'Plaza Vea — Zona Norte (Chimbote)', -9.0982, -78.5228, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-138', 'Metro — Zona Norte (Chimbote)', -9.1196, -78.5387, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-139', 'Farmacia Inkafarma — Zona Norte (Chimbote)', -9.073, -78.5253, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-140', 'Farmacia Mifarma — Zona Norte (Chimbote)', -9.0997, -78.5955, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-141', 'Estación Primax — Zona Norte (Chimbote)', -9.0618, -78.5883, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-142', 'Estación Repsol — Zona Norte (Chimbote)', -9.0647, -78.5799, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-143', 'Hotel — Zona Norte (Chimbote)', -9.0754, -78.5632, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-144', 'Restaurante — Zona Norte (Chimbote)', -9.0902, -78.6054, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-145', 'Plaza Central — Zona Sur (Chimbote)', -9.1099, -78.5276, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-146', 'Centro de Salud — Zona Sur (Chimbote)', -9.132, -78.6335, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-147', 'Plaza Vea — Zona Sur (Chimbote)', -9.0471, -78.5221, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-148', 'Metro — Zona Sur (Chimbote)', -9.1299, -78.5384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-149', 'Farmacia Inkafarma — Zona Sur (Chimbote)', -9.0469, -78.5995, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-150', 'Farmacia Mifarma — Zona Sur (Chimbote)', -9.1015, -78.5564, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-151', 'Oasis de Huacachina', -14.093, -75.763, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-152', 'Plaza Central — Centro (Ica e Huacachina)', -14.0811, -75.8191, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-153', 'Centro de Salud — Centro (Ica e Huacachina)', -14.0621, -75.7933, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-154', 'Plaza Vea — Centro (Ica e Huacachina)', -14.0411, -75.7882, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-155', 'Metro — Centro (Ica e Huacachina)', -14.1202, -75.7967, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-156', 'Farmacia Inkafarma — Centro (Ica e Huacachina)', -14.1349, -75.7155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-157', 'Farmacia Mifarma — Centro (Ica e Huacachina)', -14.0993, -75.7818, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-158', 'Estación Primax — Centro (Ica e Huacachina)', -14.0941, -75.7696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-159', 'Estación Repsol — Centro (Ica e Huacachina)', -14.0393, -75.7905, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-160', 'Hotel — Centro (Ica e Huacachina)', -14.0574, -75.7798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-161', 'Restaurante — Centro (Ica e Huacachina)', -14.1173, -75.7972, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-162', 'Plaza Central — Zona Norte (Ica e Huacachina)', -14.1406, -75.7536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-163', 'Centro de Salud — Zona Norte (Ica e Huacachina)', -14.1204, -75.7389, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-164', 'Plaza Vea — Zona Norte (Ica e Huacachina)', -14.144, -75.8004, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-165', 'Metro — Zona Norte (Ica e Huacachina)', -14.1203, -75.7356, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-166', 'Reserva Nacional de Paracas', -13.846, -76.253, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-167', 'Plaza Central — Centro (Paracas e Islas Ballestas)', -13.8495, -76.301, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-168', 'Centro de Salud — Centro (Paracas e Islas Ballestas)', -13.8877, -76.2072, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-169', 'Plaza Vea — Centro (Paracas e Islas Ballestas)', -13.8283, -76.2496, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-170', 'Metro — Centro (Paracas e Islas Ballestas)', -13.8652, -76.2098, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-171', 'Farmacia Inkafarma — Centro (Paracas e Islas Ballestas)', -13.8305, -76.2384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-172', 'Farmacia Mifarma — Centro (Paracas e Islas Ballestas)', -13.8987, -76.2099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-173', 'Estación Primax — Centro (Paracas e Islas Ballestas)', -13.8026, -76.2785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-174', 'Estación Repsol — Centro (Paracas e Islas Ballestas)', -13.8619, -76.2613, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-175', 'Hotel — Centro (Paracas e Islas Ballestas)', -13.8879, -76.2636, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-176', 'Restaurante — Centro (Paracas e Islas Ballestas)', -13.7914, -76.2726, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-177', 'Plaza Central — Zona Norte (Paracas e Islas Ballestas)', -13.7902, -76.2271, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-178', 'Centro de Salud — Zona Norte (Paracas e Islas Ballestas)', -13.8907, -76.288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-179', 'Plaza Vea — Zona Norte (Paracas e Islas Ballestas)', -13.8612, -76.2616, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-180', 'Metro — Zona Norte (Paracas e Islas Ballestas)', -13.7969, -76.2219, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-181', 'Líneas de Nazca (mirador)', -14.728, -75.13, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-182', 'Plaza Central — Centro (Nazca)', -14.8502, -74.9646, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-183', 'Centro de Salud — Centro (Nazca)', -14.8583, -74.9695, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-184', 'Plaza Vea — Centro (Nazca)', -14.8816, -74.9704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-185', 'Metro — Centro (Nazca)', -14.8883, -74.9572, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-186', 'Farmacia Inkafarma — Centro (Nazca)', -14.8723, -74.932, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-187', 'Farmacia Mifarma — Centro (Nazca)', -14.8478, -74.9304, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-188', 'Estación Primax — Centro (Nazca)', -14.8205, -74.9672, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-189', 'Estación Repsol — Centro (Nazca)', -14.8368, -74.9726, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-190', 'Hotel — Centro (Nazca)', -14.8828, -74.953, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-191', 'Restaurante — Centro (Nazca)', -14.8481, -74.9703, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-192', 'Plaza Central — Zona Norte (Nazca)', -14.8337, -74.9052, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-193', 'Centro de Salud — Zona Norte (Nazca)', -14.8647, -74.994, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-194', 'Plaza Vea — Zona Norte (Nazca)', -14.8394, -74.9149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-195', 'Metro — Zona Norte (Nazca)', -14.8555, -75.005, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-196', 'Playa de Máncora', -4.108, -81.048, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-197', 'Plaza Central — Centro (Máncora)', -4.0856, -81.0153, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-198', 'Centro de Salud — Centro (Máncora)', -4.1376, -81.0581, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-199', 'Plaza Vea — Centro (Máncora)', -4.0636, -81.1036, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-200', 'Metro — Centro (Máncora)', -4.0554, -81.0826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-201', 'Farmacia Inkafarma — Centro (Máncora)', -4.0624, -81.0204, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-202', 'Farmacia Mifarma — Centro (Máncora)', -4.0841, -81.0619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-203', 'Estación Primax — Centro (Máncora)', -4.0865, -81.0797, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-204', 'Estación Repsol — Centro (Máncora)', -4.11, -81.0704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-205', 'Hotel — Centro (Máncora)', -4.1097, -81.0002, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-206', 'Restaurante — Centro (Máncora)', -4.0619, -81.0878, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-207', 'Plaza Central — Zona Norte (Máncora)', -4.0933, -81.0424, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-208', 'Centro de Salud — Zona Norte (Máncora)', -4.1358, -81.0445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-209', 'Plaza Vea — Zona Norte (Máncora)', -4.1275, -81.0875, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-210', 'Metro — Zona Norte (Máncora)', -4.0755, -81.0121, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-211', 'Fortaleza de Kuelap', -6.418, -77.928, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-212', 'Plaza Central — Centro (Chachapoyas e Kuelap)', -6.2088, -77.9133, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-213', 'Centro de Salud — Centro (Chachapoyas e Kuelap)', -6.226, -77.8189, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-214', 'Plaza Vea — Centro (Chachapoyas e Kuelap)', -6.2171, -77.8597, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-215', 'Metro — Centro (Chachapoyas e Kuelap)', -6.2281, -77.8556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-216', 'Farmacia Inkafarma — Centro (Chachapoyas e Kuelap)', -6.1789, -77.9081, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-217', 'Farmacia Mifarma — Centro (Chachapoyas e Kuelap)', -6.1845, -77.8549, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-218', 'Estación Primax — Centro (Chachapoyas e Kuelap)', -6.2639, -77.9234, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-219', 'Estación Repsol — Centro (Chachapoyas e Kuelap)', -6.2488, -77.8503, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-220', 'Hotel — Centro (Chachapoyas e Kuelap)', -6.2365, -77.8125, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-221', 'Restaurante — Centro (Chachapoyas e Kuelap)', -6.2883, -77.913, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-222', 'Plaza Central — Zona Norte (Chachapoyas e Kuelap)', -6.2314, -77.8878, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-223', 'Centro de Salud — Zona Norte (Chachapoyas e Kuelap)', -6.1856, -77.9197, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-224', 'Plaza Vea — Zona Norte (Chachapoyas e Kuelap)', -6.2403, -77.9103, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pe150-225', 'Metro — Zona Norte (Chachapoyas e Kuelap)', -6.2573, -77.8982, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
