-- ============================================
-- Achou Trocador — Bolívia: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('bo150-001', 'Cristo de la Concordia (Cochabamba)', -17.373, -66.137, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-002', 'Plaza 14 de Septiembre (Cochabamba)', -17.3935, -66.157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-003', 'McDonald''s — Cochabamba (populosas)', -17.3983, -66.1729, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-004', 'Burger King — Cochabamba (populosas)', -17.3737, -66.1739, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-005', 'KFC — Cochabamba (populosas)', -17.3753, -66.1367, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-006', 'Plaza Central — Centro (Cochabamba (populosas))', -17.4137, -66.1483, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-007', 'Centro de Salud — Centro (Cochabamba (populosas))', -17.3666, -66.107, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-008', 'Hipermaxi — Centro (Cochabamba (populosas))', -17.3661, -66.1309, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-009', 'IC Norte — Centro (Cochabamba (populosas))', -17.3613, -66.1054, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-010', 'Farmacia Farmacorp — Centro (Cochabamba (populosas))', -17.3443, -66.1251, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-011', 'Estación YPFB — Centro (Cochabamba (populosas))', -17.4289, -66.1881, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-012', 'Hotel — Centro (Cochabamba (populosas))', -17.335, -66.1495, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-013', 'Restaurante — Centro (Cochabamba (populosas))', -17.4237, -66.1213, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-014', 'Plaza Central — Zona Norte (Cochabamba (populosas))', -17.4049, -66.1689, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-015', 'Centro de Salud — Zona Norte (Cochabamba (populosas))', -17.3647, -66.1321, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-016', 'Hipermaxi — Zona Norte (Cochabamba (populosas))', -17.3882, -66.2112, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-017', 'IC Norte — Zona Norte (Cochabamba (populosas))', -17.4026, -66.2028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-018', 'Farmacia Farmacorp — Zona Norte (Cochabamba (populosas))', -17.4248, -66.1041, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-019', 'Estación YPFB — Zona Norte (Cochabamba (populosas))', -17.3856, -66.1797, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-020', 'Hotel — Zona Norte (Cochabamba (populosas))', -17.4104, -66.1702, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-021', 'Restaurante — Zona Norte (Cochabamba (populosas))', -17.3684, -66.2024, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-022', 'Plaza Central — Zona Sur (Cochabamba (populosas))', -17.3926, -66.1295, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-023', 'Centro de Salud — Zona Sur (Cochabamba (populosas))', -17.437, -66.1048, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-024', 'Hipermaxi — Zona Sur (Cochabamba (populosas))', -17.3741, -66.208, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-025', 'IC Norte — Zona Sur (Cochabamba (populosas))', -17.3961, -66.1239, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-026', 'Farmacia Farmacorp — Zona Sur (Cochabamba (populosas))', -17.4409, -66.2155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-027', 'Estación YPFB — Zona Sur (Cochabamba (populosas))', -17.3705, -66.1087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-028', 'Hotel — Zona Sur (Cochabamba (populosas))', -17.421, -66.2137, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-029', 'Restaurante — Zona Sur (Cochabamba (populosas))', -17.3973, -66.1251, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-030', 'Plaza Central — Zona Este (Cochabamba (populosas))', -17.4221, -66.1088, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-031', 'Plaza 25 de Mayo (Sucre)', -19.0433, -65.2592, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-032', 'Subway — Sucre (populosas)', -19.0244, -65.2523, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-033', 'Pizza Hut — Sucre (populosas)', -19.0384, -65.2487, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-034', 'Starbucks — Sucre (populosas)', -19.0359, -65.2468, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-035', 'Plaza Central — Centro (Sucre (populosas))', -19.0312, -65.3158, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-036', 'Centro de Salud — Centro (Sucre (populosas))', -19.0354, -65.212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-037', 'Hipermaxi — Centro (Sucre (populosas))', -19.0927, -65.2517, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-038', 'IC Norte — Centro (Sucre (populosas))', -19.0661, -65.2802, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-039', 'Farmacia Farmacorp — Centro (Sucre (populosas))', -19.0127, -65.2838, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-040', 'Estación YPFB — Centro (Sucre (populosas))', -18.9914, -65.2019, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-041', 'Hotel — Centro (Sucre (populosas))', -19.0569, -65.2609, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-042', 'Restaurante — Centro (Sucre (populosas))', -18.9957, -65.2021, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-043', 'Plaza Central — Zona Norte (Sucre (populosas))', -19.0569, -65.2715, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-044', 'Centro de Salud — Zona Norte (Sucre (populosas))', -19.0053, -65.258, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-045', 'Hipermaxi — Zona Norte (Sucre (populosas))', -19.0762, -65.2565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-046', 'IC Norte — Zona Norte (Sucre (populosas))', -19.0701, -65.2895, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-047', 'Farmacia Farmacorp — Zona Norte (Sucre (populosas))', -19.0203, -65.2362, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-048', 'Estación YPFB — Zona Norte (Sucre (populosas))', -19.0708, -65.2919, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-049', 'Hotel — Zona Norte (Sucre (populosas))', -19.1024, -65.2784, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-050', 'Restaurante — Zona Norte (Sucre (populosas))', -19.0674, -65.2438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-051', 'Plaza Central — Zona Sur (Sucre (populosas))', -19.0931, -65.3075, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-052', 'Centro de Salud — Zona Sur (Sucre (populosas))', -19.0269, -65.2854, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-053', 'Hipermaxi — Zona Sur (Sucre (populosas))', -19.059, -65.2863, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-054', 'IC Norte — Zona Sur (Sucre (populosas))', -19.0395, -65.3006, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-055', 'Farmacia Farmacorp — Zona Sur (Sucre (populosas))', -19.1023, -65.2992, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-056', 'Estación YPFB — Zona Sur (Sucre (populosas))', -19.0986, -65.2687, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-057', 'Hotel — Zona Sur (Sucre (populosas))', -19.0448, -65.2478, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-058', 'Restaurante — Zona Sur (Sucre (populosas))', -19.1015, -65.2297, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-059', 'Plaza Central — Zona Este (Sucre (populosas))', -19.0874, -65.3062, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-060', 'Centro de Salud — Zona Este (Sucre (populosas))', -19.0034, -65.2619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-061', 'Plaza 10 de Febrero (Oruro)', -17.9833, -67.15, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-062', 'Domino''s Pizza — Oruro', -17.9904, -67.1214, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-063', 'Pollos Copacabana — Oruro', -17.967, -67.1548, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-064', 'Kansas Bolivia — Oruro', -17.9579, -67.1781, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-065', 'Plaza Central — Centro (Oruro)', -17.9402, -67.1354, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-066', 'Centro de Salud — Centro (Oruro)', -17.9665, -67.1067, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-067', 'Hipermaxi — Centro (Oruro)', -17.9621, -67.1497, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-068', 'IC Norte — Centro (Oruro)', -17.9531, -67.204, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-069', 'Farmacia Farmacorp — Centro (Oruro)', -17.9467, -67.1531, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-070', 'Estación YPFB — Centro (Oruro)', -17.9765, -67.1242, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-071', 'Hotel — Centro (Oruro)', -17.9934, -67.1435, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-072', 'Restaurante — Centro (Oruro)', -17.926, -67.1333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-073', 'Plaza Central — Zona Norte (Oruro)', -17.9374, -67.0949, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-074', 'Centro de Salud — Zona Norte (Oruro)', -17.9985, -67.1585, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-075', 'Hipermaxi — Zona Norte (Oruro)', -17.9544, -67.2068, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-076', 'IC Norte — Zona Norte (Oruro)', -18.038, -67.1541, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-077', 'Farmacia Farmacorp — Zona Norte (Oruro)', -17.9816, -67.136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-078', 'Estación YPFB — Zona Norte (Oruro)', -17.9713, -67.1397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-079', 'Hotel — Zona Norte (Oruro)', -18.0322, -67.2074, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-080', 'Restaurante — Zona Norte (Oruro)', -18.0005, -67.1606, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-081', 'Plaza Central — Zona Sur (Oruro)', -17.9712, -67.1435, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-082', 'Centro de Salud — Zona Sur (Oruro)', -17.9948, -67.1699, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-083', 'Hipermaxi — Zona Sur (Oruro)', -17.9778, -67.099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-084', 'IC Norte — Zona Sur (Oruro)', -17.9599, -67.2001, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-085', 'Farmacia Farmacorp — Zona Sur (Oruro)', -18.0019, -67.1862, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-086', 'Estación YPFB — Zona Sur (Oruro)', -18.0133, -67.1973, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-087', 'Hotel — Zona Sur (Oruro)', -18.0263, -67.1473, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-088', 'Restaurante — Zona Sur (Oruro)', -18.0041, -67.1439, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-089', 'Plaza Central — Zona Este (Oruro)', -17.943, -67.1363, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-090', 'Centro de Salud — Zona Este (Oruro)', -17.9348, -67.1776, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-091', 'Plaza Luis de Fuentes (Tarija)', -21.5355, -64.7296, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-092', 'Eli''s Pizza Express — Tarija', -21.546, -64.7427, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-093', 'Chalet La Suisse — Tarija', -21.53, -64.7082, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-094', 'La Casona — Tarija', -21.5354, -64.7436, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-095', 'Plaza Central — Centro (Tarija)', -21.5468, -64.7149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-096', 'Centro de Salud — Centro (Tarija)', -21.5493, -64.757, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-097', 'Hipermaxi — Centro (Tarija)', -21.5093, -64.677, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-098', 'IC Norte — Centro (Tarija)', -21.5816, -64.6758, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-099', 'Farmacia Farmacorp — Centro (Tarija)', -21.5645, -64.6756, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-100', 'Estación YPFB — Centro (Tarija)', -21.5341, -64.7005, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-101', 'Hotel — Centro (Tarija)', -21.4776, -64.7678, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-102', 'Restaurante — Centro (Tarija)', -21.5041, -64.699, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-103', 'Plaza Central — Zona Norte (Tarija)', -21.5518, -64.6715, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-104', 'Centro de Salud — Zona Norte (Tarija)', -21.563, -64.6924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-105', 'Hipermaxi — Zona Norte (Tarija)', -21.48, -64.7045, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-106', 'IC Norte — Zona Norte (Tarija)', -21.5244, -64.7641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-107', 'Farmacia Farmacorp — Zona Norte (Tarija)', -21.4959, -64.7302, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-108', 'Estación YPFB — Zona Norte (Tarija)', -21.5463, -64.7295, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-109', 'Hotel — Zona Norte (Tarija)', -21.5636, -64.776, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-110', 'Restaurante — Zona Norte (Tarija)', -21.5912, -64.701, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-111', 'Plaza Central — Zona Sur (Tarija)', -21.4944, -64.7297, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-112', 'Centro de Salud — Zona Sur (Tarija)', -21.5855, -64.772, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-113', 'Hipermaxi — Zona Sur (Tarija)', -21.5758, -64.6882, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-114', 'IC Norte — Zona Sur (Tarija)', -21.5016, -64.6879, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-115', 'Farmacia Farmacorp — Zona Sur (Tarija)', -21.575, -64.6713, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-116', 'Estación YPFB — Zona Sur (Tarija)', -21.5219, -64.7273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-117', 'Hotel — Zona Sur (Tarija)', -21.5205, -64.6911, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-118', 'Restaurante — Zona Sur (Tarija)', -21.5188, -64.7259, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-119', 'Plaza Central — Zona Este (Tarija)', -21.5392, -64.7614, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-120', 'Centro de Salud — Zona Este (Tarija)', -21.5004, -64.7579, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-121', 'Cerro Rico de Potosí', -19.61, -65.75, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-122', 'Bierhaus — Potosí (populosas)', -19.605, -65.7699, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-123', 'Alexander Coffee — Potosí (populosas)', -19.5696, -65.7598, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-124', 'Typica Coffee — Potosí (populosas)', -19.5889, -65.7344, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('bo150-125', 'Plaza Central — Centro (Potosí (populosas))', -19.5567, -65.8087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-126', 'Centro de Salud — Centro (Potosí (populosas))', -19.5849, -65.7753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-127', 'Hipermaxi — Centro (Potosí (populosas))', -19.6106, -65.7491, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-128', 'IC Norte — Centro (Potosí (populosas))', -19.5265, -65.7397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-129', 'Farmacia Farmacorp — Centro (Potosí (populosas))', -19.5268, -65.702, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-130', 'Estación YPFB — Centro (Potosí (populosas))', -19.5841, -65.7388, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-131', 'Hotel — Centro (Potosí (populosas))', -19.6227, -65.7155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-132', 'Restaurante — Centro (Potosí (populosas))', -19.6263, -65.7438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-133', 'Plaza Central — Zona Norte (Potosí (populosas))', -19.6297, -65.7053, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-134', 'Centro de Salud — Zona Norte (Potosí (populosas))', -19.5836, -65.8083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-135', 'Hipermaxi — Zona Norte (Potosí (populosas))', -19.5333, -65.8073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-136', 'IC Norte — Zona Norte (Potosí (populosas))', -19.557, -65.755, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-137', 'Farmacia Farmacorp — Zona Norte (Potosí (populosas))', -19.5285, -65.7124, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-138', 'Estación YPFB — Zona Norte (Potosí (populosas))', -19.5854, -65.8006, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-139', 'Hotel — Zona Norte (Potosí (populosas))', -19.593, -65.763, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-140', 'Restaurante — Zona Norte (Potosí (populosas))', -19.6198, -65.781, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-141', 'Plaza Central — Zona Sur (Potosí (populosas))', -19.5673, -65.7471, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-142', 'Centro de Salud — Zona Sur (Potosí (populosas))', -19.6431, -65.7028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-143', 'Hipermaxi — Zona Sur (Potosí (populosas))', -19.6184, -65.732, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-144', 'IC Norte — Zona Sur (Potosí (populosas))', -19.5382, -65.81, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-145', 'Farmacia Farmacorp — Zona Sur (Potosí (populosas))', -19.6413, -65.7744, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-146', 'Estación YPFB — Zona Sur (Potosí (populosas))', -19.6357, -65.759, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-147', 'Hotel — Zona Sur (Potosí (populosas))', -19.5591, -65.77, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-148', 'Restaurante — Zona Sur (Potosí (populosas))', -19.6233, -65.6983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-149', 'Plaza Central — Zona Este (Potosí (populosas))', -19.6083, -65.7879, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-150', 'Centro de Salud — Zona Este (Potosí (populosas))', -19.6233, -65.7179, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-151', 'Isla del Sol (Titicaca)', -16.03, -69.17, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-152', 'Plaza Central — Centro (Copacabana e Isla del Sol)', -16.1726, -69.0513, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-153', 'Centro de Salud — Centro (Copacabana e Isla del Sol)', -16.1564, -69.0922, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-154', 'Hipermaxi — Centro (Copacabana e Isla del Sol)', -16.1688, -69.1322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-155', 'IC Norte — Centro (Copacabana e Isla del Sol)', -16.1678, -69.0599, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-156', 'Farmacia Farmacorp — Centro (Copacabana e Isla del Sol)', -16.1285, -69.0528, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-157', 'Estación YPFB — Centro (Copacabana e Isla del Sol)', -16.1964, -69.0504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-158', 'Hotel — Centro (Copacabana e Isla del Sol)', -16.2145, -69.0592, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-159', 'Restaurante — Centro (Copacabana e Isla del Sol)', -16.1534, -69.0983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-160', 'Plaza Central — Zona Norte (Copacabana e Isla del Sol)', -16.1679, -69.1363, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-161', 'Centro de Salud — Zona Norte (Copacabana e Isla del Sol)', -16.2165, -69.1163, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-162', 'Hipermaxi — Zona Norte (Copacabana e Isla del Sol)', -16.1803, -69.1321, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-163', 'IC Norte — Zona Norte (Copacabana e Isla del Sol)', -16.1957, -69.1314, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-164', 'Farmacia Farmacorp — Zona Norte (Copacabana e Isla del Sol)', -16.1345, -69.0274, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-165', 'Estación YPFB — Zona Norte (Copacabana e Isla del Sol)', -16.1857, -69.0334, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-166', 'Casa Nacional de Moneda (Potosí)', -19.585, -65.753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-167', 'Plaza Central — Centro (Potosí (turística))', -19.6125, -65.7301, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-168', 'Centro de Salud — Centro (Potosí (turística))', -19.5921, -65.725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-169', 'Hipermaxi — Centro (Potosí (turística))', -19.6401, -65.6979, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-170', 'IC Norte — Centro (Potosí (turística))', -19.5429, -65.7059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-171', 'Farmacia Farmacorp — Centro (Potosí (turística))', -19.555, -65.7191, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-172', 'Estación YPFB — Centro (Potosí (turística))', -19.5558, -65.7356, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-173', 'Hotel — Centro (Potosí (turística))', -19.62, -65.7021, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-174', 'Restaurante — Centro (Potosí (turística))', -19.6112, -65.7074, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-175', 'Plaza Central — Zona Norte (Potosí (turística))', -19.6047, -65.8127, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-176', 'Centro de Salud — Zona Norte (Potosí (turística))', -19.6125, -65.7248, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-177', 'Hipermaxi — Zona Norte (Potosí (turística))', -19.6069, -65.7742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-178', 'IC Norte — Zona Norte (Potosí (turística))', -19.6323, -65.6974, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-179', 'Farmacia Farmacorp — Zona Norte (Potosí (turística))', -19.6427, -65.6965, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-180', 'Estación YPFB — Zona Norte (Potosí (turística))', -19.5592, -65.7356, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-181', 'Pampas del Yacuma (acceso Rurrenabaque)', -14.44, -67.527, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-182', 'Plaza Central — Centro (Rurrenabaque)', -14.4869, -67.5167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-183', 'Centro de Salud — Centro (Rurrenabaque)', -14.4745, -67.5044, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-184', 'Hipermaxi — Centro (Rurrenabaque)', -14.4078, -67.5536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-185', 'IC Norte — Centro (Rurrenabaque)', -14.406, -67.546, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-186', 'Farmacia Farmacorp — Centro (Rurrenabaque)', -14.4004, -67.5645, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-187', 'Estación YPFB — Centro (Rurrenabaque)', -14.4154, -67.4755, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-188', 'Hotel — Centro (Rurrenabaque)', -14.4752, -67.4983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-189', 'Restaurante — Centro (Rurrenabaque)', -14.4806, -67.4737, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-190', 'Plaza Central — Zona Norte (Rurrenabaque)', -14.3886, -67.5284, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-191', 'Centro de Salud — Zona Norte (Rurrenabaque)', -14.464, -67.4712, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-192', 'Hipermaxi — Zona Norte (Rurrenabaque)', -14.455, -67.4868, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-193', 'IC Norte — Zona Norte (Rurrenabaque)', -14.479, -67.5267, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-194', 'Farmacia Farmacorp — Zona Norte (Rurrenabaque)', -14.4832, -67.4833, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-195', 'Estación YPFB — Zona Norte (Rurrenabaque)', -14.4656, -67.5206, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-196', 'El Fuerte de Samaipata', -18.162, -63.818, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-197', 'Plaza Central — Centro (Samaipata)', -18.1861, -63.854, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-198', 'Centro de Salud — Centro (Samaipata)', -18.2388, -63.8277, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-199', 'Hipermaxi — Centro (Samaipata)', -18.1494, -63.8942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-200', 'IC Norte — Centro (Samaipata)', -18.2138, -63.9283, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-201', 'Farmacia Farmacorp — Centro (Samaipata)', -18.2181, -63.8643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-202', 'Estación YPFB — Centro (Samaipata)', -18.1494, -63.8921, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-203', 'Hotel — Centro (Samaipata)', -18.1593, -63.88, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-204', 'Restaurante — Centro (Samaipata)', -18.2356, -63.8675, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-205', 'Plaza Central — Zona Norte (Samaipata)', -18.1982, -63.9036, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-206', 'Centro de Salud — Zona Norte (Samaipata)', -18.1764, -63.9046, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-207', 'Hipermaxi — Zona Norte (Samaipata)', -18.1711, -63.9297, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-208', 'IC Norte — Zona Norte (Samaipata)', -18.1444, -63.9211, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-209', 'Farmacia Farmacorp — Zona Norte (Samaipata)', -18.1889, -63.8257, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-210', 'Estación YPFB — Zona Norte (Samaipata)', -18.1245, -63.8958, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-211', 'Parque Nacional Torotoro', -18.133, -65.767, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-212', 'Plaza Central — Centro (Torotoro)', -18.1073, -65.7147, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-213', 'Centro de Salud — Centro (Torotoro)', -18.1915, -65.7756, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-214', 'Hipermaxi — Centro (Torotoro)', -18.1162, -65.7804, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-215', 'IC Norte — Centro (Torotoro)', -18.1458, -65.7915, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-216', 'Farmacia Farmacorp — Centro (Torotoro)', -18.1308, -65.7432, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-217', 'Estación YPFB — Centro (Torotoro)', -18.0862, -65.8162, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-218', 'Hotel — Centro (Torotoro)', -18.0923, -65.7953, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-219', 'Restaurante — Centro (Torotoro)', -18.0978, -65.7951, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-220', 'Plaza Central — Zona Norte (Torotoro)', -18.1835, -65.708, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-221', 'Centro de Salud — Zona Norte (Torotoro)', -18.1474, -65.7164, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-222', 'Hipermaxi — Zona Norte (Torotoro)', -18.1487, -65.8103, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-223', 'IC Norte — Zona Norte (Torotoro)', -18.1328, -65.7423, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-224', 'Farmacia Farmacorp — Zona Norte (Torotoro)', -18.1698, -65.7981, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('bo150-225', 'Estación YPFB — Zona Norte (Torotoro)', -18.0984, -65.7369, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
