-- ============================================
-- Achou Trocador — Paraguai: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('py150-001', 'Terminal de Luque', -25.2697, -57.4872, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-002', 'McDonald''s — Luque', -25.2546, -57.4637, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-003', 'Burger King — Luque', -25.2651, -57.51, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-004', 'KFC — Luque', -25.2544, -57.4969, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-005', 'Plaza Central — Centro (Luque)', -25.2945, -57.5167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-006', 'Centro de Salud — Centro (Luque)', -25.2896, -57.4276, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-007', 'Superseis — Centro (Luque)', -25.2715, -57.5074, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-008', 'Stock — Centro (Luque)', -25.3287, -57.4427, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-009', 'Farmacia Farmacenter — Centro (Luque)', -25.3113, -57.4344, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-010', 'Estación Petrobras — Centro (Luque)', -25.2108, -57.5226, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-011', 'Estación Puma — Centro (Luque)', -25.2403, -57.5343, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-012', 'Hotel — Centro (Luque)', -25.3176, -57.4476, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-013', 'Restaurante — Centro (Luque)', -25.311, -57.5058, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-014', 'Plaza Central — Zona Norte (Luque)', -25.3228, -57.4582, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-015', 'Centro de Salud — Zona Norte (Luque)', -25.2227, -57.4909, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-016', 'Superseis — Zona Norte (Luque)', -25.2675, -57.4685, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-017', 'Stock — Zona Norte (Luque)', -25.2204, -57.5011, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-018', 'Farmacia Farmacenter — Zona Norte (Luque)', -25.2423, -57.432, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-019', 'Estación Petrobras — Zona Norte (Luque)', -25.2098, -57.4339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-020', 'Estación Puma — Zona Norte (Luque)', -25.243, -57.4803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-021', 'Hotel — Zona Norte (Luque)', -25.2753, -57.471, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-022', 'Restaurante — Zona Norte (Luque)', -25.24, -57.4458, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-023', 'Plaza Central — Zona Sur (Luque)', -25.2362, -57.4462, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-024', 'Centro de Salud — Zona Sur (Luque)', -25.2732, -57.4993, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-025', 'Superseis — Zona Sur (Luque)', -25.2216, -57.5382, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-026', 'Stock — Zona Sur (Luque)', -25.2242, -57.5281, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-027', 'Farmacia Farmacenter — Zona Sur (Luque)', -25.2699, -57.4947, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-028', 'Estación Petrobras — Zona Sur (Luque)', -25.2509, -57.4499, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-029', 'Estación Puma — Zona Sur (Luque)', -25.2603, -57.5324, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-030', 'Hotel — Zona Sur (Luque)', -25.2845, -57.5087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-031', 'Basílica de San Lorenzo', -25.34, -57.5083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-032', 'Subway — San Lorenzo (Paraguai)', -25.3316, -57.5125, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-033', 'Pizza Hut — San Lorenzo (Paraguai)', -25.3599, -57.4852, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-034', 'Starbucks — San Lorenzo (Paraguai)', -25.3573, -57.5345, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-035', 'Plaza Central — Centro (San Lorenzo (Paraguai))', -25.3844, -57.5265, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-036', 'Centro de Salud — Centro (San Lorenzo (Paraguai))', -25.3667, -57.5211, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-037', 'Superseis — Centro (San Lorenzo (Paraguai))', -25.3186, -57.4908, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-038', 'Stock — Centro (San Lorenzo (Paraguai))', -25.3474, -57.4761, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-039', 'Farmacia Farmacenter — Centro (San Lorenzo (Paraguai))', -25.3666, -57.4586, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-040', 'Estación Petrobras — Centro (San Lorenzo (Paraguai))', -25.3393, -57.5537, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-041', 'Estación Puma — Centro (San Lorenzo (Paraguai))', -25.3796, -57.5439, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-042', 'Hotel — Centro (San Lorenzo (Paraguai))', -25.3054, -57.5264, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-043', 'Restaurante — Centro (San Lorenzo (Paraguai))', -25.3194, -57.5593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-044', 'Plaza Central — Zona Norte (San Lorenzo (Paraguai))', -25.3353, -57.4565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-045', 'Centro de Salud — Zona Norte (San Lorenzo (Paraguai))', -25.3722, -57.5233, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-046', 'Superseis — Zona Norte (San Lorenzo (Paraguai))', -25.3636, -57.5175, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-047', 'Stock — Zona Norte (San Lorenzo (Paraguai))', -25.3664, -57.4506, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-048', 'Farmacia Farmacenter — Zona Norte (San Lorenzo (Paraguai))', -25.3757, -57.5474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-049', 'Estación Petrobras — Zona Norte (San Lorenzo (Paraguai))', -25.3646, -57.5417, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-050', 'Estación Puma — Zona Norte (San Lorenzo (Paraguai))', -25.3967, -57.5621, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-051', 'Hotel — Zona Norte (San Lorenzo (Paraguai))', -25.3295, -57.4619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-052', 'Restaurante — Zona Norte (San Lorenzo (Paraguai))', -25.2975, -57.4682, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-053', 'Plaza Central — Zona Sur (San Lorenzo (Paraguai))', -25.3406, -57.4493, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-054', 'Centro de Salud — Zona Sur (San Lorenzo (Paraguai))', -25.3576, -57.5099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-055', 'Superseis — Zona Sur (San Lorenzo (Paraguai))', -25.3221, -57.5491, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-056', 'Stock — Zona Sur (San Lorenzo (Paraguai))', -25.288, -57.5535, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-057', 'Farmacia Farmacenter — Zona Sur (San Lorenzo (Paraguai))', -25.3924, -57.4518, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-058', 'Estación Petrobras — Zona Sur (San Lorenzo (Paraguai))', -25.3534, -57.4588, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-059', 'Estación Puma — Zona Sur (San Lorenzo (Paraguai))', -25.3414, -57.4651, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-060', 'Hotel — Zona Sur (San Lorenzo (Paraguai))', -25.3069, -57.4843, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-061', 'Parque de Capiatá', -25.355, -57.445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-062', 'Domino''s Pizza — Capiatá', -25.3272, -57.4539, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-063', 'Lido Bar — Capiatá', -25.3477, -57.4567, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-064', 'Bolsi — Capiatá', -25.3655, -57.4404, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-065', 'Plaza Central — Centro (Capiatá)', -25.3779, -57.4135, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-066', 'Centro de Salud — Centro (Capiatá)', -25.3209, -57.4155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-067', 'Superseis — Centro (Capiatá)', -25.3208, -57.4417, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-068', 'Stock — Centro (Capiatá)', -25.365, -57.468, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-069', 'Farmacia Farmacenter — Centro (Capiatá)', -25.3774, -57.4112, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-070', 'Estación Petrobras — Centro (Capiatá)', -25.3237, -57.4136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-071', 'Estación Puma — Centro (Capiatá)', -25.3257, -57.4135, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-072', 'Hotel — Centro (Capiatá)', -25.3197, -57.4068, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-073', 'Restaurante — Centro (Capiatá)', -25.391, -57.4679, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-074', 'Plaza Central — Zona Norte (Capiatá)', -25.3929, -57.4692, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-075', 'Centro de Salud — Zona Norte (Capiatá)', -25.3524, -57.3944, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-076', 'Superseis — Zona Norte (Capiatá)', -25.3945, -57.4922, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-077', 'Stock — Zona Norte (Capiatá)', -25.305, -57.4098, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-078', 'Farmacia Farmacenter — Zona Norte (Capiatá)', -25.3585, -57.448, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-079', 'Estación Petrobras — Zona Norte (Capiatá)', -25.4032, -57.4149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-080', 'Estación Puma — Zona Norte (Capiatá)', -25.3383, -57.424, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-081', 'Hotel — Zona Norte (Capiatá)', -25.379, -57.3887, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-082', 'Restaurante — Zona Norte (Capiatá)', -25.3967, -57.3913, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-083', 'Plaza Central — Zona Sur (Capiatá)', -25.4109, -57.3979, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-084', 'Centro de Salud — Zona Sur (Capiatá)', -25.3227, -57.4114, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-085', 'Superseis — Zona Sur (Capiatá)', -25.312, -57.3887, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-086', 'Stock — Zona Sur (Capiatá)', -25.3198, -57.3896, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-087', 'Farmacia Farmacenter — Zona Sur (Capiatá)', -25.3518, -57.401, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-088', 'Estación Petrobras — Zona Sur (Capiatá)', -25.4046, -57.4428, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-089', 'Estación Puma — Zona Sur (Capiatá)', -25.3988, -57.4756, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-090', 'Hotel — Zona Sur (Capiatá)', -25.3028, -57.4105, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-091', 'Costanera de Encarnación', -27.34, -55.86, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-092', 'Britannia Pub — Encarnación', -27.3246, -55.8673, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-093', 'La Preferida — Encarnación', -27.3283, -55.8703, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-094', 'Acaray — Encarnación', -27.3339, -55.884, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-095', 'Plaza Central — Centro (Encarnación)', -27.2751, -55.8229, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-096', 'Centro de Salud — Centro (Encarnación)', -27.3092, -55.8515, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-097', 'Superseis — Centro (Encarnación)', -27.3094, -55.8268, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-098', 'Stock — Centro (Encarnación)', -27.2986, -55.8911, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-099', 'Farmacia Farmacenter — Centro (Encarnación)', -27.3768, -55.8769, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-100', 'Estación Petrobras — Centro (Encarnación)', -27.3458, -55.8866, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-101', 'Estación Puma — Centro (Encarnación)', -27.3301, -55.9054, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-102', 'Hotel — Centro (Encarnación)', -27.2969, -55.8272, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-103', 'Restaurante — Centro (Encarnación)', -27.3639, -55.8596, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-104', 'Plaza Central — Zona Norte (Encarnación)', -27.2968, -55.8362, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-105', 'Centro de Salud — Zona Norte (Encarnación)', -27.3339, -55.8805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-106', 'Superseis — Zona Norte (Encarnación)', -27.3098, -55.8619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-107', 'Stock — Zona Norte (Encarnación)', -27.3708, -55.8553, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-108', 'Farmacia Farmacenter — Zona Norte (Encarnación)', -27.3507, -55.8641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-109', 'Estación Petrobras — Zona Norte (Encarnación)', -27.279, -55.8436, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-110', 'Estación Puma — Zona Norte (Encarnación)', -27.3041, -55.9186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-111', 'Hotel — Zona Norte (Encarnación)', -27.3163, -55.9257, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-112', 'Restaurante — Zona Norte (Encarnación)', -27.3068, -55.8995, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-113', 'Plaza Central — Zona Sur (Encarnación)', -27.3317, -55.8461, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-114', 'Centro de Salud — Zona Sur (Encarnación)', -27.3766, -55.8707, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-115', 'Superseis — Zona Sur (Encarnación)', -27.3158, -55.8473, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-116', 'Stock — Zona Sur (Encarnación)', -27.3541, -55.8821, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-117', 'Farmacia Farmacenter — Zona Sur (Encarnación)', -27.2927, -55.8169, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-118', 'Estación Petrobras — Zona Sur (Encarnación)', -27.3636, -55.8824, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-119', 'Estación Puma — Zona Sur (Encarnación)', -27.3596, -55.882, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-120', 'Hotel — Zona Sur (Encarnación)', -27.2868, -55.9043, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-121', 'Frontera de Pedro Juan Caballero', -22.547, -55.734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-122', 'Manolo — Pedro Juan Caballero', -22.5764, -55.7309, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-123', 'Ña Eustaquia — Pedro Juan Caballero', -22.5403, -55.7488, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-124', 'Jardín de Asia — Pedro Juan Caballero', -22.5671, -55.7219, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('py150-125', 'Plaza Central — Centro (Pedro Juan Caballero)', -22.5154, -55.681, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-126', 'Centro de Salud — Centro (Pedro Juan Caballero)', -22.4945, -55.6924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-127', 'Superseis — Centro (Pedro Juan Caballero)', -22.4873, -55.741, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-128', 'Stock — Centro (Pedro Juan Caballero)', -22.5686, -55.7206, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-129', 'Farmacia Farmacenter — Centro (Pedro Juan Caballero)', -22.4955, -55.7874, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-130', 'Estación Petrobras — Centro (Pedro Juan Caballero)', -22.5335, -55.7671, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-131', 'Estación Puma — Centro (Pedro Juan Caballero)', -22.5882, -55.7533, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-132', 'Hotel — Centro (Pedro Juan Caballero)', -22.5831, -55.6921, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-133', 'Restaurante — Centro (Pedro Juan Caballero)', -22.5931, -55.6911, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-134', 'Plaza Central — Zona Norte (Pedro Juan Caballero)', -22.5811, -55.6876, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-135', 'Centro de Salud — Zona Norte (Pedro Juan Caballero)', -22.5288, -55.7325, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-136', 'Superseis — Zona Norte (Pedro Juan Caballero)', -22.575, -55.7485, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-137', 'Stock — Zona Norte (Pedro Juan Caballero)', -22.5115, -55.7742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-138', 'Farmacia Farmacenter — Zona Norte (Pedro Juan Caballero)', -22.5198, -55.7256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-139', 'Estación Petrobras — Zona Norte (Pedro Juan Caballero)', -22.5698, -55.7244, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-140', 'Estación Puma — Zona Norte (Pedro Juan Caballero)', -22.4947, -55.6854, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-141', 'Hotel — Zona Norte (Pedro Juan Caballero)', -22.5246, -55.7364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-142', 'Restaurante — Zona Norte (Pedro Juan Caballero)', -22.5023, -55.727, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-143', 'Plaza Central — Zona Sur (Pedro Juan Caballero)', -22.555, -55.7735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-144', 'Centro de Salud — Zona Sur (Pedro Juan Caballero)', -22.5286, -55.6891, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-145', 'Superseis — Zona Sur (Pedro Juan Caballero)', -22.504, -55.7769, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-146', 'Stock — Zona Sur (Pedro Juan Caballero)', -22.5868, -55.7066, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-147', 'Farmacia Farmacenter — Zona Sur (Pedro Juan Caballero)', -22.6027, -55.7755, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-148', 'Estación Petrobras — Zona Sur (Pedro Juan Caballero)', -22.533, -55.727, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-149', 'Estación Puma — Zona Sur (Pedro Juan Caballero)', -22.5974, -55.7581, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-150', 'Hotel — Zona Sur (Pedro Juan Caballero)', -22.5441, -55.7875, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-151', 'Ruinas Jesuíticas de Trinidad', -27.057, -55.628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-152', 'Plaza Central — Centro (Trinidad e Jesús de Tavarangue)', -27.0818, -55.6771, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-153', 'Centro de Salud — Centro (Trinidad e Jesús de Tavarangue)', -27.1154, -55.5969, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-154', 'Superseis — Centro (Trinidad e Jesús de Tavarangue)', -27.0608, -55.628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-155', 'Stock — Centro (Trinidad e Jesús de Tavarangue)', -27.0466, -55.6312, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-156', 'Farmacia Farmacenter — Centro (Trinidad e Jesús de Tavarangue)', -27.0461, -55.6708, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-157', 'Estación Petrobras — Centro (Trinidad e Jesús de Tavarangue)', -27.0128, -55.6802, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-158', 'Estación Puma — Centro (Trinidad e Jesús de Tavarangue)', -27.1141, -55.5766, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-159', 'Hotel — Centro (Trinidad e Jesús de Tavarangue)', -27.0134, -55.6087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-160', 'Restaurante — Centro (Trinidad e Jesús de Tavarangue)', -27.0381, -55.6732, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-161', 'Plaza Central — Zona Norte (Trinidad e Jesús de Tavarangue)', -27.0768, -55.6226, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-162', 'Centro de Salud — Zona Norte (Trinidad e Jesús de Tavarangue)', -27.036, -55.5904, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-163', 'Superseis — Zona Norte (Trinidad e Jesús de Tavarangue)', -27.068, -55.6024, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-164', 'Stock — Zona Norte (Trinidad e Jesús de Tavarangue)', -27.0083, -55.6087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-165', 'Farmacia Farmacenter — Zona Norte (Trinidad e Jesús de Tavarangue)', -27.0123, -55.6506, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-166', 'Basílica de Caacupé', -25.386, -57.142, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-167', 'Plaza Central — Centro (Caacupé)', -25.3651, -57.1938, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-168', 'Centro de Salud — Centro (Caacupé)', -25.3823, -57.1846, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-169', 'Superseis — Centro (Caacupé)', -25.4304, -57.1984, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-170', 'Stock — Centro (Caacupé)', -25.3615, -57.1514, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-171', 'Farmacia Farmacenter — Centro (Caacupé)', -25.3597, -57.1742, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-172', 'Estación Petrobras — Centro (Caacupé)', -25.4107, -57.1364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-173', 'Estación Puma — Centro (Caacupé)', -25.406, -57.1355, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-174', 'Hotel — Centro (Caacupé)', -25.4445, -57.1331, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-175', 'Restaurante — Centro (Caacupé)', -25.3524, -57.1788, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-176', 'Plaza Central — Zona Norte (Caacupé)', -25.4367, -57.1965, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-177', 'Centro de Salud — Zona Norte (Caacupé)', -25.3411, -57.1759, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-178', 'Superseis — Zona Norte (Caacupé)', -25.3432, -57.1844, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-179', 'Stock — Zona Norte (Caacupé)', -25.3732, -57.0837, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-180', 'Farmacia Farmacenter — Zona Norte (Caacupé)', -25.4294, -57.1271, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-181', 'Lago Ypacaraí (Areguá)', -25.311, -57.39, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-182', 'Plaza Central — Centro (Areguá)', -25.2788, -57.4273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-183', 'Centro de Salud — Centro (Areguá)', -25.3038, -57.362, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-184', 'Superseis — Centro (Areguá)', -25.2703, -57.3971, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-185', 'Stock — Centro (Areguá)', -25.2734, -57.3545, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-186', 'Farmacia Farmacenter — Centro (Areguá)', -25.3444, -57.3439, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-187', 'Estación Petrobras — Centro (Areguá)', -25.3269, -57.4068, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-188', 'Estación Puma — Centro (Areguá)', -25.3112, -57.3476, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-189', 'Hotel — Centro (Areguá)', -25.3141, -57.4322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-190', 'Restaurante — Centro (Areguá)', -25.3332, -57.374, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-191', 'Plaza Central — Zona Norte (Areguá)', -25.3382, -57.4397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-192', 'Centro de Salud — Zona Norte (Areguá)', -25.3531, -57.3384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-193', 'Superseis — Zona Norte (Areguá)', -25.3101, -57.3514, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-194', 'Stock — Zona Norte (Areguá)', -25.2724, -57.414, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-195', 'Farmacia Farmacenter — Zona Norte (Areguá)', -25.3647, -57.3943, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-196', 'Playa de San Bernardino', -25.323, -57.29, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-197', 'Plaza Central — Centro (San Bernardino (Paraguai))', -25.2747, -57.3145, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-198', 'Centro de Salud — Centro (San Bernardino (Paraguai))', -25.2857, -57.313, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-199', 'Superseis — Centro (San Bernardino (Paraguai))', -25.3417, -57.3172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-200', 'Stock — Centro (San Bernardino (Paraguai))', -25.3215, -57.3279, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-201', 'Farmacia Farmacenter — Centro (San Bernardino (Paraguai))', -25.3224, -57.3285, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-202', 'Estación Petrobras — Centro (San Bernardino (Paraguai))', -25.34, -57.3454, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-203', 'Estación Puma — Centro (San Bernardino (Paraguai))', -25.3552, -57.3253, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-204', 'Hotel — Centro (San Bernardino (Paraguai))', -25.2809, -57.2375, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-205', 'Restaurante — Centro (San Bernardino (Paraguai))', -25.3515, -57.2694, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-206', 'Plaza Central — Zona Norte (San Bernardino (Paraguai))', -25.3663, -57.346, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-207', 'Centro de Salud — Zona Norte (San Bernardino (Paraguai))', -25.3109, -57.2329, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-208', 'Superseis — Zona Norte (San Bernardino (Paraguai))', -25.2908, -57.2746, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-209', 'Stock — Zona Norte (San Bernardino (Paraguai))', -25.2763, -57.2655, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-210', 'Farmacia Farmacenter — Zona Norte (San Bernardino (Paraguai))', -25.3066, -57.3165, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-211', 'Colônia Menonita de Filadelfia', -22.345, -60.033, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-212', 'Plaza Central — Centro (Chaco (Filadelfia))', -22.394, -60.0235, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-213', 'Centro de Salud — Centro (Chaco (Filadelfia))', -22.2922, -60.0846, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-214', 'Superseis — Centro (Chaco (Filadelfia))', -22.3113, -59.9768, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-215', 'Stock — Centro (Chaco (Filadelfia))', -22.3671, -60.0914, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-216', 'Farmacia Farmacenter — Centro (Chaco (Filadelfia))', -22.3451, -60.0841, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-217', 'Estación Petrobras — Centro (Chaco (Filadelfia))', -22.3929, -60.0384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-218', 'Estación Puma — Centro (Chaco (Filadelfia))', -22.3649, -60.0086, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-219', 'Hotel — Centro (Chaco (Filadelfia))', -22.3369, -60.0055, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-220', 'Restaurante — Centro (Chaco (Filadelfia))', -22.3073, -60.0617, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-221', 'Plaza Central — Zona Norte (Chaco (Filadelfia))', -22.3364, -60.0733, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-222', 'Centro de Salud — Zona Norte (Chaco (Filadelfia))', -22.3621, -60.0135, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-223', 'Superseis — Zona Norte (Chaco (Filadelfia))', -22.3256, -60.0442, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-224', 'Stock — Zona Norte (Chaco (Filadelfia))', -22.3102, -60.0788, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('py150-225', 'Farmacia Farmacenter — Zona Norte (Chaco (Filadelfia))', -22.3398, -60.0672, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
