-- ============================================
-- Achou Trocador — México: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('mx150-001', 'Centro de Ecatepec', 19.6018, -99.0602, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-002', 'McDonald''s — Ecatepec de Morelos', 19.5995, -99.0442, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-003', 'Burger King — Ecatepec de Morelos', 19.6039, -99.0551, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-004', 'KFC — Ecatepec de Morelos', 19.6313, -99.0641, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-005', 'Plaza Central — Centro (Ecatepec de Morelos)', 19.6007, -99.0739, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-006', 'Centro de Salud — Centro (Ecatepec de Morelos)', 19.5753, -99.0322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-007', 'Soriana — Centro (Ecatepec de Morelos)', 19.5873, -99.0164, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-008', 'Chedraui — Centro (Ecatepec de Morelos)', 19.5631, -99.0385, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-009', 'Farmacia Farmacias del Ahorro — Centro (Ecatepec de Morelos)', 19.6004, -99.0659, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-010', 'Farmacia Farmacias Similares — Centro (Ecatepec de Morelos)', 19.6532, -99.0785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-011', 'Estación Pemex — Centro (Ecatepec de Morelos)', 19.5838, -99.0516, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-012', 'Estación Shell — Centro (Ecatepec de Morelos)', 19.6238, -99.0368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-013', 'Hotel — Centro (Ecatepec de Morelos)', 19.5983, -99.099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-014', 'Restaurante — Centro (Ecatepec de Morelos)', 19.5971, -99.0786, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-015', 'Plaza Central — Zona Norte (Ecatepec de Morelos)', 19.6377, -99.052, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-016', 'Centro de Salud — Zona Norte (Ecatepec de Morelos)', 19.6573, -99.1026, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-017', 'Soriana — Zona Norte (Ecatepec de Morelos)', 19.6428, -99.0698, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-018', 'Chedraui — Zona Norte (Ecatepec de Morelos)', 19.6478, -99.1061, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-019', 'Farmacia Farmacias del Ahorro — Zona Norte (Ecatepec de Morelos)', 19.6253, -99.0282, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-020', 'Farmacia Farmacias Similares — Zona Norte (Ecatepec de Morelos)', 19.5836, -99.0573, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-021', 'Estación Pemex — Zona Norte (Ecatepec de Morelos)', 19.5984, -99.0227, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-022', 'Estación Shell — Zona Norte (Ecatepec de Morelos)', 19.6521, -99.0598, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-023', 'Hotel — Zona Norte (Ecatepec de Morelos)', 19.5707, -99.0349, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-024', 'Restaurante — Zona Norte (Ecatepec de Morelos)', 19.5645, -99.0354, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-025', 'Plaza Central — Zona Sur (Ecatepec de Morelos)', 19.5861, -99.014, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-026', 'Centro de Salud — Zona Sur (Ecatepec de Morelos)', 19.5789, -99.1053, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-027', 'Soriana — Zona Sur (Ecatepec de Morelos)', 19.627, -99.0774, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-028', 'Chedraui — Zona Sur (Ecatepec de Morelos)', 19.624, -99.0455, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-029', 'Farmacia Farmacias del Ahorro — Zona Sur (Ecatepec de Morelos)', 19.5473, -99.0288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-030', 'Farmacia Farmacias Similares — Zona Sur (Ecatepec de Morelos)', 19.5573, -99.0018, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-031', 'Centro Histórico de León', 21.1226, -101.6822, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-032', 'Subway — León (populosas)', 21.1258, -101.6619, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-033', 'Pizza Hut — León (populosas)', 21.1252, -101.6591, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-034', 'Starbucks — León (populosas)', 21.1012, -101.6929, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-035', 'Plaza Central — Centro (León (populosas))', 21.1224, -101.6339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-036', 'Centro de Salud — Centro (León (populosas))', 21.1323, -101.6964, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-037', 'Soriana — Centro (León (populosas))', 21.1113, -101.6336, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-038', 'Chedraui — Centro (León (populosas))', 21.1482, -101.7069, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-039', 'Farmacia Farmacias del Ahorro — Centro (León (populosas))', 21.1468, -101.7227, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-040', 'Farmacia Farmacias Similares — Centro (León (populosas))', 21.1562, -101.6902, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-041', 'Estación Pemex — Centro (León (populosas))', 21.1179, -101.732, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-042', 'Estación Shell — Centro (León (populosas))', 21.116, -101.6648, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-043', 'Hotel — Centro (León (populosas))', 21.1224, -101.7395, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-044', 'Restaurante — Centro (León (populosas))', 21.172, -101.6412, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-045', 'Plaza Central — Zona Norte (León (populosas))', 21.1568, -101.6289, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-046', 'Centro de Salud — Zona Norte (León (populosas))', 21.1641, -101.6715, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-047', 'Soriana — Zona Norte (León (populosas))', 21.1592, -101.6556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-048', 'Chedraui — Zona Norte (León (populosas))', 21.1825, -101.7038, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-049', 'Farmacia Farmacias del Ahorro — Zona Norte (León (populosas))', 21.1156, -101.6967, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-050', 'Farmacia Farmacias Similares — Zona Norte (León (populosas))', 21.1162, -101.6987, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-051', 'Estación Pemex — Zona Norte (León (populosas))', 21.1623, -101.7026, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-052', 'Estación Shell — Zona Norte (León (populosas))', 21.1388, -101.7391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-053', 'Hotel — Zona Norte (León (populosas))', 21.0726, -101.7003, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-054', 'Restaurante — Zona Norte (León (populosas))', 21.1322, -101.6972, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-055', 'Plaza Central — Zona Sur (León (populosas))', 21.1511, -101.6752, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-056', 'Centro de Salud — Zona Sur (León (populosas))', 21.1496, -101.7287, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-057', 'Soriana — Zona Sur (León (populosas))', 21.0727, -101.6229, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-058', 'Chedraui — Zona Sur (León (populosas))', 21.1469, -101.6863, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-059', 'Farmacia Farmacias del Ahorro — Zona Sur (León (populosas))', 21.1333, -101.7313, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-060', 'Farmacia Farmacias Similares — Zona Sur (León (populosas))', 21.1034, -101.7306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-061', 'Puente Internacional Santa Fe', 31.735, -106.488, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-062', 'Domino''s Pizza — Ciudad Juárez (populosas)', 31.7025, -106.4167, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-063', 'VIPS — Ciudad Juárez (populosas)', 31.6868, -106.4435, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-064', 'Sanborns — Ciudad Juárez (populosas)', 31.6971, -106.4337, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-065', 'Plaza Central — Centro (Ciudad Juárez (populosas))', 31.6452, -106.4797, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-066', 'Centro de Salud — Centro (Ciudad Juárez (populosas))', 31.7313, -106.4714, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-067', 'Soriana — Centro (Ciudad Juárez (populosas))', 31.6945, -106.4404, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-068', 'Chedraui — Centro (Ciudad Juárez (populosas))', 31.7178, -106.4368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-069', 'Farmacia Farmacias del Ahorro — Centro (Ciudad Juárez (populosas))', 31.6361, -106.3682, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-070', 'Farmacia Farmacias Similares — Centro (Ciudad Juárez (populosas))', 31.6819, -106.3748, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-071', 'Estación Pemex — Centro (Ciudad Juárez (populosas))', 31.6543, -106.384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-072', 'Estación Shell — Centro (Ciudad Juárez (populosas))', 31.6681, -106.475, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-073', 'Hotel — Centro (Ciudad Juárez (populosas))', 31.6527, -106.4302, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-074', 'Restaurante — Centro (Ciudad Juárez (populosas))', 31.6493, -106.4615, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-075', 'Plaza Central — Zona Norte (Ciudad Juárez (populosas))', 31.7365, -106.4546, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-076', 'Centro de Salud — Zona Norte (Ciudad Juárez (populosas))', 31.6702, -106.4274, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-077', 'Soriana — Zona Norte (Ciudad Juárez (populosas))', 31.6925, -106.3663, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-078', 'Chedraui — Zona Norte (Ciudad Juárez (populosas))', 31.6845, -106.4503, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-079', 'Farmacia Farmacias del Ahorro — Zona Norte (Ciudad Juárez (populosas))', 31.687, -106.4826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-080', 'Farmacia Farmacias Similares — Zona Norte (Ciudad Juárez (populosas))', 31.6967, -106.3684, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-081', 'Estación Pemex — Zona Norte (Ciudad Juárez (populosas))', 31.6521, -106.4693, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-082', 'Estación Shell — Zona Norte (Ciudad Juárez (populosas))', 31.6978, -106.4462, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-083', 'Hotel — Zona Norte (Ciudad Juárez (populosas))', 31.6847, -106.4598, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-084', 'Restaurante — Zona Norte (Ciudad Juárez (populosas))', 31.6893, -106.4562, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-085', 'Plaza Central — Zona Sur (Ciudad Juárez (populosas))', 31.6483, -106.4131, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-086', 'Centro de Salud — Zona Sur (Ciudad Juárez (populosas))', 31.7424, -106.4754, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-087', 'Soriana — Zona Sur (Ciudad Juárez (populosas))', 31.6629, -106.4506, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-088', 'Chedraui — Zona Sur (Ciudad Juárez (populosas))', 31.7448, -106.4258, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-089', 'Farmacia Farmacias del Ahorro — Zona Sur (Ciudad Juárez (populosas))', 31.6745, -106.4225, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-090', 'Farmacia Farmacias Similares — Zona Sur (Ciudad Juárez (populosas))', 31.7379, -106.4523, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-091', 'Ciudad Jardín Bicentenario', 19.399, -99.014, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-092', 'El Fogoncito — Nezahualcóyotl', 19.4008, -98.9938, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-093', 'La Casa de Toño — Nezahualcóyotl', 19.417, -99.0032, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-094', 'Toks — Nezahualcóyotl', 19.4153, -98.9875, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-095', 'Plaza Central — Centro (Nezahualcóyotl)', 19.3987, -98.9975, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-096', 'Centro de Salud — Centro (Nezahualcóyotl)', 19.3971, -99.0123, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-097', 'Soriana — Centro (Nezahualcóyotl)', 19.381, -99.0258, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-098', 'Chedraui — Centro (Nezahualcóyotl)', 19.4354, -99.0606, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-099', 'Farmacia Farmacias del Ahorro — Centro (Nezahualcóyotl)', 19.3444, -99.0683, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-100', 'Farmacia Farmacias Similares — Centro (Nezahualcóyotl)', 19.3761, -98.9761, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-101', 'Estación Pemex — Centro (Nezahualcóyotl)', 19.394, -99.0223, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-102', 'Estación Shell — Centro (Nezahualcóyotl)', 19.4198, -98.9871, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-103', 'Hotel — Centro (Nezahualcóyotl)', 19.3896, -99.0024, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-104', 'Restaurante — Centro (Nezahualcóyotl)', 19.353, -99.0325, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-105', 'Plaza Central — Zona Norte (Nezahualcóyotl)', 19.3956, -99.0357, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-106', 'Centro de Salud — Zona Norte (Nezahualcóyotl)', 19.4247, -98.9554, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-107', 'Soriana — Zona Norte (Nezahualcóyotl)', 19.3921, -99.0593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-108', 'Chedraui — Zona Norte (Nezahualcóyotl)', 19.4365, -98.9665, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-109', 'Farmacia Farmacias del Ahorro — Zona Norte (Nezahualcóyotl)', 19.3634, -99.0244, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-110', 'Farmacia Farmacias Similares — Zona Norte (Nezahualcóyotl)', 19.426, -99.0178, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-111', 'Estación Pemex — Zona Norte (Nezahualcóyotl)', 19.3786, -99.017, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-112', 'Estación Shell — Zona Norte (Nezahualcóyotl)', 19.4189, -99.0225, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-113', 'Hotel — Zona Norte (Nezahualcóyotl)', 19.3599, -99.0582, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-114', 'Restaurante — Zona Norte (Nezahualcóyotl)', 19.3764, -99.0535, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-115', 'Plaza Central — Zona Sur (Nezahualcóyotl)', 19.3467, -99.0146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-116', 'Centro de Salud — Zona Sur (Nezahualcóyotl)', 19.423, -99.0483, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-117', 'Soriana — Zona Sur (Nezahualcóyotl)', 19.4436, -99.002, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-118', 'Chedraui — Zona Sur (Nezahualcóyotl)', 19.4533, -99.0557, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-119', 'Farmacia Farmacias del Ahorro — Zona Sur (Nezahualcóyotl)', 19.4154, -99.0283, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-120', 'Farmacia Farmacias Similares — Zona Sur (Nezahualcóyotl)', 19.3936, -99.0219, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-121', 'Paseo de Montejo (Mérida)', 20.98, -89.62, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-122', 'El Portón — Mérida (populosas)', 20.9635, -89.6044, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-123', 'Carl''s Jr México — Mérida (populosas)', 20.9816, -89.6069, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-124', 'Chili''s México — Mérida (populosas)', 20.9763, -89.6004, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('mx150-125', 'Plaza Central — Centro (Mérida (populosas))', 20.9643, -89.5994, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-126', 'Centro de Salud — Centro (Mérida (populosas))', 21.0219, -89.5757, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-127', 'Soriana — Centro (Mérida (populosas))', 21.0127, -89.6267, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-128', 'Chedraui — Centro (Mérida (populosas))', 20.9385, -89.6323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-129', 'Farmacia Farmacias del Ahorro — Centro (Mérida (populosas))', 20.9645, -89.6474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-130', 'Farmacia Farmacias Similares — Centro (Mérida (populosas))', 20.9836, -89.5329, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-131', 'Estación Pemex — Centro (Mérida (populosas))', 20.9238, -89.6016, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-132', 'Estación Shell — Centro (Mérida (populosas))', 20.9402, -89.5485, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-133', 'Hotel — Centro (Mérida (populosas))', 20.9308, -89.613, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-134', 'Restaurante — Centro (Mérida (populosas))', 20.9668, -89.6464, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-135', 'Plaza Central — Zona Norte (Mérida (populosas))', 20.9316, -89.6101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-136', 'Centro de Salud — Zona Norte (Mérida (populosas))', 20.9676, -89.5909, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-137', 'Soriana — Zona Norte (Mérida (populosas))', 21.0169, -89.6507, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-138', 'Chedraui — Zona Norte (Mérida (populosas))', 20.909, -89.5769, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-139', 'Farmacia Farmacias del Ahorro — Zona Norte (Mérida (populosas))', 20.9171, -89.5403, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-140', 'Farmacia Farmacias Similares — Zona Norte (Mérida (populosas))', 20.9246, -89.538, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-141', 'Estación Pemex — Zona Norte (Mérida (populosas))', 20.9124, -89.6518, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-142', 'Estación Shell — Zona Norte (Mérida (populosas))', 20.9968, -89.6228, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-143', 'Hotel — Zona Norte (Mérida (populosas))', 20.9107, -89.5853, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-144', 'Restaurante — Zona Norte (Mérida (populosas))', 20.9715, -89.591, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-145', 'Plaza Central — Zona Sur (Mérida (populosas))', 20.9539, -89.6364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-146', 'Centro de Salud — Zona Sur (Mérida (populosas))', 20.9191, -89.6087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-147', 'Soriana — Zona Sur (Mérida (populosas))', 21.0223, -89.5391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-148', 'Chedraui — Zona Sur (Mérida (populosas))', 21.0042, -89.5663, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-149', 'Farmacia Farmacias del Ahorro — Zona Sur (Mérida (populosas))', 20.945, -89.6322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-150', 'Farmacia Farmacias Similares — Zona Sur (Mérida (populosas))', 21.0164, -89.6398, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-151', 'Playa de Sayulita', 20.87, -105.44, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-152', 'Plaza Central — Centro (Sayulita)', 20.8764, -105.452, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-153', 'Centro de Salud — Centro (Sayulita)', 20.9217, -105.4672, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-154', 'Soriana — Centro (Sayulita)', 20.817, -105.4722, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-155', 'Chedraui — Centro (Sayulita)', 20.8429, -105.4956, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-156', 'Farmacia Farmacias del Ahorro — Centro (Sayulita)', 20.8214, -105.4495, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-157', 'Farmacia Farmacias Similares — Centro (Sayulita)', 20.866, -105.4553, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-158', 'Estación Pemex — Centro (Sayulita)', 20.9052, -105.4167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-159', 'Estación Shell — Centro (Sayulita)', 20.8776, -105.4492, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-160', 'Hotel — Centro (Sayulita)', 20.8696, -105.452, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-161', 'Restaurante — Centro (Sayulita)', 20.8983, -105.4895, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-162', 'Plaza Central — Zona Norte (Sayulita)', 20.8491, -105.4415, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-163', 'Centro de Salud — Zona Norte (Sayulita)', 20.8551, -105.4725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-164', 'Soriana — Zona Norte (Sayulita)', 20.8969, -105.3814, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-165', 'Chedraui — Zona Norte (Sayulita)', 20.9047, -105.4577, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-166', 'Zócalo de Taxco', 18.555, -99.606, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-167', 'Plaza Central — Centro (Taxco)', 18.5068, -99.5629, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-168', 'Centro de Salud — Centro (Taxco)', 18.5403, -99.5566, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-169', 'Soriana — Centro (Taxco)', 18.5679, -99.6171, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-170', 'Chedraui — Centro (Taxco)', 18.5863, -99.639, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-171', 'Farmacia Farmacias del Ahorro — Centro (Taxco)', 18.5718, -99.5494, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-172', 'Farmacia Farmacias Similares — Centro (Taxco)', 18.6106, -99.5573, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-173', 'Estación Pemex — Centro (Taxco)', 18.5108, -99.5973, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-174', 'Estación Shell — Centro (Taxco)', 18.4964, -99.5527, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-175', 'Hotel — Centro (Taxco)', 18.5483, -99.5777, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-176', 'Restaurante — Centro (Taxco)', 18.6049, -99.5992, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-177', 'Plaza Central — Zona Norte (Taxco)', 18.5258, -99.6591, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-178', 'Centro de Salud — Zona Norte (Taxco)', 18.5153, -99.6256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-179', 'Soriana — Zona Norte (Taxco)', 18.5252, -99.5632, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-180', 'Chedraui — Zona Norte (Taxco)', 18.5494, -99.5841, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-181', 'Zona Arqueológica de Chichén Itzá', 20.6843, -88.5678, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-182', 'Plaza Central — Centro (Chichén Itzá (acesso))', 20.639, -88.619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-183', 'Centro de Salud — Centro (Chichén Itzá (acesso))', 20.6667, -88.5746, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-184', 'Soriana — Centro (Chichén Itzá (acesso))', 20.7235, -88.6269, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-185', 'Chedraui — Centro (Chichén Itzá (acesso))', 20.7072, -88.5268, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-186', 'Farmacia Farmacias del Ahorro — Centro (Chichén Itzá (acesso))', 20.6662, -88.5918, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-187', 'Farmacia Farmacias Similares — Centro (Chichén Itzá (acesso))', 20.6467, -88.6102, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-188', 'Estación Pemex — Centro (Chichén Itzá (acesso))', 20.6878, -88.5432, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-189', 'Estación Shell — Centro (Chichén Itzá (acesso))', 20.6905, -88.6028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-190', 'Hotel — Centro (Chichén Itzá (acesso))', 20.6526, -88.6121, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-191', 'Restaurante — Centro (Chichén Itzá (acesso))', 20.6318, -88.5357, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-192', 'Plaza Central — Zona Norte (Chichén Itzá (acesso))', 20.7159, -88.6234, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-193', 'Centro de Salud — Zona Norte (Chichén Itzá (acesso))', 20.702, -88.5085, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-194', 'Soriana — Zona Norte (Chichén Itzá (acesso))', 20.6559, -88.6227, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-195', 'Chedraui — Zona Norte (Chichén Itzá (acesso))', 20.6357, -88.5706, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-196', 'Laguna de los Siete Colores (Bacalar)', 18.679, -88.397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-197', 'Plaza Central — Centro (Bacalar)', 18.7351, -88.3865, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-198', 'Centro de Salud — Centro (Bacalar)', 18.6216, -88.4371, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-199', 'Soriana — Centro (Bacalar)', 18.7027, -88.3777, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-200', 'Chedraui — Centro (Bacalar)', 18.6522, -88.4544, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-201', 'Farmacia Farmacias del Ahorro — Centro (Bacalar)', 18.6936, -88.3445, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-202', 'Farmacia Farmacias Similares — Centro (Bacalar)', 18.7097, -88.4355, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-203', 'Estación Pemex — Centro (Bacalar)', 18.7286, -88.3689, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-204', 'Estación Shell — Centro (Bacalar)', 18.7062, -88.3822, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-205', 'Hotel — Centro (Bacalar)', 18.6801, -88.4011, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-206', 'Restaurante — Centro (Bacalar)', 18.7111, -88.4019, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-207', 'Plaza Central — Zona Norte (Bacalar)', 18.6466, -88.4498, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-208', 'Centro de Salud — Zona Norte (Bacalar)', 18.6223, -88.3669, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-209', 'Soriana — Zona Norte (Bacalar)', 18.666, -88.3914, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-210', 'Chedraui — Zona Norte (Bacalar)', 18.6747, -88.3632, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-211', 'Ruta del Vino (Valle de Guadalupe)', 32.087, -116.559, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-212', 'Plaza Central — Centro (Valle de Guadalupe)', 32.042, -116.512, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-213', 'Centro de Salud — Centro (Valle de Guadalupe)', 32.1015, -116.613, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-214', 'Soriana — Centro (Valle de Guadalupe)', 32.0998, -116.5029, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-215', 'Chedraui — Centro (Valle de Guadalupe)', 32.0788, -116.5649, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-216', 'Farmacia Farmacias del Ahorro — Centro (Valle de Guadalupe)', 32.0871, -116.6003, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-217', 'Farmacia Farmacias Similares — Centro (Valle de Guadalupe)', 32.0666, -116.529, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-218', 'Estación Pemex — Centro (Valle de Guadalupe)', 32.1204, -116.6046, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-219', 'Estación Shell — Centro (Valle de Guadalupe)', 32.1331, -116.5209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-220', 'Hotel — Centro (Valle de Guadalupe)', 32.0523, -116.5413, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-221', 'Restaurante — Centro (Valle de Guadalupe)', 32.0584, -116.5125, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-222', 'Plaza Central — Zona Norte (Valle de Guadalupe)', 32.1399, -116.5145, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-223', 'Centro de Salud — Zona Norte (Valle de Guadalupe)', 32.0839, -116.504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-224', 'Soriana — Zona Norte (Valle de Guadalupe)', 32.1447, -116.5973, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('mx150-225', 'Chedraui — Zona Norte (Valle de Guadalupe)', 32.1164, -116.5907, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
