-- ============================================
-- Achou Trocador — Costa Rica: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('cr150-001', 'Teatro Nacional de Costa Rica', 9.9333, -84.0779, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-002', 'Mercado Central de San José', 9.935, -84.081, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-003', 'McDonald''s — San José (Costa Rica)', 9.8996, -84.0908, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-004', 'Burger King — San José (Costa Rica)', 9.9473, -84.0612, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-005', 'KFC — San José (Costa Rica)', 9.924, -84.1056, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-006', 'Plaza Central — Centro (San José (Costa Rica))', 9.9549, -84.0762, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-007', 'Centro de Salud — Centro (San José (Costa Rica))', 9.8852, -84.1088, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-008', 'Automercado — Centro (San José (Costa Rica))', 9.9466, -84.0963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-009', 'Walmart — Centro (San José (Costa Rica))', 9.9207, -84.0819, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-010', 'Farmacia Farmacia Fischel — Centro (San José (Costa Rica))', 9.9419, -84.0547, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-011', 'Estación Delta — Centro (San José (Costa Rica))', 9.9488, -84.1096, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-012', 'Estación Uno — Centro (San José (Costa Rica))', 9.9557, -84.1256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-013', 'Hotel — Centro (San José (Costa Rica))', 9.953, -84.0478, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-014', 'Restaurante — Centro (San José (Costa Rica))', 9.9484, -84.0689, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-015', 'Plaza Central — Zona Norte (San José (Costa Rica))', 9.9484, -84.063, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-016', 'Centro de Salud — Zona Norte (San José (Costa Rica))', 9.955, -84.0749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-017', 'Automercado — Zona Norte (San José (Costa Rica))', 9.9298, -84.0414, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-018', 'Walmart — Zona Norte (San José (Costa Rica))', 9.9063, -84.0899, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-019', 'Farmacia Farmacia Fischel — Zona Norte (San José (Costa Rica))', 9.9318, -84.1368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-020', 'Estación Delta — Zona Norte (San José (Costa Rica))', 9.9077, -84.1069, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-021', 'Estación Uno — Zona Norte (San José (Costa Rica))', 9.9172, -84.1076, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-022', 'Hotel — Zona Norte (San José (Costa Rica))', 9.9774, -84.1075, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-023', 'Restaurante — Zona Norte (San José (Costa Rica))', 9.9241, -84.1455, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-024', 'Plaza Central — Zona Sur (San José (Costa Rica))', 9.9724, -84.0326, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-025', 'Centro de Salud — Zona Sur (San José (Costa Rica))', 9.8865, -84.0689, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-026', 'Automercado — Zona Sur (San José (Costa Rica))', 9.9814, -84.0641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-027', 'Walmart — Zona Sur (San José (Costa Rica))', 9.9842, -84.1198, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-028', 'Farmacia Farmacia Fischel — Zona Sur (San José (Costa Rica))', 9.9805, -84.1143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-029', 'Estación Delta — Zona Sur (San José (Costa Rica))', 9.9585, -84.1148, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-030', 'Estación Uno — Zona Sur (San José (Costa Rica))', 9.9375, -84.15, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-031', 'Parque Central de Alajuela', 10.0167, -84.2167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-032', 'Subway — Alajuela', 10.0023, -84.2362, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-033', 'Pizza Hut — Alajuela', 10.0127, -84.1902, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-034', 'Starbucks — Alajuela', 10.0227, -84.2022, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-035', 'Plaza Central — Centro (Alajuela)', 9.9971, -84.1601, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-036', 'Centro de Salud — Centro (Alajuela)', 10.0736, -84.2702, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-037', 'Automercado — Centro (Alajuela)', 9.9798, -84.1898, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-038', 'Walmart — Centro (Alajuela)', 10.0325, -84.1973, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-039', 'Farmacia Farmacia Fischel — Centro (Alajuela)', 10.0729, -84.2579, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-040', 'Estación Delta — Centro (Alajuela)', 10.0182, -84.2518, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-041', 'Estación Uno — Centro (Alajuela)', 10.0091, -84.1958, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-042', 'Hotel — Centro (Alajuela)', 10.041, -84.2229, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-043', 'Restaurante — Centro (Alajuela)', 10.0013, -84.205, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-044', 'Plaza Central — Zona Norte (Alajuela)', 10.032, -84.2222, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-045', 'Centro de Salud — Zona Norte (Alajuela)', 10.0406, -84.2627, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-046', 'Automercado — Zona Norte (Alajuela)', 9.9823, -84.2337, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-047', 'Walmart — Zona Norte (Alajuela)', 9.9715, -84.2721, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-048', 'Farmacia Farmacia Fischel — Zona Norte (Alajuela)', 10.0637, -84.1779, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-049', 'Estación Delta — Zona Norte (Alajuela)', 9.9991, -84.2306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-050', 'Estación Uno — Zona Norte (Alajuela)', 9.9876, -84.2003, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-051', 'Hotel — Zona Norte (Alajuela)', 9.9869, -84.2641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-052', 'Restaurante — Zona Norte (Alajuela)', 9.9961, -84.2155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-053', 'Plaza Central — Zona Sur (Alajuela)', 10.0614, -84.2037, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-054', 'Centro de Salud — Zona Sur (Alajuela)', 9.9948, -84.21, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-055', 'Automercado — Zona Sur (Alajuela)', 10.0498, -84.2184, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-056', 'Walmart — Zona Sur (Alajuela)', 9.9973, -84.2223, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-057', 'Farmacia Farmacia Fischel — Zona Sur (Alajuela)', 9.9777, -84.182, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-058', 'Estación Delta — Zona Sur (Alajuela)', 10.0596, -84.1937, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-059', 'Estación Uno — Zona Sur (Alajuela)', 9.9902, -84.2204, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-060', 'Hotel — Zona Sur (Alajuela)', 10.0177, -84.1693, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-061', 'Basílica de Los Ángeles (Cartago)', 9.8644, -83.9194, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-062', 'Domino''s Pizza — Cartago (Costa Rica)', 9.8572, -83.9172, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-063', 'Soda Tapia — Cartago (Costa Rica)', 9.8352, -83.911, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-064', 'Pops — Cartago (Costa Rica)', 9.8383, -83.9118, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-065', 'Plaza Central — Centro (Cartago (Costa Rica))', 9.8181, -83.9725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-066', 'Centro de Salud — Centro (Cartago (Costa Rica))', 9.8986, -83.9511, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-067', 'Automercado — Centro (Cartago (Costa Rica))', 9.8192, -83.9454, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-068', 'Walmart — Centro (Cartago (Costa Rica))', 9.8825, -83.9426, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-069', 'Farmacia Farmacia Fischel — Centro (Cartago (Costa Rica))', 9.9013, -83.95, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-070', 'Estación Delta — Centro (Cartago (Costa Rica))', 9.8885, -83.9285, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-071', 'Estación Uno — Centro (Cartago (Costa Rica))', 9.8821, -83.8706, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-072', 'Hotel — Centro (Cartago (Costa Rica))', 9.8883, -83.943, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-073', 'Restaurante — Centro (Cartago (Costa Rica))', 9.9003, -83.8768, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-074', 'Plaza Central — Zona Norte (Cartago (Costa Rica))', 9.8865, -83.9696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-075', 'Centro de Salud — Zona Norte (Cartago (Costa Rica))', 9.8292, -83.9512, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-076', 'Automercado — Zona Norte (Cartago (Costa Rica))', 9.8227, -83.9105, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-077', 'Walmart — Zona Norte (Cartago (Costa Rica))', 9.8616, -83.943, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-078', 'Farmacia Farmacia Fischel — Zona Norte (Cartago (Costa Rica))', 9.8631, -83.8724, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-079', 'Estación Delta — Zona Norte (Cartago (Costa Rica))', 9.8875, -83.902, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-080', 'Estación Uno — Zona Norte (Cartago (Costa Rica))', 9.8349, -83.8734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-081', 'Hotel — Zona Norte (Cartago (Costa Rica))', 9.824, -83.8926, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-082', 'Restaurante — Zona Norte (Cartago (Costa Rica))', 9.8235, -83.9172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-083', 'Plaza Central — Zona Sur (Cartago (Costa Rica))', 9.8844, -83.9533, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-084', 'Centro de Salud — Zona Sur (Cartago (Costa Rica))', 9.8797, -83.9184, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-085', 'Automercado — Zona Sur (Cartago (Costa Rica))', 9.8533, -83.9351, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-086', 'Walmart — Zona Sur (Cartago (Costa Rica))', 9.8969, -83.9296, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-087', 'Farmacia Farmacia Fischel — Zona Sur (Cartago (Costa Rica))', 9.8574, -83.9651, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-088', 'Estación Delta — Zona Sur (Cartago (Costa Rica))', 9.8824, -83.9287, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-089', 'Estación Uno — Zona Sur (Cartago (Costa Rica))', 9.8935, -83.9451, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-090', 'Hotel — Zona Sur (Cartago (Costa Rica))', 9.8977, -83.924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-091', 'Fortín de Heredia', 9.9989, -84.1167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-092', 'Spoon — Heredia', 10.0267, -84.1387, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-093', 'Rosti Pollos — Heredia', 10.0134, -84.1153, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-094', 'Antojitos — Heredia', 9.9987, -84.1273, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-095', 'Plaza Central — Centro (Heredia)', 10.0248, -84.1543, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-096', 'Centro de Salud — Centro (Heredia)', 10.0358, -84.099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-097', 'Automercado — Centro (Heredia)', 10.0366, -84.0873, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-098', 'Walmart — Centro (Heredia)', 10.0089, -84.0988, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-099', 'Farmacia Farmacia Fischel — Centro (Heredia)', 10.0353, -84.1025, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-100', 'Estación Delta — Centro (Heredia)', 10.0535, -84.0917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-101', 'Estación Uno — Centro (Heredia)', 9.9495, -84.1577, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-102', 'Hotel — Centro (Heredia)', 10.0043, -84.0576, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-103', 'Restaurante — Centro (Heredia)', 9.9749, -84.1146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-104', 'Plaza Central — Zona Norte (Heredia)', 9.9467, -84.0966, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-105', 'Centro de Salud — Zona Norte (Heredia)', 10.0, -84.136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-106', 'Automercado — Zona Norte (Heredia)', 9.986, -84.1045, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-107', 'Walmart — Zona Norte (Heredia)', 9.9813, -84.1173, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-108', 'Farmacia Farmacia Fischel — Zona Norte (Heredia)', 10.058, -84.0607, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-109', 'Estación Delta — Zona Norte (Heredia)', 10.0253, -84.0938, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-110', 'Estación Uno — Zona Norte (Heredia)', 9.9426, -84.0895, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-111', 'Hotel — Zona Norte (Heredia)', 10.0413, -84.1686, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-112', 'Restaurante — Zona Norte (Heredia)', 9.9985, -84.0992, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-113', 'Plaza Central — Zona Sur (Heredia)', 9.9716, -84.0902, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-114', 'Centro de Salud — Zona Sur (Heredia)', 10.0431, -84.0997, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-115', 'Automercado — Zona Sur (Heredia)', 10.0255, -84.1387, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-116', 'Walmart — Zona Sur (Heredia)', 9.9833, -84.136, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-117', 'Farmacia Farmacia Fischel — Zona Sur (Heredia)', 9.9733, -84.1306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-118', 'Estación Delta — Zona Sur (Heredia)', 10.0174, -84.0581, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-119', 'Estación Uno — Zona Sur (Heredia)', 10.0363, -84.1373, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-120', 'Hotel — Zona Sur (Heredia)', 9.9723, -84.0735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-121', 'Paseo de los Turistas (Puntarenas)', 9.976, -84.8384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-122', 'Bagelmen''s — Puntarenas', 9.9771, -84.8227, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-123', 'Fresh Market Café — Puntarenas', 9.9611, -84.8247, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-124', 'Marisquería La Princesa — Puntarenas', 9.977, -84.8096, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('cr150-125', 'Plaza Central — Centro (Puntarenas)', 9.9658, -84.8826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-126', 'Centro de Salud — Centro (Puntarenas)', 9.96, -84.8631, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-127', 'Automercado — Centro (Puntarenas)', 9.9751, -84.8787, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-128', 'Walmart — Centro (Puntarenas)', 9.9467, -84.8385, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-129', 'Farmacia Farmacia Fischel — Centro (Puntarenas)', 9.9569, -84.782, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-130', 'Estación Delta — Centro (Puntarenas)', 9.9444, -84.8713, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-131', 'Estación Uno — Centro (Puntarenas)', 9.98, -84.8279, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-132', 'Hotel — Centro (Puntarenas)', 10.0023, -84.8289, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-133', 'Restaurante — Centro (Puntarenas)', 9.9678, -84.8798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-134', 'Plaza Central — Zona Norte (Puntarenas)', 9.9255, -84.8737, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-135', 'Centro de Salud — Zona Norte (Puntarenas)', 9.9922, -84.7802, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-136', 'Automercado — Zona Norte (Puntarenas)', 9.9672, -84.8547, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-137', 'Walmart — Zona Norte (Puntarenas)', 9.9665, -84.8305, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-138', 'Farmacia Farmacia Fischel — Zona Norte (Puntarenas)', 9.9789, -84.806, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-139', 'Estación Delta — Zona Norte (Puntarenas)', 10.0084, -84.8034, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-140', 'Estación Uno — Zona Norte (Puntarenas)', 9.9283, -84.8338, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-141', 'Hotel — Zona Norte (Puntarenas)', 9.9847, -84.7827, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-142', 'Restaurante — Zona Norte (Puntarenas)', 10.0066, -84.8753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-143', 'Plaza Central — Zona Sur (Puntarenas)', 9.9506, -84.8061, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-144', 'Centro de Salud — Zona Sur (Puntarenas)', 9.9657, -84.7818, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-145', 'Automercado — Zona Sur (Puntarenas)', 9.9177, -84.8918, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-146', 'Walmart — Zona Sur (Puntarenas)', 10.0278, -84.8906, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-147', 'Farmacia Farmacia Fischel — Zona Sur (Puntarenas)', 9.9919, -84.8303, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-148', 'Estación Delta — Zona Sur (Puntarenas)', 9.9818, -84.8586, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-149', 'Estación Uno — Zona Sur (Puntarenas)', 9.9161, -84.8239, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-150', 'Hotel — Zona Sur (Puntarenas)', 9.9608, -84.8807, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-151', 'Reserva Bosque Nuboso Monteverde', 10.301, -84.808, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-152', 'Plaza Central — Centro (Monteverde)', 10.3098, -84.8521, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-153', 'Centro de Salud — Centro (Monteverde)', 10.2881, -84.772, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-154', 'Automercado — Centro (Monteverde)', 10.3534, -84.8356, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-155', 'Walmart — Centro (Monteverde)', 10.246, -84.8293, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-156', 'Farmacia Farmacia Fischel — Centro (Monteverde)', 10.2723, -84.785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-157', 'Estación Delta — Centro (Monteverde)', 10.3337, -84.7753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-158', 'Estación Uno — Centro (Monteverde)', 10.2697, -84.8256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-159', 'Hotel — Centro (Monteverde)', 10.3071, -84.7718, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-160', 'Restaurante — Centro (Monteverde)', 10.3263, -84.8292, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-161', 'Plaza Central — Zona Norte (Monteverde)', 10.2551, -84.7714, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-162', 'Centro de Salud — Zona Norte (Monteverde)', 10.2827, -84.8296, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-163', 'Automercado — Zona Norte (Monteverde)', 10.2976, -84.8474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-164', 'Walmart — Zona Norte (Monteverde)', 10.33, -84.784, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-165', 'Farmacia Farmacia Fischel — Zona Norte (Monteverde)', 10.2566, -84.8211, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-166', 'Playa Jacó', 9.614, -84.628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-167', 'Plaza Central — Centro (Jacó)', 9.5654, -84.6812, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-168', 'Centro de Salud — Centro (Jacó)', 9.6361, -84.6778, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-169', 'Automercado — Centro (Jacó)', 9.557, -84.5873, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-170', 'Walmart — Centro (Jacó)', 9.6129, -84.6323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-171', 'Farmacia Farmacia Fischel — Centro (Jacó)', 9.6652, -84.5751, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-172', 'Estación Delta — Centro (Jacó)', 9.6165, -84.6248, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-173', 'Estación Uno — Centro (Jacó)', 9.5662, -84.5861, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-174', 'Hotel — Centro (Jacó)', 9.5859, -84.63, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-175', 'Restaurante — Centro (Jacó)', 9.6706, -84.5845, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-176', 'Plaza Central — Zona Norte (Jacó)', 9.5588, -84.6306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-177', 'Centro de Salud — Zona Norte (Jacó)', 9.6343, -84.5888, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-178', 'Automercado — Zona Norte (Jacó)', 9.6393, -84.5986, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-179', 'Walmart — Zona Norte (Jacó)', 9.5681, -84.646, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-180', 'Farmacia Farmacia Fischel — Zona Norte (Jacó)', 9.6042, -84.6411, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-181', 'Parque Nacional Tortuguero', 10.541, -83.504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-182', 'Plaza Central — Centro (Tortuguero)', 10.5224, -83.4978, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-183', 'Centro de Salud — Centro (Tortuguero)', 10.4882, -83.5288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-184', 'Automercado — Centro (Tortuguero)', 10.5071, -83.5494, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-185', 'Walmart — Centro (Tortuguero)', 10.5168, -83.4845, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-186', 'Farmacia Farmacia Fischel — Centro (Tortuguero)', 10.4904, -83.5379, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-187', 'Estación Delta — Centro (Tortuguero)', 10.568, -83.5311, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-188', 'Estación Uno — Centro (Tortuguero)', 10.5372, -83.4703, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-189', 'Hotel — Centro (Tortuguero)', 10.5061, -83.5455, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-190', 'Restaurante — Centro (Tortuguero)', 10.5488, -83.4543, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-191', 'Plaza Central — Zona Norte (Tortuguero)', 10.5427, -83.4877, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-192', 'Centro de Salud — Zona Norte (Tortuguero)', 10.5944, -83.5469, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-193', 'Automercado — Zona Norte (Tortuguero)', 10.5959, -83.4891, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-194', 'Walmart — Zona Norte (Tortuguero)', 10.5192, -83.4628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-195', 'Farmacia Farmacia Fischel — Zona Norte (Tortuguero)', 10.5014, -83.5481, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-196', 'Playa Cocles (Puerto Viejo)', 9.656, -82.755, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-197', 'Plaza Central — Centro (Puerto Viejo de Talamanca)', 9.6772, -82.8083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-198', 'Centro de Salud — Centro (Puerto Viejo de Talamanca)', 9.6926, -82.738, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-199', 'Automercado — Centro (Puerto Viejo de Talamanca)', 9.6723, -82.7467, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-200', 'Walmart — Centro (Puerto Viejo de Talamanca)', 9.6856, -82.7315, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-201', 'Farmacia Farmacia Fischel — Centro (Puerto Viejo de Talamanca)', 9.7104, -82.7451, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-202', 'Estación Delta — Centro (Puerto Viejo de Talamanca)', 9.6591, -82.7723, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-203', 'Estación Uno — Centro (Puerto Viejo de Talamanca)', 9.6257, -82.7063, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-204', 'Hotel — Centro (Puerto Viejo de Talamanca)', 9.639, -82.8122, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-205', 'Restaurante — Centro (Puerto Viejo de Talamanca)', 9.596, -82.7211, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-206', 'Plaza Central — Zona Norte (Puerto Viejo de Talamanca)', 9.6802, -82.7273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-207', 'Centro de Salud — Zona Norte (Puerto Viejo de Talamanca)', 9.7082, -82.802, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-208', 'Automercado — Zona Norte (Puerto Viejo de Talamanca)', 9.6734, -82.7579, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-209', 'Walmart — Zona Norte (Puerto Viejo de Talamanca)', 9.6408, -82.8138, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-210', 'Farmacia Farmacia Fischel — Zona Norte (Puerto Viejo de Talamanca)', 9.7081, -82.7339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-211', 'Playa Santa Teresa', 9.646, -85.167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-212', 'Plaza Central — Centro (Santa Teresa e Mal País)', 9.5972, -85.2177, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-213', 'Centro de Salud — Centro (Santa Teresa e Mal País)', 9.5883, -85.177, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-214', 'Automercado — Centro (Santa Teresa e Mal País)', 9.5965, -85.174, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-215', 'Walmart — Centro (Santa Teresa e Mal País)', 9.607, -85.2025, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-216', 'Farmacia Farmacia Fischel — Centro (Santa Teresa e Mal País)', 9.6538, -85.1952, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-217', 'Estación Delta — Centro (Santa Teresa e Mal País)', 9.7041, -85.1505, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-218', 'Estación Uno — Centro (Santa Teresa e Mal País)', 9.6425, -85.1862, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-219', 'Hotel — Centro (Santa Teresa e Mal País)', 9.7008, -85.1798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-220', 'Restaurante — Centro (Santa Teresa e Mal País)', 9.6008, -85.2182, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-221', 'Plaza Central — Zona Norte (Santa Teresa e Mal País)', 9.6373, -85.1224, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-222', 'Centro de Salud — Zona Norte (Santa Teresa e Mal País)', 9.6792, -85.1424, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-223', 'Automercado — Zona Norte (Santa Teresa e Mal País)', 9.5887, -85.1442, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-224', 'Walmart — Zona Norte (Santa Teresa e Mal País)', 9.6207, -85.152, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('cr150-225', 'Farmacia Farmacia Fischel — Zona Norte (Santa Teresa e Mal País)', 9.6874, -85.192, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
