-- ============================================
-- Achou Trocador — Panamá: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('pa150-001', 'Parque San Miguelito', 9.0333, -79.5, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-002', 'McDonald''s — San Miguelito', 9.024, -79.4791, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-003', 'Burger King — San Miguelito', 9.0225, -79.5069, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-004', 'KFC — San Miguelito', 9.0072, -79.4978, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-005', 'Plaza Central — Centro (San Miguelito)', 9.0196, -79.5473, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-006', 'Centro de Salud — Centro (San Miguelito)', 8.9974, -79.5597, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-007', 'Rey — Centro (San Miguelito)', 9.0874, -79.5139, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-008', 'Super 99 — Centro (San Miguelito)', 8.997, -79.5412, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-009', 'Farmacia Farmacias Arrocha — Centro (San Miguelito)', 9.0567, -79.5022, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-010', 'Estación Delta — Centro (San Miguelito)', 8.9773, -79.492, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-011', 'Estación Puma — Centro (San Miguelito)', 9.0268, -79.4893, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-012', 'Hotel — Centro (San Miguelito)', 8.9843, -79.4406, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-013', 'Restaurante — Centro (San Miguelito)', 9.0399, -79.5067, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-014', 'Plaza Central — Zona Norte (San Miguelito)', 9.0844, -79.4707, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-015', 'Centro de Salud — Zona Norte (San Miguelito)', 9.0149, -79.4735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-016', 'Rey — Zona Norte (San Miguelito)', 9.0895, -79.5536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-017', 'Super 99 — Zona Norte (San Miguelito)', 9.0266, -79.5276, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-018', 'Farmacia Farmacias Arrocha — Zona Norte (San Miguelito)', 9.0379, -79.47, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-019', 'Estación Delta — Zona Norte (San Miguelito)', 9.0102, -79.4792, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-020', 'Estación Puma — Zona Norte (San Miguelito)', 9.0379, -79.5583, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-021', 'Hotel — Zona Norte (San Miguelito)', 9.0391, -79.5194, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-022', 'Restaurante — Zona Norte (San Miguelito)', 8.9885, -79.4678, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-023', 'Plaza Central — Zona Sur (San Miguelito)', 8.995, -79.4788, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-024', 'Centro de Salud — Zona Sur (San Miguelito)', 9.0917, -79.457, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-025', 'Rey — Zona Sur (San Miguelito)', 8.9992, -79.4852, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-026', 'Super 99 — Zona Sur (San Miguelito)', 9.0566, -79.5539, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-027', 'Farmacia Farmacias Arrocha — Zona Sur (San Miguelito)', 9.0726, -79.5059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-028', 'Estación Delta — Zona Sur (San Miguelito)', 8.9741, -79.4786, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-029', 'Estación Puma — Zona Sur (San Miguelito)', 9.057, -79.49, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-030', 'Hotel — Zona Sur (San Miguelito)', 9.0461, -79.5465, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-031', 'Centro de Arraiján', 8.95, -79.65, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-032', 'Subway — Arraiján', 8.9519, -79.6311, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-033', 'Pizza Hut — Arraiján', 8.9256, -79.6412, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-034', 'Starbucks — Arraiján', 8.9282, -79.6715, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-035', 'Plaza Central — Centro (Arraiján)', 8.9878, -79.6781, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-036', 'Centro de Salud — Centro (Arraiján)', 8.9073, -79.6704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-037', 'Rey — Centro (Arraiján)', 8.8984, -79.6323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-038', 'Super 99 — Centro (Arraiján)', 9.0051, -79.6063, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-039', 'Farmacia Farmacias Arrocha — Centro (Arraiján)', 8.933, -79.6555, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-040', 'Estación Delta — Centro (Arraiján)', 8.955, -79.7026, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-041', 'Estación Puma — Centro (Arraiján)', 8.9974, -79.6256, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-042', 'Hotel — Centro (Arraiján)', 8.9138, -79.6353, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-043', 'Restaurante — Centro (Arraiján)', 8.9435, -79.6253, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-044', 'Plaza Central — Zona Norte (Arraiján)', 8.9118, -79.6485, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-045', 'Centro de Salud — Zona Norte (Arraiján)', 8.9819, -79.6815, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-046', 'Rey — Zona Norte (Arraiján)', 8.9474, -79.6905, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-047', 'Super 99 — Zona Norte (Arraiján)', 8.9125, -79.7095, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-048', 'Farmacia Farmacias Arrocha — Zona Norte (Arraiján)', 8.9136, -79.6924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-049', 'Estación Delta — Zona Norte (Arraiján)', 8.95, -79.6281, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-050', 'Estación Puma — Zona Norte (Arraiján)', 8.9673, -79.6159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-051', 'Hotel — Zona Norte (Arraiján)', 8.9426, -79.6835, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-052', 'Restaurante — Zona Norte (Arraiján)', 8.9507, -79.6586, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-053', 'Plaza Central — Zona Sur (Arraiján)', 8.972, -79.6623, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-054', 'Centro de Salud — Zona Sur (Arraiján)', 8.9184, -79.6774, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-055', 'Rey — Zona Sur (Arraiján)', 8.941, -79.6751, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-056', 'Super 99 — Zona Sur (Arraiján)', 8.9024, -79.6477, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-057', 'Farmacia Farmacias Arrocha — Zona Sur (Arraiján)', 8.9387, -79.6157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-058', 'Estación Delta — Zona Sur (Arraiján)', 8.9581, -79.708, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-059', 'Estación Puma — Zona Sur (Arraiján)', 8.903, -79.6554, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-060', 'Hotel — Zona Sur (Arraiján)', 8.9671, -79.6114, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-061', 'Parque de La Chorrera', 8.88, -79.783, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-062', 'Domino''s Pizza — La Chorrera', 8.8741, -79.7947, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-063', 'Niko''s Café — La Chorrera', 8.8901, -79.7747, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-064', 'El Trapiche — La Chorrera', 8.8538, -79.7988, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-065', 'Plaza Central — Centro (La Chorrera)', 8.932, -79.8325, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-066', 'Centro de Salud — Centro (La Chorrera)', 8.9131, -79.7428, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-067', 'Rey — Centro (La Chorrera)', 8.8398, -79.741, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-068', 'Super 99 — Centro (La Chorrera)', 8.8473, -79.7832, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-069', 'Farmacia Farmacias Arrocha — Centro (La Chorrera)', 8.9335, -79.7996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-070', 'Estación Delta — Centro (La Chorrera)', 8.8342, -79.8055, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-071', 'Estación Puma — Centro (La Chorrera)', 8.881, -79.728, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-072', 'Hotel — Centro (La Chorrera)', 8.9206, -79.7529, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-073', 'Restaurante — Centro (La Chorrera)', 8.8599, -79.7386, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-074', 'Plaza Central — Zona Norte (La Chorrera)', 8.8508, -79.7538, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-075', 'Centro de Salud — Zona Norte (La Chorrera)', 8.8638, -79.7688, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-076', 'Rey — Zona Norte (La Chorrera)', 8.8541, -79.8086, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-077', 'Super 99 — Zona Norte (La Chorrera)', 8.9091, -79.8082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-078', 'Farmacia Farmacias Arrocha — Zona Norte (La Chorrera)', 8.8224, -79.8236, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-079', 'Estación Delta — Zona Norte (La Chorrera)', 8.9032, -79.748, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-080', 'Estación Puma — Zona Norte (La Chorrera)', 8.8715, -79.7405, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-081', 'Hotel — Zona Norte (La Chorrera)', 8.8257, -79.734, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-082', 'Restaurante — Zona Norte (La Chorrera)', 8.8489, -79.7507, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-083', 'Plaza Central — Zona Sur (La Chorrera)', 8.9125, -79.8254, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-084', 'Centro de Salud — Zona Sur (La Chorrera)', 8.8699, -79.7414, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-085', 'Rey — Zona Sur (La Chorrera)', 8.8257, -79.7601, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-086', 'Super 99 — Zona Sur (La Chorrera)', 8.8223, -79.7367, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-087', 'Farmacia Farmacias Arrocha — Zona Sur (La Chorrera)', 8.8738, -79.7729, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-088', 'Estación Delta — Zona Sur (La Chorrera)', 8.8982, -79.7678, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-089', 'Estación Puma — Zona Sur (La Chorrera)', 8.9141, -79.8044, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-090', 'Hotel — Zona Sur (La Chorrera)', 8.9177, -79.7816, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-091', 'Parque Cervantes (David)', 8.4333, -82.4333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-092', 'Manolo Caracol — David (Panamá)', 8.4577, -82.4236, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-093', 'Gauchos Steak House — David (Panamá)', 8.4581, -82.4419, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-094', 'Rincón Suizo — David (Panamá)', 8.4286, -82.4179, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-095', 'Plaza Central — Centro (David (Panamá))', 8.4301, -82.3739, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-096', 'Centro de Salud — Centro (David (Panamá))', 8.3837, -82.3775, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-097', 'Rey — Centro (David (Panamá))', 8.4842, -82.3949, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-098', 'Super 99 — Centro (David (Panamá))', 8.3809, -82.3778, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-099', 'Farmacia Farmacias Arrocha — Centro (David (Panamá))', 8.3985, -82.4227, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-100', 'Estación Delta — Centro (David (Panamá))', 8.4446, -82.401, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-101', 'Estación Puma — Centro (David (Panamá))', 8.4748, -82.4824, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-102', 'Hotel — Centro (David (Panamá))', 8.4517, -82.4665, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-103', 'Restaurante — Centro (David (Panamá))', 8.483, -82.4567, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-104', 'Plaza Central — Zona Norte (David (Panamá))', 8.4295, -82.4655, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-105', 'Centro de Salud — Zona Norte (David (Panamá))', 8.4252, -82.3944, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-106', 'Rey — Zona Norte (David (Panamá))', 8.4783, -82.3938, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-107', 'Super 99 — Zona Norte (David (Panamá))', 8.3991, -82.4184, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-108', 'Farmacia Farmacias Arrocha — Zona Norte (David (Panamá))', 8.3895, -82.4485, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-109', 'Estación Delta — Zona Norte (David (Panamá))', 8.4699, -82.4039, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-110', 'Estación Puma — Zona Norte (David (Panamá))', 8.4866, -82.4488, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-111', 'Hotel — Zona Norte (David (Panamá))', 8.4872, -82.3962, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-112', 'Restaurante — Zona Norte (David (Panamá))', 8.4277, -82.464, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-113', 'Plaza Central — Zona Sur (David (Panamá))', 8.482, -82.4469, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-114', 'Centro de Salud — Zona Sur (David (Panamá))', 8.3868, -82.4319, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-115', 'Rey — Zona Sur (David (Panamá))', 8.4294, -82.4389, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-116', 'Super 99 — Zona Sur (David (Panamá))', 8.4177, -82.392, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-117', 'Farmacia Farmacias Arrocha — Zona Sur (David (Panamá))', 8.3759, -82.4277, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-118', 'Estación Delta — Zona Sur (David (Panamá))', 8.4118, -82.4826, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-119', 'Estación Puma — Zona Sur (David (Panamá))', 8.4765, -82.4552, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-120', 'Hotel — Zona Sur (David (Panamá))', 8.4811, -82.4101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-121', 'Zona Livre de Colón', 9.3547, -79.9008, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-122', 'Athens Pizza — Colón (Panamá)', 9.3799, -79.9081, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-123', 'Jimmy''s — Colón (Panamá)', 9.3567, -79.8943, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-124', 'Cochinita Pibil — Colón (Panamá)', 9.3321, -79.9176, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('pa150-125', 'Plaza Central — Centro (Colón (Panamá))', 9.345, -79.8443, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-126', 'Centro de Salud — Centro (Colón (Panamá))', 9.3815, -79.9226, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-127', 'Rey — Centro (Colón (Panamá))', 9.4141, -79.9017, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-128', 'Super 99 — Centro (Colón (Panamá))', 9.3889, -79.8442, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-129', 'Farmacia Farmacias Arrocha — Centro (Colón (Panamá))', 9.3983, -79.8925, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-130', 'Estación Delta — Centro (Colón (Panamá))', 9.4018, -79.8691, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-131', 'Estación Puma — Centro (Colón (Panamá))', 9.3114, -79.9403, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-132', 'Hotel — Centro (Colón (Panamá))', 9.3688, -79.8861, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-133', 'Restaurante — Centro (Colón (Panamá))', 9.3562, -79.9143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-134', 'Plaza Central — Zona Norte (Colón (Panamá))', 9.3858, -79.9381, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-135', 'Centro de Salud — Zona Norte (Colón (Panamá))', 9.304, -79.8884, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-136', 'Rey — Zona Norte (Colón (Panamá))', 9.3423, -79.9432, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-137', 'Super 99 — Zona Norte (Colón (Panamá))', 9.3838, -79.8913, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-138', 'Farmacia Farmacias Arrocha — Zona Norte (Colón (Panamá))', 9.4014, -79.9329, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-139', 'Estación Delta — Zona Norte (Colón (Panamá))', 9.3138, -79.8604, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-140', 'Estación Puma — Zona Norte (Colón (Panamá))', 9.3018, -79.8583, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-141', 'Hotel — Zona Norte (Colón (Panamá))', 9.3544, -79.8955, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-142', 'Restaurante — Zona Norte (Colón (Panamá))', 9.4018, -79.9368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-143', 'Plaza Central — Zona Sur (Colón (Panamá))', 9.3463, -79.8409, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-144', 'Centro de Salud — Zona Sur (Colón (Panamá))', 9.3939, -79.8909, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-145', 'Rey — Zona Sur (Colón (Panamá))', 9.3136, -79.8747, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-146', 'Super 99 — Zona Sur (Colón (Panamá))', 9.3725, -79.8693, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-147', 'Farmacia Farmacias Arrocha — Zona Sur (Colón (Panamá))', 9.3476, -79.9308, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-148', 'Estación Delta — Zona Sur (Colón (Panamá))', 9.3458, -79.9178, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-149', 'Estación Puma — Zona Sur (Colón (Panamá))', 9.2999, -79.8854, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-150', 'Hotel — Zona Sur (Colón (Panamá))', 9.301, -79.8798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-151', 'Isla Colón (Bocas del Toro)', 9.34, -82.242, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-152', 'Plaza Central — Centro (Bocas del Toro)', 9.305, -82.2958, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-153', 'Centro de Salud — Centro (Bocas del Toro)', 9.3132, -82.2298, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-154', 'Rey — Centro (Bocas del Toro)', 9.3985, -82.2159, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-155', 'Super 99 — Centro (Bocas del Toro)', 9.3878, -82.2384, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-156', 'Farmacia Farmacias Arrocha — Centro (Bocas del Toro)', 9.2972, -82.2298, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-157', 'Estación Delta — Centro (Bocas del Toro)', 9.333, -82.2585, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-158', 'Estación Puma — Centro (Bocas del Toro)', 9.331, -82.2273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-159', 'Hotel — Centro (Bocas del Toro)', 9.3416, -82.1957, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-160', 'Restaurante — Centro (Bocas del Toro)', 9.2803, -82.2536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-161', 'Plaza Central — Zona Norte (Bocas del Toro)', 9.3995, -82.1862, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-162', 'Centro de Salud — Zona Norte (Bocas del Toro)', 9.3775, -82.2391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-163', 'Rey — Zona Norte (Bocas del Toro)', 9.3527, -82.2755, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-164', 'Super 99 — Zona Norte (Bocas del Toro)', 9.3834, -82.2749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-165', 'Farmacia Farmacias Arrocha — Zona Norte (Bocas del Toro)', 9.2844, -82.1859, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-166', 'Islas de San Blas (acceso)', 9.55, -78.95, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-167', 'Plaza Central — Centro (San Blas (Guna Yala))', 9.5385, -78.8911, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-168', 'Centro de Salud — Centro (San Blas (Guna Yala))', 9.5456, -78.9193, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-169', 'Rey — Centro (San Blas (Guna Yala))', 9.5912, -79.0033, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-170', 'Super 99 — Centro (San Blas (Guna Yala))', 9.5835, -78.9472, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-171', 'Farmacia Farmacias Arrocha — Centro (San Blas (Guna Yala))', 9.5261, -78.9803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-172', 'Estación Delta — Centro (San Blas (Guna Yala))', 9.5314, -78.9923, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-173', 'Estación Puma — Centro (San Blas (Guna Yala))', 9.5687, -78.971, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-174', 'Hotel — Centro (San Blas (Guna Yala))', 9.5027, -78.8983, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-175', 'Restaurante — Centro (San Blas (Guna Yala))', 9.5141, -78.9474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-176', 'Plaza Central — Zona Norte (San Blas (Guna Yala))', 9.5415, -78.995, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-177', 'Centro de Salud — Zona Norte (San Blas (Guna Yala))', 9.5162, -78.9519, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-178', 'Rey — Zona Norte (San Blas (Guna Yala))', 9.5076, -78.9435, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-179', 'Super 99 — Zona Norte (San Blas (Guna Yala))', 9.4932, -78.9299, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-180', 'Farmacia Farmacias Arrocha — Zona Norte (San Blas (Guna Yala))', 9.543, -78.9632, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-181', 'Cráter de El Valle de Antón', 8.6, -80.13, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-182', 'Plaza Central — Centro (El Valle de Antón)', 8.6469, -80.1847, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-183', 'Centro de Salud — Centro (El Valle de Antón)', 8.5897, -80.1248, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-184', 'Rey — Centro (El Valle de Antón)', 8.645, -80.1383, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-185', 'Super 99 — Centro (El Valle de Antón)', 8.5731, -80.188, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-186', 'Farmacia Farmacias Arrocha — Centro (El Valle de Antón)', 8.5912, -80.1017, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-187', 'Estación Delta — Centro (El Valle de Antón)', 8.6332, -80.1507, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-188', 'Estación Puma — Centro (El Valle de Antón)', 8.6551, -80.1407, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-189', 'Hotel — Centro (El Valle de Antón)', 8.6354, -80.1082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-190', 'Restaurante — Centro (El Valle de Antón)', 8.6365, -80.1748, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-191', 'Plaza Central — Zona Norte (El Valle de Antón)', 8.6262, -80.1339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-192', 'Centro de Salud — Zona Norte (El Valle de Antón)', 8.543, -80.1194, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-193', 'Rey — Zona Norte (El Valle de Antón)', 8.5714, -80.1273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-194', 'Super 99 — Zona Norte (El Valle de Antón)', 8.5975, -80.1365, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-195', 'Farmacia Farmacias Arrocha — Zona Norte (El Valle de Antón)', 8.6144, -80.186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-196', 'Playa de Isla Taboga', 8.792, -79.558, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-197', 'Plaza Central — Centro (Isla Taboga)', 8.7834, -79.5574, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-198', 'Centro de Salud — Centro (Isla Taboga)', 8.7453, -79.5597, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-199', 'Rey — Centro (Isla Taboga)', 8.8455, -79.5088, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-200', 'Super 99 — Centro (Isla Taboga)', 8.772, -79.5964, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-201', 'Farmacia Farmacias Arrocha — Centro (Isla Taboga)', 8.77, -79.5911, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-202', 'Estación Delta — Centro (Isla Taboga)', 8.7453, -79.6075, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-203', 'Estación Puma — Centro (Isla Taboga)', 8.7656, -79.5642, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-204', 'Hotel — Centro (Isla Taboga)', 8.7736, -79.6157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-205', 'Restaurante — Centro (Isla Taboga)', 8.8051, -79.5753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-206', 'Plaza Central — Zona Norte (Isla Taboga)', 8.744, -79.5963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-207', 'Centro de Salud — Zona Norte (Isla Taboga)', 8.845, -79.6006, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-208', 'Rey — Zona Norte (Isla Taboga)', 8.8455, -79.5902, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-209', 'Super 99 — Zona Norte (Isla Taboga)', 8.8313, -79.5209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-210', 'Farmacia Farmacias Arrocha — Zona Norte (Isla Taboga)', 8.8498, -79.5835, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-211', 'Fuertes de Portobelo', 9.554, -79.651, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-212', 'Plaza Central — Centro (Portobelo)', 9.5413, -79.6817, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-213', 'Centro de Salud — Centro (Portobelo)', 9.5542, -79.7083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-214', 'Rey — Centro (Portobelo)', 9.5799, -79.6355, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-215', 'Super 99 — Centro (Portobelo)', 9.5909, -79.6364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-216', 'Farmacia Farmacias Arrocha — Centro (Portobelo)', 9.515, -79.6729, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-217', 'Estación Delta — Centro (Portobelo)', 9.5027, -79.595, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-218', 'Estación Puma — Centro (Portobelo)', 9.5129, -79.6086, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-219', 'Hotel — Centro (Portobelo)', 9.5384, -79.6649, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-220', 'Restaurante — Centro (Portobelo)', 9.6135, -79.6098, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-221', 'Plaza Central — Zona Norte (Portobelo)', 9.5653, -79.662, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-222', 'Centro de Salud — Zona Norte (Portobelo)', 9.5617, -79.6876, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-223', 'Rey — Zona Norte (Portobelo)', 9.5352, -79.7071, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-224', 'Super 99 — Zona Norte (Portobelo)', 9.5976, -79.6626, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('pa150-225', 'Farmacia Farmacias Arrocha — Zona Norte (Portobelo)', 9.6125, -79.5995, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
