-- ============================================
-- Achou Trocador — Rep. Dominicana: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('do150-001', 'Parque Mirador del Este', 18.47, -69.83, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-002', 'McDonald''s — Santo Domingo Este', 18.4509, -69.8333, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-003', 'Burger King — Santo Domingo Este', 18.4573, -69.8331, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-004', 'KFC — Santo Domingo Este', 18.4514, -69.8283, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-005', 'Plaza Central — Centro (Santo Domingo Este)', 18.4554, -69.8224, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-006', 'Centro de Salud — Centro (Santo Domingo Este)', 18.46, -69.8628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-007', 'La Sirena — Centro (Santo Domingo Este)', 18.4616, -69.8146, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-008', 'Jumbo (Nacional) — Centro (Santo Domingo Este)', 18.4423, -69.8437, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-009', 'Farmacia Farmacia Carol — Centro (Santo Domingo Este)', 18.5276, -69.7804, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-010', 'Estación Isla — Centro (Santo Domingo Este)', 18.4974, -69.7948, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-011', 'Estación Texaco — Centro (Santo Domingo Este)', 18.4139, -69.8856, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-012', 'Hotel — Centro (Santo Domingo Este)', 18.4743, -69.8552, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-013', 'Restaurante — Centro (Santo Domingo Este)', 18.5045, -69.876, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-014', 'Plaza Central — Zona Norte (Santo Domingo Este)', 18.473, -69.8459, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-015', 'Centro de Salud — Zona Norte (Santo Domingo Este)', 18.472, -69.8099, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-016', 'La Sirena — Zona Norte (Santo Domingo Este)', 18.5031, -69.7731, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-017', 'Jumbo (Nacional) — Zona Norte (Santo Domingo Este)', 18.4863, -69.8143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-018', 'Farmacia Farmacia Carol — Zona Norte (Santo Domingo Este)', 18.5088, -69.8403, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-019', 'Estación Isla — Zona Norte (Santo Domingo Este)', 18.486, -69.8343, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-020', 'Estación Texaco — Zona Norte (Santo Domingo Este)', 18.4985, -69.8697, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-021', 'Hotel — Zona Norte (Santo Domingo Este)', 18.5216, -69.7884, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-022', 'Restaurante — Zona Norte (Santo Domingo Este)', 18.4975, -69.7919, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-023', 'Plaza Central — Zona Sur (Santo Domingo Este)', 18.414, -69.8541, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-024', 'Centro de Salud — Zona Sur (Santo Domingo Este)', 18.5252, -69.7925, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-025', 'La Sirena — Zona Sur (Santo Domingo Este)', 18.486, -69.8486, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-026', 'Jumbo (Nacional) — Zona Sur (Santo Domingo Este)', 18.5129, -69.8842, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-027', 'Farmacia Farmacia Carol — Zona Sur (Santo Domingo Este)', 18.525, -69.7726, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-028', 'Estación Isla — Zona Sur (Santo Domingo Este)', 18.4525, -69.816, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-029', 'Estación Texaco — Zona Sur (Santo Domingo Este)', 18.4118, -69.7998, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-030', 'Hotel — Zona Sur (Santo Domingo Este)', 18.5237, -69.8726, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-031', 'Monumento a los Héroes (Santiago RD)', 19.4517, -70.697, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-032', 'Subway — Santiago de los Caballeros', 19.4676, -70.7232, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-033', 'Pizza Hut — Santiago de los Caballeros', 19.4374, -70.7024, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-034', 'Starbucks — Santiago de los Caballeros', 19.4294, -70.7139, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-035', 'Plaza Central — Centro (Santiago de los Caballeros)', 19.4327, -70.7241, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-036', 'Centro de Salud — Centro (Santiago de los Caballeros)', 19.4628, -70.7205, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-037', 'La Sirena — Centro (Santiago de los Caballeros)', 19.4122, -70.7427, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-038', 'Jumbo (Nacional) — Centro (Santiago de los Caballeros)', 19.4312, -70.7347, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-039', 'Farmacia Farmacia Carol — Centro (Santiago de los Caballeros)', 19.508, -70.6416, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-040', 'Estación Isla — Centro (Santiago de los Caballeros)', 19.4739, -70.658, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-041', 'Estación Texaco — Centro (Santiago de los Caballeros)', 19.4321, -70.7423, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-042', 'Hotel — Centro (Santiago de los Caballeros)', 19.4471, -70.7124, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-043', 'Restaurante — Centro (Santiago de los Caballeros)', 19.4755, -70.64, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-044', 'Plaza Central — Zona Norte (Santiago de los Caballeros)', 19.4913, -70.7545, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-045', 'Centro de Salud — Zona Norte (Santiago de los Caballeros)', 19.4272, -70.6728, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-046', 'La Sirena — Zona Norte (Santiago de los Caballeros)', 19.4171, -70.6468, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-047', 'Jumbo (Nacional) — Zona Norte (Santiago de los Caballeros)', 19.4077, -70.6917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-048', 'Farmacia Farmacia Carol — Zona Norte (Santiago de los Caballeros)', 19.3954, -70.7217, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-049', 'Estación Isla — Zona Norte (Santiago de los Caballeros)', 19.4051, -70.6988, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-050', 'Estación Texaco — Zona Norte (Santiago de los Caballeros)', 19.4182, -70.64, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-051', 'Hotel — Zona Norte (Santiago de los Caballeros)', 19.4145, -70.7176, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-052', 'Restaurante — Zona Norte (Santiago de los Caballeros)', 19.4483, -70.6509, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-053', 'Plaza Central — Zona Sur (Santiago de los Caballeros)', 19.406, -70.7161, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-054', 'Centro de Salud — Zona Sur (Santiago de los Caballeros)', 19.4921, -70.7096, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-055', 'La Sirena — Zona Sur (Santiago de los Caballeros)', 19.4217, -70.6941, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-056', 'Jumbo (Nacional) — Zona Sur (Santiago de los Caballeros)', 19.4369, -70.731, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-057', 'Farmacia Farmacia Carol — Zona Sur (Santiago de los Caballeros)', 19.4194, -70.6762, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-058', 'Estación Isla — Zona Sur (Santiago de los Caballeros)', 19.5013, -70.7556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-059', 'Estación Texaco — Zona Sur (Santiago de los Caballeros)', 19.4081, -70.6969, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-060', 'Hotel — Zona Sur (Santiago de los Caballeros)', 19.4704, -70.6536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-061', 'Basílica de Higüey', 18.6144, -68.7075, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-062', 'Domino''s Pizza — Higüey', 18.6021, -68.7139, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-063', 'El Conuco — Higüey', 18.6087, -68.678, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-064', 'Adrian Tropical — Higüey', 18.5888, -68.7016, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-065', 'Plaza Central — Centro (Higüey)', 18.6666, -68.7564, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-066', 'Centro de Salud — Centro (Higüey)', 18.6461, -68.6645, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-067', 'La Sirena — Centro (Higüey)', 18.6093, -68.745, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-068', 'Jumbo (Nacional) — Centro (Higüey)', 18.6536, -68.6999, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-069', 'Farmacia Farmacia Carol — Centro (Higüey)', 18.5581, -68.6941, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-070', 'Estación Isla — Centro (Higüey)', 18.5694, -68.6771, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-071', 'Estación Texaco — Centro (Higüey)', 18.6042, -68.688, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-072', 'Hotel — Centro (Higüey)', 18.5554, -68.6686, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-073', 'Restaurante — Centro (Higüey)', 18.6743, -68.649, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-074', 'Plaza Central — Zona Norte (Higüey)', 18.5629, -68.648, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-075', 'Centro de Salud — Zona Norte (Higüey)', 18.5673, -68.7259, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-076', 'La Sirena — Zona Norte (Higüey)', 18.5707, -68.7018, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-077', 'Jumbo (Nacional) — Zona Norte (Higüey)', 18.5759, -68.6723, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-078', 'Farmacia Farmacia Carol — Zona Norte (Higüey)', 18.6683, -68.6803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-079', 'Estación Isla — Zona Norte (Higüey)', 18.6281, -68.6888, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-080', 'Estación Texaco — Zona Norte (Higüey)', 18.5864, -68.6818, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-081', 'Hotel — Zona Norte (Higüey)', 18.5798, -68.6533, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-082', 'Restaurante — Zona Norte (Higüey)', 18.6729, -68.6504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-083', 'Plaza Central — Zona Sur (Higüey)', 18.5695, -68.674, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-084', 'Centro de Salud — Zona Sur (Higüey)', 18.5922, -68.6643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-085', 'La Sirena — Zona Sur (Higüey)', 18.6431, -68.749, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-086', 'Jumbo (Nacional) — Zona Sur (Higüey)', 18.5588, -68.6563, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-087', 'Farmacia Farmacia Carol — Zona Sur (Higüey)', 18.6068, -68.7234, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-088', 'Estación Isla — Zona Sur (Higüey)', 18.5719, -68.6913, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-089', 'Estación Texaco — Zona Sur (Higüey)', 18.6548, -68.754, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-090', 'Hotel — Zona Sur (Higüey)', 18.6081, -68.7257, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-091', 'Catedral de San Cristóbal', 18.4167, -70.1, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-092', 'Pat''e Palo — San Cristóbal (RD)', 18.3975, -70.0844, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-093', 'La Bricola — San Cristóbal (RD)', 18.4156, -70.0768, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-094', 'Mesón de la Cava — San Cristóbal (RD)', 18.4373, -70.1278, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-095', 'Plaza Central — Centro (San Cristóbal (RD))', 18.3728, -70.1484, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-096', 'Centro de Salud — Centro (San Cristóbal (RD))', 18.4641, -70.0494, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-097', 'La Sirena — Centro (San Cristóbal (RD))', 18.399, -70.0907, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-098', 'Jumbo (Nacional) — Centro (San Cristóbal (RD))', 18.3968, -70.1052, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-099', 'Farmacia Farmacia Carol — Centro (San Cristóbal (RD))', 18.4289, -70.1323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-100', 'Estación Isla — Centro (San Cristóbal (RD))', 18.4431, -70.0472, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-101', 'Estación Texaco — Centro (San Cristóbal (RD))', 18.3656, -70.0566, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-102', 'Hotel — Centro (San Cristóbal (RD))', 18.4373, -70.0613, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-103', 'Restaurante — Centro (San Cristóbal (RD))', 18.3888, -70.128, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-104', 'Plaza Central — Zona Norte (San Cristóbal (RD))', 18.3959, -70.0413, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-105', 'Centro de Salud — Zona Norte (San Cristóbal (RD))', 18.4227, -70.1171, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-106', 'La Sirena — Zona Norte (San Cristóbal (RD))', 18.4344, -70.0578, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-107', 'Jumbo (Nacional) — Zona Norte (San Cristóbal (RD))', 18.4291, -70.1231, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-108', 'Farmacia Farmacia Carol — Zona Norte (San Cristóbal (RD))', 18.4537, -70.1064, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-109', 'Estación Isla — Zona Norte (San Cristóbal (RD))', 18.4193, -70.1565, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-110', 'Estación Texaco — Zona Norte (San Cristóbal (RD))', 18.3641, -70.1391, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-111', 'Hotel — Zona Norte (San Cristóbal (RD))', 18.4007, -70.1304, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-112', 'Restaurante — Zona Norte (San Cristóbal (RD))', 18.4506, -70.1176, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-113', 'Plaza Central — Zona Sur (San Cristóbal (RD))', 18.424, -70.0754, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-114', 'Centro de Salud — Zona Sur (San Cristóbal (RD))', 18.4468, -70.0785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-115', 'La Sirena — Zona Sur (San Cristóbal (RD))', 18.4069, -70.0542, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-116', 'Jumbo (Nacional) — Zona Sur (San Cristóbal (RD))', 18.3828, -70.1233, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-117', 'Farmacia Farmacia Carol — Zona Sur (San Cristóbal (RD))', 18.3846, -70.095, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-118', 'Estación Isla — Zona Sur (San Cristóbal (RD))', 18.4107, -70.1141, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-119', 'Estación Texaco — Zona Sur (San Cristóbal (RD))', 18.3603, -70.1322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-120', 'Hotel — Zona Sur (San Cristóbal (RD))', 18.4572, -70.1482, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-121', 'Catedral de La Vega', 19.2233, -70.5292, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-122', 'Jalao — La Vega (RD)', 19.2248, -70.5076, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-123', 'Mesón D''Bari — La Vega (RD)', 19.2041, -70.525, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-124', 'Zumo — La Vega (RD)', 19.2375, -70.5099, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('do150-125', 'Plaza Central — Centro (La Vega (RD))', 19.1699, -70.5241, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-126', 'Centro de Salud — Centro (La Vega (RD))', 19.2109, -70.5568, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-127', 'La Sirena — Centro (La Vega (RD))', 19.2493, -70.4913, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-128', 'Jumbo (Nacional) — Centro (La Vega (RD))', 19.187, -70.474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-129', 'Farmacia Farmacia Carol — Centro (La Vega (RD))', 19.2827, -70.5275, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-130', 'Estación Isla — Centro (La Vega (RD))', 19.197, -70.5198, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-131', 'Estación Texaco — Centro (La Vega (RD))', 19.283, -70.4836, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-132', 'Hotel — Centro (La Vega (RD))', 19.2402, -70.5387, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-133', 'Restaurante — Centro (La Vega (RD))', 19.1924, -70.5172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-134', 'Plaza Central — Zona Norte (La Vega (RD))', 19.2026, -70.4954, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-135', 'Centro de Salud — Zona Norte (La Vega (RD))', 19.2745, -70.5752, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-136', 'La Sirena — Zona Norte (La Vega (RD))', 19.2798, -70.5294, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-137', 'Jumbo (Nacional) — Zona Norte (La Vega (RD))', 19.2544, -70.5429, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-138', 'Farmacia Farmacia Carol — Zona Norte (La Vega (RD))', 19.2549, -70.5738, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-139', 'Estación Isla — Zona Norte (La Vega (RD))', 19.2164, -70.589, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-140', 'Estación Texaco — Zona Norte (La Vega (RD))', 19.2035, -70.5078, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-141', 'Hotel — Zona Norte (La Vega (RD))', 19.251, -70.4729, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-142', 'Restaurante — Zona Norte (La Vega (RD))', 19.2068, -70.5003, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-143', 'Plaza Central — Zona Sur (La Vega (RD))', 19.1947, -70.5829, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-144', 'Centro de Salud — Zona Sur (La Vega (RD))', 19.2034, -70.5647, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-145', 'La Sirena — Zona Sur (La Vega (RD))', 19.2406, -70.4844, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-146', 'Jumbo (Nacional) — Zona Sur (La Vega (RD))', 19.2685, -70.5799, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-147', 'Farmacia Farmacia Carol — Zona Sur (La Vega (RD))', 19.2782, -70.5121, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-148', 'Estación Isla — Zona Sur (La Vega (RD))', 19.2512, -70.5653, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-149', 'Estación Texaco — Zona Sur (La Vega (RD))', 19.2181, -70.4942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-150', 'Hotel — Zona Sur (La Vega (RD))', 19.2773, -70.5537, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-151', 'Playa Bávaro (Punta Cana)', 18.5601, -68.3725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-152', 'Plaza Central — Centro (Punta Cana e Bávaro)', 18.5691, -68.3721, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-153', 'Centro de Salud — Centro (Punta Cana e Bávaro)', 18.5112, -68.3306, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-154', 'La Sirena — Centro (Punta Cana e Bávaro)', 18.5134, -68.4195, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-155', 'Jumbo (Nacional) — Centro (Punta Cana e Bávaro)', 18.5604, -68.4187, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-156', 'Farmacia Farmacia Carol — Centro (Punta Cana e Bávaro)', 18.5764, -68.3377, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-157', 'Estación Isla — Centro (Punta Cana e Bávaro)', 18.5604, -68.378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-158', 'Estación Texaco — Centro (Punta Cana e Bávaro)', 18.5505, -68.3206, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-159', 'Hotel — Centro (Punta Cana e Bávaro)', 18.5615, -68.4204, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-160', 'Restaurante — Centro (Punta Cana e Bávaro)', 18.6029, -68.3882, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-161', 'Plaza Central — Zona Norte (Punta Cana e Bávaro)', 18.6106, -68.4053, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-162', 'Centro de Salud — Zona Norte (Punta Cana e Bávaro)', 18.5482, -68.3227, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-163', 'La Sirena — Zona Norte (Punta Cana e Bávaro)', 18.5353, -68.3757, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-164', 'Jumbo (Nacional) — Zona Norte (Punta Cana e Bávaro)', 18.5222, -68.3251, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-165', 'Farmacia Farmacia Carol — Zona Norte (Punta Cana e Bávaro)', 18.5202, -68.3438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-166', 'Teleférico de Puerto Plata', 19.78, -70.7, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-167', 'Plaza Central — Centro (Puerto Plata e Playa Dorada)', 19.8167, -70.7212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-168', 'Centro de Salud — Centro (Puerto Plata e Playa Dorada)', 19.8474, -70.7206, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-169', 'La Sirena — Centro (Puerto Plata e Playa Dorada)', 19.8369, -70.6618, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-170', 'Jumbo (Nacional) — Centro (Puerto Plata e Playa Dorada)', 19.7538, -70.7287, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-171', 'Farmacia Farmacia Carol — Centro (Puerto Plata e Playa Dorada)', 19.8041, -70.7326, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-172', 'Estación Isla — Centro (Puerto Plata e Playa Dorada)', 19.737, -70.6963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-173', 'Estación Texaco — Centro (Puerto Plata e Playa Dorada)', 19.7892, -70.7254, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-174', 'Hotel — Centro (Puerto Plata e Playa Dorada)', 19.8103, -70.6801, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-175', 'Restaurante — Centro (Puerto Plata e Playa Dorada)', 19.8288, -70.7276, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-176', 'Plaza Central — Zona Norte (Puerto Plata e Playa Dorada)', 19.7619, -70.6922, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-177', 'Centro de Salud — Zona Norte (Puerto Plata e Playa Dorada)', 19.7862, -70.7303, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-178', 'La Sirena — Zona Norte (Puerto Plata e Playa Dorada)', 19.7741, -70.7376, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-179', 'Jumbo (Nacional) — Zona Norte (Puerto Plata e Playa Dorada)', 19.8262, -70.6414, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-180', 'Farmacia Farmacia Carol — Zona Norte (Puerto Plata e Playa Dorada)', 19.7514, -70.6442, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-181', 'Playa Las Terrenas', 19.3167, -69.55, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-182', 'Plaza Central — Centro (Las Terrenas)', 19.3734, -69.5477, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-183', 'Centro de Salud — Centro (Las Terrenas)', 19.2844, -69.5669, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-184', 'La Sirena — Centro (Las Terrenas)', 19.2669, -69.5106, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-185', 'Jumbo (Nacional) — Centro (Las Terrenas)', 19.3703, -69.6029, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-186', 'Farmacia Farmacia Carol — Centro (Las Terrenas)', 19.2924, -69.5868, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-187', 'Estación Isla — Centro (Las Terrenas)', 19.2794, -69.4924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-188', 'Estación Texaco — Centro (Las Terrenas)', 19.3114, -69.5368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-189', 'Hotel — Centro (Las Terrenas)', 19.306, -69.564, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-190', 'Restaurante — Centro (Las Terrenas)', 19.3501, -69.6073, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-191', 'Plaza Central — Zona Norte (Las Terrenas)', 19.2578, -69.5624, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-192', 'Centro de Salud — Zona Norte (Las Terrenas)', 19.3077, -69.5479, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-193', 'La Sirena — Zona Norte (Las Terrenas)', 19.3625, -69.5219, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-194', 'Jumbo (Nacional) — Zona Norte (Las Terrenas)', 19.3371, -69.5144, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-195', 'Farmacia Farmacia Carol — Zona Norte (Las Terrenas)', 19.3727, -69.5942, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-196', 'Isla Saona (acceso Bayahibe)', 18.167, -68.7, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-197', 'Plaza Central — Centro (Bayahibe e Isla Saona)', 18.3893, -68.7931, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-198', 'Centro de Salud — Centro (Bayahibe e Isla Saona)', 18.4045, -68.8365, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-199', 'La Sirena — Centro (Bayahibe e Isla Saona)', 18.3951, -68.8486, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-200', 'Jumbo (Nacional) — Centro (Bayahibe e Isla Saona)', 18.417, -68.8364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-201', 'Farmacia Farmacia Carol — Centro (Bayahibe e Isla Saona)', 18.4295, -68.8984, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-202', 'Estación Isla — Centro (Bayahibe e Isla Saona)', 18.3928, -68.8476, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-203', 'Estación Texaco — Centro (Bayahibe e Isla Saona)', 18.3573, -68.8527, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-204', 'Hotel — Centro (Bayahibe e Isla Saona)', 18.3956, -68.9055, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-205', 'Restaurante — Centro (Bayahibe e Isla Saona)', 18.3345, -68.8172, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-206', 'Plaza Central — Zona Norte (Bayahibe e Isla Saona)', 18.3234, -68.8561, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-207', 'Centro de Salud — Zona Norte (Bayahibe e Isla Saona)', 18.3507, -68.8149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-208', 'La Sirena — Zona Norte (Bayahibe e Isla Saona)', 18.3773, -68.8129, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-209', 'Jumbo (Nacional) — Zona Norte (Bayahibe e Isla Saona)', 18.3969, -68.8722, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-210', 'Farmacia Farmacia Carol — Zona Norte (Bayahibe e Isla Saona)', 18.4307, -68.8619, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-211', 'Bahía de Samaná', 19.2058, -69.3364, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-212', 'Plaza Central — Centro (Samaná e Cayo Levantado)', 19.1603, -69.2875, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-213', 'Centro de Salud — Centro (Samaná e Cayo Levantado)', 19.2116, -69.3059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-214', 'La Sirena — Centro (Samaná e Cayo Levantado)', 19.2371, -69.288, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-215', 'Jumbo (Nacional) — Centro (Samaná e Cayo Levantado)', 19.2248, -69.372, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-216', 'Farmacia Farmacia Carol — Centro (Samaná e Cayo Levantado)', 19.1966, -69.3518, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-217', 'Estación Isla — Centro (Samaná e Cayo Levantado)', 19.2207, -69.3527, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-218', 'Estación Texaco — Centro (Samaná e Cayo Levantado)', 19.2335, -69.3357, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-219', 'Hotel — Centro (Samaná e Cayo Levantado)', 19.2544, -69.3609, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-220', 'Restaurante — Centro (Samaná e Cayo Levantado)', 19.2395, -69.3584, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-221', 'Plaza Central — Zona Norte (Samaná e Cayo Levantado)', 19.2234, -69.2928, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-222', 'Centro de Salud — Zona Norte (Samaná e Cayo Levantado)', 19.2348, -69.295, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-223', 'La Sirena — Zona Norte (Samaná e Cayo Levantado)', 19.2385, -69.2791, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-224', 'Jumbo (Nacional) — Zona Norte (Samaná e Cayo Levantado)', 19.2354, -69.3058, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('do150-225', 'Farmacia Farmacia Carol — Zona Norte (Samaná e Cayo Levantado)', 19.1992, -69.322, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
