-- ============================================
-- Achou Trocador — Venezuela: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('ve150-001', 'Plaza Bolívar de Maracay', 10.2469, -67.5958, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-002', 'McDonald''s — Maracay', 10.2295, -67.6183, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-003', 'Burger King — Maracay', 10.2354, -67.5852, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-004', 'KFC — Maracay', 10.2534, -67.6065, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-005', 'Plaza Central — Centro (Maracay)', 10.3025, -67.5544, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-006', 'Centro de Salud — Centro (Maracay)', 10.2986, -67.5727, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-007', 'Central Madeirense — Centro (Maracay)', 10.2656, -67.5628, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-008', 'Automercados Plaza''s — Centro (Maracay)', 10.2094, -67.5387, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-009', 'Farmacia Farmatodo — Centro (Maracay)', 10.2195, -67.643, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-010', 'Estación PDV — Centro (Maracay)', 10.205, -67.6149, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-011', 'Hotel — Centro (Maracay)', 10.2183, -67.5974, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-012', 'Restaurante — Centro (Maracay)', 10.2744, -67.5912, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-013', 'Plaza Central — Zona Norte (Maracay)', 10.2317, -67.6535, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-014', 'Centro de Salud — Zona Norte (Maracay)', 10.2532, -67.5914, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-015', 'Central Madeirense — Zona Norte (Maracay)', 10.3058, -67.6516, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-016', 'Automercados Plaza''s — Zona Norte (Maracay)', 10.2242, -67.5484, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-017', 'Farmacia Farmatodo — Zona Norte (Maracay)', 10.2902, -67.6408, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-018', 'Estación PDV — Zona Norte (Maracay)', 10.2126, -67.6076, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-019', 'Hotel — Zona Norte (Maracay)', 10.2152, -67.6358, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-020', 'Restaurante — Zona Norte (Maracay)', 10.2363, -67.5992, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-021', 'Plaza Central — Zona Sur (Maracay)', 10.2147, -67.5607, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-022', 'Centro de Salud — Zona Sur (Maracay)', 10.1981, -67.5599, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-023', 'Central Madeirense — Zona Sur (Maracay)', 10.2749, -67.6479, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-024', 'Automercados Plaza''s — Zona Sur (Maracay)', 10.1999, -67.5876, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-025', 'Farmacia Farmatodo — Zona Sur (Maracay)', 10.2607, -67.5847, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-026', 'Estación PDV — Zona Sur (Maracay)', 10.2371, -67.5562, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-027', 'Hotel — Zona Sur (Maracay)', 10.2466, -67.6475, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-028', 'Restaurante — Zona Sur (Maracay)', 10.2571, -67.614, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-029', 'Plaza Central — Zona Este (Maracay)', 10.2394, -67.5441, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-030', 'Centro de Salud — Zona Este (Maracay)', 10.2508, -67.6281, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-031', 'Catedral de Maturín', 9.745, -63.178, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-032', 'Subway — Maturín', 9.7559, -63.1541, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-033', 'Pizza Hut — Maturín', 9.745, -63.174, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-034', 'Starbucks — Maturín', 9.7381, -63.1907, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-035', 'Plaza Central — Centro (Maturín)', 9.7119, -63.1186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-036', 'Centro de Salud — Centro (Maturín)', 9.7112, -63.1848, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-037', 'Central Madeirense — Centro (Maturín)', 9.7658, -63.1186, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-038', 'Automercados Plaza''s — Centro (Maturín)', 9.7976, -63.143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-039', 'Farmacia Farmatodo — Centro (Maturín)', 9.8006, -63.1237, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-040', 'Estación PDV — Centro (Maturín)', 9.7813, -63.1382, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-041', 'Hotel — Centro (Maturín)', 9.7039, -63.1425, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-042', 'Restaurante — Centro (Maturín)', 9.6932, -63.17, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-043', 'Plaza Central — Zona Norte (Maturín)', 9.7404, -63.1248, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-044', 'Centro de Salud — Zona Norte (Maturín)', 9.6988, -63.1803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-045', 'Central Madeirense — Zona Norte (Maturín)', 9.7044, -63.2151, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-046', 'Automercados Plaza''s — Zona Norte (Maturín)', 9.6995, -63.215, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-047', 'Farmacia Farmatodo — Zona Norte (Maturín)', 9.7662, -63.2034, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-048', 'Estación PDV — Zona Norte (Maturín)', 9.7045, -63.1964, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-049', 'Hotel — Zona Norte (Maturín)', 9.7294, -63.2191, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-050', 'Restaurante — Zona Norte (Maturín)', 9.7259, -63.1313, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-051', 'Plaza Central — Zona Sur (Maturín)', 9.783, -63.2265, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-052', 'Centro de Salud — Zona Sur (Maturín)', 9.7412, -63.2129, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-053', 'Central Madeirense — Zona Sur (Maturín)', 9.7357, -63.1339, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-054', 'Automercados Plaza''s — Zona Sur (Maturín)', 9.7108, -63.2074, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-055', 'Farmacia Farmatodo — Zona Sur (Maturín)', 9.7343, -63.2238, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-056', 'Estación PDV — Zona Sur (Maturín)', 9.7829, -63.205, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-057', 'Hotel — Zona Sur (Maturín)', 9.8005, -63.1529, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-058', 'Restaurante — Zona Sur (Maturín)', 9.7765, -63.1489, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-059', 'Plaza Central — Zona Este (Maturín)', 9.698, -63.2264, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-060', 'Centro de Salud — Zona Este (Maturín)', 9.8032, -63.1294, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-061', 'Casa Fuerte de Barcelona', 10.1333, -64.6833, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-062', 'Domino''s Pizza — Barcelona (Venezuela)', 10.1486, -64.6563, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-063', 'Arturo''s — Barcelona (Venezuela)', 10.1282, -64.6857, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-064', 'Doña Arepa — Barcelona (Venezuela)', 10.1512, -64.6728, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-065', 'Plaza Central — Centro (Barcelona (Venezuela))', 10.1584, -64.6549, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-066', 'Centro de Salud — Centro (Barcelona (Venezuela))', 10.0837, -64.6525, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-067', 'Central Madeirense — Centro (Barcelona (Venezuela))', 10.175, -64.7244, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-068', 'Automercados Plaza''s — Centro (Barcelona (Venezuela))', 10.1358, -64.6853, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-069', 'Farmacia Farmatodo — Centro (Barcelona (Venezuela))', 10.0812, -64.6666, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-070', 'Estación PDV — Centro (Barcelona (Venezuela))', 10.1139, -64.7307, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-071', 'Hotel — Centro (Barcelona (Venezuela))', 10.1495, -64.6712, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-072', 'Restaurante — Centro (Barcelona (Venezuela))', 10.0939, -64.703, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-073', 'Plaza Central — Zona Norte (Barcelona (Venezuela))', 10.1571, -64.673, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-074', 'Centro de Salud — Zona Norte (Barcelona (Venezuela))', 10.1653, -64.7358, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-075', 'Central Madeirense — Zona Norte (Barcelona (Venezuela))', 10.1629, -64.7289, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-076', 'Automercados Plaza''s — Zona Norte (Barcelona (Venezuela))', 10.0904, -64.7314, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-077', 'Farmacia Farmatodo — Zona Norte (Barcelona (Venezuela))', 10.1453, -64.721, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-078', 'Estación PDV — Zona Norte (Barcelona (Venezuela))', 10.1651, -64.7134, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-079', 'Hotel — Zona Norte (Barcelona (Venezuela))', 10.0854, -64.685, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-080', 'Restaurante — Zona Norte (Barcelona (Venezuela))', 10.1255, -64.7333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-081', 'Plaza Central — Zona Sur (Barcelona (Venezuela))', 10.0805, -64.7349, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-082', 'Centro de Salud — Zona Sur (Barcelona (Venezuela))', 10.1411, -64.644, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-083', 'Central Madeirense — Zona Sur (Barcelona (Venezuela))', 10.1566, -64.6374, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-084', 'Automercados Plaza''s — Zona Sur (Barcelona (Venezuela))', 10.1739, -64.6258, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-085', 'Farmacia Farmatodo — Zona Sur (Barcelona (Venezuela))', 10.1646, -64.7114, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-086', 'Estación PDV — Zona Sur (Barcelona (Venezuela))', 10.15, -64.7153, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-087', 'Hotel — Zona Sur (Barcelona (Venezuela))', 10.1837, -64.6618, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-088', 'Restaurante — Zona Sur (Barcelona (Venezuela))', 10.1097, -64.6916, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-089', 'Plaza Central — Zona Este (Barcelona (Venezuela))', 10.1552, -64.6669, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-090', 'Centro de Salud — Zona Este (Barcelona (Venezuela))', 10.1196, -64.7139, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-091', 'Paseo Orinoco (Ciudad Bolívar)', 8.1222, -63.5497, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-092', 'Areperas El Punto Criollo — Ciudad Bolívar', 8.1368, -63.5693, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-093', 'Panadería Alba — Ciudad Bolívar', 8.1094, -63.5653, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-094', 'La Huerta — Ciudad Bolívar', 8.1266, -63.5703, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-095', 'Plaza Central — Centro (Ciudad Bolívar)', 8.1644, -63.4979, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-096', 'Centro de Salud — Centro (Ciudad Bolívar)', 8.1801, -63.6007, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-097', 'Central Madeirense — Centro (Ciudad Bolívar)', 8.0939, -63.4929, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-098', 'Automercados Plaza''s — Centro (Ciudad Bolívar)', 8.1076, -63.596, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-099', 'Farmacia Farmatodo — Centro (Ciudad Bolívar)', 8.0635, -63.4991, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-100', 'Estación PDV — Centro (Ciudad Bolívar)', 8.1043, -63.5037, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-101', 'Hotel — Centro (Ciudad Bolívar)', 8.169, -63.5944, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-102', 'Restaurante — Centro (Ciudad Bolívar)', 8.1058, -63.5544, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-103', 'Plaza Central — Zona Norte (Ciudad Bolívar)', 8.1641, -63.5371, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-104', 'Centro de Salud — Zona Norte (Ciudad Bolívar)', 8.1674, -63.5618, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-105', 'Central Madeirense — Zona Norte (Ciudad Bolívar)', 8.1721, -63.503, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-106', 'Automercados Plaza''s — Zona Norte (Ciudad Bolívar)', 8.0759, -63.5161, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-107', 'Farmacia Farmatodo — Zona Norte (Ciudad Bolívar)', 8.1385, -63.5638, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-108', 'Estación PDV — Zona Norte (Ciudad Bolívar)', 8.0622, -63.5307, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-109', 'Hotel — Zona Norte (Ciudad Bolívar)', 8.066, -63.5612, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-110', 'Restaurante — Zona Norte (Ciudad Bolívar)', 8.1389, -63.5816, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-111', 'Plaza Central — Zona Sur (Ciudad Bolívar)', 8.1717, -63.5449, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-112', 'Centro de Salud — Zona Sur (Ciudad Bolívar)', 8.1605, -63.5028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-113', 'Central Madeirense — Zona Sur (Ciudad Bolívar)', 8.1227, -63.559, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-114', 'Automercados Plaza''s — Zona Sur (Ciudad Bolívar)', 8.1086, -63.504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-115', 'Farmacia Farmatodo — Zona Sur (Ciudad Bolívar)', 8.0768, -63.5842, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-116', 'Estación PDV — Zona Sur (Ciudad Bolívar)', 8.0846, -63.5333, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-117', 'Hotel — Zona Sur (Ciudad Bolívar)', 8.1302, -63.5855, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-118', 'Restaurante — Zona Sur (Ciudad Bolívar)', 8.1489, -63.559, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-119', 'Plaza Central — Zona Este (Ciudad Bolívar)', 8.0974, -63.5504, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-120', 'Centro de Salud — Zona Este (Ciudad Bolívar)', 8.1476, -63.5948, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-121', 'Teleférico de Mérida (Venezuela)', 8.592, -71.162, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-122', 'Tostadas El Buen Sabor — Mérida (Venezuela)', 8.6085, -71.1864, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-123', 'Mister Donut Venezuela — Mérida (Venezuela)', 8.605, -71.1844, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-124', 'Frescolita Bar — Mérida (Venezuela)', 8.5979, -71.1847, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('ve150-125', 'Plaza Central — Centro (Mérida (Venezuela))', 8.542, -71.1059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-126', 'Centro de Salud — Centro (Mérida (Venezuela))', 8.5911, -71.1378, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-127', 'Central Madeirense — Centro (Mérida (Venezuela))', 8.58, -71.2028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-128', 'Automercados Plaza''s — Centro (Mérida (Venezuela))', 8.641, -71.203, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-129', 'Farmacia Farmatodo — Centro (Mérida (Venezuela))', 8.6139, -71.126, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-130', 'Estación PDV — Centro (Mérida (Venezuela))', 8.6098, -71.13, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-131', 'Hotel — Centro (Mérida (Venezuela))', 8.649, -71.1429, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-132', 'Restaurante — Centro (Mérida (Venezuela))', 8.5376, -71.1768, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-133', 'Plaza Central — Zona Norte (Mérida (Venezuela))', 8.5597, -71.148, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-134', 'Centro de Salud — Zona Norte (Mérida (Venezuela))', 8.5915, -71.2052, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-135', 'Central Madeirense — Zona Norte (Mérida (Venezuela))', 8.5852, -71.2078, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-136', 'Automercados Plaza''s — Zona Norte (Mérida (Venezuela))', 8.5325, -71.1959, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-137', 'Farmacia Farmatodo — Zona Norte (Mérida (Venezuela))', 8.602, -71.1316, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-138', 'Estación PDV — Zona Norte (Mérida (Venezuela))', 8.554, -71.1177, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-139', 'Hotel — Zona Norte (Mérida (Venezuela))', 8.6046, -71.1812, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-140', 'Restaurante — Zona Norte (Mérida (Venezuela))', 8.6448, -71.1993, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-141', 'Plaza Central — Zona Sur (Mérida (Venezuela))', 8.5971, -71.1212, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-142', 'Centro de Salud — Zona Sur (Mérida (Venezuela))', 8.5675, -71.1774, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-143', 'Central Madeirense — Zona Sur (Mérida (Venezuela))', 8.5743, -71.1147, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-144', 'Automercados Plaza''s — Zona Sur (Mérida (Venezuela))', 8.5977, -71.1963, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-145', 'Farmacia Farmatodo — Zona Sur (Mérida (Venezuela))', 8.5706, -71.1436, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-146', 'Estación PDV — Zona Sur (Mérida (Venezuela))', 8.5979, -71.1764, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-147', 'Hotel — Zona Sur (Mérida (Venezuela))', 8.5476, -71.1947, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-148', 'Restaurante — Zona Sur (Mérida (Venezuela))', 8.5522, -71.1458, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-149', 'Plaza Central — Zona Este (Mérida (Venezuela))', 8.62, -71.1091, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-150', 'Centro de Salud — Zona Este (Mérida (Venezuela))', 8.6435, -71.17, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-151', 'Playa El Agua (Margarita)', 11.133, -63.833, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-152', 'Plaza Central — Centro (Isla de Margarita (Porlamar))', 10.9617, -63.8699, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-153', 'Centro de Salud — Centro (Isla de Margarita (Porlamar))', 10.9014, -63.9044, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-154', 'Central Madeirense — Centro (Isla de Margarita (Porlamar))', 10.9174, -63.8696, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-155', 'Automercados Plaza''s — Centro (Isla de Margarita (Porlamar))', 10.9406, -63.8524, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-156', 'Farmacia Farmatodo — Centro (Isla de Margarita (Porlamar))', 10.9326, -63.8101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-157', 'Estación PDV — Centro (Isla de Margarita (Porlamar))', 11.0119, -63.8502, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-158', 'Hotel — Centro (Isla de Margarita (Porlamar))', 10.9272, -63.8588, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-159', 'Restaurante — Centro (Isla de Margarita (Porlamar))', 10.9392, -63.8075, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-160', 'Plaza Central — Zona Norte (Isla de Margarita (Porlamar))', 10.9338, -63.821, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-161', 'Centro de Salud — Zona Norte (Isla de Margarita (Porlamar))', 11.0169, -63.856, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-162', 'Central Madeirense — Zona Norte (Isla de Margarita (Porlamar))', 11.0035, -63.8459, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-163', 'Automercados Plaza''s — Zona Norte (Isla de Margarita (Porlamar))', 10.9329, -63.8888, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-164', 'Farmacia Farmatodo — Zona Norte (Isla de Margarita (Porlamar))', 10.9401, -63.8232, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-165', 'Estación PDV — Zona Norte (Isla de Margarita (Porlamar))', 11.012, -63.8767, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-166', 'Salto Ángel (acceso Canaima)', 5.97, -62.536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-167', 'Plaza Central — Centro (Canaima e Salto Ángel)', 6.1981, -62.9117, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-168', 'Centro de Salud — Centro (Canaima e Salto Ángel)', 6.1744, -62.8166, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-169', 'Central Madeirense — Centro (Canaima e Salto Ángel)', 6.2845, -62.8286, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-170', 'Automercados Plaza''s — Centro (Canaima e Salto Ángel)', 6.2147, -62.8956, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-171', 'Farmacia Farmatodo — Centro (Canaima e Salto Ángel)', 6.1765, -62.8803, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-172', 'Estación PDV — Centro (Canaima e Salto Ángel)', 6.2438, -62.8176, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-173', 'Hotel — Centro (Canaima e Salto Ángel)', 6.2448, -62.8629, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-174', 'Restaurante — Centro (Canaima e Salto Ángel)', 6.1762, -62.9095, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-175', 'Plaza Central — Zona Norte (Canaima e Salto Ángel)', 6.247, -62.8706, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-176', 'Centro de Salud — Zona Norte (Canaima e Salto Ángel)', 6.2734, -62.8566, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-177', 'Central Madeirense — Zona Norte (Canaima e Salto Ángel)', 6.214, -62.8243, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-178', 'Automercados Plaza''s — Zona Norte (Canaima e Salto Ángel)', 6.2254, -62.8567, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-179', 'Farmacia Farmatodo — Zona Norte (Canaima e Salto Ángel)', 6.1792, -62.8511, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-180', 'Estación PDV — Zona Norte (Canaima e Salto Ángel)', 6.2726, -62.8804, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-181', 'Archipiélago Los Roques', 11.8167, -66.6667, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-182', 'Plaza Central — Centro (Los Roques)', 11.876, -66.6218, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-183', 'Centro de Salud — Centro (Los Roques)', 11.7988, -66.614, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-184', 'Central Madeirense — Centro (Los Roques)', 11.7816, -66.6735, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-185', 'Automercados Plaza''s — Centro (Los Roques)', 11.8298, -66.641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-186', 'Farmacia Farmatodo — Centro (Los Roques)', 11.8334, -66.6423, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-187', 'Estación PDV — Centro (Los Roques)', 11.8678, -66.7091, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-188', 'Hotel — Centro (Los Roques)', 11.8514, -66.7229, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-189', 'Restaurante — Centro (Los Roques)', 11.8556, -66.6208, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-190', 'Plaza Central — Zona Norte (Los Roques)', 11.8582, -66.6503, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-191', 'Centro de Salud — Zona Norte (Los Roques)', 11.8323, -66.692, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-192', 'Central Madeirense — Zona Norte (Los Roques)', 11.7605, -66.7141, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-193', 'Automercados Plaza''s — Zona Norte (Los Roques)', 11.8006, -66.69, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-194', 'Farmacia Farmatodo — Zona Norte (Los Roques)', 11.7929, -66.6654, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-195', 'Estación PDV — Zona Norte (Los Roques)', 11.7601, -66.6251, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-196', 'Pico Bolívar (acceso Mérida)', 8.556, -71.045, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-197', 'Plaza Central — Centro (Mérida (turística, Venezuela))', 8.6159, -71.2021, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-198', 'Centro de Salud — Centro (Mérida (turística, Venezuela))', 8.5499, -71.1447, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-199', 'Central Madeirense — Centro (Mérida (turística, Venezuela))', 8.5752, -71.1335, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-200', 'Automercados Plaza''s — Centro (Mérida (turística, Venezuela))', 8.5491, -71.2187, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-201', 'Farmacia Farmatodo — Centro (Mérida (turística, Venezuela))', 8.6395, -71.1169, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-202', 'Estación PDV — Centro (Mérida (turística, Venezuela))', 8.591, -71.1049, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-203', 'Hotel — Centro (Mérida (turística, Venezuela))', 8.5603, -71.1536, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-204', 'Restaurante — Centro (Mérida (turística, Venezuela))', 8.5922, -71.1157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-205', 'Plaza Central — Zona Norte (Mérida (turística, Venezuela))', 8.6115, -71.1243, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-206', 'Centro de Salud — Zona Norte (Mérida (turística, Venezuela))', 8.5529, -71.1723, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-207', 'Central Madeirense — Zona Norte (Mérida (turística, Venezuela))', 8.6073, -71.1093, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-208', 'Automercados Plaza''s — Zona Norte (Mérida (turística, Venezuela))', 8.5645, -71.2143, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-209', 'Farmacia Farmatodo — Zona Norte (Mérida (turística, Venezuela))', 8.6001, -71.1083, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-210', 'Estación PDV — Zona Norte (Mérida (turística, Venezuela))', 8.6301, -71.141, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-211', 'Parque Nacional Morrocoy', 10.85, -68.217, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-212', 'Plaza Central — Centro (Morrocoy)', 10.795, -68.1761, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-213', 'Centro de Salud — Centro (Morrocoy)', 10.8374, -68.2593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-214', 'Central Madeirense — Centro (Morrocoy)', 10.8073, -68.2672, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-215', 'Automercados Plaza''s — Centro (Morrocoy)', 10.8272, -68.1795, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-216', 'Farmacia Farmatodo — Centro (Morrocoy)', 10.8337, -68.1683, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-217', 'Estación PDV — Centro (Morrocoy)', 10.8616, -68.1627, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-218', 'Hotel — Centro (Morrocoy)', 10.8998, -68.1892, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-219', 'Restaurante — Centro (Morrocoy)', 10.834, -68.2361, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-220', 'Plaza Central — Zona Norte (Morrocoy)', 10.8676, -68.1819, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-221', 'Centro de Salud — Zona Norte (Morrocoy)', 10.8058, -68.2302, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-222', 'Central Madeirense — Zona Norte (Morrocoy)', 10.8335, -68.1722, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-223', 'Automercados Plaza''s — Zona Norte (Morrocoy)', 10.8165, -68.1591, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-224', 'Farmacia Farmatodo — Zona Norte (Morrocoy)', 10.7931, -68.2394, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('ve150-225', 'Estación PDV — Zona Norte (Morrocoy)', 10.7936, -68.2209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
