-- ============================================
-- Achou Trocador — Espanha: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('es150-001', 'Cidade das Artes e das Ciências (Valencia)', 39.454, -0.353, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-002', 'McDonald''s — Valencia (Espanha)', 39.4482, -0.355, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-003', 'Burger King — Valencia (Espanha)', 39.4797, -0.3573, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-004', 'KFC — Valencia (Espanha)', 39.4496, -0.3654, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-005', 'Plaza Central — Centro (Valencia (Espanha))', 39.4646, -0.3661, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-006', 'Centro de Salud — Centro (Valencia (Espanha))', 39.5075, -0.3725, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-007', 'Mercadona — Centro (Valencia (Espanha))', 39.4967, -0.3507, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-008', 'Carrefour — Centro (Valencia (Espanha))', 39.4597, -0.3885, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-009', 'Farmacia — Centro (Valencia (Espanha))', 39.4225, -0.4113, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-010', 'Estación Repsol — Centro (Valencia (Espanha))', 39.5283, -0.3792, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-011', 'Estación Cepsa — Centro (Valencia (Espanha))', 39.512, -0.347, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-012', 'Hotel — Centro (Valencia (Espanha))', 39.4875, -0.4274, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-013', 'Restaurante — Centro (Valencia (Espanha))', 39.5234, -0.4357, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-014', 'Plaza Central — Zona Norte (Valencia (Espanha))', 39.465, -0.3198, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-015', 'Centro de Salud — Zona Norte (Valencia (Espanha))', 39.4298, -0.3717, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-016', 'Mercadona — Zona Norte (Valencia (Espanha))', 39.4105, -0.4244, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-017', 'Carrefour — Zona Norte (Valencia (Espanha))', 39.5059, -0.3352, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-018', 'Farmacia — Zona Norte (Valencia (Espanha))', 39.414, -0.3278, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-019', 'Estación Repsol — Zona Norte (Valencia (Espanha))', 39.4145, -0.3473, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-020', 'Estación Cepsa — Zona Norte (Valencia (Espanha))', 39.4982, -0.3438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-021', 'Hotel — Zona Norte (Valencia (Espanha))', 39.4879, -0.3852, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-022', 'Restaurante — Zona Norte (Valencia (Espanha))', 39.4101, -0.3263, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-023', 'Plaza Central — Zona Sur (Valencia (Espanha))', 39.4492, -0.3211, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-024', 'Centro de Salud — Zona Sur (Valencia (Espanha))', 39.4282, -0.3553, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-025', 'Mercadona — Zona Sur (Valencia (Espanha))', 39.4888, -0.3345, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-026', 'Carrefour — Zona Sur (Valencia (Espanha))', 39.4296, -0.4066, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-027', 'Farmacia — Zona Sur (Valencia (Espanha))', 39.5277, -0.3882, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-028', 'Estación Repsol — Zona Sur (Valencia (Espanha))', 39.4452, -0.359, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-029', 'Estación Cepsa — Zona Sur (Valencia (Espanha))', 39.4983, -0.3566, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-030', 'Hotel — Zona Sur (Valencia (Espanha))', 39.496, -0.3366, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-031', 'Basílica del Pilar (Zaragoza)', 41.656, -0.889, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-032', 'Subway — Zaragoza', 41.6697, -0.8915, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-033', 'Pizza Hut — Zaragoza', 41.6283, -0.8777, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-034', 'Starbucks — Zaragoza', 41.662, -0.8639, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-035', 'Plaza Central — Centro (Zaragoza)', 41.7018, -0.924, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-036', 'Centro de Salud — Centro (Zaragoza)', 41.6757, -0.8503, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-037', 'Mercadona — Centro (Zaragoza)', 41.7037, -0.8444, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-038', 'Carrefour — Centro (Zaragoza)', 41.6242, -0.8886, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-039', 'Farmacia — Centro (Zaragoza)', 41.5904, -0.851, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-040', 'Estación Repsol — Centro (Zaragoza)', 41.635, -0.8785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-041', 'Estación Cepsa — Centro (Zaragoza)', 41.6253, -0.9309, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-042', 'Hotel — Centro (Zaragoza)', 41.6405, -0.9291, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-043', 'Restaurante — Centro (Zaragoza)', 41.5933, -0.9272, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-044', 'Plaza Central — Zona Norte (Zaragoza)', 41.6527, -0.8758, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-045', 'Centro de Salud — Zona Norte (Zaragoza)', 41.5978, -0.9082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-046', 'Mercadona — Zona Norte (Zaragoza)', 41.6997, -0.8593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-047', 'Carrefour — Zona Norte (Zaragoza)', 41.6066, -0.9021, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-048', 'Farmacia — Zona Norte (Zaragoza)', 41.6237, -0.8844, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-049', 'Estación Repsol — Zona Norte (Zaragoza)', 41.6237, -0.9425, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-050', 'Estación Cepsa — Zona Norte (Zaragoza)', 41.6307, -0.9167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-051', 'Hotel — Zona Norte (Zaragoza)', 41.6613, -0.9351, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-052', 'Restaurante — Zona Norte (Zaragoza)', 41.6575, -0.9265, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-053', 'Plaza Central — Zona Sur (Zaragoza)', 41.7085, -0.9059, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-054', 'Centro de Salud — Zona Sur (Zaragoza)', 41.646, -0.9278, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-055', 'Mercadona — Zona Sur (Zaragoza)', 41.699, -0.9155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-056', 'Carrefour — Zona Sur (Zaragoza)', 41.5965, -0.8814, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-057', 'Farmacia — Zona Sur (Zaragoza)', 41.7052, -0.9175, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-058', 'Estación Repsol — Zona Sur (Zaragoza)', 41.6576, -0.903, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-059', 'Estación Cepsa — Zona Sur (Zaragoza)', 41.638, -0.9118, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-060', 'Hotel — Zona Sur (Zaragoza)', 41.6184, -0.8634, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-061', 'Real Alcázar de Sevilha', 37.3838, -5.9903, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-062', 'Domino''s Pizza — Sevilha', 37.3913, -5.9963, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-063', '100 Montaditos — Sevilha', 37.393, -5.964, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-064', 'Rodilla — Sevilha', 37.4068, -6.0065, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-065', 'Plaza Central — Centro (Sevilha)', 37.3991, -5.9655, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-066', 'Centro de Salud — Centro (Sevilha)', 37.3802, -6.0282, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-067', 'Mercadona — Centro (Sevilha)', 37.3826, -5.9614, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-068', 'Carrefour — Centro (Sevilha)', 37.3538, -6.0429, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-069', 'Farmacia — Centro (Sevilha)', 37.371, -5.94, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-070', 'Estación Repsol — Centro (Sevilha)', 37.3865, -5.9828, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-071', 'Estación Cepsa — Centro (Sevilha)', 37.3624, -5.9521, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-072', 'Hotel — Centro (Sevilha)', 37.3926, -5.9745, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-073', 'Restaurante — Centro (Sevilha)', 37.3486, -5.9397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-074', 'Plaza Central — Zona Norte (Sevilha)', 37.387, -5.9603, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-075', 'Centro de Salud — Zona Norte (Sevilha)', 37.4406, -5.9392, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-076', 'Mercadona — Zona Norte (Sevilha)', 37.3452, -6.0264, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-077', 'Carrefour — Zona Norte (Sevilha)', 37.386, -5.9459, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-078', 'Farmacia — Zona Norte (Sevilha)', 37.4104, -6.0138, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-079', 'Estación Repsol — Zona Norte (Sevilha)', 37.4451, -6.0124, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-080', 'Estación Cepsa — Zona Norte (Sevilha)', 37.3819, -5.9315, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-081', 'Hotel — Zona Norte (Sevilha)', 37.3863, -6.028, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-082', 'Restaurante — Zona Norte (Sevilha)', 37.4077, -6.0438, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-083', 'Plaza Central — Zona Sur (Sevilha)', 37.4048, -5.9365, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-084', 'Centro de Salud — Zona Sur (Sevilha)', 37.3575, -6.0396, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-085', 'Mercadona — Zona Sur (Sevilha)', 37.4301, -5.9816, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-086', 'Carrefour — Zona Sur (Sevilha)', 37.4051, -6.0036, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-087', 'Farmacia — Zona Sur (Sevilha)', 37.3332, -5.9798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-088', 'Estación Repsol — Zona Sur (Sevilha)', 37.3663, -6.0031, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-089', 'Estación Cepsa — Zona Sur (Sevilha)', 37.4015, -5.9689, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-090', 'Hotel — Zona Sur (Sevilha)', 37.4367, -6.0101, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-091', 'Alcazaba de Málaga', 36.7213, -4.4157, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-092', 'Pans & Company — Málaga', 36.7302, -4.4363, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-093', 'VIPS — Málaga', 36.7425, -4.4129, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-094', 'Telepizza — Málaga', 36.6916, -4.4458, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-095', 'Plaza Central — Centro (Málaga)', 36.738, -4.426, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-096', 'Centro de Salud — Centro (Málaga)', 36.7728, -4.3704, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-097', 'Mercadona — Centro (Málaga)', 36.7441, -4.4639, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-098', 'Carrefour — Centro (Málaga)', 36.6795, -4.4022, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-099', 'Farmacia — Centro (Málaga)', 36.6814, -4.4424, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-100', 'Estación Repsol — Centro (Málaga)', 36.7195, -4.4106, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-101', 'Estación Cepsa — Centro (Málaga)', 36.7296, -4.3797, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-102', 'Hotel — Centro (Málaga)', 36.7262, -4.4809, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-103', 'Restaurante — Centro (Málaga)', 36.7684, -4.4457, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-104', 'Plaza Central — Zona Norte (Málaga)', 36.6617, -4.3627, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-105', 'Centro de Salud — Zona Norte (Málaga)', 36.6746, -4.3731, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-106', 'Mercadona — Zona Norte (Málaga)', 36.7533, -4.4556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-107', 'Carrefour — Zona Norte (Málaga)', 36.7448, -4.4344, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-108', 'Farmacia — Zona Norte (Málaga)', 36.7589, -4.3727, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-109', 'Estación Repsol — Zona Norte (Málaga)', 36.758, -4.4766, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-110', 'Estación Cepsa — Zona Norte (Málaga)', 36.6849, -4.4684, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-111', 'Hotel — Zona Norte (Málaga)', 36.6787, -4.4327, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-112', 'Restaurante — Zona Norte (Málaga)', 36.7126, -4.4325, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-113', 'Plaza Central — Zona Sur (Málaga)', 36.7451, -4.3753, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-114', 'Centro de Salud — Zona Sur (Málaga)', 36.6846, -4.4274, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-115', 'Mercadona — Zona Sur (Málaga)', 36.7347, -4.4255, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-116', 'Carrefour — Zona Sur (Málaga)', 36.7707, -4.4319, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-117', 'Farmacia — Zona Sur (Málaga)', 36.7584, -4.4209, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-118', 'Estación Repsol — Zona Sur (Málaga)', 36.715, -4.3884, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-119', 'Estación Cepsa — Zona Sur (Málaga)', 36.738, -4.447, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-120', 'Hotel — Zona Sur (Málaga)', 36.6872, -4.462, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-121', 'Museu Guggenheim Bilbao', 43.2687, -2.934, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-122', 'Ginos — Bilbao', 43.2428, -2.932, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-123', 'La Tagliatella — Bilbao', 43.2564, -2.9068, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-124', 'Foster''s Hollywood — Bilbao', 43.2763, -2.9256, 'familia', 'Cadena de restaurante popular — dirección aproximada, candidato potencial a tener cambiador de bebés.', false),
  ('es150-125', 'Plaza Central — Centro (Bilbao)', 43.2597, -2.9273, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-126', 'Centro de Salud — Centro (Bilbao)', 43.2919, -2.9111, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-127', 'Mercadona — Centro (Bilbao)', 43.2391, -2.9895, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-128', 'Carrefour — Centro (Bilbao)', 43.3184, -2.9769, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-129', 'Farmacia — Centro (Bilbao)', 43.2398, -2.9392, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-130', 'Estación Repsol — Centro (Bilbao)', 43.2994, -2.9087, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-131', 'Estación Cepsa — Centro (Bilbao)', 43.2943, -2.9821, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-132', 'Hotel — Centro (Bilbao)', 43.2371, -2.9128, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-133', 'Restaurante — Centro (Bilbao)', 43.208, -2.8789, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-134', 'Plaza Central — Zona Norte (Bilbao)', 43.2454, -2.9901, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-135', 'Centro de Salud — Zona Norte (Bilbao)', 43.2227, -2.9593, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-136', 'Mercadona — Zona Norte (Bilbao)', 43.3026, -2.9381, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-137', 'Carrefour — Zona Norte (Bilbao)', 43.3144, -2.9038, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-138', 'Farmacia — Zona Norte (Bilbao)', 43.2868, -2.9126, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-139', 'Estación Repsol — Zona Norte (Bilbao)', 43.2525, -2.9758, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-140', 'Estación Cepsa — Zona Norte (Bilbao)', 43.2487, -2.9176, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-141', 'Hotel — Zona Norte (Bilbao)', 43.3073, -2.9769, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-142', 'Restaurante — Zona Norte (Bilbao)', 43.3068, -2.89, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-143', 'Plaza Central — Zona Sur (Bilbao)', 43.2722, -2.994, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-144', 'Centro de Salud — Zona Sur (Bilbao)', 43.2326, -2.8815, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-145', 'Mercadona — Zona Sur (Bilbao)', 43.2104, -2.9836, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-146', 'Carrefour — Zona Sur (Bilbao)', 43.2048, -2.982, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-147', 'Farmacia — Zona Sur (Bilbao)', 43.2387, -2.9533, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-148', 'Estación Repsol — Zona Sur (Bilbao)', 43.2732, -2.9853, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-149', 'Estación Cepsa — Zona Sur (Bilbao)', 43.2555, -2.9155, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-150', 'Hotel — Zona Sur (Bilbao)', 43.3169, -2.9043, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-151', 'Catedral de Palma de Mallorca', 39.5674, 2.6474, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-152', 'Plaza Central — Centro (Palma e Mallorca)', 39.6152, 2.681, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-153', 'Centro de Salud — Centro (Palma e Mallorca)', 39.5438, 2.6785, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-154', 'Mercadona — Centro (Palma e Mallorca)', 39.5164, 2.6925, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-155', 'Carrefour — Centro (Palma e Mallorca)', 39.5805, 2.6853, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-156', 'Farmacia — Centro (Palma e Mallorca)', 39.5398, 2.5996, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-157', 'Estación Repsol — Centro (Palma e Mallorca)', 39.5917, 2.636, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-158', 'Estación Cepsa — Centro (Palma e Mallorca)', 39.5466, 2.6637, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-159', 'Hotel — Centro (Palma e Mallorca)', 39.5627, 2.6765, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-160', 'Restaurante — Centro (Palma e Mallorca)', 39.5481, 2.6925, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-161', 'Plaza Central — Zona Norte (Palma e Mallorca)', 39.5857, 2.6213, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-162', 'Centro de Salud — Zona Norte (Palma e Mallorca)', 39.5336, 2.5921, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-163', 'Mercadona — Zona Norte (Palma e Mallorca)', 39.5873, 2.6864, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-164', 'Carrefour — Zona Norte (Palma e Mallorca)', 39.5972, 2.6247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-165', 'Farmacia — Zona Norte (Palma e Mallorca)', 39.5097, 2.6962, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-166', 'Teide (acesso Tenerife)', 28.2716, -16.6423, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-167', 'Plaza Central — Centro (Tenerife)', 28.4211, -16.2743, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-168', 'Centro de Salud — Centro (Tenerife)', 28.4832, -16.2109, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-169', 'Mercadona — Centro (Tenerife)', 28.4571, -16.3064, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-170', 'Carrefour — Centro (Tenerife)', 28.4827, -16.2655, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-171', 'Farmacia — Centro (Tenerife)', 28.446, -16.2799, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-172', 'Estación Repsol — Centro (Tenerife)', 28.4525, -16.3063, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-173', 'Estación Cepsa — Centro (Tenerife)', 28.4113, -16.3022, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-174', 'Hotel — Centro (Tenerife)', 28.4295, -16.2836, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-175', 'Restaurante — Centro (Tenerife)', 28.4265, -16.2102, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-176', 'Plaza Central — Zona Norte (Tenerife)', 28.5044, -16.2905, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-177', 'Centro de Salud — Zona Norte (Tenerife)', 28.5161, -16.2806, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-178', 'Mercadona — Zona Norte (Tenerife)', 28.4628, -16.2295, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-179', 'Carrefour — Zona Norte (Tenerife)', 28.5104, -16.2138, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-180', 'Farmacia — Zona Norte (Tenerife)', 28.4127, -16.1937, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-181', 'Alhambra de Granada', 37.176, -3.588, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-182', 'Plaza Central — Centro (Granada)', 37.1961, -3.6416, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-183', 'Centro de Salud — Centro (Granada)', 37.1686, -3.6298, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-184', 'Mercadona — Centro (Granada)', 37.1693, -3.6377, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-185', 'Carrefour — Centro (Granada)', 37.1654, -3.6237, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-186', 'Farmacia — Centro (Granada)', 37.1462, -3.6564, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-187', 'Estación Repsol — Centro (Granada)', 37.2373, -3.6082, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-188', 'Estación Cepsa — Centro (Granada)', 37.1763, -3.5917, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-189', 'Hotel — Centro (Granada)', 37.1451, -3.6465, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-190', 'Restaurante — Centro (Granada)', 37.1351, -3.5721, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-191', 'Plaza Central — Zona Norte (Granada)', 37.1237, -3.6066, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-192', 'Centro de Salud — Zona Norte (Granada)', 37.2124, -3.5937, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-193', 'Mercadona — Zona Norte (Granada)', 37.1635, -3.5392, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-194', 'Carrefour — Zona Norte (Granada)', 37.2203, -3.6129, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-195', 'Farmacia — Zona Norte (Granada)', 37.204, -3.56, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-196', 'Dalt Vila (Ibiza)', 38.9067, 1.437, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-197', 'Plaza Central — Centro (Ibiza)', 38.9183, 1.397, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-198', 'Centro de Salud — Centro (Ibiza)', 38.8662, 1.3817, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-199', 'Mercadona — Centro (Ibiza)', 38.9665, 1.3684, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-200', 'Carrefour — Centro (Ibiza)', 38.9287, 1.4323, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-201', 'Farmacia — Centro (Ibiza)', 38.9302, 1.3623, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-202', 'Estación Repsol — Centro (Ibiza)', 38.9, 1.3825, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-203', 'Estación Cepsa — Centro (Ibiza)', 38.8825, 1.3641, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-204', 'Hotel — Centro (Ibiza)', 38.8667, 1.3824, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-205', 'Restaurante — Centro (Ibiza)', 38.9529, 1.4167, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-206', 'Plaza Central — Zona Norte (Ibiza)', 38.909, 1.368, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-207', 'Centro de Salud — Zona Norte (Ibiza)', 38.8911, 1.4805, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-208', 'Mercadona — Zona Norte (Ibiza)', 38.9348, 1.4151, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-209', 'Carrefour — Zona Norte (Ibiza)', 38.9075, 1.4194, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-210', 'Farmacia — Zona Norte (Ibiza)', 38.9275, 1.4024, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-211', 'Playa de La Concha (San Sebastián)', 43.316, -1.982, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-212', 'Plaza Central — Centro (San Sebastián)', 43.2737, -2.0071, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-213', 'Centro de Salud — Centro (San Sebastián)', 43.3567, -1.9932, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-214', 'Mercadona — Centro (San Sebastián)', 43.3587, -2.0328, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-215', 'Carrefour — Centro (San Sebastián)', 43.3366, -2.0362, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-216', 'Farmacia — Centro (San Sebastián)', 43.2981, -1.9501, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-217', 'Estación Repsol — Centro (San Sebastián)', 43.363, -1.9954, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-218', 'Estación Cepsa — Centro (San Sebastián)', 43.3315, -1.9259, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-219', 'Hotel — Centro (San Sebastián)', 43.3777, -1.9624, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-220', 'Restaurante — Centro (San Sebastián)', 43.3062, -1.9556, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-221', 'Plaza Central — Zona Norte (San Sebastián)', 43.3609, -2.0247, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-222', 'Centro de Salud — Zona Norte (San Sebastián)', 43.2896, -1.9798, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-223', 'Mercadona — Zona Norte (San Sebastián)', 43.3409, -1.9955, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-224', 'Carrefour — Zona Norte (San Sebastián)', 43.3339, -1.9653, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false),
  ('es150-225', 'Farmacia — Zona Norte (San Sebastián)', 43.2822, -2.0053, 'familia', 'Lugar investigado, todavía sin visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
