-- ============================================
-- Achou Trocador — Portugal: 150 locais populosos + 75 turisticos
-- Nao verificados. Coordenadas aproximadas -- comunidade local confirma.
-- Rode isso no SQL Editor do MESMO projeto Supabase dos passos anteriores.
-- ============================================

insert into public.spots (id, name, lat, lng, location, notes, verified)
values
  ('pt150-001', 'Palácio da Pena (Sintra)', 38.7876, -9.3906, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-002', 'McDonald''s — Sintra (populosas)', 38.8164, -9.4075, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-003', 'Burger King — Sintra (populosas)', 38.8043, -9.402, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-004', 'KFC — Sintra (populosas)', 38.7827, -9.3718, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-005', 'Praça Central — Centro (Sintra (populosas))', 38.7928, -9.3666, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-006', 'UBS — Centro (Sintra (populosas))', 38.8003, -9.4074, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-007', 'Continente — Centro (Sintra (populosas))', 38.8552, -9.3411, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-008', 'Pingo Doce — Centro (Sintra (populosas))', 38.8148, -9.36, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-009', 'Farmácia — Centro (Sintra (populosas))', 38.7668, -9.3843, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-010', 'Posto Galp — Centro (Sintra (populosas))', 38.8219, -9.3275, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-011', 'Posto BP — Centro (Sintra (populosas))', 38.7669, -9.361, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-012', 'Hotel — Centro (Sintra (populosas))', 38.7969, -9.4238, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-013', 'Restaurante — Centro (Sintra (populosas))', 38.7721, -9.436, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-014', 'Praça Central — Zona Norte (Sintra (populosas))', 38.817, -9.4222, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-015', 'UBS — Zona Norte (Sintra (populosas))', 38.8557, -9.3352, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-016', 'Continente — Zona Norte (Sintra (populosas))', 38.8363, -9.3748, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-017', 'Pingo Doce — Zona Norte (Sintra (populosas))', 38.8587, -9.3419, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-018', 'Farmácia — Zona Norte (Sintra (populosas))', 38.8097, -9.4336, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-019', 'Posto Galp — Zona Norte (Sintra (populosas))', 38.8484, -9.3831, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-020', 'Posto BP — Zona Norte (Sintra (populosas))', 38.7447, -9.3437, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-021', 'Hotel — Zona Norte (Sintra (populosas))', 38.8041, -9.3304, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-022', 'Restaurante — Zona Norte (Sintra (populosas))', 38.8037, -9.3796, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-023', 'Praça Central — Zona Sul (Sintra (populosas))', 38.7648, -9.3292, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-024', 'UBS — Zona Sul (Sintra (populosas))', 38.8591, -9.3723, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-025', 'Continente — Zona Sul (Sintra (populosas))', 38.748, -9.3398, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-026', 'Pingo Doce — Zona Sul (Sintra (populosas))', 38.8272, -9.3254, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-027', 'Farmácia — Zona Sul (Sintra (populosas))', 38.746, -9.4085, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-028', 'Posto Galp — Zona Sul (Sintra (populosas))', 38.8191, -9.3326, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-029', 'Posto BP — Zona Sul (Sintra (populosas))', 38.7946, -9.354, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-030', 'Hotel — Zona Sul (Sintra (populosas))', 38.8284, -9.3476, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-031', 'Caves do Vinho do Porto (Gaia)', 41.136, -8.611, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-032', 'Subway — Vila Nova de Gaia', 41.138, -8.6316, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-033', 'Pizza Hut — Vila Nova de Gaia', 41.1002, -8.6089, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-034', 'Starbucks — Vila Nova de Gaia', 41.1125, -8.6228, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-035', 'Praça Central — Centro (Vila Nova de Gaia)', 41.1532, -8.6242, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-036', 'UBS — Centro (Vila Nova de Gaia)', 41.1079, -8.6362, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-037', 'Continente — Centro (Vila Nova de Gaia)', 41.1507, -8.5844, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-038', 'Pingo Doce — Centro (Vila Nova de Gaia)', 41.1452, -8.6044, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-039', 'Farmácia — Centro (Vila Nova de Gaia)', 41.064, -8.6677, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-040', 'Posto Galp — Centro (Vila Nova de Gaia)', 41.1361, -8.6616, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-041', 'Posto BP — Centro (Vila Nova de Gaia)', 41.0862, -8.6304, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-042', 'Hotel — Centro (Vila Nova de Gaia)', 41.181, -8.6136, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-043', 'Restaurante — Centro (Vila Nova de Gaia)', 41.1242, -8.591, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-044', 'Praça Central — Zona Norte (Vila Nova de Gaia)', 41.0844, -8.6715, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-045', 'UBS — Zona Norte (Vila Nova de Gaia)', 41.1742, -8.5778, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-046', 'Continente — Zona Norte (Vila Nova de Gaia)', 41.1754, -8.5691, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-047', 'Pingo Doce — Zona Norte (Vila Nova de Gaia)', 41.1551, -8.6541, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-048', 'Farmácia — Zona Norte (Vila Nova de Gaia)', 41.1811, -8.619, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-049', 'Posto Galp — Zona Norte (Vila Nova de Gaia)', 41.1158, -8.5909, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-050', 'Posto BP — Zona Norte (Vila Nova de Gaia)', 41.1238, -8.5559, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-051', 'Hotel — Zona Norte (Vila Nova de Gaia)', 41.1351, -8.6418, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-052', 'Restaurante — Zona Norte (Vila Nova de Gaia)', 41.1115, -8.5902, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-053', 'Praça Central — Zona Sul (Vila Nova de Gaia)', 41.1183, -8.6439, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-054', 'UBS — Zona Sul (Vila Nova de Gaia)', 41.0782, -8.6147, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-055', 'Continente — Zona Sul (Vila Nova de Gaia)', 41.0651, -8.6464, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-056', 'Pingo Doce — Zona Sul (Vila Nova de Gaia)', 41.1019, -8.6014, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-057', 'Farmácia — Zona Sul (Vila Nova de Gaia)', 41.1451, -8.5923, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-058', 'Posto Galp — Zona Sul (Vila Nova de Gaia)', 41.1572, -8.6124, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-059', 'Posto BP — Zona Sul (Vila Nova de Gaia)', 41.0691, -8.6518, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-060', 'Hotel — Zona Sul (Vila Nova de Gaia)', 41.1466, -8.6387, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-061', 'Bom Jesus do Monte (Braga)', 41.554, -8.378, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-062', 'Domino''s Pizza — Braga', 41.5182, -8.4074, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-063', 'Nando''s Portugal — Braga', 41.5381, -8.4213, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-064', 'A Padaria Portuguesa — Braga', 41.5656, -8.4483, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-065', 'Praça Central — Centro (Braga)', 41.5586, -8.3932, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-066', 'UBS — Centro (Braga)', 41.5315, -8.3973, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-067', 'Continente — Centro (Braga)', 41.5956, -8.3715, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-068', 'Pingo Doce — Centro (Braga)', 41.555, -8.4294, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-069', 'Farmácia — Centro (Braga)', 41.5793, -8.3709, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-070', 'Posto Galp — Centro (Braga)', 41.4941, -8.481, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-071', 'Posto BP — Centro (Braga)', 41.5931, -8.4723, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-072', 'Hotel — Centro (Braga)', 41.5566, -8.4568, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-073', 'Restaurante — Centro (Braga)', 41.59, -8.4448, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-074', 'Praça Central — Zona Norte (Braga)', 41.5645, -8.382, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-075', 'UBS — Zona Norte (Braga)', 41.5952, -8.4718, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-076', 'Continente — Zona Norte (Braga)', 41.5895, -8.4175, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-077', 'Pingo Doce — Zona Norte (Braga)', 41.495, -8.4414, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-078', 'Farmácia — Zona Norte (Braga)', 41.5614, -8.402, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-079', 'Posto Galp — Zona Norte (Braga)', 41.5946, -8.4747, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-080', 'Posto BP — Zona Norte (Braga)', 41.548, -8.477, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-081', 'Hotel — Zona Norte (Braga)', 41.5702, -8.382, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-082', 'Restaurante — Zona Norte (Braga)', 41.4938, -8.3859, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-083', 'Praça Central — Zona Sul (Braga)', 41.4893, -8.417, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-084', 'UBS — Zona Sul (Braga)', 41.5964, -8.4505, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-085', 'Continente — Zona Sul (Braga)', 41.5905, -8.4401, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-086', 'Pingo Doce — Zona Sul (Braga)', 41.5026, -8.3921, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-087', 'Farmácia — Zona Sul (Braga)', 41.5453, -8.4109, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-088', 'Posto Galp — Zona Sul (Braga)', 41.5805, -8.4594, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-089', 'Posto BP — Zona Sul (Braga)', 41.5563, -8.4728, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-090', 'Hotel — Zona Sul (Braga)', 41.5782, -8.4096, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-091', 'Universidade de Coimbra', 40.2076, -8.4258, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-092', 'Jerónimo — Coimbra', 40.1946, -8.3967, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-093', 'Pastelaria Aloma — Coimbra', 40.1983, -8.4285, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-094', 'Cervejaria Trindade — Coimbra', 40.2239, -8.4155, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-095', 'Praça Central — Centro (Coimbra)', 40.2462, -8.3702, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-096', 'UBS — Centro (Coimbra)', 40.1455, -8.3846, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-097', 'Continente — Centro (Coimbra)', 40.1863, -8.418, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-098', 'Pingo Doce — Centro (Coimbra)', 40.168, -8.462, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-099', 'Farmácia — Centro (Coimbra)', 40.2566, -8.3534, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-100', 'Posto Galp — Centro (Coimbra)', 40.2159, -8.3572, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-101', 'Posto BP — Centro (Coimbra)', 40.1457, -8.397, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-102', 'Hotel — Centro (Coimbra)', 40.1776, -8.3503, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-103', 'Restaurante — Centro (Coimbra)', 40.2608, -8.4496, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-104', 'Praça Central — Zona Norte (Coimbra)', 40.1447, -8.3878, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-105', 'UBS — Zona Norte (Coimbra)', 40.2445, -8.4249, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-106', 'Continente — Zona Norte (Coimbra)', 40.2509, -8.3951, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-107', 'Pingo Doce — Zona Norte (Coimbra)', 40.1552, -8.3933, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-108', 'Farmácia — Zona Norte (Coimbra)', 40.2379, -8.3541, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-109', 'Posto Galp — Zona Norte (Coimbra)', 40.2223, -8.4086, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-110', 'Posto BP — Zona Norte (Coimbra)', 40.1572, -8.3706, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-111', 'Hotel — Zona Norte (Coimbra)', 40.2575, -8.4103, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-112', 'Restaurante — Zona Norte (Coimbra)', 40.144, -8.4016, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-113', 'Praça Central — Zona Sul (Coimbra)', 40.2157, -8.3553, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-114', 'UBS — Zona Sul (Coimbra)', 40.2478, -8.4287, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-115', 'Continente — Zona Sul (Coimbra)', 40.2238, -8.4006, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-116', 'Pingo Doce — Zona Sul (Coimbra)', 40.2034, -8.4152, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-117', 'Farmácia — Zona Sul (Coimbra)', 40.2373, -8.4306, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-118', 'Posto Galp — Zona Sul (Coimbra)', 40.184, -8.4613, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-119', 'Posto BP — Zona Sul (Coimbra)', 40.2409, -8.3994, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-120', 'Hotel — Zona Sul (Coimbra)', 40.1793, -8.4189, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-121', 'Castelo de São Filipe (Setúbal)', 38.517, -8.903, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-122', 'O Rei dos Frangos — Setúbal', 38.5399, -8.8864, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-123', 'Solar dos Presuntos — Setúbal', 38.496, -8.8656, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-124', 'Pans & Company Portugal — Setúbal', 38.5454, -8.9045, 'familia', 'Rede de restaurante popular — endereço aproximado, potencial candidato a ter trocador de fraldas.', false),
  ('pt150-125', 'Praça Central — Centro (Setúbal)', 38.4988, -8.9282, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-126', 'UBS — Centro (Setúbal)', 38.4658, -8.854, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-127', 'Continente — Centro (Setúbal)', 38.5657, -8.8866, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-128', 'Pingo Doce — Centro (Setúbal)', 38.4889, -8.8941, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-129', 'Farmácia — Centro (Setúbal)', 38.4913, -8.8527, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-130', 'Posto Galp — Centro (Setúbal)', 38.4924, -8.8293, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-131', 'Posto BP — Centro (Setúbal)', 38.551, -8.8852, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-132', 'Hotel — Centro (Setúbal)', 38.5521, -8.9127, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-133', 'Restaurante — Centro (Setúbal)', 38.5781, -8.9128, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-134', 'Praça Central — Zona Norte (Setúbal)', 38.4948, -8.9374, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-135', 'UBS — Zona Norte (Setúbal)', 38.5394, -8.8473, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-136', 'Continente — Zona Norte (Setúbal)', 38.5256, -8.9304, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-137', 'Pingo Doce — Zona Norte (Setúbal)', 38.5196, -8.8816, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-138', 'Farmácia — Zona Norte (Setúbal)', 38.4722, -8.9302, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-139', 'Posto Galp — Zona Norte (Setúbal)', 38.4857, -8.8934, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-140', 'Posto BP — Zona Norte (Setúbal)', 38.533, -8.9151, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-141', 'Hotel — Zona Norte (Setúbal)', 38.5135, -8.8389, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-142', 'Restaurante — Zona Norte (Setúbal)', 38.5607, -8.858, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-143', 'Praça Central — Zona Sul (Setúbal)', 38.4912, -8.8678, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-144', 'UBS — Zona Sul (Setúbal)', 38.5108, -8.8486, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-145', 'Continente — Zona Sul (Setúbal)', 38.574, -8.9063, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-146', 'Pingo Doce — Zona Sul (Setúbal)', 38.5572, -8.9185, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-147', 'Farmácia — Zona Sul (Setúbal)', 38.5276, -8.8691, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-148', 'Posto Galp — Zona Sul (Setúbal)', 38.5071, -8.8659, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-149', 'Posto BP — Zona Sul (Setúbal)', 38.5126, -8.9023, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-150', 'Hotel — Zona Sul (Setúbal)', 38.5269, -8.8418, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-151', 'Ribeira do Porto', 41.141, -8.612, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-152', 'Praça Central — Centro (Porto)', 41.1315, -8.6308, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-153', 'UBS — Centro (Porto)', 41.1569, -8.6762, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-154', 'Continente — Centro (Porto)', 41.1329, -8.5823, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-155', 'Pingo Doce — Centro (Porto)', 41.1279, -8.6079, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-156', 'Farmácia — Centro (Porto)', 41.2093, -8.5965, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-157', 'Posto Galp — Centro (Porto)', 41.1065, -8.6301, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-158', 'Posto BP — Centro (Porto)', 41.108, -8.5983, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-159', 'Hotel — Centro (Porto)', 41.1414, -8.6055, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-160', 'Restaurante — Centro (Porto)', 41.1975, -8.6149, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-161', 'Praça Central — Zona Norte (Porto)', 41.1018, -8.6478, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-162', 'UBS — Zona Norte (Porto)', 41.1661, -8.6105, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-163', 'Continente — Zona Norte (Porto)', 41.1745, -8.5833, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-164', 'Pingo Doce — Zona Norte (Porto)', 41.206, -8.6692, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-165', 'Farmácia — Zona Norte (Porto)', 41.1897, -8.6837, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-166', 'Praia dos Pescadores (Albufeira)', 37.085, -8.257, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-167', 'Praça Central — Centro (Albufeira)', 37.0404, -8.2081, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-168', 'UBS — Centro (Albufeira)', 37.1318, -8.2907, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-169', 'Continente — Centro (Albufeira)', 37.1032, -8.2855, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-170', 'Pingo Doce — Centro (Albufeira)', 37.1024, -8.2373, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-171', 'Farmácia — Centro (Albufeira)', 37.0893, -8.2343, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-172', 'Posto Galp — Centro (Albufeira)', 37.0337, -8.3054, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-173', 'Posto BP — Centro (Albufeira)', 37.1026, -8.2422, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-174', 'Hotel — Centro (Albufeira)', 37.1075, -8.2557, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-175', 'Restaurante — Centro (Albufeira)', 37.0883, -8.2264, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-176', 'Praça Central — Zona Norte (Albufeira)', 37.1018, -8.2757, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-177', 'UBS — Zona Norte (Albufeira)', 37.0783, -8.2574, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-178', 'Continente — Zona Norte (Albufeira)', 37.128, -8.2241, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-179', 'Pingo Doce — Zona Norte (Albufeira)', 37.0537, -8.2205, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-180', 'Farmácia — Zona Norte (Albufeira)', 37.1025, -8.2943, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-181', 'Levada do Funchal', 32.68, -16.95, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-182', 'Praça Central — Centro (Funchal e Madeira)', 32.6612, -16.9748, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-183', 'UBS — Centro (Funchal e Madeira)', 32.7211, -16.9378, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-184', 'Continente — Centro (Funchal e Madeira)', 32.7203, -16.9062, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-185', 'Pingo Doce — Centro (Funchal e Madeira)', 32.6595, -16.8701, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-186', 'Farmácia — Centro (Funchal e Madeira)', 32.6459, -16.9379, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-187', 'Posto Galp — Centro (Funchal e Madeira)', 32.6987, -16.9712, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-188', 'Posto BP — Centro (Funchal e Madeira)', 32.7127, -16.9773, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-189', 'Hotel — Centro (Funchal e Madeira)', 32.6781, -16.9125, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-190', 'Restaurante — Centro (Funchal e Madeira)', 32.6919, -16.8815, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-191', 'Praça Central — Zona Norte (Funchal e Madeira)', 32.6296, -16.8926, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-192', 'UBS — Zona Norte (Funchal e Madeira)', 32.691, -16.9646, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-193', 'Continente — Zona Norte (Funchal e Madeira)', 32.7041, -16.8983, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-194', 'Pingo Doce — Zona Norte (Funchal e Madeira)', 32.6368, -16.9594, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-195', 'Farmácia — Zona Norte (Funchal e Madeira)', 32.7232, -16.927, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-196', 'Ponta da Piedade (Lagos)', 37.083, -8.669, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-197', 'Praça Central — Centro (Lagos (Algarve))', 37.0666, -8.6273, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-198', 'UBS — Centro (Lagos (Algarve))', 37.1371, -8.6297, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-199', 'Continente — Centro (Lagos (Algarve))', 37.1533, -8.6171, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-200', 'Pingo Doce — Centro (Lagos (Algarve))', 37.132, -8.7317, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-201', 'Farmácia — Centro (Lagos (Algarve))', 37.0544, -8.6706, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-202', 'Posto Galp — Centro (Lagos (Algarve))', 37.0491, -8.6618, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-203', 'Posto BP — Centro (Lagos (Algarve))', 37.1271, -8.6205, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-204', 'Hotel — Centro (Lagos (Algarve))', 37.1426, -8.6895, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-205', 'Restaurante — Centro (Lagos (Algarve))', 37.1341, -8.7289, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-206', 'Praça Central — Zona Norte (Lagos (Algarve))', 37.0421, -8.6955, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-207', 'UBS — Zona Norte (Lagos (Algarve))', 37.0776, -8.7083, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-208', 'Continente — Zona Norte (Lagos (Algarve))', 37.1385, -8.7069, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-209', 'Pingo Doce — Zona Norte (Lagos (Algarve))', 37.0633, -8.6888, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-210', 'Farmácia — Zona Norte (Lagos (Algarve))', 37.1056, -8.6359, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-211', 'Lagoa das Sete Cidades (São Miguel)', 37.859, -25.78, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-212', 'Praça Central — Centro (Ponta Delgada e São Miguel)', 37.77, -25.6887, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-213', 'UBS — Centro (Ponta Delgada e São Miguel)', 37.7552, -25.7191, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-214', 'Continente — Centro (Ponta Delgada e São Miguel)', 37.725, -25.6626, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-215', 'Pingo Doce — Centro (Ponta Delgada e São Miguel)', 37.7488, -25.7051, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-216', 'Farmácia — Centro (Ponta Delgada e São Miguel)', 37.7146, -25.7328, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-217', 'Posto Galp — Centro (Ponta Delgada e São Miguel)', 37.7328, -25.6339, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-218', 'Posto BP — Centro (Ponta Delgada e São Miguel)', 37.7767, -25.6708, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-219', 'Hotel — Centro (Ponta Delgada e São Miguel)', 37.7101, -25.639, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-220', 'Restaurante — Centro (Ponta Delgada e São Miguel)', 37.7506, -25.6705, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-221', 'Praça Central — Zona Norte (Ponta Delgada e São Miguel)', 37.7547, -25.6226, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-222', 'UBS — Zona Norte (Ponta Delgada e São Miguel)', 37.7972, -25.6798, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-223', 'Continente — Zona Norte (Ponta Delgada e São Miguel)', 37.7333, -25.7316, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-224', 'Pingo Doce — Zona Norte (Ponta Delgada e São Miguel)', 37.7987, -25.6874, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false),
  ('pt150-225', 'Farmácia — Zona Norte (Ponta Delgada e São Miguel)', 37.7642, -25.65, 'familia', 'Local pesquisado, ainda sem visita confirmada. Coordenadas aproximadas.', false)
on conflict (id) do nothing;
